### PR TITLE
1.18.1 - Document CRL usage (#13275)

### PR DESCRIPTION
**Pull request by kfaseela**
Since the implementation PR is merged to 1.18 https://github.com/istio/istio/pull/45130/files
Reverts istio/istio.io#13310
Fixes: https://github.com/istio/istio.io/issues/13328

### CODE REVIEW

**Comment by frankbu** [comment]
This is reverting the revert?

**Comment by kfaseela** [comment]
> This is reverting the revert?

yes... means put the original doc change back.. because CRL changes are now merged to 1.18, and will be part of 1.18.1. But I am not sure when we should merge the docs PR, so i added a dnm

**Comment by frankbu** [comment]
> because CRL changes are now merged to 1.18, and will be part of 1.18.1

I see, so I guess this change should merge AFTER 1.18.1 is released then.

**Review by ericvn — APPROVED** [review]
Approve but hold until we ship 1.18.1

**Comment by ericvn** [comment]
ready to merge with 1.18.1

**Pull request merged**
