### PR TITLE
zh-translation: /news/2019/istio-security-003-004/index.md

### PR DESCRIPTION
**Pull request by sbilly**
ref: https://github.com/servicemesher/istio-official-translation/issues/1216

### CODE REVIEW

**Comment by tanjunchen** [comment]
Sign CLA.
FIx Conflicts

**Comment by sbilly** [comment]
@googlebot I signed it!

**Comment by tanjunchen** [comment]
ref:https://github.com/servicemesher/istio-official-translation/issues/1216
the origin issue had been closed , so close this pr . Thanks your jobs!

**Pull request closed without merging**
