### PR TITLE
[release-1.9] Update istio ref to 1.9.4

### PR DESCRIPTION
**Pull request by ericvn**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by ericvn** [comment]
Looking into the logs of the failure, it appears that an `istioctl` command run during the multicluster and maybe some of the profile=none do not use the HUB/TAG values specified in the Makefile nor the istio.test.{hub/tag} parameters. I see in the log, `gcr.io/istio-release/pilot:1.9-alpha.6e4665c22b35447ab2c4509b37b4009b319ba945: not found"` which is trying to use the TAG from the SHA specified in the go.mod file.

**Comment by stevenctl** [comment]
should we bump this to .4 tomorrow?

**Comment by ericvn** [comment]
@stevenctl I can move as soon as .4 is built.

**Review by stevenctl — APPROVED** [review]

**Review by frankbu — APPROVED** [review]

**Pull request merged**
