### PR TITLE
[zh] sync /docs/tasks/traffic-management/egress/egress-gateway

### PR DESCRIPTION
**Pull request by virtualss**
issue #15144 

correct incorrect numbering list and remove redundant content

## Description

correct document redundant line

## Reviewers

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

>  original English document. 
[apply-Kubernetes-network-policies](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/#apply-Kubernetes-network-policies)

### CODE REVIEW

**Comment by kfaseela** [comment]
Please sign the CLA

**Review by windsonsea — APPROVED** [review]
lgtm, thanks

**Pull request merged**
