### PR TITLE
move otel-collector to namespace observability

### PR DESCRIPTION
**Pull request by zirain**
follow up: https://github.com/istio/istio/pull/49143

### CODE REVIEW

**Comment by zirain** [comment]
@craigbox this PR will be OK after 1.21.0 released because of some dependence issue.

**Comment by craigbox** [comment]
ok, I'll bug you next week :)

**Comment by ericvn** [comment]
Missed this PR and may have been able to pull this in without disabling the test.

**Review by hanxiaop — APPROVED** [review]

**Pull request merged**
