### PR TITLE
use bookinfo pod to check envoy version

### PR DESCRIPTION
**Pull request by shamsher31**
To fix https://github.com/istio/istio.io/issues/8843

Before:
```
$ kubectl exec -it prometheus-68b46fc8bb-dc965 -c istio-proxy -n istio-system pilot-agent request GET server_info
Error from server (NotFound): pods "prometheus-68b46fc8bb-dc965" not found
```
After:
```
$ kubectl exec -it productpage-v1-6b746f74dc-9stvs -c istio-proxy -n default  pilot-agent request GET server_info | grep "version"
 "version": "2d4ec97f3ac7b3256d060e1bb8aa6c415f5cef63/1.17.0/Clean/RELEASE/BoringSSL",
```

### CODE REVIEW

**Comment by ericvn** [comment]
Not sure which Kubectl versions support the `--`
```
k exec -it productpage-v1-6b746f74dc-5brdk -c istio-proxy -n default  pilot-agent request GET server_info | grep "version"
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
```

```
k exec -it productpage-v1-6b746f74dc-5brdk -c istio-proxy -n default  -- pilot-agent request GET server_info | grep "version"
 "version": "2d4ec97f3ac7b3256d060e1bb8aa6c415f5cef63/1.17.0/Clean/RELEASE/BoringSSL",
```

**Comment by ericvn** [comment]
Also, it's good that the `grep` was added, but it still leaves 9 or so lines of out (which aren't reflected in the example output). Not sure if we can use `jq` or some another `grep` to maybe help identify the specific line (although only one matches the format of the example output.

**Comment by ericvn** [comment]
Maybe. We do have `jq` on other pages.
```
kubectl exec -it productpage-v1-6b746f74dc-5brdk -c istio-proxy -n default  -- pilot-agent request GET server_info --log_as_json | jq {version}
{
   "version": "2d4ec97f3ac7b3256d060e1bb8aa6c415f5cef63/1.17.0/Clean/RELEASE/BoringSSL"
                                                                                       }
                                                                                       ```

**Comment by shamsher31** [comment]
Thanks @ericvn, the output with jq looks better.

**Review by ericvn — APPROVED** [review]

**Pull request merged**
