### PR TITLE
[release-1.19] Update the istio test reference to the 1.19.1 candidate

### PR DESCRIPTION
**Pull request by ericvn**
Please provide a description for what this PR is for.

Update the istio test reference to the 1.19.1 candidate

### CODE REVIEW

**Comment by ericvn** [comment]
`ops/configuration/traffic-management/dns-proxy/test.sh` failed:
```

```

**Comment by ericvn** [comment]
`/tasks/security/authorization/authz-ingress/gtwapi_test.sh` failed:
```
deployment "httpbin" successfully rolled out
gateway.gateway.networking.k8s.io/httpbin-gateway created
httproute.gateway.networking.k8s.io/httpbin created
error: timed out waiting for the condition on gateways/httpbin-gateway
```

**Review by dhawton — APPROVED** [review]

**Review by frankbu — APPROVED** [review]

**Comment by ericvn** [comment]
/test doc.test.profile-default


circuit-breaking flake

**Comment by ericvn** [comment]
Flake in tasks/security/authorization/authz-ingress/gtwapi_test.sh in profile-default?

**Comment by ericvn** [comment]
/test doc.test.profile-default

traffic-shifting.

**Comment by ericvn** [comment]
Looks like tasks/security/authorization/authz-tcp/test.sh failed this time? So things are still pretty flakey.

**Comment by ericvn** [comment]
Will merge with the test flakes as the RN PR is waiting as well.

**Pull request merged**
