### PR TITLE
[release-1.19] Update to use 1.19.5 for testing

### PR DESCRIPTION
**Pull request by ericvn**
Update to use 1.19.5 for testing

### CODE REVIEW

**Comment by ericvn** [comment]
/test doc.test.profile-none

prow job updated to allow a longer run

**Review by kfaseela — APPROVED** [review]

**Comment by ericvn** [comment]
I note that the none test is failing in `tasks/traffic-management/tcp-traffic-shifting/gtwapi_test.sh/gtwapi_test.sh`. I'm not yet convinced this is a timing issue, but hoping. I do note that we had to change the test in 1.20 to minimal (and tweak the cleanup). If the timing doesn't fix it, that's my next change.

**Pull request merged**
