### PR TITLE
Add DoneOps to pro_services providers

### PR DESCRIPTION
**Pull request by jmymy**
Adding DoneOps to pro_services providers

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by rvennam — APPROVED** [review]

**Review by ericvn — APPROVED** [review]

**Comment by jmymy** [comment]
doesn't look like a failure on my code. Looks to be an issue with the test script?

**Comment by jmymy** [comment]
confirming it ran successfully the first time and haven't changed the commit / sha so assuming another upstream merge.
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/10328/lint_istio.io/1437392447893147648

**Comment by ericvn** [comment]
There is a problem with linting across the repos. A fix is coming.

**Comment by jmymy** [comment]
@ericvn can we get a cherry-pick please? 😃

**Pull request merged**
