### PR TITLE
Remove Galley Architecture section

### PR DESCRIPTION
**Pull request by therealmitchconnors**
Galley no longer exists as a command, and the information documented in this section has not been true since the introduction of IstioD.  We should probably look at the information in the Citadel section as well, but I am less certain of that.

### CODE REVIEW

**Comment by ericvn** [comment]
As a note looking at some other PRs, Citadel may just be a rename to `Istio certificate authority`.

**Comment by ericvn** [comment]
I'm not a git expert and know how to create the suggestions for you in this PR for the lint failures but basically you need to go into: `news/releases/1.1.x/announcing-1.1/change-notes/index.html` and `news/releases/1.1.x/announcing-1.1/index.html` and change the link adding in the archive for that release. The link should be `https://archive.istio.io/1.1/docs/ops/deployment/architecture/#galley`.

**Comment by frankbu** [comment]
@therealmitchconnors Please fix the lint errors so this PR can merge. Instructions are here: https://preliminary.istio.io/about/contribute/remove-content/#reconcile-broken-links

**Comment by sdake** [comment]
@therealmitchconnors These two CI failures should follow this simple flowchart: https://preliminary.istio.io/about/contribute/remove-content/#reconcile-broken-links

```
- ./public/news/releases/1.1.x/announcing-1.1/change-notes/index.html
  *  linking to /docs/ops/deployment/architecture/#galley, but galley does not exist (line 12814)
     <a href="/docs/ops/deployment/architecture/#galley">Galley</a>
- ./public/news/releases/1.1.x/announcing-1.1/index.html
  *  linking to /docs/ops/deployment/architecture/#galley, but galley does not exist (line 14098)
     <a href="/docs/ops/deployment/architecture/#galley">Galley</a>
```

the files that need to be modified:
- content/en/news/releases/1.1.x/announcing-1.1/change-notes/index.md
- content/en/news/release/1.1.x/announcing-1.1/index.md

a simple search and replace across the repo (or grep + vi are my workflow) will do.

@frankbu I have to wonder if there is a simple way to add user-friendly strings to the CI. I may have a look at it in 2 or 3 years, as soon as my backlog clears up ;-)

Cheers
-steve

**Comment by frankbu** [comment]
@therealmitchconnors It's a little tricky, because the referenced doc in your case has moved since release 1.1. Here's exactly what you need to do.

In these two files:

- content/en/news/releases/1.1.x/announcing-1.1/change-notes/index.md
- content/en/news/release/1.1.x/announcing-1.1/index.md

change the broken link:

- `/docs/ops/deployment/architecture/#galley` -> `https://archive.istio.io/v1.1/docs/concepts/what-is-istio/#galley`

**Pull request merged**
