### PR TITLE
Automatically add a warning to older blog posts about them being potentially out of date

### PR DESCRIPTION
**Pull request by geeknoid**

### CODE REVIEW

**Comment by geeknoid** [comment]
Note that since preliminary.istio.io is configured for 1.4 and all posts predate that release, it means all blog posts get the warning on preliminary.istio.io.

**Comment by frankbu** [comment]
Is there a way we can mark posts that we know are not outdated, either because the content is not release-specific or we know it still works? Post like [this one](https://deploy-preview-5134--preliminary-istio.netlify.com/blog/2017/0.1-canary/) look strange because they have two warnings now, one that says it may be obsolete, followed by another that says it's been updated.

**Comment by geeknoid** [comment]
OK, I'll add a flag to suppress the auto-warning

**Comment by geeknoid** [comment]
Oh actually, for those blogs we can just skip the target_release field in front-matter. How about I go ahead with the PR as-is, and you (@frankbu) can submit another PR that removes the target_release front-matter from blogs you feel are "timeless"?

**Pull request merged**
