### PR TITLE
Added Gateway creation to kubernetes-ingress page

### PR DESCRIPTION
**Pull request by s-bauer**
I think it's required to have a gateway listening in order for istio to serve requests to kubernetes ingress resources. Correct me if I'm wrong and/or missing something!

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by s-bauer** [comment]
@googlebot I signed it!

**Review by howardjohn — COMMENTED** [review]
This shouldn't be needed since Istio 1.6+

**Comment by howardjohn** [comment]
Istiod will internally auto-generate such a gateway when you use Ingress. You can see the autogenerated Gateway by `curl localhost:8080/debug/configz` in istiod

**Comment by s-bauer** [comment]
Running 1.7.3, let me verify it again!

**Comment by s-bauer** [comment]
Yep verified it's not needed. Why is nothing working on my first attempt today. I really need to get some sleep :)
Anyway, thanks for your help, really appreciate it. I might still open another PR for the cert-manager integration as there could be more detail.

**Pull request closed without merging**
