### PR TITLE
zh: fix a translation error

### PR DESCRIPTION
**Pull request by javafuns**

### CODE REVIEW

**Comment by fleeto** [comment]
`[trans-bot:N/A]`

Thank you @javafuns, the [related task issue](https://github.com/servicemesher/istio-official-translation/issues/955) has no assignee. will not be reported to the task issues

**Comment by javafuns** [comment]
It's not merged. @rootsongjc @fleeto Anything I can do to move it forward ?

**Comment by rootsongjc** [comment]
You're not authorized to push to this branch. Visit https://help.github.com/articles/about-protected-branches/ for more information. I have no idea why this error happened.

**Pull request merged**
