### PR TITLE
fix slack invite link

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by craigbox** [comment]
@SkyfireFrancisZ @howardjohn can we update slack.istio.io to use the new link?  Did we recreate the service?

**Comment by hzxuzhonghu** [comment]
@craigbox we should update https://github.com/istio/test-infra/edit/master/infra/gcp/istio-io/run.tf

**Comment by hzxuzhonghu** [comment]
It is redirected

**Comment by craigbox** [comment]
Ah, that is new and I didn't know about it - yes, that seems to be the right thing to update. 👍

**Comment by craigbox** [comment]
closing this in favour of a PR against the `run.tf` file that @hzxuzhonghu is going to send w😁

**Pull request closed without merging**
