### PR TITLE
Clarify sampling rate details for 1.0

### LINKED ISSUE #3178: Default sampling rate doc is incorrect
In the current [documentation](https://istio.io/docs/tasks/telemetry/distributed-tracing/#trace-sampling) of distributed tracing, the default sampling rate is described to sample all requests, However, this is not the case in version `1.0.5` or later. The sampling rate is set to `1.0` (1%) in the Helm install [values.yaml](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/values.yaml#L37). This has been modified in Istio PR [9798](https://github.com/istio/istio/pull/9798).

AFAIK, the sampling rate was indeed at 100% at some point. Either one of the documentation or the default values should change, whatever makes more sense as default.

### PR DESCRIPTION
**Pull request by douglas-reid**
Fix #3178

### CODE REVIEW

**Comment by geeknoid** [comment]
Is it possible you're using an old snapshot, and that's leading to the CI failures?

Could you try to rebase and push again and see if the CI failures go away?

Thanks.

**Comment by douglas-reid** [comment]
This is for `release-1.0` branch.  Running `git fetch upstream --prune && git rebase upstream/release-1.0` results in `Current branch update-trace-task-1.0 is up to date.`

**Comment by douglas-reid** [comment]
i think the external links are legitimately broken... as they reference pages that have been removed since the 1.0 branch was cut.

Look at: https://istio.io/docs/reference/config/istio.networking.v1alpha3/#LoadBalancerSettings. The link there to Envoy's load balancing settings results in a 404.

**Comment by geeknoid** [comment]
Oh, I didn't notice this was on the 1.0 branch. Those links are just always broken at this point...

**Pull request merged**
