### PR TITLE
Fixes: https://github.com/istio/istio.io/issues/7374

### PR DESCRIPTION
**Pull request by sdake**
Link to a video with closed captioning capability for accessibility.
The other slide deck was only visible within google, and the community
is unable to see it without signing in to the read only team drive.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by sdake** [comment]
@frankbu - spoke with @howardjohn via slack - he gave consent to changing his blog post by adding this video.

Cheers,
-steve

**Comment by sdake** [comment]
(waiting on netlify deploy to see how this renders.

**Comment by frankbu** [comment]
There are many problems with this:

1. Firefox preview (depending on version) is either a blank space on the screen or a message that says "can't open youtube video in place for security reasons + a button to open the video in a new window. Chrome just has an error message (refused to connect).
2. Looking at the video, it seems like a very different thing from the slides. The slides gave a clear set of pictures to illustrate how canary deploy and in-place upgrade compare. The video, on the other hand, talks about a lot of things - 10 minutes before it even gets to the canary deploy/revision part, and doesn't show how it compares to in-place upgrade.
3. We've decided that blogs are supposed to be 1-time frozen posts. Fixing problems (like the slides permission issue) is OK, but changing the topic of the blog with very different content is not.

@sdake If you want a blog to advertise your video, you should create a new post about the video, with a link to (not embed) your video.

**Comment by sdake** [comment]
@frankbu fair enough. I did speak with John before submitting this PR and he said it was fine to replace the deck with the video. I'll close out this PR, as i have no other feasible way to resolve the problem.

Cheers,
-steve

**Pull request closed without merging**
