### PR TITLE
Update index.md - minor grammatical correction

### PR DESCRIPTION
**Pull request by LionOnTheChase**
'then' doesn't seem correct grammatically in this sentence.

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by kfaseela** [comment]
@LionOnTheChase would be nice if you could get the CLA part fixed first

**Comment by ericvn** [comment]
Also, was this change submitted from istio.io? We need to also carry this to the main branch.

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by ericvn** [comment]
Since the CLA wasn't approved, I did create a duplicate of this PR: https://github.com/istio/istio.io/pull/12231 so that it could be merged before the upcoming 1.16 release and will be updated in that documentation.

Will close this PR for now.

**Pull request closed without merging**
