### PR TITLE
Update direct upgrade warning

### PR DESCRIPTION
**Pull request by therealmitchconnors**
As of May, skipping a single minor version is supported.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by craigbox — COMMENTED** [review]
Is this only true for canary upgrades?  Do we want to call that out if so?

**Comment by therealmitchconnors** [comment]
I will leave it to @Monkeyanator to clarify what variety of upgrades we test.

**Comment by therealmitchconnors** [comment]
I just got clarification from @jacob-delgado that Helm upgrades are also tested.  It's not clear whether non-revision based upgrades are included.

**Review by Xunzhuo — COMMENTED** [review]
LGTM

**Comment by craigbox** [comment]
> It's not clear whether non-revision based upgrades are included.

Assuming they are still supported, who can clear that up?  @howardjohn may know

**Comment by howardjohn** [comment]
You can do single version in place upgrade, 2 version upgrade with canary

**Comment by craigbox** [comment]
ok, on looking again, I think this is fine to go in because there is _a_ method to do two versions, and we probably do recommend the canary approach :)

**Review by craigbox — APPROVED** [review]

**Pull request merged**
