### PR TITLE
Deautomator: update istio@ test reference

### PR DESCRIPTION
**Pull request by bleggett**
## Description

Manual rebase of https://github.com/istio/istio.io/pull/15759

on top of latest tip with fixed tests from https://github.com/istio/istio.io/pull/15756

## Reviewers

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

### CODE REVIEW

**Comment by bleggett** [comment]
As this is failing on `gen` anyway, manually bumped this to today's Istio ref: 1c546ae8a14a9a64f171c7fe228925ebaf3a3348

**Review by craigbox — APPROVED** [review]
I am @craigbox and I approve this message

**Comment by craigbox** [comment]
/test doc.test.multicluster

(error doesn't look like it was caused by this PR)

**Comment by bleggett** [comment]
> /test doc.test.multicluster
> 
> (error doesn't look like it was caused by this PR)

Possible it is  a side effect of https://github.com/istio/istio/commit/9a92966ae83b430994b5caa21aeb819cda438614 (though it doesn't look like it) - if so, merge this and create an issue with my name on it.

**Comment by craigbox** [comment]
Can't merge with failing test?

**Comment by dhawton** [comment]
> Can't merge with failing test?

@bleggett we'd have to disable the failing test temporarily and re-enable in the followup... that might be the best course of action tbh. Set `tests: no` at the top, rerun `make gen` and that will do it.

**Pull request merged**
