### PR TITLE
[release-1.19] Update test reference to 1.19.8

### PR DESCRIPTION
**Pull request by ericvn**
## Description

Update test reference to 1.19.8

### CODE REVIEW

**Comment by ericvn** [comment]
/test doc.test.profile-default

flake

**Review by kfaseela — APPROVED** [review]

**Comment by ericvn** [comment]
Might need some additional updates besides the canary ones needed in 1.20...

**Comment by ericvn** [comment]
messed up cut/paste

**Comment by hanxiaop** [comment]
@ericvn Thanks for fixing the test!

**Review by craigbox — APPROVED** [review]

**Pull request merged**
