### PR TITLE
Redirect download scripts to master instead of stable branch

### PR DESCRIPTION
**Pull request by jwendell**
Fixes https://github.com/istio/istio/issues/26115

### CODE REVIEW

**Comment by jwendell** [comment]
How can we use different scripts per release if the url redirects to only one place? We don't have one url per release. It's a single [short] url.

If we, for some reason, modify the script to work on 1.7 that somehow only works for 1.7 (hypothetically speaking), then the url is broken for all other versions. In practice, we should have only one script that works for every supported version.

That's why I see that script belonging to another [neutral] place, for example, test-infra, which only has master branch and contains everything to support all the supported releases.

**Comment by shamsher31** [comment]
> If we, for some reason, modify the script to work on 1.7 that somehow only works for 1.7 (hypothetically speaking), then the url is broken for all other versions. In practice, we should have only one script that works for every supported version.

I agree with you @jwendell. The download URL should point to master.

**Comment by ericvn** [comment]
Added to WG agenda. I'm going more off prior process and discussions I had with Martin when making changes to the script in the past.

**Comment by ericvn** [comment]
Per WG discussion, we will go back to using the script in `master`

**Pull request merged**
