### PR TITLE
Correcting the IP ranges used in IKS

### PR DESCRIPTION
**Pull request by mbanikazemi**

### CODE REVIEW

**Comment by mbanikazemi** [comment]
@frankbu 172.20.0.0 was never used. It must be a typo. The 10.10.10.0/24 range was used very briefly very early on and was changed to 172.21.0.0/16 to allow for larger number of services. So perhaps we should remove the 10.10.10.0/24 as well. What do you think?

**Comment by linsun** [comment]
This change looks right to me, when comparing to my IKS clusters... all services being used are 172.21.x

Examples:

```
$ kubectl get services
NAME           TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
kubernetes     ClusterIP   172.21.0.1     <none>        443/TCP    48d
redis-master   ClusterIP   172.21.94.10   <none>        6379/TCP   47d
redis-slave    ClusterIP   172.21.142.8   <none>        6379/TCP   47d```

**Comment by linsun** [comment]
@kitch can you comment?

**Comment by kitch** [comment]
LGTM. The service IP range for IKS has always been `172.21.0.0/16`.

**Comment by linsun** [comment]
@kitch thanks!  should we remove the other two, e.g. `172.30.0.0/16\,10.10.10.0/24`?

**Comment by frankbu** [comment]
In that case, this has never been documented correctly, which I suppose implies nobody has used it.
Nevertheless, we should probably also fix it in at least the release-1.0 branch.

**Comment by linsun** [comment]
+1 on fix it in 1.0 :)

**Comment by linsun** [comment]
I'd suggest leave as it is.

**Comment by mbanikazemi** [comment]
Addressed issue #3124 
A new pull request for release-1.0

**Pull request merged**
