### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by adammil2000** [comment]
Looks good to me. Just FYI, both of the failing URLs are actually working fine and is likely a transient error when the tests ran. You could just make a comment containing the words "/retest" and see if it passes now.

**Comment by geeknoid** [comment]
@hzxuzhonghu Could you rebase so we can merge this please?

Thanks.

**Comment by hzxuzhonghu** [comment]
sorry, i missed the notification

**Pull request merged**
