### PR TITLE
Update reference docs

### PR DESCRIPTION
**Pull request by jasonwzm**
Update reference docs. This replaces https://github.com/istio/istio.io/pull/6419

### CODE REVIEW

**Comment by jasonwzm** [comment]
lint is broken due to `authn tls-check` is removed in https://github.com/istio/istio/pull/21070. We will need a fix to those references.

**Comment by ericvn** [comment]
I'm not sure of the entire process, but I suspect anything you are updating here will end up getting overwritten by the automation processes since you are changing auto-generated files that are passed in.

**Comment by jasonwzm** [comment]
Yes, automation updates auto-generated docs but some of our handwritten docs refer to the auto-generated docs, once the auto-generated docs no longer exist, linter will fail.

**Comment by jasonwzm** [comment]
@ericvn @rootsongjc Please approve. Thanks!

**Comment by jasonwzm** [comment]
ping

**Pull request merged**
