### PR TITLE
fix httpbin.com -> httpbin.org

### PR DESCRIPTION
**Pull request by xichengliudui**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by frankbu** [comment]
This is generated documentation. Please send a PR to fix the original source in the istio/api repository.

https://github.com/istio/api/blob/e1d5fcda8061f83479d165662048eb654e7af2b9/networking/v1alpha3/service_entry.proto#L293

**Review by ericvn — CHANGES_REQUESTED** [review]
As Frank noted, this change needs to be in an upstream PR.

Look at lines like https://github.com/istio/api/blob/master/networking/v1beta1/service_entry.proto#L294 for making the changes. You'll need to do a `make gen` and then get the PR there.

**Pull request closed without merging**
