### PR TITLE
Add SAP as a consumer

### PR DESCRIPTION
**Pull request by Shegox**
Hello team, 

this PR adds the logo/name of SAP as user of Istio. With the ongoing Polidea revamp of the webpage I wasn't sure where I should add the logo. I opted now for just the [new case studies page](https://preliminary.istio.io/latest/about/case-studies), but if I should add it to the [`community/customers`](https://istio.io/latest/about/community/customers/) page as well, please just let me know.

Our colleagues from the trademark team asks us to include following notice about the usage of the logo, I hope that is fine:

> Purpose: Use of SAP Logo as a user on https://istio.io/latest/about/case-studies
> Logo Identification: SAP Logo
> 
> Actual use of the SAP logo described above commits the Requesting Company to the following:
> - Use of the SAP logo is limited solely to the Purpose
> - Use of the SAP logo must conform to [SAP’s trademark use guidelines](https://www.sap.com/corporate/en/legal/trademark.html#proper-use)
> - The context in which the SAP logo is displayed shall be positive to SAP and its products and services
> 
> SAP hereby consents to the use of its logo for the limited Purpose stated above and Company’s use of the logo will serve as its acknowledgment of the accuracy of the representations upon which this consent relies. SAP may revoke this consent at any time and without notice if Company violates any of the representations or conditions contained in this email. SAP may revoke this notice under any other circumstances with thirty (30) days notice to you.
> SAP reserves all intellectual property rights in and to its trademarks. Company’s use of the SAP trademarks in violation of this consent letter may be subject to legal action under applicable law. SAP’s consent and the logos and/or trademarks to which the consent applies are provided to Company as-is with no warranties of any type.

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by craigbox** [comment]
Hi Tobias, thanks!  You've put it in the right place.

Would it also be fair to list Kyma as an integration with Istio and SAP Cloud Platform as a provider of it?

**Comment by Shegox** [comment]
Hi @craigbox, thats a good idea. Thanks!

I will need to check with a few of our internal colleagues on how to best add that as I'm not too familiar with what information would be best suited to add to the page.

I'm moving in the mean time the PR to draft and come back as soon as I know more.

**Comment by craigbox** [comment]
Let me know if you think we should do it together - my preference is
probably to merge this one and look at the others separately.

**Comment by Shegox** [comment]
@craigbox sounds like a good plan. Give me some time next week and I will check with our colleagues from kyma in detail what they as well thing makes sense to highlight. Do you have anything particular in mind what should/shouldn't be listed on the integrations/providers pages? Do you think something like 1317e23d3f54fe7d512dd4e991f86f298d67c1a1 would go in the right direction?

**Comment by craigbox** [comment]
mos def.

>

**Comment by Shegox** [comment]
@craigbox do you think this one is then good to be merged as well?

**Review by craigbox — APPROVED** [review]

**Comment by craigbox** [comment]
Yep, done. Thanks!

**Pull request merged**
