### PR TITLE
Fix istio oldies 1.0 fortio and diagram

### LINKED ISSUE #11311: istio oldies [1.0], perf concepts: restored some url to woking but iframe not showing
So 
https://github.com/istio/istio.io/blob/release-1.0/content/docs/concepts/performance-and-scalability/index.md

has iframes to showcase some fortio graphs, which we restored (they were broken for a while) - thanks a lot Craig for the DNS update (the new deployment is https://github.com/fortio/demo-deployment if anyone is curious)

e.g https://fortio.istio.io/?xMin=2&xMax=110&xLog=true&yMin=&yMax=&yLog=false&sel=qps_400-s1_to_s2-0.7.1-2018-04-05-22-06&sel=qps_400-s1_to_s2-0.6.0-2018-04-05-22-33 now works again for instance

but looking at the actual live site:

https://istio.io/v1.0/docs/concepts/performance-and-scalability/#synthetic-end-to-end-benchmarks

no iframes there somehow?

(also a couple of broken images)

This being said given this is 1.0 and super old it doesn't matter too much - I was hoping the dns was a quick fix, and maybe if that is also a super small fix otherwise I understand it's not worth fixing
 
Thanks!

### PR DESCRIPTION
**Pull request by ldemailly**
Fixes #11311

Please provide a description for what this PR is for.

Add the iframe present in the source in the branch back into the html
Also fixes the diagram broken link

The first commit is whitespace to make the second commit readable (it does make the page a bit heavier)
so to review: https://github.com/istio/istio.io/pull/11312/commits/66b985998c85bed93d9be6da63246649c8ce9782

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [x] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by craigbox** [comment]
Could we have a version without [d385701](https://github.com/istio/istio.io/pull/11312/commits/d3857011b63894100eee65177558dc633dccbdb4) perhaps?

**Comment by ldemailly** [comment]
> Could we have a version without [d385701](https://github.com/istio/istio.io/pull/11312/commits/d3857011b63894100eee65177558dc633dccbdb4) perhaps?

it's going to be hard to do and review but I can try to find the exact point to insert in a thousands of character line(s)

**Comment by ldemailly** [comment]
@craigbox https://github.com/istio/istio.io/pull/11350 is without the reformatting... quite hard to read (and hopefully didn't make a mistake; made it using search and replace of the end of paragraphs)

**Comment by ldemailly** [comment]
https://deploy-preview-11312--preliminary-istio.netlify.app/v1.0/docs/concepts/performance-and-scalability/ is the fixed page (vs https://istio.io/v1.0/docs/concepts/performance-and-scalability/ )

**Comment by ldemailly** [comment]
closing in favor of #11350

**Pull request closed without merging**
