### PR TITLE
update istioctl command for istio operator remove

### PR DESCRIPTION
**Pull request by my-git9**
Please provide a description for what this PR is for.
https://github.com/istio/istio/pull/41245/files

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by zirain** [comment]
amazing, is this doc auto-generated? cc @ericvn

**Comment by ericvn** [comment]
@zirain Yes it is. See the top of the file:
```
---
WARNING: THIS IS AN AUTO-GENERATED FILE, DO NOT EDIT. PLEASE MODIFY THE ORIGINAL SOURCE IN THE 'https://github.com/istio/istio' REPO
source_repo: https://github.com/istio/istio
title: istioctl
```
In the main stream it is updated nightly from the code in the istio/istio main branch.

**Comment by my-git9** [comment]
OK, I will close it

**Comment by ericvn** [comment]
Basically to see what is in the generated file you can do a `make istioctl` and then  `istioctl collateral -o some_directory --html_fragment_with_front_matter`.

**Comment by ericvn** [comment]
Looks like it actually was merged as part of https://github.com/istio/istio.io/pull/12063

**Comment by my-git9** [comment]
OK, thanks @ericvn

**Pull request closed without merging**
