### PR TITLE
missing a space after "kubectl get pods -l"

### PR DESCRIPTION
**Pull request by danielmenezesbr**
missing a space after the command

[ ] Configuration Infrastructure
[X]Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by ericvn** [comment]
As noted by the failing test, please run `make gen` to update the script.

**Comment by danielmenezesbr** [comment]
@ericvn I do `make gen`  but the CI still reports an error.

**Comment by ericvn** [comment]
@danielmenezesbr The `make gen` did fix the CI failure in for he `gencheck` test. The remaining failing test is a test flake. I did kick off another run and expect it to pass.

**Review by ericvn — APPROVED** [review]

**Pull request merged**
