### PR TITLE
[release-1.5] Add an entry on the (potentially) breaking change for resource visibility

### LINKED ISSUE #7506: [release-1.5] Add entry on the (potentially) breaking change for resource visibility in Istio 1.5
Manual cherrypick required.

#7496 failed to apply on top of branch "release-1.5":
```Applying: Add an entry on the (potentially) breaking change for resource visibility changes related to `VirtualService`s.
error: Failed to merge in the changes.
Using index info to reconstruct a base tree...
M	content/en/news/releases/1.5.x/announcing-1.5/upgrade-notes/index.md
Falling back to patching base and 3-way merge...
Auto-merging content/en/news/releases/1.5.x/announcing-1.5/upgrade-notes/index.md
CONFLICT (content): Merge conflict in content/en/news/releases/1.5.x/announcing-1.5/upgrade-notes/index.md
Patch failed at 0001 Add an entry on the (potentially) breaking change for resource visibility changes related to `VirtualService`s.

```

### PR DESCRIPTION
**Pull request by chadlwilson**
Manual cherry-pick from #7496 (fixes #7506)

(cherry picked from commit b21d6182f12e68ade8b1a6383a2abf5fb2af04c6)

[X] Docs
[X] Networking

### CODE REVIEW

**Comment by chadlwilson** [comment]
Tried to run `make lint` locally, but sadly it is getting stuck in some `html-proofing` Ruby code on this particular branch.

**Comment by chadlwilson** [comment]
The lint errors seem unrelated to my change, so I'm a bit unsure how/whether they need to be resolved here as they presumably were pre-existing.

- warnings from WASM docs on specific Github line links
- a broken link from `1.3` change notes

**Comment by ericvn** [comment]
In the past we typically didn't update archives after they were changed per prior remarks from @frankbu. I know there are some upcoming changes that will allow changes in archives. @davidhauck will have some comments on that.

**Comment by frankbu** [comment]
@chadlwilson As @ericvn said, in the past, we were never able to update the archive sites (they were frozen), but @davidhauck is completely reworking the way we publish the archive sites, which should be ready in a couple of days, so this will be a first attempt at merging a change into an archive site. (in general, I think we still only want to do it rarely, if the archive site is still a supported release, which it is in this case).

That said, the lint error seems to be a bug in the current Istio 1.5 archive. Notice that if you go to [this page](https://archive.istio.io/v1.5/docs/tasks/traffic-management/ingress/) and then click on either of the `Secure Gateways (xxx)` links, it will take you to the Portuguese doc (i.e., `https://archive.istio.io/v1.5/pt-br/...`. Something is definitely getting messed up with these pages, and I think that's why the linter is reporting a broken link.

^^^ @davidhauck, any idea? Do you think this will be fixed in your new published archive site?

**Comment by davidhauck** [comment]
It's not fixed in my new site sadly: https://davidhauck-isito-io.netlify.app/v1.5/docs/tasks/traffic-management/ingress/. Currently looking into why that's happening. My current guess is that the doc has an alias for itself (the secure-ingress-sds page). Since both the pt-br and en version both have the SAME alias, there are multiple pages competing for the same redirect alias. In this case, I guess it chose the pt-br version. I've actually noticed that before. When both the pt-br version and the eng version have the same aliases, it goes to the pt-br version.

**Comment by chadlwilson** [comment]
Thanks for sharing the context, all - no worries in this case. Can merge when/if ready as a test case for updating archives :-)

Funny you mention issues with the `pt-br` redirects/aliases. I noticed a few weeks ago a spate of people sharing links in Istio Slack (and personally with me when privating discussing issues specific to our setup) that were the often-outdated portuguese pages. Many of these are not yet translated from English so people were not aware of the potential problem unless they really looked closely e.g at _10 minutos lidos_) for no apparent reason...

image

Out of scope of this PR/discussion, but as a user it feels a little bit dangerous to have stale english content hiding within `pt-br` :-/

**Comment by ericvn** [comment]
@frankbu What's the status on the Portuguese translation effort? At one point I heard it had stopped, and we should probably pull it off the site. I've heard that there might be a group that wanted to pick it up again, but admit I haven't seen much work if there is.

**Comment by frankbu** [comment]
@ericvn, because the pt-br docs are, for the most part, just an outdated version of the en docs we don't lint check them and we don't include them in the language selection menu (gear), so theoretically they should be hidden. I'm not sure how people are finding them anyway, unless the bug I pointed out above is more prevalent than I thought. I think it might be a good idea to not build the pt-br docs at all at this point, unless somebody steps up and does a reasonably complete first pass at translating them.

WDYT @davidhauck? Can we disable pt-br completely for now?

**Comment by davidhauck** [comment]
Yep, I could easily add a config item to ignore all the files under content/pt-br, if that's what we decide on

**Comment by frankbu** [comment]
Force merging this to get it into github. It won't appear on the the 1.5 archive site until @davidhauck rebuilds the site, should be within a few days. (The lint error will also be fixed at that time).

**Pull request merged**
