### PR TITLE
Use --prune in upgrade to avoid issues.

### PR DESCRIPTION
**Pull request by elfinhe**
Add `--prune -l release=istio` in the control plane upgrade.

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by elfinhe** [comment]
@howardjohn hi John, can you help review this PR?

**Comment by elfinhe** [comment]
> What issues does this fix?

https://github.com/istio/istio.io/issues/5125
Trying to fix this one, but I was assuming --prune is recommended in upgrade.

**Comment by howardjohn** [comment]
I am just worried this may accidentally lead to deleted config. Does everything in our install have `release: istio`?

**Comment by elfinhe** [comment]
> I am just worried this may accidentally lead to deleted config. Does everything in our install have `release: istio`?

I agree. That's too aggressive. Let me do more tests.

**Pull request closed without merging**
