### PR TITLE
Update istio test reference

### PR DESCRIPTION
**Pull request by ericvn**
Please provide a description for what this PR is for.

Update the istio test reference to commit later than the automated release over the weekend. Wanting to verify that one of the tests now pass due to https://github.com/istio/istio/pull/45943.

### CODE REVIEW

**Comment by ericvn** [comment]
Looks like the images might not have been available yet.

**Comment by ericvn** [comment]
I am unable to get the test to pass locally or set up spire with a kind cluster or IKS cluster (all seem to have different reasons the ingress-gateway never becomes ready). I also tried on 1.18.0 so not sure why this used to work.

**Comment by ericvn** [comment]
Also needs https://github.com/istio/istio/pull/45954 to merge to fix an issue where a nightly spire related image is causing a failure.

**Comment by ericvn** [comment]
See second commit to test fixing the image version with sed.

**Comment by ericvn** [comment]
Last failure was a new one: `/setup/install/operator/test.sh`.

**Comment by ericvn** [comment]
Next test has a flake:
```
2023-07-12T14:19:48.744703Z	info	tf	=== DONE (failed):  Test: 'tests_setup_profile-none[TestDocs/ops/ambient/getting-started/gtwapi_test.sh/gtwapi_test.sh] (3m0.148860933s)' ===
```

**Comment by ericvn** [comment]
And operator has failed again, will investigate this one some more.

**Comment by ericvn** [comment]
Fix for operator tet: https://github.com/istio/istio.io/pull/13549

**Comment by ericvn** [comment]
Revert the sed change since istio now contains the change from `nightly`. Also pick up new istio commit that contains https://github.com/istio/istio/pull/45954.

**Review by frankbu — APPROVED** [review]

**Pull request merged**
