### PR TITLE
Enable jwt-route

### PR DESCRIPTION
**Pull request by ericvn**
## Description

Fixes https://github.com/istio/istio.io/issues/14224

### CODE REVIEW

**Review by kfaseela — APPROVED** [review]

**Comment by ericvn** [comment]
/test doc.test.profile-default

@kyessenov Looks like the jwt-route test is still failing. I think the upstream change should be in this istio commit.

**Comment by kyessenov** [comment]
@ericvn No, it's still under review.

**Comment by ericvn** [comment]
/retest

build wasn't available yet

**Comment by ericvn** [comment]
/test doc.test.profile-default

flake

**Pull request merged**
