### PR TITLE
Update callout colours in _light_theme.scss for better contrast and aesthetic

### PR DESCRIPTION
**Pull request by MeenuyD**
The callout colours have been updated to improve contrast and better fit the aesthetic of the site. Changes include:

- Updated quote callout background and border colours
- Updated tip callout background and border colours
- Updated idea callout background and border colours
- Updated warning callout background and border colours
#14666

### CODE REVIEW

**Comment by craigbox** [comment]
Thanks for the contribution!

These still seem like "pastel colours" in a world of solid blues and purples.  (The original pallet comes from when the site looked like [this](https://istio.io/v1.2/docs/concepts/what-is-istio/).)  I was hoping we would find something that fit the design of the new site a little better. 

Perhaps try using something like https://color.adobe.com/ ?

**Comment by craigbox** [comment]
@MeenuyD did you want to continue with this PR?

**Comment by MeenuyD** [comment]
Sorry but due to some issue I could not able to do that I will do

**Pull request closed without merging**
