### PR TITLE
[release-1.14] Update istio test reference to 1.14.5 build

### PR DESCRIPTION
**Pull request by ericvn**
Please provide a description for what this PR is for.

Update the istio/istio reference for testing to the istio commit used with the latest 1.14.5 build.

### CODE REVIEW

**Comment by ericvn** [comment]
Force pushed to remove the commit moving to the respin commit. See if the last istio commit seems to be the issue.

**Comment by ericvn** [comment]
Passed again, so strongly suspect https://github.com/istio/istio/pull/41286 is what is causing the gateway-api test to fail.

**Comment by ericvn** [comment]
Am istio PR for 1.14 is incoming which will hopefully fix the issue. New commit when that PR is merged and images built.

**Review by frankbu — APPROVED** [review]

**Pull request merged**
