### PR TITLE
Adding KodeKloud's Istio Service Mesh Course to Istio.io

### PR DESCRIPTION
**Pull request by nimeshmora**
## Description

This PR adds a detailed and structured Istio Service Mesh course from KodeKloud to Istio.io. The course covers essential topics, including service mesh concepts, Istio architecture, traffic management, security, observability, and advanced traffic control. It also includes practical hands-on labs and projects to reinforce learning and provide real-world experience. This addition aims to enhance the resources available for Istio users and facilitate better understanding and adoption of Istio service mesh.

## Reviewers

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation
- [X] Training

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by kfaseela** [comment]
could you please sign the CLA?

**Comment by kfaseela** [comment]
here is how the preview looks, please move the course after the LF courses. https://deploy-preview-15276--preliminary-istio.netlify.app/latest/about/training

**Comment by nimeshmora** [comment]
> could you please sign the CLA?

I have signed it actually. 
Screenshot 2024-06-12 at 12 47 30

**Comment by kfaseela** [comment]
> * The email address for the commit ([5b66085](https://github.com/istio/istio.io/commit/5b6608529be86d7564f877feae08ff846d2bbc31), [b55925a](https://github.com/istio/istio.io/commit/b55925af438089de8045de81de44858559106bb1)) is not linked to the GitHub account,

The error says `The email address for the commit (https://github.com/istio/istio.io/commit/5b6608529be86d7564f877feae08ff846d2bbc31, https://github.com/istio/istio.io/commit/b55925af438089de8045de81de44858559106bb1) is not linked to the GitHub account,`

**Comment by nimeshmora** [comment]
> > * The email address for the commit ([5b66085](https://github.com/istio/istio.io/commit/5b6608529be86d7564f877feae08ff846d2bbc31), [b55925a](https://github.com/istio/istio.io/commit/b55925af438089de8045de81de44858559106bb1)) is not linked to the GitHub account,
> 
> The error says `The email address for the commit (https://github.com/istio/istio.io/commit/5b6608529be86d7564f877feae08ff846d2bbc31, https://github.com/istio/istio.io/commit/b55925af438089de8045de81de44858559106bb1) is not linked to the GitHub account,`

Okay, i think i have commited with KodeKloud internal email but my personal GitHub Account associated with my other email. Let's me 

> > * The email address for the commit ([5b66085](https://github.com/istio/istio.io/commit/5b6608529be86d7564f877feae08ff846d2bbc31), [b55925a](https://github.com/istio/istio.io/commit/b55925af438089de8045de81de44858559106bb1)) is not linked to the GitHub account,
> 
> The error says `The email address for the commit (https://github.com/istio/istio.io/commit/5b6608529be86d7564f877feae08ff846d2bbc31, https://github.com/istio/istio.io/commit/b55925af438089de8045de81de44858559106bb1) is not linked to the GitHub account,`

Done! Accidentally committed with other email. I have amended proper author details and now it looks good! @kfaseela

**Review by kfaseela — APPROVED** [review]

**Comment by nimeshmora** [comment]
@kfaseela thanks. When will this change be reflected in the site?

**Comment by kfaseela** [comment]
> @kfaseela thanks. When will this change be reflected in the site?

should be available already now. I was wondering if the logo would have looked better with a darker background

**Pull request merged**
