### PR TITLE
Announce steering election and TOC election result

### PR DESCRIPTION
**Pull request by craigbox**
[X] Docs

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by shamsher31 — APPROVED** [review]
@craigbox I really like your commit message.

**Comment by craigbox** [comment]
> @craigbox I really like your commit message.

I'm going        to leave a bunch of.     trailing spaces here.    just.      because I can.

**Review by linsun — APPROVED** [review]
Congrats @howardjohn and @brian-avery, well deserved!!

**Review by ericvn — APPROVED** [review]

**Comment by brian-avery** [comment]
Thanks Lin :)

**Comment by ericvn** [comment]
Congrats @howardjohn and @brian-avery.

**Comment by brian-avery** [comment]
Thanks Eric :)

**Pull request merged**
