### PR TITLE
add istio security 2020-10 news to Chinese.

### PR DESCRIPTION
**Pull request by elkan1788**
zh-translation: add istio security 2020-10 news to Chinese.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by SataQiu — COMMENTED** [review]
/ok-to-test

**Comment by kebe7jun** [comment]
@elkan1788 请修复一下 lint。

**Review by kebe7jun — APPROVED** [review]

**Pull request merged**
