### PR TITLE
update:/en/docs/ops/integrations/kiali/index.md?

### PR DESCRIPTION
**Pull request by yanrongshi**
Fixed a link address error 
And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by yanrongshi** [comment]
@Xunzhuo  is this is a issues? boss

**Comment by craigbox** [comment]
As #10752, these links should remain relative links to the rendered documentation.

**Comment by yanrongshi** [comment]
>

**Pull request closed without merging**
