### PR TITLE
Enhance release announcement with documentation links.

### PR DESCRIPTION
**Pull request by rcaballeromx**

### CODE REVIEW

**Comment by geeknoid** [comment]
Could you redo this PR? As it is, it includes a bunch of changed files it shouldn't.

Thanks.

**Comment by geeknoid** [comment]
A request:

To make it easier to review, it's preferable not to combine reformatting/reindenting with normal editing activities. As it is, most lines of the files show up as diffs.

Thanks.

**Comment by rcaballeromx** [comment]
@geeknoid I'll give it another shot.

**Comment by rcaballeromx** [comment]
> A request:
> 
> To make it easier to review, it's preferable not to combine reformatting/reindenting with normal editing activities. As it is, most lines of the files show up as diffs.
> 
> Thanks.
My editor auto wraps the lines to 80 character length on save, I'll change the config to avoid this in the future.

**Comment by rcaballeromx** [comment]
Replaced with PR #3821

**Pull request closed without merging**
