### PR TITLE
[zh]: fix locality-load-balancing/failover/index.md link fail

### PR DESCRIPTION
**Pull request by aimuz**
Signed-off-by: aimuz <mr.imuz@gmail.com>

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by aimuz** [comment]
@zirain Can you help review it?

**Comment by zirain** [comment]
you should apply to join org to skip `need-ok-test`, like https://github.com/istio/community/pull/884

**Review by zirain — APPROVED** [review]
lgtm, thanks!

**Comment by aimuz** [comment]
Do you know how to join istio slack? It seems to require an invitation link

It doesn't seem to automatically create a cherrypick

**Pull request merged**
