### PR TITLE
Remove AWS Kops as a docummented option

### PR DESCRIPTION
**Pull request by sdake**
This doesn't mean you can't get AWS Kops to deploy Istio, just that
nobody cares to maintain the documentation.  If in the future someone
wishes to maintain the documentation, we can consider adding this page
back in.  I would suggest however a page on any EKS specific requirements
needed for Istio as this will be the more likely path folks take to run
Istio.

### CODE REVIEW

**Comment by sdake** [comment]
@geeknoid not sure what to make of the circleci lint error...

**Comment by geeknoid** [comment]
Could you rebase and repush please?  That should cure the CI failure.

Thanks.

**Comment by mabushey** [comment]
@sdake 
> I would suggest however a page on any EKS specific requirements
needed for Istio as this will be the more likely path folks take to run
Istio.

I doubt it. Why pay extra for EKS when Kops or Typhoon can set it up for you? I think most people on AWS use Kops.

**Pull request merged**
