### PR TITLE
zh-translation:content/zh/boilerplates/trace-generation.md

### PR DESCRIPTION
**Pull request by romainshen**
ref: https://github.com/servicemesher/istio-official-translation/issues/1354

### CODE REVIEW

**Comment by romainshen** [comment]
@googlebot I signed it!

**Comment by tanjunchen** [comment]
image

fix line 6 according to en/ original file format

**Comment by tanjunchen** [comment]
@romainshen   @rootsongjc 同理 已经被翻译 文件位置已经改变 建议关闭

**Pull request closed without merging**
