### PR TITLE
zh-translation:sync virtual-machines/test.sh

### PR DESCRIPTION
**Pull request by my-git9**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by zirain** [comment]
@ericvn do you think we need do test in other language
IMHO, tests running on English is enough.

**Comment by ericvn** [comment]
@zirain I'm not convinced that the translated document tests would continue to pass. In some instances, we need to make changes to the English pages, say in the command output or the commands as well as the tests scripts as Istio evolves. Since we don't update the translated packages/tests at the same time as we do the English pages, I expect that the non-English tests may become broken over time.

The problem is support for those translated pages/tests. In some cases, I may have spent a week to get the English pages back to passing (after switching the back to testing against the main branch following a release). I'm not sure who we can get to do the same things on the translated pages. Making the tests non-required would allow PRs to continue to merge, but I don't want to continually have non-required tests failing.

This does bring up whether we should be showing any of the translated pages with a check mark meaning we are running a test against them.

**Comment by zirain** [comment]
@ericvn refer to [here](https://github.com/istio/istio.io/blob/5bc9c873e362f64b96eeb1c378475be1b6ae5c7f/tests/tests.mk#L48), I think we do not need to update tests in other language.

**Comment by ericvn** [comment]
@zirain Correct. We only run tests against the English docs today. As I noted above, if we wanted to run against the translated docs, it may or may not work. My prior remarks were against enabling tests on the translated pages, unless support would come from some group. Translated tests don't need to be updated unless those tests would be enabled at some point.

**Review by ericvn — APPROVED** [review]
Their is no translated text in this PR. only English updates.

**Pull request merged**
