### PR TITLE
zh: some small trivial changes

### PR DESCRIPTION
**Pull request by icyyyyer**
some small trivial changes

### CODE REVIEW

**Comment by rootsongjc** [comment]
@icyyyyer Please sign the CLA first.

**Comment by icyyyyer** [comment]
> @icyyyyer Please sign the CLA first.

ok~if I should pullRequest 

> I signed it!

**Comment by rootsongjc** [comment]
@icyyyyer Please merge the master and re-lint to pass the CI.

**Comment by rootsongjc** [comment]
@icyyyyer Please re-lint to pass the CI.

**Comment by icyyyyer** [comment]
> @icyyyyer Please re-lint to pass the CI.

I can't run linting because I couldn't pull the "gcr.io/istio-testing/website-builder:2018-10-08" image

**Comment by rootsongjc** [comment]
`/docs/tasks/teltmetry/servicegraph` has been deleeted, close the issue.

**Pull request closed without merging**
