### PR TITLE
toss in action

### PR DESCRIPTION
**Pull request by JacksChoco**

### CODE REVIEW

**Comment by JacksChoco** [comment]
@ericvn Can you check this?

**Comment by ericvn** [comment]
@JacksChoco I did approve it, but it also needs approval from several others because the PR has changes in the other languages as well.

**Comment by JacksChoco** [comment]
Thanks for answering!

**Comment by ericvn** [comment]
One bit of advice to simply getting your work on would be to remove the non-English language content. Our typical workflow is to have English language content submitted and then the various translation teams will translate to PT or CN. This would reduce the number of approvals needed to just the English team for this PR.

**Comment by JacksChoco** [comment]
I switched with your advice.

**Pull request merged**
