### PR TITLE
Polidea update - layout fixes

### LINKED ISSUE #9436: Layout errors on new site
https://preliminary.istio.io/latest/about/service-mesh:

- The breadcrumb bar should be aligned left under the Istio logo.
- The headings should have the same margins as the first body text
- There should be a margin on either side roughly equivalent to the width of the Istio logo (which you can see most clearly on the three "Concepts" sections
- The logos for each Concept should be larger in their boxes.

## Breadcrumbs and subheaders

image

vs

image

(Please also check [solutions pages](https://preliminary.istio.io/latest/about/solutions/enabling-defense-in-depth-for-enterprise-applications/) as the breadcrumb header is in the wrong place there too.)

## Logos
 vs 

## Margin

image

vs

image

### PR DESCRIPTION
**Pull request by wbartosz**
This pull request includes layout fixes raised in https://github.com/istio/istio.io/issues/9436.
Closes #9436 and #9473.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by craigbox** [comment]
LGTM, some layout fixes to raise new issues for.  Assigning to @davidhauck to approve.

**Comment by craigbox** [comment]
Closes #9473 too.

**Review by davidhauck — APPROVED** [review]

**Review by craigbox — APPROVED** [review]

**Pull request merged**
