### PR TITLE
Cherrypick #14996 (attempt 3)

### LINKED ISSUE #15286: [release-1.22] Homepage changes for ambient overview content
Manual cherrypick required.

#14996 failed to apply on top of branch "release-1.22":
```
Applying: Test homepage changes for preview.
Applying: update logos
Applying: three buttons
Applying: changes to scroller
Applying: sass: align buttons at bottom of panels
Applying: fixup banner title and subtitle styling
Applying: oops
Applying: scope white headline color to banner
Applying: scope header margin overrides to banner section
Applying: fixup page header margins, restore subtitle class to What is Istio section
Applying: semibold banner title
Applying: set landing page paragraph size, remove subtitle classes
Applying: update logos and CSS for such
Applying: you REALLY LIKE BLANK LINES but ONLY AT THE ENDS, linter
Applying: Add page hierarchy
Applying: CNI content
Applying: WIP
Applying: cut cut cut
Applying: preview /about/service-mesh page
Applying: WIP
Applying: preview latest updates
Applying: tweaks
Applying: correct link
Applying: lint fix
Applying: Proper formatting, lint be damned
Applying: new iconography
Applying: next round
Using index info to reconstruct a base tree...
Falling back to patching base and 3-way merge...
CONFLICT (add/add): Merge conflict in content/en/docs/ambient/getting-started/index.md
Auto-merging content/en/docs/ambient/getting-started/index.md
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0027 next round
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

```

### PR DESCRIPTION
**Pull request by craigbox**
Adds the changes from #14996 to the current docs.
One change in `zh` due to replacing a logo.

Resolves #15286.
#15323 broke the CI.
#15324 was meant to fix that, but it still had the same commit ID.

This one is from my fork, not from istio.io, which hopefully fixes everything. 

- [x] Docs

### CODE REVIEW

**Comment by dhawton** [comment]
Success this time!

**Comment by craigbox** [comment]
The getting started guide has thoroughly moved on since this PR.

Note to self, to proceed I am considering cherry-picking the following, in order:

* https://github.com/istio/istio.io/pull/15168
* https://github.com/istio/istio.io/pull/15241
* this one
* https://github.com/istio/istio.io/pull/15293

**Comment by craigbox** [comment]
cf. https://github.com/istio/istio.io/pull/15333 and merge the best one

**Comment by craigbox** [comment]
Closing assuming we'll merge #15333.

**Pull request closed without merging**
