### PR TITLE
Fixup master branch post 1.20 branch cut

### PR DESCRIPTION
**Pull request by ericvn**
## Description

Fixup master branch post 1.20 branch cut

### CODE REVIEW

**Comment by ericvn** [comment]
Also waiting to see if all the tests pass in the post-submit for https://github.com/istio/istio.io/commit/cc163586b86ce97baf532a2c045b8f37037e2480

**Comment by ericvn** [comment]
/test lint

Also not sure why the linter is being flakey.

**Comment by ericvn** [comment]
TestDocs/setup/install/operator/test.sh  failed in the other PR. Rerunning that again..

**Comment by ericvn** [comment]
The failure noted above is expected since there is no actual 1.20.0 release artifacts available at this point.

**Review by dhawton — APPROVED** [review]

**Review by frankbu — APPROVED** [review]

**Pull request merged**
