### PR TITLE
Fix in-place upgrade doc to be more accurate

### PR DESCRIPTION
**Pull request by hanxiaop**
## Description

The upgrade is an alias of install command, with no additional check.

## Reviewers

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

### CODE REVIEW

**Comment by linsun** [comment]
Does istioctl upgrade still work? While I don't object to use istioctl install for upgrade, I do think istioctl upgrade is more clear to users and keep the doc unchanged can reduce questions from users.

**Comment by hanxiaop** [comment]
> Does istioctl upgrade still work? While I don't object to use istioctl install for upgrade, I do think istioctl upgrade is more clear to users and keep the doc unchanged can reduce questions from users.

It works but it's just an alias to the install command, with no additional check. Since you have the preference to it, I can just revise the upgrade description to be more accurate instead of chaning the command.

**Review by dhawton — APPROVED** [review]
Agree that upgrade might be more clear.. LGTM

**Comment by rvennam** [comment]
If `upgrade` is just an alias and doesn't do anything different than `install`, it feels misleading to use it. Can't we just make it `install`?

**Comment by dhawton** [comment]
> If `upgrade` is just an alias and doesn't do anything different than `install`, it feels misleading to use it. Can't we just make it `install`?

I think upgrade is more clear, tbh.

**Comment by hanxiaop** [comment]
> If `upgrade` is just an alias and doesn't do anything different than `install`, it feels misleading to use it. Can't we just make it `install`?

I actually don't know if it has been deprecated or not. What I do know is that `upgrade` was different from `install`, and it may have been changed to be an alias of install due to bugs. After that, there should have been no changes for at least two years. When I read the doc, I thought it's quite not accurate now.

**Comment by dhawton** [comment]
It is basically an alias: https://github.com/istio/istio/blob/master/operator/cmd/mesh/upgrade.go#L30...

though https://github.com/istio/istio/blob/master/operator/cmd/mesh/upgrade.go#L39C6-L39C54 says it does perform checks.

**Comment by hanxiaop** [comment]
> It is basically an alias: https://github.com/istio/istio/blob/master/operator/cmd/mesh/upgrade.go#L30...
> 
> though https://github.com/istio/istio/blob/master/operator/cmd/mesh/upgrade.go#L39C6-L39C54 says it does perform checks. I don't see any checks being performed, so this could be needing changed as well.

Yes, they are exactly same commands for years. The description is not accurate as well.

**Comment by hanxiaop** [comment]
I'd like to merge this one since the old text is not accurate and misleading, and the command description has been corrected https://github.com/istio/istio/pull/49012. We can discuss further if there's a need to revise 'upgrade' to 'install'.

**Pull request merged**
