### PR TITLE
Update tablegen.py to update the installation option table for 1.1

### PR DESCRIPTION
**Pull request by johnma14**
Updated tablegen.py to process the configuration options from the values.yaml
files under /istio/install/kubernetes/heml/subcharts directory and the
remaining configuration options like global, istiocoredns, istio_cni from
values.yaml under /istio/install/kubernetes/helm/istio directory.

### CODE REVIEW

**Comment by geeknoid** [comment]
How about running this against the current 1.1 bits and including the resulting output with the PR? Otherwise, it's difficult to know whether the script is doing the right thing.

Thanks.

**Comment by geeknoid** [comment]
That helps, but I meant to actually add the file to the PR and check it in with the PR. Is that possible?

**Comment by johnma14** [comment]
@geeknoid thanks for the review

**Comment by johnma14** [comment]
@geeknoid oh yes absolutely. I can updated the index.md under installation-options directory itself. Will that help?

**Comment by geeknoid** [comment]
Yes, that'd be great.

**Comment by geeknoid** [comment]
Your PR seems to have picked up some unrelated files. If you could remove those please, then we can merge your changes in.

Thanks.

**Comment by johnma14** [comment]
Closing this PR since I could not the branches to sync correctly. Reopened another PR for this issue at: https://github.com/istio/istio.io/pull/3188. Thanks

**Pull request closed without merging**
