### PR TITLE
update intel's post link address

### PR DESCRIPTION
**Pull request by irisdingbj**
update intel's post link address in graduation blog

### CODE REVIEW

**Comment by ericvn** [comment]
@irisdingbj I don't see the URL is pointing to post related Istio's graduation.

**Comment by ericvn** [comment]
@craigbox Thoughts on this link?

**Comment by irisdingbj** [comment]
> @irisdingbj I don't see the URL is pointing to post related Istio's graduation.

1st paragraph focus on istio introduction directly.  2nd paragraph focus on celebrating the graduation:
Intel, an active contributor to Istio since 2020, joins the community celebrating the recent milestone from incubating project to become a Cloud Native Computing Foundation* (CNCF) [graduated project](https://www.cncf.io/projects).

**Review by craigbox — APPROVED** [review]

**Comment by craigbox** [comment]
considered updating the link to https://community.intel.com/t5/Blogs/Tech-Innovation/open-intel/How-Intel-s-Contributions-Can-Boost-Istio-Service-Mesh/post/1503821#toc-hId-1185660177 but it's OK to go live as is

**Pull request merged**
