### PR TITLE
remove file : docs/ops/configuration/security/root-transition/index.md

### PR DESCRIPTION
**Pull request by elkan1788**
Remove file in path:  docs/ops/configuration/security/root-transition/index.md

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by kebe7jun** [comment]
@elkan1788  Can you find the PR for the deletion of this English document?

**Review by SataQiu — COMMENTED** [review]
/ok-to-test

**Comment by elkan1788** [comment]
> @elkan1788 Can you find the PR for the deletion of this English document?

Seems the PR is here: #8876

**Review by kebe7jun — APPROVED** [review]
lgtm

**Pull request merged**
