### PR TITLE
Remove progress bars from curl (occuring on Mac)

### PR DESCRIPTION
**Pull request by ericvn**

### CODE REVIEW

**Comment by ericvn** [comment]
/assign @rcaballeromx 

New to Istio.io and not sure why the deploy/netlify seems to be hung.

**Comment by rcaballeromx** [comment]
@ericvn I'll take a look and try to figure it out.

**Comment by geeknoid** [comment]
Not sure why Netlify is stuck on this one.... I'll just force-push the change in.

Thanks.

**Pull request merged**
