### PR TITLE
[release-1.17] Update istio test reference for 1.17.3

### PR DESCRIPTION
**Pull request by ericvn**
Please provide a description for what this PR is for.

Update istio test reference for 1.17.3

### CODE REVIEW

**Comment by ericvn** [comment]
Current manifest has `b29f9595ea092524354677ebc3dc173d84877aec` which matches.

**Comment by ericvn** [comment]
Latest manifest:
```
  istio:
    sha: b72da5eaaeb1f57e3bbc4642e64b2e256bbab8ee
```

**Review by kfaseela — APPROVED** [review]

**Comment by ericvn** [comment]
Release is published, so let merge.

**Pull request merged**
