### PR TITLE
Add ambient profile for docs test

### PR DESCRIPTION
**Pull request by kfaseela**
## Description

Now that we have more documentation and document tests coming with ambient profile, I think it makes better sense to have an ambient profile created separately?

Wait on https://github.com/istio/test-infra/pull/5374

## Reviewers

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

### CODE REVIEW

**Comment by kfaseela** [comment]
The cleanup section of the ambient test will fail until we have https://github.com/istio/istio/pull/51329/files

**Comment by kfaseela** [comment]
@dhawton i am separating out the test changes and profile creation, so that this PR can be merged first. https://github.com/istio/istio.io/pull/15220/files seems to have issues and may be delayed, so the test will otherwise fail until that gets merged.

**Review by craigbox — APPROVED** [review]

**Pull request merged**
