### PR TITLE
Add 'istio' and 'kubernetes' to .spelling

### PR DESCRIPTION
**Pull request by my-git9**
Add 'istio' and 'kubernetes' to .spelling

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [x] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by ericvn — CHANGES_REQUESTED** [review]
Thanks for the PR, but istio and kubernetes are incorrect spellings and need capitalization, thus the reason they are not in the .spelling file.

**Comment by ericvn** [comment]
I do see in one of the PR's the request that this change should be added. 

It is related to specifying a link for a header and the normal link for a header is all lowercase. Example from another file:
```
## Istio 的好处{#benefits-of-Istio}
```
The spellchecker checks each of the entries in this link, and if it was `istio` as it is by default, that fails. So in the translated files, where we actually specify the links, we have some of the links using uppercase characters to satisfy the spelling. So far that seems to be the norm. In the English docs, we don't override the links, so they aren't spellchecked. 

I'm reluctant to add the lowercase versions of the specific names as it would allow someone later to possibly not capitalize the name. I'm wondering if we can not spellcheck the specified links.

@craigbox What are your thoughts.

**Comment by craigbox** [comment]
I like the idea of not spell checking link anchors, but I don't know how much effort that is.

**Comment by ericvn** [comment]
https://github.com/istio/istio.io/pull/11159 removes the need to add entries for heading anchors.

**Pull request closed without merging**
