### PR TITLE
Change default monitoring port

### PR DESCRIPTION
**Pull request by ericvn**
Documentation updates that coincide with https://github.com/istio/istio/pull/11421 which changed the default monitoring port from 9093 to 15014.

WIP until that PR is merged.

### CODE REVIEW

**Comment by rcaballeromx** [comment]
@geeknoid Should we update the ports on the HTML of the reference guide or should the update take place in the code?

**Comment by geeknoid** [comment]
All the changes in docs/reference should be removed from this PR. The changes need to happen in the source code and they'll be reflected in the doc repo next time I run the grabReferenceDocs script.

**Comment by ericvn** [comment]
Per @geeknoid I removed the docs/reference file changes from this PR - Done

**Comment by ericvn** [comment]
Removed the [WIP] since the underlying [istio/istio#11421](https://github.com/istio/istio/pull/11421) was merged.

**Pull request merged**
