### PR TITLE
Blog for adding the suport of legacy Kubernetes service accounts

### PR DESCRIPTION
**Pull request by lei-tang**
Please provide a description for what this PR is for: blog for adding the suport of legacy Kubernetes service accounts.

[ ] Configuration Infrastructure
[X ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by adammil2000** [comment]
This blog post is so short, should it be added to the release notes instead? See this example from 1.4: https://istio.io/news/releases/1.4.x/announcing-1.4/

**Comment by lei-tang** [comment]
I am fine with either a blog or https://istio.io/news/releases/1.5.x/announcing-1.5/. https://istio.io/news/releases/1.5.x/announcing-1.5/ does not exist yet. We may first add the blog and then add a similar notice in https://istio.io/news/releases/1.5.x/announcing-1.5/.

**Comment by frankbu** [comment]
@lei-tang I agree with @adammil2000 that this is too short for a blog post. Please moving it to the 1.5 release notes.

**Comment by lei-tang** [comment]
Moved to https://istio.io/news/releases/1.5.x/announcing-1.5/. Please take a look.

**Comment by myidpt** [comment]
This should go into https://github.com/istio/istio.io/pull/6551.
Closing.

**Comment by myidpt** [comment]
It's already in the release notes.

**Pull request closed without merging**
