### PR TITLE
Add  envoy ratelimiting test

### PR DESCRIPTION
**Pull request by gargnupur**
Please provide a description for what this PR is for.
Added Envoy Ratelimiting Test. This is resurrection of PR https://github.com/istio/istio/pull/23513/
And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

Ref: https://github.com/istio/istio/issues/22068
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ X] Policies and Telemetry
[ ] Security
[X ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by frankbu** [comment]
This isn't a doc test, so it doesn't belong in this repo.

@gargnupur I think you sent this to the wrong repo, should have been `istio/istio`, not `istio/istio.io`.

**Comment by gargnupur** [comment]
@frankbu : We will be writing a blog post for this.. this is just an example for users on how to use envoy's ratelimiting, thus won't go to istio/istio repo. This is after discussions with @nmittler , @howardjohn and @mandarjog on istio/istio#23513

**Comment by ericvn** [comment]
@gargnupur If you want the test here, you'll need to provide the doc page that drives the test. Most tests would go under sample in istio/istio as @frankbu noted.

**Comment by frankbu** [comment]
@gargnupur I think there has been a misunderstanding. Examples that are described by docs do not belong in the istio/istio.io repo. They are either in istio/istio/samples, or if it's described in a blog (as opposed to mainline docs), it can be somewhere else completely (although istio/istio/samples, is fine for those as well). The only "tests" that belong in this repo are ones that "test the doc" itself (see https://github.com/istio/istio.io/blob/master/tests/README.md).

If you want to discuss this further, feel free to add it to agenda for the doc WG call.

**Pull request closed without merging**
