### PR TITLE
Update test reference to latest istio

### PR DESCRIPTION
**Pull request by ericvn**
Please provide a description for what this PR is for.

Test to see if latest istio changes fix prior testing issues: https://github.com/istio/istio.io/pull/10274

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by craigbox — APPROVED** [review]

**Comment by craigbox** [comment]
Is 5f52cdb related, Eric?

**Comment by ericvn** [comment]
@craigbox There seem to be a few changes that have happened in the istio branch like the rename of the chart. At this point I'm just trying to verify if they are changes in the docs, or more changes upstream.

**Comment by ericvn** [comment]
Hold to verify that removing the extraneous web hook is valid.

**Review by craigbox — APPROVED** [review]

**Pull request merged**
