### PR TITLE
gateway-api: enable mutual tls test

### PR DESCRIPTION
**Pull request by frankbu**
Depends on https://github.com/istio/istio/pull/41559.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by frankbu** [comment]
It looks like the test is failing because the required fix in https://github.com/istio/istio/pull/41559 is not available in the istio build being used by the test framework.

@ericvn Can you please confirm?

**Comment by ericvn** [comment]
@frankbu I can did into this further on Monday, but I believe that https://github.com/istio/istio/pull/41559 is only in the `master` branch and not in the `release-1.16` branch of istio/istio. istio.io is only testing against the 1.16 branch until it releases. We either need to move the istio function to 1.16 or will have to wait to merge this when we can accept 1.17 changes.

**Review by ericvn — APPROVED** [review]

**Review by kfaseela — APPROVED** [review]

**Pull request merged**
