### PR TITLE
Convert TCP traffic shifting test

### PR DESCRIPTION
**Pull request by frankbu**

### CODE REVIEW

**Comment by brian-avery** [comment]
These health check failures look like legitimate failures due to: https://github.com/istio/istio/issues/22602

v1alpha1/policy no longer exists.

**Comment by frankbu** [comment]
> v1alpha1/policy no longer exists.

@brian-avery yeah, that's hilarious, it was working earlier today when I converted the test. So now [this part of the document](https://preliminary.istio.io/docs/ops/configuration/mesh/app-health-check/#liveness-and-readiness-probes-with-command-option) is outdated and needs to be updated. I guess that's why we have these tests :)

**Pull request merged**
