### PR TITLE
Update Authentication page

### PR DESCRIPTION
**Pull request by jacob-delgado**
Fixes https://github.com/istio/istio.io/issues/7194

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by jacob-delgado** [comment]
@googlebot I consent

Not sure if this works. I can put up a PR if need be with my CLA verified email

**Comment by jacob-delgado** [comment]
@googlebot I signed it!

**Comment by jacob-delgado** [comment]
This may not work since I did it via the istio.io website and not git.

**Comment by frankbu** [comment]
@googlebot

**Comment by howardjohn** [comment]
@jacob-delgado you may need to add your username and/or github email to the CLA? is that possible? `38300436+jacob-delgado@users.noreply.github.com`

**Comment by jacob-delgado** [comment]
> @jacob-delgado you may need to add your username and/or github email to the CLA? is that possible? `38300436+jacob-delgado@users.noreply.github.com`

AFAIK it is managed by organization. Closed in lieu of https://github.com/istio/istio.io/pull/7198

**Pull request closed without merging**
