### PR TITLE
Add outlier check column in proxy config command

### PR DESCRIPTION
**Pull request by voanhduy1512**
Update docs for `istioctl proxy-config endpoints`, depends on https://github.com/istio/istio/pull/13119

### CODE REVIEW

**Comment by geeknoid** [comment]
@frankbu Looks good?

**Comment by frankbu** [comment]
This needs to wait for https://github.com/istio/istio/pull/13119 to be merged.
/hold

**Comment by voanhduy1512** [comment]
https://github.com/istio/istio/pull/13119 has been merged.

**Comment by geeknoid** [comment]
This PR now has a merge conflict. Could you rebase and repush so we can merge this?

Thanks.

**Pull request merged**
