### PR TITLE
remove namespce for cluster scope resources.

### PR DESCRIPTION
**Pull request by morvencao**
[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by ericvn** [comment]
@frankbu Thoughts on this change as I know you were working on the tests a short time ago? The updated line is run in the test.sh so I believe this change is OK.

**Review by frankbu — APPROVED** [review]
I agree this is better. Since it's a cluster-scoped resource, it's in every namespace, so explicitly using -n external-istiod is somewhat confusing.

**Review by ericvn — APPROVED** [review]

**Comment by ericvn** [comment]
circuit breaker test is still flakey.

**Pull request merged**
