### PR TITLE
[release-1.14] Update 1.14.4 test reference with another build

### PR DESCRIPTION
**Pull request by ericvn**
Please provide a description for what this PR is for.

Another 1.14.4 build

### CODE REVIEW

**Comment by ericvn** [comment]
Add a hold in case there is another build

**Review by frankbu — APPROVED** [review]

**Comment by ericvn** [comment]
Looking at the the first failure, we have an older issue where the pods are listed in different orders. We fixed in later releases.

**Comment by ericvn** [comment]
Running again since I think the failure is a flake, that we fixed later. Will look in a bit at back porting some of that.

**Review by craigbox — APPROVED** [review]

**Pull request merged**
