### PR TITLE
zh:sync /enabling-defense-in-depth-for-enterprise-applications/

### PR DESCRIPTION
**Pull request by windsonsea**
Sync with en.
```
content/zh/about/solutions/enabling-defense-in-depth-for-enterprise-applications/index.md
```

- [x] Docs

### CODE REVIEW

**Review by zirain — CHANGES_REQUESTED** [review]
this doc is not fully synced

**Comment by windsonsea** [comment]
> this doc is not fully synced

Checked the en version only has these text currently.

https://github.com/istio/istio.io/blob/master/content/en/about/solutions/enabling-defense-in-depth-for-enterprise-applications/index.md

**Review by zirain — APPROVED** [review]

**Comment by zirain** [comment]
I see, I will take a look at the case study page

**Comment by zirain** [comment]
FYI https://github.com/istio/istio.io/pull/12149

**Pull request merged**
