### PR TITLE
Tracing by default in the demo profile is 1%, not 100%

### PR DESCRIPTION
**Pull request by jgreens**
Noticed an inconsistency in the docs. Please close this PR if I am incorrect

### CODE REVIEW

**Comment by douglas-reid** [comment]
That certainly is not the intention: https://github.com/istio/istio/blob/master/manifests/profiles/demo.yaml#L51-L52

**Comment by frankbu** [comment]
Closing because this is not the intent. If it isn't working as documented, need to open an istio/istio issue.

**Pull request closed without merging**
