### PR TITLE
Add KubeCon EU Istio sessions to the blog

### PR DESCRIPTION
**Pull request by kfaseela**

### CODE REVIEW

**Review by linsun — COMMENTED** [review]
Thanks!!  If you search istio, i think we have a few more talks.  Worth adding them?

**Comment by kfaseela** [comment]
> Thanks!! If you search istio, i think we have a few more talks. Worth adding them?

will take a look

**Comment by dhawton** [comment]
> > Thanks!! If you search istio, i think we have a few more talks. Worth adding them?
> 
> will take a look

I'll hold off reviewing until you can look

**Comment by kfaseela** [comment]
@linsun I have added the missing sessions, you can take a look now.

**Review by dhawton — APPROVED** [review]
LGTM. Threw a DNM as you asked @linsun for a review. Feel free to remove when ready to publish.

**Review by linsun — APPROVED** [review]
Thanks Faseela

**Pull request merged**
