### PR TITLE
update istio.io/istio

### PR DESCRIPTION
**Pull request by zirain**
manual update istio.io/istio to latest, cc @ericvn

### CODE REVIEW

**Comment by ericvn** [comment]
Looks like possible another annotation was added without adding it in istio/api:
```
received:
"Warning [IST0108] (Pod default/bookinfo-gateway-istio-59ccf58b67-f8n6q) Unknown annotation: istio.io/rev
Warning [IST0108] (Pod default/details-v1-6997d94bb9-dp9pl) Unknown annotation: istio.io/rev
Warning [IST0108] (Pod default/productpage-v1-58b4c9bff8-v7mpk) Unknown annotation: istio.io/rev
Warning [IST0108] (Pod default/ratings-v1-b8f8fcf49-4z6jb) Unknown annotation: istio.io/rev
Warning [IST0108] (Pod default/reviews-v1-5896f547f5-csvvx) Unknown annotation: istio.io/rev
Warning [IST0108] (Pod default/reviews-v2-5d99885bc9-7k8pf) Unknown annotation: istio.io/rev
Warning [IST0108] (Pod default/reviews-v3-589cb4d56c-fn5p7) Unknown annotation: istio.io/rev"
expected:
"✔ No validation issues found when analyzing namespace: default."
```

**Comment by ericvn** [comment]
Looking, we need https://github.com/istio/api/pull/2743 to merge.

**Comment by zirain** [comment]
replaced by https://github.com/istio/istio.io/pull/13030

**Pull request closed without merging**
