### PR TITLE
zh: fix typo for glossary page

### PR DESCRIPTION
**Pull request by songleo**

### CODE REVIEW

**Comment by loverto** [comment]
- ./public/blog/2017/0.1-announcement/index.html
  *  External link https://www.projectcalico.org/welcoming-istio-to-the-kubernetes-networking-community failed: got a time out (response code 301)
htmlproofer 3.9.2 | Error:  HTML-Proofer found 1 failure!

**Comment by loverto** [comment]
重新提交以解决该问题

**Comment by songleo** [comment]
@loverto Hello, do you mean to close this PR and resubmit a PR?  thank you.

**Comment by SataQiu** [comment]
Create an empty commit, then push it to trigger the CI.
```sh
$ git commit --allow-empty -m "retest" && git push
```

**Comment by songleo** [comment]
.@SataQiu thanks for your help.

**Pull request merged**
