### PR TITLE
Try to fix doc test

### PR DESCRIPTION
**Pull request by hanxiaop**
Please provide a description for what this PR is for.

This PR https://github.com/istio/istio/pull/43041 adds Jaeger to otel collector but actually it is not installed. Temporarily add Jaeger deployment to fix the test, will add otel tracing test as well once the doc is finished.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [x] Developer Infrastructure

### CODE REVIEW

**Comment by hanxiaop** [comment]
Looks like it still has the issue after deploying Jaeger.
```
Creating test debug file: /logs/artifacts/tests-setup-profile-demo-9d0dee/TestDocs/tasks/observability/logs/otel-provider/test.sh/test.sh/_test_context/test.sh_debug.txt
deployment.apps/jaeger created
service/tracing created
service/zipkin created
service/jaeger-collector created
Waiting for deployment "jaeger" rollout to finish: 0 of 1 updated replicas are available...
deployment "jaeger" successfully rolled out
configmap/opentelemetry-collector-conf created
service/opentelemetry-collector created
deployment.apps/opentelemetry-collector created
Waiting for deployment "opentelemetry-collector" rollout to finish: 0 of 1 updated replicas are available...
deployment "opentelemetry-collector" successfully rolled out
telemetry.telemetry.istio.io/sleep-logging created
namespace/default not labeled
serviceaccount/sleep created
service/sleep created
deployment.apps/sleep created
Waiting for deployment "sleep" rollout to finish: 0 of 1 updated replicas are available...
deployment "sleep" successfully rolled out
serviceaccount/httpbin created
service/httpbin created
deployment.apps/httpbin created
Waiting for deployment "httpbin" rollout to finish: 0 of 1 updated replicas are available...
deployment "httpbin" successfully rolled out
VERIFY FAILED snip_test_the_access_log_2 (timeout after 120s):
received:
"2023-03-14T11:07:30.414Z	info	otlpreceiver/otlp.go:88	Starting HTTP server on endpoint 0.0.0.0:4318	{"kind": "receiver", "name": "otlp", "pipeline": "traces"}
2023-03-14T11:07:30.414Z	info	pipelines/pipelines.go:106	Exporter started.	{"kind": "receiver", "name": "otlp", "pipeline": "traces"}
2023-03-14T11:07:30.414Z	info	pipelines/pipelines.go:102	Exporter is starting...	{"kind": "receiver", "name": "opencensus", "pipeline": "traces"}
2023-03-14T11:07:30.414Z	info	pipelines/pipelines.go:106	Exporter started.	{"kind": "receiver", "name": "opencensus", "pipeline": "traces"}
2023-03-14T11:07:30.415Z	info	pipelines/pipelines.go:102	Exporter is starting...	{"kind": "receiver", "name": "otlp", "pipeline": "logs"}
2023-03-14T11:07:30.415Z	info	pipelines/pipelines.go:106	Exporter started.	{"kind": "receiver", "name": "otlp", "pipeline": "logs"}
2023-03-14T11:07:30.415Z	info	healthcheck/handler.go:129	Health Check state change	{"status": "ready"}
2023-03-14T11:07:30.415Z	info	service/collector.go:220	Starting otelcol...	{"Version": "0.54.0", "NumCPU": 16}
2023-03-14T11:07:30.415Z	info	service/collector.go:128	Everything is ready. Begin running and processing data.
2023-03-14T11:07:31.414Z	info	jaegerexporter@v0.54.0/exporter.go:186	State of the connection with the Jaeger Collector backend	{"kind": "exporter", "data_type": "traces", "name": "jaeger", "state": "READY"}"
expected:
"outbound|8000||httpbin.default.svc.cluster.local"
```

**Comment by ericvn** [comment]
That's what I saw yesterday when I did a quick test deploying jaeger thinking it would solve the problem. I was't sure what needs to be updated.

**Comment by hanxiaop** [comment]
@ericvn Looks like the meshconfig is incorrect which leads to the problem, created a fix https://github.com/istio/istio/pull/43940

**Comment by ericvn** [comment]
Hopefully, this is now covered by https://github.com/istio/istio.io/pull/12895.

**Comment by hanxiaop** [comment]
> #12895

Yes it's already covered. Thanks

**Comment by hanxiaop** [comment]
Close since https://github.com/istio/istio.io/pull/12895 has been merged.

**Pull request closed without merging**
