### PR TITLE
Slack updates

### PR DESCRIPTION
**Pull request by craigbox**
Replace "istio.slack.com" with "slack.istio.io" throughout the site, as we are now in "open invite, no form".

slack.istio.io:

- if you're logged in, will take you straight to slack
- if you're not logged in, will ask for your email
  - if you aren't on the workspace, it will create you an account
  - if you already were, if will send you a link to login

This feels like a better compromise than sending people to a link where they can enter a username/password if they are a user, but get no help on what to do next if they are not.

/cc @rvennam @louiscryan 

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by craigbox** [comment]
I only really want commit 4c71be9 here - is there a simple way to remove all the rest?

**Comment by frankbu** [comment]
@craigbox Not sure what "the rest" that you don't want is. Looks like there are 11 vs 9 changed files. If you just don't want the two extra changes, then git pull the original versions of those two files in your local branch and push the result.

Also, not sure why the CLA bot is complaining. 

^^^ @howardjohn?

**Comment by ericvn** [comment]
Googlebot probably want's @davidhauck consent since he did one of the commits.

**Comment by davidhauck** [comment]
Yeah some of those commits shouldn't be getting merged in here. The commit of mine is already in master.

@craigbox create a new branch off of master (after fetching latest), and then cherry pick the commit you want. e.g.

git fetch
git checkout master
git merge origin/master --ff-only
git checkout -b new_branch_name
git cherry-pick 4c71be9
git push origin

and then create a new PR off of new_branch_name

**Comment by craigbox** [comment]
I can do it that way, but I was trying to figure out how to do it in this
branch. :)

**Comment by ericvn** [comment]
I think could do an interactive rebase of the current branch on upstream/master and then drop the commits you don't want (save everything first). Then you'd have to do a force push.

`git rebase -i upstream/master`

**Comment by frankbu** [comment]
Closing for now. @craigbox please reopen when it's ready to merge.

**Pull request closed without merging**
