### PR TITLE
Polidea update - FAQ page

### PR DESCRIPTION
**Pull request by agatastpa**
PR contains FAQ page.

Note: Table of contents component will be improved in later PR. 

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by craigbox** [comment]
/ok-to-test

The jumping doesn't quite work (possibly because of the header overlap?) 

For example, when I hit "Applications"

image

**Comment by agatastpa** [comment]
@craigbox thanks for your comment - whole 'Table of contents' component will be improved in later later PR, including improved styles.

**Comment by craigbox** [comment]
lol,  hello Albert 😸 
/cc @qwertyuiop888

**Comment by qwertyuiop888** [comment]
hi Craig, im just spectating 😄. @agatastpa the changes look amazing so far!

**Pull request merged**
