### PR TITLE
[zh] Translate all in-Pod blog flow images into Chinese

### PR DESCRIPTION
**Pull request by wilsonwu**
## Description

Translate all in-Pod blog flow images into Chinese

## Reviewers

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [x] Localization/Translation

### CODE REVIEW

**Comment by windsonsea** [comment]
content/zh/blog/2024/inpod-traffic-redirection-ambient/pod-added-to-ambient.svg
- Istio-cni 节点代理监视为 Ambient 打了标签的新 Pod

**Comment by windsonsea** [comment]
content/zh/blog/2024/inpod-traffic-redirection-ambient/traffic-flows-between-pods-in-ambient.svg

右侧绿色文字：
在端口 15008 上作为 HBONE 保留 Pod（目标端口 5151）

- 通过本地 ztunnel 嗅探进出 Pod 的所有流量
- `带有长长蒿草的 Sidecar` 说法太奇怪了，这应该是一个方言行话，需要反复调研

**Comment by windsonsea** [comment]
content/zh/blog/2024/inpod-traffic-redirection-ambient/traffic-flows-plaintext.svg

- 通过本地 ztunnel 嗅探进出 Pod 的所有流量
- `带有长长蒿草的 Sidecar` 很奇怪，这应该是一个俚语，需要去调研

**Comment by wilsonwu** [comment]
All suggestions applied.

For the `sidecar with long, long straws`, I think it is a metaphor sentence, just like we also said "什么东西长草了", means it is too old.

Not sure it is correct or not.

**Comment by windsonsea** [comment]
@hanxiaop , is any special opinion about this sentence:

Sidecar with long, long straws

**Comment by hanxiaop** [comment]
> @hanxiaop , is any special opinion about this sentence:
> 
> * sidecar with long, long straws

@windsonsea Not a English expert, I think it means that something is not apparent and is hidden behind something else?

**Comment by hanxiaop** [comment]
Maybe something like `一种不显而易见的边车`

**Comment by wilsonwu** [comment]
Let's wait for more suggestions for this translation.

**Comment by wilsonwu** [comment]
> Maybe something like `一种不显而易见的边车`

Based on this opinion, seems it means “隐藏很深的边车”

**Comment by wilsonwu** [comment]
> 一种不显而易见

I'd like to apply this if no better translation.

**Review by windsonsea — APPROVED** [review]
well, lgtm

**Pull request merged**
