### PR TITLE
Fixed tiny grammar problem.

### PR DESCRIPTION
**Pull request by dsbos**
Fixed to intended verb "set up" (from actually written noun "setup").

### CODE REVIEW

**Comment by frankbu** [comment]
@dsbos Please sign the CLA so we can merge your fix. Thanks.
https://github.com/istio/istio.io/pull/7393#issuecomment-633242991

**Comment by dsbos** [comment]
> @dsbos Please sign the CLA so we can merge your fix. Thanks.

Okay, signed.

I'm pretty sure I signed it before. (I definitely signed it before for something; I _think_ it was for Istio.) Why did I have to sign it again?

**Comment by dsbos** [comment]
I wrote:

> Okay, signed.

But I see that the checks still say "cla/google — Need a CLA for one or more commit authors "

Did signing the CLA not succeed? Did I miss something?

**Comment by frankbu** [comment]
@dsbos You need to add a single line comment that says: `@googlebot I signed it!`

**Comment by dsbos** [comment]
@googlebot I signed it!

**Comment by howardjohn** [comment]
@dsbos did you follow the steps to associate the CLA email you signed with your github account? The CLA tool is looking for a cla for your username `@users.noreply.github.com` which may not be what you signed the CLA with

**Comment by dsbos** [comment]
> The CLA tool is looking for a cla for your username @users.noreply.github.com which may not be what you signed the CLA with

Where is it getting `@users.noreply.github.com` from?

That looks somewhat like a From/Reply-To address for notifications from GitHub.

That's certainly not any GitHub ID or e-mail address of mine.

**Comment by howardjohn** [comment]
@dsbos I think github automatically creates it if you don't have an email associated with your account (or maybe if you don't make it "public"?)

**Comment by dsbos** [comment]
> @dsbos I think github automatically creates it if you don't have an email associated with your account (or maybe if you don't make it "public"?)

But I have an e-mail address associated with my GitHub account. (If I didn't, I wouldn't getting the e-mail notifications I'm getting from GitHub about these comments on this PR.)

**Comment by dsbos** [comment]
Okay, here's something:

I went to my GitHub page/account, went to my fork of `istio.io` (created using the "Edit this Page on GitHub"), cloned that repository locally, looked at branches `patch-1` and `patch-2`, and looked at the commits.

Both commit contain `@users.noreply.github.com` as part of the author e-mail address:

`Author: Daniel Barclay <dsbos@users.noreply.github.com>`

Why is the CLA checker taking `@users.noreply.github.com` as a user name (per https://github.com/istio/istio.io/pull/7393#issuecomment-636898453)?

**Comment by howardjohn** [comment]
Sorry I think it was not clear. Its looking for a CLA for `dsbos@users.noreply.github.com`. I assume you signed it with some real non github email so it fails?

**Comment by dsbos** [comment]
> Its looking for a CLA for dsbos@users.noreply.github.com.

Roger. But why it is doing that? 

I signed a similar CLA used on GitHub (probably an Apache Foundation one (for Kubernetes?), and haven't had any trouble with not making my e-mail address public. 

> I assume you signed it with some real non github email ...
Yes

**Comment by dsbos** [comment]
@googlebot I signed it!

**Pull request merged**
