### PR TITLE
doc: Fix typo

### PR DESCRIPTION
**Pull request by imjoey**
Correct the word `shceme` to `scheme`.

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by imjoey** [comment]
@googlebot I signed it!

**Comment by geeknoid** [comment]
We've been revising our CI system and this PR got stuck in the middle. Could you please rebase and repush please?

Sorry for the inconvenience.

**Comment by imjoey** [comment]
Hi @geeknoid , that's all right. Code rebasing is done. Thanks for your work.

**Pull request merged**
