### PR TITLE
Add istio ecosystem project to 1.4 release notes.

### PR DESCRIPTION
**Pull request by aattuluri**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by aattuluri** [comment]
@geeknoid Please let me know if this can go in istio 1.3.4 release notes.

**Comment by geeknoid** [comment]
The istio-ecosystem stuff is not officially supported by the Istio project, so I don't believe we should mention this in the Isito release notes.

Thanks.

**Comment by aattuluri** [comment]
@geeknoid 
I saw that its mentioned in [1.2 release notes](https://istio.io/news/2019/announcing-1.2/). Hence, submitted this.

**Comment by sdake** [comment]
@aattuluri Thank you for the submission and interest in the release notes process. While those two projects were added to the 1.2 release notes, I don't believe they should have been.

It was a clear mistake for us to document ecosystem projects on the istio.io website because those projects don't follow the Istio governance model. If they were to be imported into the istio github namespace, there is a hard requirement that the component follows the [documented](https://github.com/istio/community) Istio governance processes. In exchange, the new component would have full access to all Istio resources when applying the dev/alpha/beta/stable release criteria.

I'm not sure what is left for this PR but I hope to see your work in the wild :)

Cheers
-steve

**Comment by aattuluri** [comment]
@sdake Thanks for the explanation, I am closing the PR.

**Pull request closed without merging**
