### PR TITLE
Twitter logo update

### PR DESCRIPTION
**Pull request by tmsagarofficial**
This PR is reference to https://github.com/istio/community/issues/1240
Pls check and let me know with any discussion

- [x] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [x] Developer Infrastructure

### CODE REVIEW

**Comment by wilsonwu** [comment]
You can find a white color logo from: https://about.twitter.com/en/who-we-are/brand-toolkit

**Comment by wilsonwu** [comment]
> You can find a white color logo from: https://about.twitter.com/en/who-we-are/brand-toolkit

You just done, sorry.

**Comment by kfaseela** [comment]
you can see the preview here: https://deploy-preview-14053--preliminary-istio.netlify.app/

**Comment by wilsonwu** [comment]
> what does ok-to-test mean exactly in simple terms ??

It is a rule for istio community, new contributter must get a ok-to-test from maintainer then the CI works.

**Comment by wilsonwu** [comment]
> you can see the preview here: https://deploy-preview-14053--preliminary-istio.netlify.app/

Looks very good.

**Review by ericvn — APPROVED** [review]

**Pull request merged**
