### PR TITLE
update azure platform setup

### PR DESCRIPTION
**Pull request by phillipgibson**
Please provide a description for what this PR is for.

Update the Azure Platform Setup doc.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by phillipgibson** [comment]
@ericvn Can you help me out why the lint job is failing? Thanks.

**Comment by ericvn** [comment]
@phillipgibson If you click on `link` for the failing test, it will take you to the failing job. There you can click on the build log link and you will see this:
```
  ./en/docs/setup/platform-setup/azure/index.md
       80 | : It is possible to use other api model definitions which will  
       80 | ich will work with Istio. The MutatingAdmissionWebhook and ValidatingAdmissionWebhoo 
       80 |  MutatingAdmissionWebhook and ValidatingAdmissionWebhook admission control flags and R 
       80 |  are enabled by default. See [aks-engine api model default values](htt 
       80 | d by default. See [aks-engine api model default values](https:/ 

>> 5 spelling errors found in 903 files
```
If you run `make test` locally (it takes a while), the actual misspelled words will be in red.

I suspect api should be API on 3 lines, and you will need backticks around the specific web hook names.

**Comment by phillipgibson** [comment]
> @phillipgibson If you click on `link` for the failing test, it will take you to the failing job. There you can click on the build log link and you will see this:
> 
> ```
>   ./en/docs/setup/platform-setup/azure/index.md
>        80 | : It is possible to use other api model definitions which will  
>        80 | ich will work with Istio. The MutatingAdmissionWebhook and ValidatingAdmissionWebhoo 
>        80 |  MutatingAdmissionWebhook and ValidatingAdmissionWebhook admission control flags and R 
>        80 |  are enabled by default. See [aks-engine api model default values](htt 
>        80 | d by default. See [aks-engine api model default values](https:/ 
> 
> >> 5 spelling errors found in 903 files
> ```
> 
> If you run `make test` locally (it takes a while), the actual misspelled words will be in red.
> 
> I suspect api should be API on 3 lines, and you will need backticks around the specific web hook names.

Ok. The test failed on previously merged content that was not a part of my PR. Let me see about addressing it.

**Comment by phillipgibson** [comment]
@ericvn I think we got everything taken care of to merge.

**Review by ericvn — APPROVED** [review]

**Pull request merged**
