### PR TITLE
Fix flakiest test

### PR DESCRIPTION
**Pull request by ericvn**
Please provide a description for what this PR is for.

tasks/traffic-management/tcp-traffic-shifting/gtwapi_test.sh seems to be the flakiest test at the moment. Disabling it.

### CODE REVIEW

**Comment by frankbu** [comment]
The cause of this test failing seems to be:
```
memcache.go:238] couldn'\''t get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
```

which IIUC is because the kubectl kubeconfig isn't set correctly ... seems like there's something (timing?) that sometimes causes the test to run without proper setup.

It would be good to try to track down the actual setup(?) problem.

**Comment by ericvn** [comment]
@frankbu I agree it's some sort of timing issue as most flakes are. If you have time to chase that.

**Comment by ericvn** [comment]
Agree in the bad case I see this in the log:
```
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec '' -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
```
where normally the exec `` is exec sleep-...

**Comment by ericvn** [comment]
Looking at another log, it has the same. The sleep is found for the first call, but not the remainder....

**Comment by ericvn** [comment]
Try update to only get value once (which seems to work) and use it repeatedly instead of getting value each time.

**Comment by frankbu** [comment]
I agree that not repeatedly getting the sleep pod is better, regardless of whether or not it fixes the flake, but if it does fix it, it would be good to get to the bottom of why it does. I can't see any reason why it shouldn't work with the repeated get, unless there's some kind of kubernetes timing issue, maybe related to the fact that it's repeatedly calling exec that does tcp network calls?

**Comment by frankbu** [comment]
Another puzzling question is why does the exact same get/exec loop not flake when we run the same test using Istio config instead of Gateway API before it calls `snip_apply_weightbased_tcp_routing_4`? Very strange

**Comment by kfaseela** [comment]
> I agree that not repeatedly getting the sleep pod is better, regardless of whether or not it fixes the flake, but if it does fix it, it would be good to get to the bottom of why it does. I can't see any reason why it shouldn't work with the repeated get, unless there's some kind of kubernetes timing issue, maybe related to the fact that it's repeatedly calling exec that does tcp network calls?

It is calling in a tight loop. We can see how this behaves when we do the same locally using a simple script.

**Review by frankbu — APPROVED** [review]
Let's merge and see if this reduces the number of flakes going forward. If it does, would be nice to figure out why.

**Comment by kfaseela** [comment]
thanks @ericvn !

**Comment by ericvn** [comment]
Shucks. The issue is still there:
```
+++__verify_with_retry(): snip_apply_weightbased_tcp_routing_4
++++snip_apply_weightbased_tcp_routing_4(): kubectl get pod -l app=sleep -n istio-io-tcp-traffic-shifting -o 'jsonpath={.items..metadata.name}'
+++snip_apply_weightbased_tcp_routing_4(): export SLEEP=sleep-bc9998558-5xngk
+++snip_apply_weightbased_tcp_routing_4(): SLEEP=sleep-bc9998558-5xngk
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
++__verify_with_retry(): out='E0120 19:54:49.503134  173438 memcache.go:238] couldn'\''t get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0120 19:54:49.503987  173438 memcache.go:238] couldn'\''t get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0120 19:54:49.506018  173438 memcache.go:238] couldn'\''t get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0120 19:54:49.507929  173438 memcache.go:238] couldn'\''t get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?
E0120 19:54:49.590281  173451 memcache.go:238] couldn'\''t get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0120 19:54:49.591137  173451 memcache.go:238] couldn'\''t get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0120 19:54:49.592988  173451 memcache.go:238] couldn'\''t get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0120 19:54:49.594973  173451 memcache.go:238] couldn'\''t get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
```
Something more kubernetes related.

**Comment by ericvn** [comment]
Is the sleep pod stopped for some reason?

**Pull request merged**
