### PR TITLE
Remove anyuid instructions for OpenShift

### PR DESCRIPTION
**Pull request by rh-tokeefe**
These instructions are no longer needed after these changes https://github.com/istio/istio/pull/45394

### CODE REVIEW

**Comment by jwendell** [comment]
This targets 1.20
/hold

**Comment by jwendell** [comment]
It looks like my `/hold` above did not do the trick :)

**Comment by ericvn** [comment]
> It looks like my `/hold` above did not do the trick :)

I think the /commands need to be on the first line

**Review by jwendell — APPROVED** [review]

**Review by dhawton — APPROVED** [review]
LGTM

**Comment by ericvn** [comment]
Main branch is now 1.20, removing hold.

**Pull request merged**
