### PR TITLE
Added a FAQ - describes ztunnel is not a SPOF.

### LINKED ISSUE #15246: Add ambient mode section to FAQ
start with "Is ztunnel a SPOF?" - content from https://blog.howardjohn.info/posts/ambient-spof/

### PR DESCRIPTION
**Pull request by ayushrakesh**
## Description

Added a FAQ describing why ztunnel is not a Single Point of Failure.

## Reviewers

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

### CODE REVIEW

**Comment by kfaseela** [comment]
please sign the CLA

**Comment by ayushrakesh** [comment]
> please sign the CLA

@kfaseela  I have signed now, please check it

**Comment by kfaseela** [comment]
cc @howardjohn

**Pull request closed without merging**
