### PR TITLE
Define and link SDS on first mention

### PR DESCRIPTION
**Pull request by adammil2000**
Solve the problem where the user gets confused because we talk about SDS all of a sudden as if we've already explained it to them.

### CODE REVIEW

**Comment by ericvn** [comment]
Not a very exhaustive search (just the other platform setup pages), but I think the `docs/setup/platform-setup/minikube/` page could use the same change.

**Comment by ericvn** [comment]
@adammil2000 Did you want to pick up the change in the minikube file I mentioned above as well?

**Comment by adammil2000** [comment]
Fixed, thanks!

**Comment by ericvn** [comment]
@adammil2000 I believe I got the spife changes in #6379 so if you remove the last commit from this PR, it should remove the additional approvers and this PR might merge?

**Comment by DonaldSpencer** [comment]
Testing 123

**Pull request merged**
