### PR TITLE
[release-1.8] change header for platform per TOC guidance (#8788)

### PR DESCRIPTION
**Pull request by jacob-delgado**
Cherry-pick of f7ece2bc0136150fbce53df68b04a24778d7e4db into release-1.8 branch

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by ericvn** [comment]
Note that the TOC approved a slight change to what's in master so a future cherry pick will include that change plus this change.

**Comment by ericvn** [comment]
Also noting there is an automated cherry pick in #8827

**Comment by jacob-delgado** [comment]
Also cherry-picked 91f02268ad79a268d6df4286803be57679522092

**Comment by jacob-delgado** [comment]
@googlebot I consent.

**Comment by ericvn** [comment]
@googlebot I consent.

**Review by ericvn — APPROVED** [review]

**Pull request merged**
