### PR TITLE
updated azure platform setup

### PR DESCRIPTION
**Pull request by phillipgibson**
Please provide a description for what this PR is for.

Update Azure Platform Setup

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by phillipgibson** [comment]
I have signed the EasyCLA numerous times. Not sure what the test is failing on.

**Comment by ericvn** [comment]
Currently, the EasyCLA is not required. I'm not sure why it is failing for you however.

**Comment by phillipgibson** [comment]
> https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user might have some information on fixing this.

@ericvn I believe I fixed the link now. Please verify.

**Comment by ericvn** [comment]
@phillipgibson I do see the name as a link, so would think that it would be fixed.

**Comment by phillipgibson** [comment]
I'm going to close this PR and start with a new clone.

**Pull request closed without merging**
