### PR TITLE
Manually cherry pick 1.22.5, 1.23.2 release notes and 2024-006 security update with all fixes to master

### PR DESCRIPTION
**Pull request by wilsonwu**
## Description

Cherry pick #15710 #15712 #15713

Just update the docs without all snips, please review it is correct or not.

## Reviewers

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

### CODE REVIEW

**Comment by dhawton** [comment]
Hold off until they're merged please, since the 1.21 release note will change.

**Review by dhawton — CHANGES_REQUESTED** [review]
1.21 release note will not match this.

**Comment by wilsonwu** [comment]
> 1.21 release note will not match this.

Done, remove the 1.21 changes.

**Comment by dhawton** [comment]
Closing to redo so they're cherrypicked with proper attributions to the author(s).

**Pull request closed without merging**
