### PR TITLE
zh-translation:content/zh/faq/general/where-is-the-documentation.md

### PR DESCRIPTION
**Pull request by lilinji**
https://github.com/servicemesher/istio-official-translation/issues/1409

### CODE REVIEW

**Comment by lilinji** [comment]
> /ok-to-test

**Comment by lilinji** [comment]
> @lilinji: The following test **failed**, say `/retest` to rerun them all:
> 
> Test name	Commit	Details	Rerun command
> lint_istio.io	[865fa8b](https://github.com/istio/istio.io/commit/865fa8b0de684e6e3cecafbe4ad94a7cc2eb79c8)	[link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio.io/5394/lint_istio.io/1391)	`/test lint_istio.io`

/retest

**Comment by tanjunchen** [comment]
Please Fix Conflicts.
I think it can be merged Once review

**Comment by tanjunchen** [comment]
@rootsongjc  @lilinji    这个已经被翻译了 并且英文原文变了 建议关闭

**Comment by lilinji** [comment]
好的 一会我关闭

发自我的iPhone

**Pull request closed without merging**
