### PR TITLE
Update current version to 1.12.1

### PR DESCRIPTION
**Pull request by dgn**

### CODE REVIEW

**Comment by dgn** [comment]
added a hold we can sync with pushing the release live

**Review by ericvn — APPROVED** [review]
I typically add another commit to the cherry-pick PR with the data/args.yaml change, but will approve this manual one.

**Comment by dgn** [comment]
> I typically add another commit to the cherry-pick PR with the data/args.yaml change, but will approve this manual one.

good to know :) will do that next time. thanks!

**Pull request merged**
