### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by TC-wang**
**Documentation bug**

Fix meshConfig location in IstioOperator.

- [ ] Configuration Infrastructure
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by craigbox — APPROVED** [review]

**Comment by rvennam** [comment]
@TC-wang have you signed the CLA? https://github.com/istio/istio.io/pull/10393/checks?check_run_id=3740017159

**Comment by TC-wang** [comment]
> @TC-wang have you signed the CLA? https://github.com/istio/istio.io/pull/10393/checks?check_run_id=3740017159


@rvennam thank you. I have signed the CLA. Please scan it again

**Comment by rvennam** [comment]
@TC-wang still failing... 44******9@qq***m

**Comment by ajyuan** [comment]
Hi, noticed some confusion with the CLA check. It now gets re-run by pressing the Re-run button in the details for the check (on the left side of https://github.com/istio/istio.io/pull/10393/checks?check_run_id=3740017159), instead of by GitHub comments.

**Pull request merged**
