### PR TITLE
Update polidea - update style and ts linters

### PR DESCRIPTION
**Pull request by Jakub-Sadowski**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by davidhauck** [comment]
lgtm

**Comment by aijamalnk** [comment]
Thanks everyone! Is this ready to merge?

**Comment by ericvn** [comment]
OK. This is against another branch that doesn't actually run the `lint` test. Was expecting that to be here, but I guess will be run when the changes are made in a PR on the main branch.

**Review by craigbox — APPROVED** [review]

**Pull request merged**
