### PR TITLE
Update DaoCloud link to latest version of mesh product

### PR DESCRIPTION
**Pull request by wilsonwu**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by hanxiaop — APPROVED** [review]
/lgtm

**Comment by ericvn** [comment]
DO we have any confirmation from DaoCloud that this link should be updated?

**Comment by kebe7jun** [comment]
> Do we have any confirmation from DaoCloud that this link should be updated?

I can confirm that there is no problem.

**Review by kebe7jun — APPROVED** [review]

**Review by ericvn — APPROVED** [review]
Thanks for the confirmation

**Pull request merged**
