### PR TITLE
Blog post - Istio Vulnerability Scanner tool

### PR DESCRIPTION
**Pull request by chaltenio**
## Description

Blog post announcement - Free Istio Vulnerability Scanner tool.

## Reviewers

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

### CODE REVIEW

**Comment by linsun** [comment]
/hold

The steering committee is discussing if this is appropriate to post as a blog.

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by linsun** [comment]
I saw @craigbox closed this without comment, was not sure if the feedback was provided to the PR author. For transparency, steering has discussed this blog and don't think we should publish it in istio.io.

**Comment by craigbox** [comment]
The feedback was provided :)

**Comment by chaltenio** [comment]
Thanks for the update folks. I would appreciate it if you could establish guidelines for blog posts so that we know what is allowed and what is not next time.

Regarding those steering discussions, are they recorded and uploaded on Youtube for transparency? Cheers

**Comment by craigbox** [comment]
No, they're not.  We have thoughts on how to improve the process.

Guidelines are definitely on the backlog.

**Pull request closed without merging**
