### PR TITLE
Ambient install user sub-guides

### PR DESCRIPTION
**Pull request by srampal**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [X] Ambient
- [X] Docs
- [X] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by craigbox** [comment]
Given all the recent changes, should we try and revive this PR @srampal?

**Comment by srampal** [comment]
> Given all the recent changes, should we try and revive this PR @srampal?

@craigbox so the original plan for ambient user guides was to have "install"/ "upgrade" related user guides as pages/ docs within the "User guides" folder.  However a "Helm install" doc was added in the top level folder and the index.md in this commit was also somewhat out of date given all the changes we made to the ztunnel user's giude etc.  So now the questions are:  (1) Do we expect to have multiple user guides related to "install/upgrade" type operations for ambient ? (2) Should all such user guides including the "helm install" user guide in the parent folder be moved inside the overall "user guides" folder ?    If yes, then lets first just move the helm install user guide into this folder for now and later add more install/ upgrade guides either via this PR/ issue and/or new ones. Thoughts ?

**Comment by craigbox** [comment]
By 1.22, I think we want to have a hierarchy which looks like

/docs/setup/install/
/docs/setup/upgrade/

/docs/ambient/setup/install
/docs/ambient/setup/upgrade

(etc)

So, for now, if the content is good and useful, let's get it merged in a place that makes sense for the current hierarchy - under `/docs/ops/ambient/install/` I guess - and we can move things around as we need.

**Comment by craigbox** [comment]
(See https://docs.google.com/spreadsheets/d/1ag5zhMOm2flEK7w5D7Sv3pbpHsx7afG2hs74-h2MHCY/edit#gid=0 which suggests that we will have install docs for Helm and istioctl both.)

**Comment by craigbox** [comment]
Do you think there's anything in this draft which we should lift out, or should we close it? @srampal

**Pull request closed without merging**
