### PR TITLE
Fix Default dnsRefreshRate

### PR DESCRIPTION
**Pull request by srmars**
Please provide a description for what this PR is for.

This PR is related to https://github.com/istio/istio/issues/42075

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by zirain** [comment]
reference page is generated from api, so you should send a PR to api repo.

**Review by ericvn — CHANGES_REQUESTED** [review]
See th stop of this file. This file is copied from another repo and the change will need to be made there,

**Comment by ericvn** [comment]
This change should be made here: https://github.com/istio/api/blob/master/mesh/v1alpha1/config.proto#L304.

Closing this PR.

**Pull request closed without merging**
