### PR TITLE
Fix PR template checklist format

### PR DESCRIPTION
**Pull request by gonzaloserrano**
Fixes checklist being properly rendered when creating a new PR.

### CODE REVIEW

**Comment by craigbox** [comment]
/ok-to-test

Thanks for the PR!  I'll leave it for someone to check that the assignment automation still works if this becomes a MD-rendered list.

**Comment by gonzaloserrano** [comment]
No progress on this, so I'm closing it.

**Comment by craigbox** [comment]
Sorry Gonzalo; maybe @brian-avery will know?

**Comment by brian-avery** [comment]
Just tested this and it works -- https://github.com/istio/bots/pull/392

**Review by brian-avery — APPROVED** [review]

**Comment by brian-avery** [comment]
@craigbox can you please approve this now?

**Comment by craigbox** [comment]
Certainly!

**Review by craigbox — APPROVED** [review]

**Pull request merged**
