### PR TITLE
1.23.3 Release notes 

### PR DESCRIPTION
**Pull request by thedebugger**

### CODE REVIEW

**Review by dhawton — APPROVED** [review]

**Comment by thedebugger** [comment]
Release has been published (currently in draft mode) https://github.com/istio/istio/releases

**Comment by mikemorris** [comment]
Looks like there's a diff on `go.mod` when rerunning `make gen`, may need to just try rerunning that and committing the diff.

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
Direct merge, see https://istio.slack.com/archives/C078Q0ZLFLK/p1729790387937259 for context

**Comment by thedebugger** [comment]
Why we forced merge this PR - Some tests were failing tests because kong/httpbin broke upstream. We pulled in go based httpbin changes from master but now tests are failing because the httpbin output has changed and for other reasons as well. But those failures were unrelated to 1.23.3, so we forced merged to unblock the release. Thanks @howardjohn for help

**Pull request merged**
