### PR TITLE
fix(): add missing cleanup instructions

### PR DESCRIPTION
**Pull request by jaellio**
Please provide a description for what this PR is for.
Part of #11720

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by rvennam** [comment]
Personally, I don't think uninstalling all of Istio at the end makes sense for every task. Cleanup should just remove the resources created that were specific to that task. wdyt?

**Comment by jaellio** [comment]
> Personally, I don't think uninstalling all of Istio at the end makes sense for every task. Cleanup should just remove the resources created that were specific to that task. wdyt?

Good point, I'll take another look through these cases and only include uninstall instructions when it makes sense and otherwise only include instructions to bring the environment back to its initial state.

**Review by keithmattix — APPROVED** [review]

**Review by ericvn — APPROVED** [review]

**Comment by ericvn** [comment]
Thanks @jaellio

**Pull request merged**
