### PR TITLE
fix table

### PR DESCRIPTION
**Pull request by Arhell**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

resolve https://github.com/istio/istio.io/issues/11516

### CODE REVIEW

**Comment by ericvn** [comment]
Would you give an example of what this fixes?

**Comment by Arhell** [comment]
https://deploy-preview-12142--preliminary-istio.netlify.app/latest/docs/reference/config/istio.operator.v1alpha1/#KubernetesResourcesSpec

https://deploy-preview-12142--preliminary-istio.netlify.app/latest/docs/tasks/observability/logs/otel-provider/#default-access-log-format

https://deploy-preview-12142--preliminary-istio.netlify.app/latest/docs/releases/feature-stages/#feature-phase-definitions

**Review by ericvn — APPROVED** [review]
Thanks.

**Comment by Arhell** [comment]
I looked at a lot of examples and this is the best option for site, it is also used in docsy.

**Pull request merged**
