### PR TITLE
[release-1.19] Update test reference and reference docs for 1.19.9

### PR DESCRIPTION
**Pull request by ericvn**
## Description

Run istio.io tests with new istio commit. Also update the reference docs.

### CODE REVIEW

**Review by dhawton — APPROVED** [review]

**Comment by ericvn** [comment]
Both failures:
```
error: timed out waiting for the condition on gateways/gateway
Failed to deploy gateway gateway in namespace istio-ingress
```

**Comment by ericvn** [comment]
/test doc.test.profile-none

One of the two similarly failing tests passed the last time, so are both flakes?

**Comment by ericvn** [comment]
In the last run, the other test flaked, so looking back, 1 run both tests failed, next run, test 1 failed, next run test 2 failed.

**Comment by ericvn** [comment]
In the last run, the other test flaked, so looking back, 1 run both tests failed, next run, test 1 failed, next run test 2 failed.

**Review by frankbu — APPROVED** [review]

**Pull request merged**
