### PR TITLE
zh-translation: about/contribute/_index.md

### PR DESCRIPTION
**Pull request by lxd5866**
[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by wzshiming** [comment]
/ok-to-test

Please sign the CLA

**Comment by lxd5866** [comment]
> @googlebot I signed it!

@googlebot I signed it!

**Review by kebe7jun — APPROVED** [review]

**Review by rootsongjc — APPROVED** [review]
/LGT

**Review by rootsongjc — APPROVED** [review]
/LGTM

**Pull request merged**
