### PR TITLE
enh: enlarge search icon for better visibility

### PR DESCRIPTION
**Pull request by kushthedude**
Signed-off-by: Kush Trivedi <kushthedude@gmail.com>

- Enlarges search icon for better visibility
- This issue refers #7783 

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by sdake — APPROVED** [review]
I am not sure what the first file changed does. I am APPROVING this PR - with the assumption that another reviewer will ensure the changes to the layout file are correct.

Really nice job - especially for a first PR!!

Rendering: https://deploy-preview-8459--preliminary-istio.netlify.app/

For a followup independent PR, would you be willing to enhance the size of the `Options and Settings` gear icon to match the size of this search icon?

And for a final PR - could you enhance the size of the X box next to the search icon. It is really hard to find...

It may be that not all of these enhancements are accepted, which is why I requested per PR enhancements (so they could be individually reviewed).

I find these types of changes super beneficial for those with vision difficulty (such as myself). These relatively small changes have an awesome impact on accessibility.

**Comment by kushthedude** [comment]
Thanks, @sdake!
> I am not sure what the first file changed does.

The first file change is needed to add an extra attribute to the class with the icon name so that when the class name would be `icon magnifier` both `svg.icon` && `svg.magnifier` styles will be applied.

> It may be that not all of these enhancements are accepted, which is why I requested per PR enhancements (so they could be individually reviewed).

Sure I will make the follow-up PRs for the issues you mentioned 😄

**Comment by frankbu** [comment]
@kushthedude Thanks for the enhancement, but I'm not sure if we should be tweaking these kinds of things outside of a more coordinated overall improvement to the site usability. There is work underway to improve the UX and layout, but maybe this is OK as a temporary improvement?

@craigbox, how does this fit with things you are planning?

**Comment by craigbox** [comment]
We'll be doing a complete visual overhaul of the site in the next 3 months, but it will probably not land for a while, and so enhancements like these to the existing site are super useful.  Thanks, Kush!

**Review by ericvn — APPROVED** [review]

**Pull request merged**
