### PR TITLE
Fix example for customising Istio sidecar injection

### LINKED ISSUE #12774: Not working example for customising istio sidecar injection
Hi, the current example to customise the sidecar injection is not complete and therefore is not working.
The current example is as follows:

```
apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
  - name: hello
    image: alpine
  - name: istio-proxy
    image: auto
    resources:
      requests:
        cpu: "100m"
    volumeMounts:
    - mountPath: /etc/certs
      name: certs
    lifecycle:
      preStop:
        exec:
          command: ["sleep", "10"]
  volumes:
  - name: certs
    secret:
      secretName: istio-certs
```

Link: https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#customizing-injection

However, it doesn't mention that either the sidecar.istio.io/inject label at pod level or the istio-injection label at namespace level is still needed.

Could you review it?
Thanks!

### PR DESCRIPTION
**Pull request by SRodi**
* Add missing label sidecar.istio.io/inject: "true"
* Fix #12774

- [ ] Configuration Infrastructure
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by SRodi** [comment]
Can I please get a review of this PR @zirain @johnma14 ? thanks

**Comment by howardjohn** [comment]
Not sure how I feel about this TBH. Literally the same page describes how to inject pods. Injecting pods with a pod label isntead of namespace label is a niche case. Users should just read https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#controlling-the-injection-policy to understand how to inject IMO

**Comment by SRodi** [comment]
> Not sure how I feel about this TBH. Literally the same page describes how to inject pods. Injecting pods with a pod label isntead of namespace label is a niche case. Users should just read https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#controlling-the-injection-policy to understand how to inject IMO

I agree with you @howardjohn as how to inject is mentioned in the same page. But I also see the point of @adriABC in #12774 as the standalone example in the doc is incomplete (and sure is a niche case). According to the existing doc and the yaml shown, the `example` pod will be deployed to default namespace, but there will be no sidecar injected as no label is specified either at pod level or namespace level.

**Comment by howardjohn** [comment]
you could say the same about literally any other sample deployment Istio has. none of them have a pod label for injection

**Comment by SRodi** [comment]
closing this based on conversation above. thanks for the input @howardjohn. Will someone close https://github.com/istio/istio.io/issues/12774 too?

**Pull request closed without merging**
