### PR TITLE
Try enabling authz-dry-run test

### PR DESCRIPTION
**Pull request by ericvn**
## Description

Try enabling authz-dry-run test

Fixes https://github.com/istio/istio/issues/50039

### CODE REVIEW

**Comment by ericvn** [comment]
/test doc.test.profile-demo

flake in rate-limit

**Comment by ericvn** [comment]
Looking at the test output, it seems the author-dry-run test is timing out:
```
=== RUN   TestDocs/tasks/security/authorization/authz-dry-run/test.sh/test.sh
2024-04-23T19:11:10.712965Z	info	tf	=== BEGIN: Test: 'tests_setup_profile-default[TestDocs/tasks/security/authorization/authz-dry-run/test.sh/test.sh]' ===
2024-04-23T19:11:10.713068Z	info	tf	Running command script test.sh
panic: test timed out after 1h0m0s
```
I'll let someone else investigate it further.

**Comment by ericvn** [comment]
Looking at artifacts, this step might be timing out:
```
+snip_check_dryrun_result_in_tracing_using_zipkin_1(): istioctl dashboard zipkin
+__verify_with_retry(): local cmp_func=__cmp_contains
+__verify_with_retry(): local func=query_zipkin
+__verify_with_retry(): local 'expected=ns[foo]-policy[deny-path-headers]-rule[0]'
+__verify_with_retry(): local failonerr=
+__verify_with_retry(): local max_time=120
+__verify_with_retry(): local delay=1
+__verify_with_retry(): local expected_consecutive=1
+__verify_with_retry(): local start_time
++__verify_with_retry(): date +%s
+__verify_with_retry(): start_time=1713899491
+__verify_with_retry(): local end_time
+__verify_with_retry(): end_time=1713899611
+__verify_with_retry(): local current_time=1713899491
+__verify_with_retry(): local errexit_state
++__verify_with_retry(): shopt -po errexit
++__verify_with_retry(): true
+__verify_with_retry(): errexit_state='set +o errexit'
+__verify_with_retry(): set +e
+__verify_with_retry(): local consecutive=0
+__verify_with_retry(): true
++__verify_with_retry(): query_zipkin
+++query_zipkin(): kubectl get pod -l app=sleep -n foo -o 'jsonpath={.items..metadata.name}'
++query_zipkin(): kubectl exec sleep-9454cc476-nm69t -c sleep -n foo -- curl http://httpbin.foo:8000/headers -H 'X-B3-Sampled: 1' -s
++query_zipkin(): curl -s 'http://localhost:9411/zipkin/api/v2/traces?serviceName=httpbin.foo'
+__verify_with_retry(): out='{
  "headers": {
    "Accept": "*/*", 
    "Host": "httpbin.foo:8000", 
    "User-Agent": "curl/8.7.1", 
    "X-B3-Sampled": "1", 
    "X-Envoy-Attempt-Count": "1", 
    "X-Forwarded-Client-Cert": "By=spiffe://cluster.local/ns/foo/sa/httpbin;Hash=314b6e520de4c6986b2c69b7b3aed03a1f5746b7e5181530bcb3f4e02dec8baa;Subject=\"\";URI=spiffe://cluster.local/ns/foo/sa/sleep"
  }
}
[]'
```

**Comment by ericvn** [comment]
```
# Start the Zipkin dashboard and verify the trace result includes the dry-run policy name
snip_check_dryrun_result_in_tracing_using_zipkin_1 &
_verify_contains query_zipkin "ns[foo]-policy[deny-path-headers]-rule[0]"
pgrep istioctl | xargs kill
```
I know there were Zipkin changes.

**Comment by howardjohn** [comment]
Oh if we are checking zipkin then we need to enable zipkin probably

**Comment by ericvn** [comment]
I do see that there is a 
```
# Install Prometheus and Zipkin
_deploy_and_wait_for_addons prometheus zipkin
```
which should do a
```
kubectl apply -f samples/addons/extras/zipkin.yaml
                 _wait_for_deployment istio-system zipkin
```

**Comment by howardjohn** [comment]
You need to also configure it to use zipkin; before, the default install did this.

So either https://istio.io/latest/docs/tasks/observability/distributed-tracing/telemetry-api/#enable-tracing-for-mesh or https://istio.io/latest/docs/tasks/observability/distributed-tracing/mesh-and-proxy-config/

**Comment by zirain** [comment]
related to https://github.com/istio/istio/pull/49615?

**Comment by ericvn** [comment]
> related to [istio/istio#49615](https://github.com/istio/istio/pull/49615)?

Yes, I believe so. Question is what does the @istio/wg-security-maintainers team want to do with the doc (as they own it)? Should this just section be removed or the steps to document this be changed.

**Comment by zirain** [comment]
wait for the result of https://github.com/istio/istio.io/pull/14965

**Comment by ericvn** [comment]
Closing this in favor of https://github.com/istio/istio.io/pull/14965.

**Pull request closed without merging**
