### PR TITLE
Enable the ambient mode getting started tests

### PR DESCRIPTION
**Pull request by ericvn**
## Description

Test to see the ambient mode getting started failures.

### CODE REVIEW

**Comment by ericvn** [comment]
gateway test fails with:
```
deployment "istiod" successfully rolled out
daemon set "ztunnel" successfully rolled out
daemon set "istio-cni-node" successfully rolled out
content/en/docs/ambient/getting-started/test.sh: line 41: snip_download_and_install_9_out: unbound variable
```
while the normal test is failing on a verify like:
```
VERIFY FAILED snip_download_and_install_7 (timeout after 120s):
received:
"NAME                                        READY   STATUS    RESTARTS   AGE
pod/istio-cni-node-nhfqn                    1/1     Running   0          2m10s
pod/istio-ingressgateway-7bb7649f89-28p26   1/1     Running   0          2m10s
pod/istiod-55b74b77bd-stb9n                 1/1     Running   0          2m13s
pod/ztunnel-q98d9                           1/1     Running   0          2m6s

NAME                            DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
daemonset.apps/istio-cni-node   1         1         1       1            1           kubernetes.io/os=linux   2m10s
daemonset.apps/ztunnel          1         1         1       1            1           kubernetes.io/os=linux   2m6s"
expected:
"NAME                                    READY   STATUS    RESTARTS   AGE
pod/istio-cni-node-zq94l                    1/1     Running   0          2m7s
pod/istio-ingressgateway-56b9cb5485-ksnvc   1/1     Running   0          2m7s
pod/istiod-56d848857c-mhr5w                 1/1     Running   0          2m9s
pod/ztunnel-srrnm                           1/1     Running   0          2m5s

NAME             DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
daemonset.apps/istio-cni-node   1         1         1       1            1           kubernetes.io/os=linux   2m16s
daemonset.apps/ztunnel          1         1         1       1            1           kubernetes.io/os=linux   2m10s"
```
I'm curious if the verify like doesn't like `/`s in the token.

**Comment by ericvn** [comment]
Next test failure is a missing line, pod/istio-ingressgateway, in a snippet?
```
VERIFY FAILED snip_download_and_install_8 (timeout after 120s):
received:
"NAME                                        READY   STATUS    RESTARTS   AGE
pod/istio-cni-node-jxlw5                    1/1     Running   0          2m17s
pod/istio-ingressgateway-7bb7649f89-p9g48   1/1     Running   0          2m17s
pod/istiod-55b74b77bd-h57f7                 1/1     Running   0          2m22s
pod/ztunnel-hx55t                           1/1     Running   0          2m15s

NAME                            DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
daemonset.apps/istio-cni-node   1         1         1       1            1           kubernetes.io/os=linux   2m17s
daemonset.apps/ztunnel          1         1         1       1            1           kubernetes.io/os=linux   2m15s"
expected:
"NAME                      READY   STATUS    RESTARTS   AGE
pod/istio-cni-node-zq94l      1/1     Running   0          2m15s
pod/istiod-56d848857c-mhr5w   1/1     Running   0          2m23s
pod/ztunnel-srrnm             1/1     Running   0          2m9s

NAME             DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
daemonset.apps/istio-cni-node   1         1         1       1            1           kubernetes.io/os=linux   2m16s
daemonset.apps/ztunnel          1         1         1       1            1           kubernetes.io/os=linux   2m10s"
```

**Comment by ericvn** [comment]
I created a PR, https://github.com/istio/istio.io/pull/14944, to get past the first failure.

**Comment by ericvn** [comment]
Someone can continue with this work if they so chose after my above referenced verify_like change PR is merged.

**Comment by ericvn** [comment]
I'll leave this PR open for a short time to see if the test.sh gets further. The gtw-test.sh will need more work.

**Comment by ericvn** [comment]
Closing, letting someone else continue the enablement of the tests.

**Comment by kfaseela** [comment]
Shall I look into this?

**Comment by kfaseela** [comment]
> @kfaseela, I am pretty sure the breaks are due to code I contributed so I was planning to take a look at it. Should have a chance today

sure pls go ahead

**Pull request closed without merging**
