### PR TITLE
zh-translation: /docs/tasks/security/webhook/index.md

### PR DESCRIPTION
**Pull request by ilylia**
ref: https://github.com/servicemesher/istio-official-translation/issues/1516

### CODE REVIEW

**Comment by ilylia** [comment]
This depends on https://github.com/servicemesher/istio-official-translation/issues/1515 which accepted by @Lovnx .
Should I add this file, or wait for him?

**Comment by tanjunchen** [comment]
@ilylia  fix conflicts . maybe ci runs ok

**Comment by ilylia** [comment]
> @ilylia fix conflicts . maybe ci runs ok

thanks.

**Comment by yuxiaobo96** [comment]
@rootsongjc 
Please help merge.

**Pull request merged**
