### PR TITLE
GKE typo fix

### PR DESCRIPTION
**Pull request by NoahNsimbe**
Fixes typo for Google Kubernetes Engine

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by ericvn — COMMENTED** [review]
LGTM as this matches the other pages. However, I'll leave to @craigbox to approve as a Google person.

**Comment by ericvn** [comment]
I made the changes. Will wait on @craigbox to approve.

**Review by craigbox — APPROVED** [review]
done

**Pull request merged**
