### PR TITLE
[Release 1.3] Temporarily disable the user guide of Istio Vault integration for release 1.3

### PR DESCRIPTION
**Pull request by lei-tang**
Istio release 1.3 uses new k8s JWT (https://github.com/istio/istio/pull/16147), which breaks the user guide of Istio Vault CA integration for release 1.3.
This PR temporarily disables the user guide of Istio Vault CA integration for release 1.3.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ x] Security
[ ] Test and Release
[ x] User Experience
[ ] Developer Infrastructure

Resolves https://github.com/istio/istio/issues/16606.

### CODE REVIEW

**Comment by lei-tang** [comment]
#https://github.com/istio/istio/issues/16606

**Comment by lei-tang** [comment]
@istio/wg-docs-maintainers @istio/wg-docs-maintainers-english @istio/wg-docs-maintainers-chinese  I am not sure the failure of istio.io-lint test is related to this PR; ./public/about/feature-stages/index.html in the failure log is not a file in the repository. Do you know how to fix these istio.io-lint errors?

**Comment by pitlv2109** [comment]
@lei-tang There are other docs that are linked to `/docs/tasks/security/vault-ca`, you need to edit them as well.

**Comment by myidpt** [comment]
@rcaballeromx @geeknoid @sdake Could any of you review this? It's a feature removal, should be quite easy to review :) It's currently a blocker for 1.3.0.

**Pull request merged**
