### PR TITLE
Remove decoration dots

### PR DESCRIPTION
**Pull request by Arhell**
issue https://github.com/istio/istio.io/issues/9729

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

example https://deploy-preview-10259--preliminary-istio.netlify.app/latest/docs/examples/bookinfo/

### CODE REVIEW

**Comment by craigbox** [comment]
The read tracking that we were talking about isn’t the “time to read”, it’s the dots that display on pages like this: https://istio.io/latest/news/releases/1.9.x/

**Comment by Arhell** [comment]
@craigbox done

**Review by craigbox — APPROVED** [review]
Comprehensive; LGTM!

**Pull request merged**
