### PR TITLE
zh: servicemesher/istio-official-translation#758

### PR DESCRIPTION
**Pull request by haiker2011**

### CODE REVIEW

**Comment by fleeto** [comment]
`[trans-bot:N/A]`

Thank you @haiker2011, there are more than 1 files in your PR, will not be reported to the task issues.

**Comment by haiker2011** [comment]
@fleeto I have delete the  irrelevant file

**Comment by haiker2011** [comment]
fix https://github.com/servicemesher/istio-official-translation/issues/758

**Pull request merged**
