### PR TITLE
Updated mesh expansion guide

### PR DESCRIPTION
**Pull request by LisaFC**
Supercedes #2959 - same change, minus many many old changes in the same branch.

### CODE REVIEW

**Comment by costinm** [comment]
Hi Lisa, would it be possible to cherry-pick this into 1.0 branch as well ?

**Comment by LisaFC** [comment]
Done so in #3104

**Comment by incfly** [comment]
After walking through this updated instructions with latest istio daily build for 1.1, I run into issues.

So this PR removes the `istioctl register <service-name> endpints protoco:port` using Kubenetetes selector-less to generate DNS mappings. However the default installment does not generate any DNS mappings based on ServiceEntry (multi cluster does, when we install a CoreDNS plugin pod).

This means we don't have a service VIP for services on VM, and I hit `404`.

Running `istioctl register will fix that`.

Do I miss something? What's our intended solution regarding VIP for `ServiceEntry` mesh expansion services? @rshriram @costinm 

Without that, customers can't get it work.

**Pull request merged**
