### PR TITLE
zh-translation: about/contribute/formatting/index.md

### PR DESCRIPTION
**Pull request by elkan1788**
Upgrade the Chinese translation in path:  about/contribute/formatting/index.md

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by SataQiu — COMMENTED** [review]
/ok-to-test

**Review by kebe7jun — COMMENTED** [review]
请修复一下 lint test 哦。

**Review by kebe7jun — APPROVED** [review]
LGTM

**Pull request merged**
