### PR TITLE
[release-1.7] Cherry-pick #8184 for logo changes

### PR DESCRIPTION
**Pull request by craigbox**
[X] Docs

Manually cherry-pick #8184, fix failed automated attempt in #8185.

### CODE REVIEW

**Comment by craigbox** [comment]
https://deploy-preview-8193--istio-staging.netlify.app/latest/about/community/customers/ spot-check LGTM

**Comment by ericvn** [comment]
I admit I was expecting 3 files to be changed here, and not a lot of the .svg files. Do you know if the changes in files are those caused by the IMGBOT and it's shrinking of files?

**Comment by craigbox** [comment]
Yes, after diffing the directories I saw that the files had been optimized.  Not 100% sure why, but it seemed a win to move them. I can skip this step if it's disruptive.

**Review by frankbu — APPROVED** [review]
I guess it's fine to replace the exiting images with the optimized ones, but I would have thought that the imagebot would/should have done that automatically. Maybe we are supposed to add the cherrypick label to imagebot PRs, but we haven't been doing that?

**Comment by ericvn** [comment]
imagebot only runs agains master as far as I know.  I was always unsure of cherrypicking because as things diverge, the changes may or may not be correct for both versions.

**Comment by ericvn** [comment]
And if the cherrypick fails, the imagebot isn't going to understand an issue being opened and assigned to it to do it manually.

**Pull request merged**
