### PR TITLE
Adds Northflank as a provider

### PR DESCRIPTION
**Pull request by DeciderWill**
Signed-off-by: Will <will@northflank.com>

Please provide a description for what this PR is for.

Northflank is a developer platform to deploy microservices, cron jobs and stateful databases from development to production. Load-balancing, service mesh, and network security play an important part of our platform. We integrate and provide Istio and Istio Service Mesh in our platform to provide TCP & HTTP load-balancing, mTLS, network observability, and other security measures such as IP+Basic Auth.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by ericvn** [comment]
Looking at the `lint` test details, it appears that your indentation is incorrect. The other test is likely a flake and will hopefully pass when you submit the commit for the lint failure.

**Comment by DeciderWill** [comment]
@ericvn - thanks, I've now signed the CLA as well now.

**Review by Arhell — COMMENTED** [review]
cc @craigbox

**Review by craigbox — APPROVED** [review]
Thanks for using Istio, Will!  We'd love to hear more about what you're doing.  Please feel free to reach out to me (this GitHub ID at Google.com) if you'd like to be a case study...

**Comment by ericvn** [comment]
@DeciderWill The CLA doesn't seem to be satisfied.

**Comment by DeciderWill** [comment]
> @DeciderWill The CLA doesn't seem to be satisfied.

Is it possible to retrigger the check without committing again?

**Comment by craigbox** [comment]
yes, a repo member can trigger it (done)

**Pull request merged**
