### PR TITLE
add README for multicluster docs tests

### PR DESCRIPTION
**Pull request by kfaseela**
## Description

Adding README for the steps needed to run multicluster docs tests locally 

## Reviewers

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

### CODE REVIEW

**Comment by kfaseela** [comment]
is this flake expected to fail like this several times!!!

**Review by bleggett — APPROVED** [review]
Awesome, ty!

**Comment by bleggett** [comment]
> is this flake expected to fail like this several times!!!

Yeah - https://github.com/istio/istio.io/issues/15505 is a problem test.

**Review by dhawton — APPROVED** [review]

**Comment by kfaseela** [comment]
or update the test-infra not to run tests on README updates :D

**Pull request merged**
