### PR TITLE
Correct wording in Prometheus integration docs

### PR DESCRIPTION
**Pull request by danielgospodinow**
Correct wording and slightly improve readability.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA
https://github.com/istio/istio.io/pull/10483/checks?check_run_id=4149797909

**Comment by danielgospodinow** [comment]
> Please sign CLA https://github.com/istio/istio.io/pull/10483/checks?check_run_id=4149797909

I have signed it. 👌🏼

**Review by craigbox — APPROVED** [review]

**Pull request merged**
