### PR TITLE
[zh] Sync #14933 move ambient to top level in docs into Chinese

### PR DESCRIPTION
**Pull request by wilsonwu**
## Description

Sync #14933 move ambient to top level in docs into Chinese

## Reviewers

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [x] Localization/Translation

### CODE REVIEW

**Review by windsonsea — COMMENTED** [review]
lgtm for the text

**Comment by wilsonwu** [comment]
> lgtm for the text

Seems need additional approval.

**Review by windsonsea — APPROVED** [review]
Thanks

**Pull request merged**
