### PR TITLE
[zh] sync /setup/upgrade/helm/

### PR DESCRIPTION
**Pull request by windsonsea**
Sync with en.
```
content/zh/docs/setup/upgrade/helm/index.md
```
- [x] Docs

### CODE REVIEW

**Comment by windsonsea** [comment]
Hi @zirain , could you help to check why the lint is always failed? I checked the [error log](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/12585/lint_istio.io/1622210967335079936), but don't know how to fix it 😓

**Comment by zirain** [comment]
> Hi @zirain , could you help to check why the lint is always failed? I checked the [error log](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/12585/lint_istio.io/1622210967335079936), but don't know how to fix it 😓

will take a look later.

**Comment by zirain** [comment]
when you meet weird error, you can try rebase from master branch.

**Review by zirain — APPROVED** [review]
LGTM

**Pull request merged**
