### PR TITLE
Fixed typo in cipher suites

### PR DESCRIPTION
**Pull request by sha-rath**
Fixed a small typo in the cipher suites. It has to be ECDHE-ECDSA-AES256-GCM-SHA384. 

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by craigbox** [comment]
+security maintainers to confirm; looks right but I see mentions of "CDHE-*" online too.  Possibly a typo that's been circulating, possibly a different thing.

**Comment by sha-rath** [comment]
I checked the valid cipher suites in Istio source code and I can confirm that it is ECDHE-*

**Review by howardjohn — APPROVED** [review]

**Comment by craigbox** [comment]
@kebe7jun to approve for CN

**Pull request merged**
