### PR TITLE
Update to latest 1.16 commit

### PR DESCRIPTION
**Pull request by ericvn**
Please provide a description for what this PR is for.

Pull for https://github.com/istio/istio.io/pull/12213.

### CODE REVIEW

**Review by frankbu — APPROVED** [review]

**Review by kfaseela — APPROVED** [review]

**Comment by ericvn** [comment]
Needed to wait for the release post-submit to create the images for the referenced istio commit.

**Comment by ericvn** [comment]
Make DNM to wait for a later 1.16.0 build.

**Comment by ericvn** [comment]
This should now match the 1.16.0 build.

**Comment by ericvn** [comment]
Something about the new gateway tests are flakey. INthis case, it seems like a kubectl delete of the gateway isn't happening quick enough.

**Pull request merged**
