### PR TITLE
[zh] Sync #16045 fix typo in OpenShift pre-requisites for ambient into Chinese

### PR DESCRIPTION
**Pull request by wilsonwu**
## Description

Sync #16045 fix typo in OpenShift pre-requisites for ambient into Chinese

## Reviewers

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [x] Localization/Translation

### CODE REVIEW

**Comment by wilsonwu** [comment]
How to trigger the deployment again?

**Comment by windsonsea** [comment]
how about try to run:

```
git reset
git commit --amend --no-edit
git push -f
```

**Review by windsonsea — APPROVED** [review]

**Pull request merged**
