### PR TITLE
Update multicluster test kind image

### PR DESCRIPTION
**Pull request by ericvn**
Please provide a description for what this PR is for.

The current kind 1.20.5 image does not work with kind 0.14.0. Update the image to 1.21.1 which does.

### CODE REVIEW

**Review by nmittler — APPROVED** [review]

**Comment by ericvn** [comment]
Hopefully @craigbox will be able to approve this, else I will approve just to keep the repo pipeline working as the 1.14 release is very close.

**Review by Xunzhuo — APPROVED** [review]
LGTM

**Pull request merged**
