### PR TITLE
Remove unneeded icons from src/icons

### PR DESCRIPTION
**Pull request by ChristinaMak**
Addresses #9768 

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by johnma14 — COMMENTED** [review]
LGTM

**Review by craigbox — APPROVED** [review]
Thanks for this!

**Pull request merged**
