### PR TITLE
Add new istio.io design

### PR DESCRIPTION
**Pull request by Jakub-Sadowski**
Update master
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by ericvn** [comment]
I do see other `Polidea` related PRs. I assume they will be merged into this one at some point.

**Comment by Jakub-Sadowski** [comment]
> I do see other `Polidea` related PRs. I assume they will be merged into this one at some point.

Yes, before merging this one, it will be updated with them

**Comment by ericvn** [comment]
To see why your `lint` test is failing, you can click on `Details` to the right of the test, and then click on the `Raw build-log.txt` link to see what the failure is.  Currently, it has:
```
Start building sites … 
Total in 12974 ms
Error: Error building site: TOCSS: failed to transform "sass/_all.scss" (text/x-scss): resource "scss/sass/_all.scss_b95b077eb505d5c0aff8055eaced30ad" not found in file cache
Makefile.core.mk:91: recipe for target 'build_nominify' failed
make: *** [build_nominify] Error 255
```

**Comment by craigbox** [comment]
Setting cla to yes as the commits in question are merges from master to the update branch.

**Review by davidhauck — APPROVED** [review]

**Review by craigbox — APPROVED** [review]
👍

**Review by ericvn — APPROVED** [review]

**Pull request merged**
