### PR TITLE
[zh]: fix ommon-problems/network-issues/index.md

### PR DESCRIPTION
**Pull request by aimuz**
Signed-off-by: aimuz <mr.imuz@gmail.com>

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by zirain — APPROVED** [review]

**Comment by aimuz** [comment]
doc.test.profile_default 
Seems to be frequent errors, also in other PRs, do we need to fix him

**Comment by kfaseela** [comment]
> doc.test.profile_default Seems to be frequent errors, also in other PRs, do we need to fix him

@aimuz yes the test is really flaky. Would be great if you have some time to look into why this fails

**Comment by aimuz** [comment]
@kfaseela Yes, I'm looking into that.

**Pull request merged**
