### PR TITLE
Change baseEjectionTime to be less than maxEjectionTime (default 300s)

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
@ericvn @ramaraochavali @nmittler 

Hope this can fix

### CODE REVIEW

**Comment by ericvn** [comment]
@hzxuzhonghu You shouldn't be updating go.* files at all, especially changing it to a different branch. That requires additional changes in other files.

Are you thinking the just updating the DR will help, or are you thinking there is another fix needed?

**Comment by hzxuzhonghu** [comment]
Only dr change

**Comment by ericvn** [comment]
A quick sanity check running the DR change shows the tests should now pass. 

https://github.com/istio/istio/pull/30602 will fix the issue where 10m could still have been specified and the maxEjectionTime would have been increased to be greater than or equal the baseEjectionTime.

Thanks @hzxuzhonghu.

**Comment by ericvn** [comment]
Only test failure at this point was the customize metrics flake.

**Comment by ericvn** [comment]
The customize metrics test is a flake. No reason to keep testing.

**Review by ericvn — APPROVED** [review]

**Pull request merged**
