### PR TITLE
Add Thought Machine customer logo

### PR DESCRIPTION
**Pull request by RoryCrispin**
We use Istio at Thought Machine and would be pleased to add our logo to the list of customers.
I'll be happy to confirm this request from my rory@thoughtmachine.net email address. 

A little about us:
Thought Machine has built the next generation of core banking technology. 
Our core banking engine Vault is powering the smartest, most ambitious banks in the world. With our software, banks can tap into all the benefits of cloud infrastructure – speed, security, resilience, availability and continuous innovation to create brilliant customer-centric propositions.

Few providers deliver on the promise of cloud native technology. 
At Thought Machine, it’s in our DNA. 

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by RoryCrispin** [comment]
I'm onto it w.r.t the CLA!

**Review by craigbox — APPROVED** [review]

**Review by kebe7jun — COMMENTED** [review]
/ok-to-test

**Comment by RoryCrispin** [comment]
@googlebot I signed it!

**Comment by RoryCrispin** [comment]
Looks like this CLA may take a couple of days to go through while someone at Google checks it. I'll be back.. 😎

**Comment by craigbox** [comment]
(I am sorry for how tedious this is)

Thought Machine is showing as having signed a CLA.  Are you in the group of people who it covers, Rory?
https://cla.developers.google.com/about#add-contributors

**Comment by RoryCrispin** [comment]
> (I am sorry for how tedious this is)
Aha that's okay thank you. I appreciate you taking a look.

Something must be wrong here because I'm not seeing any CLA memberships for my user which is in the correct group. I've emailed cla-submissions@google.com to find out what's wrong here. 

Just in case.. @googlebot I signed it!

**Comment by RoryCrispin** [comment]
@googlebot I signed it!

**Review by kebe7jun — APPROVED** [review]

**Pull request merged**
