### PR TITLE
Add steering links to istio.io

### PR DESCRIPTION
**Pull request by sdake**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by sdake** [comment]
I can do.

Cheers,
-steve

**Comment by frankbu** [comment]
cc @istio/steering-committee

**Comment by craigbox** [comment]
See https://github.com/istio/istio.io/pull/8363#issuecomment-716832957

>A team are about to look into this as a whole, but I personally believe that istio.io is for users, and GH istio/community is for contributors. I see no reason to expose how the sausage is made on the marketing website. 
> Steve, what problem were you trying to solve? I could see a high-level page talking about the governance of the project, including Steering, being part of the upcoming revision.

**Comment by frankbu** [comment]
Superseded by #8382

**Pull request closed without merging**
