### PR TITLE
[release-1.20] Update test reference to 1.20.4

### PR DESCRIPTION
**Pull request by ericvn**
## Description

Update test reference to 1.20.4.

First pass picking the update_deps commit.

### CODE REVIEW

**Comment by ericvn** [comment]
/test doc.test.profile-default

tasks/security/authorization/authz-ingress/gtwapi_test.sh

**Comment by ericvn** [comment]
/test doc.test.profile-none

revision tests

**Comment by ericvn** [comment]
Revision tests failed again. I'm suspicious there is a change in the new build that might require a doc change.

**Comment by ericvn** [comment]
Pull in test/doc changes from https://github.com/istio/istio.io/pull/14520

**Review by craigbox — APPROVED** [review]

**Pull request merged**
