### PR TITLE
Update to latest istio commit. Fix egress test

### PR DESCRIPTION
**Pull request by ericvn**
## Description

Supersedes https://github.com/istio/istio.io/pull/14374 containing a test fix.

### CODE REVIEW

**Review by dhawton — APPROVED** [review]

**Review by kfaseela — APPROVED** [review]

**Comment by ericvn** [comment]
/test doc.test.profile-default

flake?

**Comment by ericvn** [comment]
/test doc.test.profile-default

Flakes

**Comment by ericvn** [comment]
/test doc.test.profile-default

Flakes

**Comment by ericvn** [comment]
/test doc.test.profile-default

Flakes - one more time

**Pull request merged**
