### PR TITLE
Add otel headers to tracing faq

### PR DESCRIPTION
**Pull request by hanxiaop**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by zirain** [comment]
should we also update samples in istio repo?

**Comment by zirain** [comment]
@hanxiaop would you like to finish this?

**Comment by hanxiaop** [comment]
> @hanxiaop would you like to finish this?

@zirain Sure, I'll update the sample.

**Comment by zirain** [comment]
FYI

https://github.com/istio/istio/blob/7b24ef916be2375fcb4b599bdd96bb3058b813ac/samples/bookinfo/src/productpage/productpage.py#L200

**Review by zirain — APPROVED** [review]
lgtm

**Review by kfaseela — APPROVED** [review]

**Pull request merged**
