### PR TITLE
Improving the accuracy and completeness of the Admiral project description

### PR DESCRIPTION
**Pull request by benchi**
Improving the accuracy and completeness of the Admiral project description
https://github.com/istio/istio.io/issues/8510

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by benchi** [comment]
@googlebot I signed it!

**Review by aattuluri — APPROVED** [review]
lgtm

**Review by frankbu — APPROVED** [review]

**Pull request merged**
