### PR TITLE
zh-translation: content/zh/about/contribute/build/index.md

### PR DESCRIPTION
**Pull request by caoyukun0430**
[ ] Configuration Infrastructure
[X ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by caoyukun0430** [comment]
@googlebot I fixed it.

**Review by kebe7jun — APPROVED** [review]
lgtm

**Pull request merged**
