### PR TITLE
zh:/about/faq/metrics-and-logs/mixer-migration.md

### PR DESCRIPTION
**Pull request by yanrongshi**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by Xunzhuo — APPROVED** [review]

**Comment by yanrongshi** [comment]
@zirain why [do-not-merge]?

**Comment by zirain** [comment]
@Xunzhuo add DNM after approved

image

**Review by kebe7jun — APPROVED** [review]

**Review by Xunzhuo — APPROVED** [review]

**Pull request merged**
