### PR TITLE
Syncing polidea-update

### PR DESCRIPTION
**Pull request by wbartosz**
This pull request is an update of the Istio's polidea-update branch to keep it in sync with the master.

The following pull request will include relevant changes. Current pull request will only include changes which were already made to master.

cc: @davidhauck 

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by wbartosz** [comment]
@googlebot I signed it!

**Comment by frankbu** [comment]
What is branch `polidea-update`? Unless I'm missing something, it's just a copy of master, so why is it needed?

**Comment by ericvn** [comment]
@frankbu Per discussion in the WG call this past week, this should be the branch that the team is doing work on the new istio.io.

**Pull request closed without merging**
