### PR TITLE
fix translation errors

### PR DESCRIPTION
**Pull request by wulianglongrd**
Fix translation errors

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by kebe7jun — APPROVED** [review]

**Comment by ericvn** [comment]
One thing to note is that making a change in 1.14 will not make the change in master and this change will be reverted in a few weeks when we move to the current master branch. These PRs should really be cherry-picked to master.

**Comment by kebe7jun** [comment]
> One thing to note is that making a change in 1.14 will not make the change in master and this change will be reverted in a few weeks when we move to the current master branch. These PRs should really be cherry-picked to master if it's not already fixed there.

I'm sorry, I didn't pay attention.

**Comment by craigbox** [comment]
just add this comment

/cherry-pick master

**Pull request merged**
