### PR TITLE
Build a new 1.6 archive to remove trailing . in directory name

### PR DESCRIPTION
**Pull request by ericvn**
Fixes: https://github.com/istio/istio.io/issues/9154

Generated via `make build-old-archive-1.6.0`

@davidhauck Do all these changes make sense for doing that?

The key change `...nsions/metadata_exchange.html./index.html → ...y_extensions/metadata_exchange/index.html ` removing the trailing `.` is included.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by ericvn** [comment]
This should fix the cloning problem for the main branch. I'm not sure what happens if thy check out one of the other branches, like release-19, which will still contain the directory in the 1.6 archive.

**Comment by davidhauck** [comment]
So the process to generate this was to first update istio/api to fix the link, and then we re-ran the generate command here which detected that change?

**Comment by ericvn** [comment]
@davidhauck 

First PR was https://github.com/istio/proxy/pull/3214. This removed the trailing period on the location line of the pb.html so the file should be copied to a directory without the `.`

Second PR, https://github.com/istio/istio.io/pull/9166, was to run the istio.io command to actually pull the changes from the other repos. I was hoping there would only be the one file change, but there were a couple command updates as well.

Third PR is this one. Ran the command to build the new 1.6 archive here. I do notice the directory name changed in several places, so we certainly needed to update more than the the directory name as was attempted in a few other PRs.

**Comment by ericvn** [comment]
I checked a dozen files or so, and for those, the change was something like:
```
href=/v1.6/docs/reference/config/proxy_extensions/metadata_exchange.html./>Metadata Exchange Config</a></li>
href=/v1.6/docs/reference/config/proxy_extensions/metadata_exchange/>Metadata Exchange Config</a></li>
```
within the search button?

**Comment by davidhauck** [comment]
Got it, LGTM

**Comment by ericvn** [comment]
One thing I noticed in the second PR above is that the html also got removed from the directory name. Not sure which part of the code did that. But it matches the change I see in a few of the files..
```
...nsions/metadata_exchange.html./index.html → ...y_extensions/metadata_exchange/index.html
```

**Comment by ericvn** [comment]
I did move around the new 1.6 archive, looking specifically at the page with the new URL and well as a bunch of others, and things look ok: https://deploy-preview-9179--preliminary-istio.netlify.app/v1.6/docs/reference/config/proxy_extensions/metadata_exchange/ 

I don't think we need to cherry pick this change back to release-1.9, so there will be no change to the .6 archive there.

**Comment by ericvn** [comment]
/test doc.test.profile_none_istio.io

as there was VM test failure (I think that one is a much less frequent flake).

**Comment by ericvn** [comment]
The two failing tests are known failures until https://github.com/istio/istio/issues/31317 is fixed.

**Review by davidhauck — APPROVED** [review]

**Pull request merged**
