### PR TITLE
Samples referenced was in incorrect directory

### PR DESCRIPTION
**Pull request by jacob-delgado**
Istio docs testing. Found an issue with one of the commands.

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by craigbox** [comment]
Are you sure?  A quick sanity check shows the file at `https://github.com/istio/istio/blob/master/operator/samples/pilot-k8s.yaml`

**Comment by jacob-delgado** [comment]
> operator

In the actual 1.11.0 tarball it's

```
$  find . -name pilot-k8s.yaml
./samples/operator/pilot-k8s.yaml
```

so it is getting packaged up differently than it is in the github repo.

**Comment by craigbox** [comment]
SGTM, but might pay to get @istio/wg-environments-maintainers for comment on if this was a deliberate change and has any other impact.

**Review by howardjohn — APPROVED** [review]

**Review by craigbox — APPROVED** [review]

**Review by ericvn — APPROVED** [review]
See https://github.com/istio/release-builder/blob/master/pkg/build/archive.go#L82-L84 for copy done in archive.

**Pull request merged**
