### PR TITLE
Update index.md: Found a command missing from the Chinese document

### PR DESCRIPTION
**Pull request by jiac3366**
When I were browsing the chinese document, I found a command missing from the document

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by Xunzhuo** [comment]
Please sign CLA @jiac3366 Thanks

**Comment by jiac3366** [comment]
> Please sign CLA @jiac3366 Thanks

sorry, I submitted PR for the first time. I signed it just now, but perhaps it's not effective...What should I do next?

**Comment by Xunzhuo** [comment]
cc @jiac3366 , I  rerun this job and it passed. I have fixed the lint errors for you. Thanks for your PR :)

**Review by Xunzhuo — APPROVED** [review]

**Pull request merged**
