### PR TITLE
Remove links to outdated code

### PR DESCRIPTION
**Pull request by sdake**
The code for this was removed in:
https://github.com/istio/istio/pull/14678/files

I don't read/speak ZH, so struggle to understand how to properly
reword the text.  In the interim, just remove the links from the ZH
pages.

Fixes: https://github.com/istio/istio.io/issues/4417

### CODE REVIEW

**Comment by rlenglet** [comment]
This will need to be backported to `release-1.2` and `release-1.1` branches.

**Comment by geeknoid** [comment]
There is no release-1.1 branch in the doc repo, and we don't need to fix broken links in the release-1.1 branch as that branch will be archived next week.

**Comment by geeknoid** [comment]
Stills seems to be one remaining bad link.

**Comment by geeknoid** [comment]
Uh ho, looks like Envoy might have changed some of their content just now as new links are broken

**Comment by sdake** [comment]
I added the api changes separately so I could keep track of them for the api repo.

**Pull request merged**
