### PR TITLE
fix additional broken in-doc header links

### PR DESCRIPTION
**Pull request by kfaseela**
## Description

Part of https://github.com/istio/istio.io/issues/15624

## Reviewers

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

### CODE REVIEW

**Comment by kfaseela** [comment]
cc @jaellio

**Review by dhawton — APPROVED** [review]

**Comment by kfaseela** [comment]
Cc @wilsonwu

**Review by windsonsea — APPROVED** [review]

**Comment by wilsonwu** [comment]
> Cc @wilsonwu

Sorry for replay late, the links only update is all fine, but lots of Chinese content out of date, maybe cherry pick will blocked, there is an issue #15567, let's get a chance to make it up to date.

**Comment by jaellio** [comment]
@kfaseela Thanks for making the fix!!

**Comment by zirain** [comment]
I recall we have linter for dead link, why it didn't work?

**Comment by dhawton** [comment]
> I recall we have linter for dead link, why it didn't work?

We haven't had that one in a long time, unfortunately.

**Pull request merged**
