### PR TITLE
zh: switch to discuss.istio.io

### PR DESCRIPTION
**Pull request by rootsongjc**
- Refer to https://github.com/istio/istio.io/pull/3071 @geeknoid 
- Replace 跟踪 with 追踪 @fleeto

### CODE REVIEW

**Comment by geeknoid** [comment]
Deploy preview for *preliminary-istio* failed.

Built with commit 8c94f581dcf6eba2d68f1f21d98576feae3a53e3

https://app.netlify.com/sites/preliminary-istio/deploys/5c3818385d52e70008325c75

**Comment by rootsongjc** [comment]
@geeknoid This PR has changed `i18n/zh.toml` which is owned by the OWNERS. Need you manually merge.

**Pull request merged**
