### PR TITLE
Update istio test ref for anticipated 1.19.0

### PR DESCRIPTION
**Pull request by ericvn**
Please provide a description for what this PR is for.

Update istio test ref for anticipated 1.19.0

### CODE REVIEW

**Comment by ericvn** [comment]
Failed `tasks/traffic-management/ingress/gateway-api/test.sh` with:
```
namespace/istio-ingress created
gateway.gateway.networking.k8s.io/gateway created
httproute.gateway.networking.k8s.io/http created
error: timed out waiting for the condition on gateways/gateway
Failed to deploy gateway gateway in namespace istio-ingress
```

**Comment by ericvn** [comment]
`ops/configuration/traffic-management/network-topologies/gtwapi_test.sh` failed with:
```
*** apply httpbin gateway ***
gateway.gateway.networking.k8s.io/httpbin-gateway created
httproute.gateway.networking.k8s.io/httpbin created
error: timed out waiting for the condition on gateways/httpbin-gateway
```

**Comment by ericvn** [comment]
And this time, no flakes.

**Comment by ericvn** [comment]
Looks like there may be another PR in istio so will need to update for that.

**Comment by ericvn** [comment]
tasks/traffic-management/ingress/gateway-api/test.sh again:
```
namespace/istio-ingress created
gateway.gateway.networking.k8s.io/gateway created
httproute.gateway.networking.k8s.io/http created
error: timed out waiting for the condition on gateways/gateway
Failed to deploy gateway gateway in namespace istio-ingress
```

**Comment by ericvn** [comment]
Repeat of earlier tasks/traffic-management/ingress/gateway-api/test.sh.

**Review by frankbu — APPROVED** [review]

**Comment by ericvn** [comment]
Actually, need to close this one since it should have merged pre branch cut. Will need to redo on the new branch..

**Pull request closed without merging**
