### PR TITLE
Update istio.io/istio ref to 1.9.0-beta.0

### PR DESCRIPTION
**Pull request by ericvn**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by frankbu — APPROVED** [review]

**Review by frankbu — COMMENTED** [review]
tests failing?

**Comment by ericvn** [comment]
I didn't expect that things would pass here, as it seems we are always broken after making the release branch and moving the `master` test ref back to the `master` branch which usually has a big number of changes.

**Comment by ericvn** [comment]
Profile_none still is failing in `/tasks/observability/metrics/customize-metrics/test.sh ` 
```
VERIFY FAILED snip_verify_the_results_2 
```

Haven't looked at the others.

**Comment by ericvn** [comment]
profile_default has 3 failures:
TestDocs/tasks/security/authentication/authn-policy/test.sh/test.sh 
```VERIFY FAILED snip_enduser_authentication_10 (timeout after 120s):
received:
"200
200
200
200
200
200
200
200
200
200"
expected:
"200
401"
```

tasks/traffic-management/fault-injection/test.sh/test.sh has:
```
VERIFY FAILED get_bookinfo_productpage_jason
```

tasks/traffic-management/request-routing/test.sh/test.sh/_test_context/ has:
```
VERIFY FAILED get_bookinfo_productpage_jason (timeout after 120s):
```

**Comment by ericvn** [comment]
profile multicluster has:

setup/install/multicluster/primary-remote**/test.sh/test.sh/_test_context/test.sh both have
```VERIFY FAILED snip_install_the_eastwest_gateway_in_cluster1_2 (timeout after 120s):
received:
"Error from server (NotFound): services "istio-eastwestgateway" not found"
expected:
"NAME                    TYPE           CLUSTER-IP    EXTERNAL-IP    PORT(S)   AGE
istio-eastwestgateway   LoadBalancer   10.80.6.124   34.75.71.237   ...       51s"
```

setup/install/multicluster/multi-primary_multi-network/test.sh/test.sh/_test_context/test.sh:
```
VERIFY FAILED snip_verifying_crosscluster_traffic_1 (timeout after 120s):
```

**Comment by ericvn** [comment]
The `Customize Istio Metrics` page isn't very descriptive and talks about commands that are there, etc. One needs to look at the test to actually see how to recreate what is done on the page.

**Comment by ericvn** [comment]
A number of Issues were created in istio.io/istio for the above problems:

https://github.com/istio/istio/issues/29388
https://github.com/istio/istio/issues/29388

**Comment by ericvn** [comment]
Still waiting on the various teams to work on their created issues to fix the test failures.

**Comment by ericvn** [comment]
Current status is 3 multicluster and 1 security test are still failing. The security issue has an owner, @linsun has commented in each remaining issue and I have asked in the respective Slack channels about the issues.

**Review by brian-avery — APPROVED** [review]

**Comment by ericvn** [comment]
I notice after moving to 1.9, two additional tests failed (flakes?) in the default profile.

**Comment by ericvn** [comment]
At this point we have issues created for all the failing tests. They are marked as release blockers for 1.9. Per the discussion in the Istio #docs channel, I think we can merge this one.

**Review by nmittler — APPROVED** [review]

**Pull request merged**
