### PR TITLE
Ambient get started update

### PR DESCRIPTION
**Pull request by linsun**
## Description

Updated ambient get started to latest change on waypoint, also:

fixes: https://github.com/istio/istio/issues/50145
## Reviewers

- [x ] Ambient
- [x ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

### CODE REVIEW

**Comment by linsun** [comment]
@howardjohn can you take a quick look to see if there is any other simplification we can apply?

I kept L7 authz policy for productpage as it is nice to show the waypoint proxy worked on multiple services, just didn't call it from ingress-gw.

I removed the inpod stuff checking, think it is best to have it in a debug/ztunnel section vs getting started as inpod is the only mode we support so no need to check it. :)

**Review by dhawton — APPROVED** [review]
Changes look good to me on first pass. I put a DNM to allow others to look as well.

**Review by bleggett — COMMENTED** [review]
In light of https://github.com/istio/istio/pull/50572 tweaked slightly

**Comment by linsun** [comment]
> In light of [istio/istio#50572](https://github.com/istio/istio/pull/50572) tweaked slightly

Yep, thank you for the suggestions!

**Review by ilrudie — APPROVED** [review]
looks good, left a few minor tweaks but no show stoppers

**Comment by linsun** [comment]
> looks good, left a few minor tweaks but no show stoppers

Thanks! I forgot to remove the extra cmd, good catch!

**Comment by linsun** [comment]
remove don't merge as this is better than what we have - we can always iterate on the content.

**Pull request merged**
