### PR TITLE
Fix a link for analysis

### PR DESCRIPTION
**Pull request by hanxiaop**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by zirain — APPROVED** [review]

**Review by ericvn — COMMENTED** [review]
The links may be updated, but looks like we have an issue with links in the indented text.
Screenshot 2022-10-09 at 10 07 43 PM

**Comment by hanxiaop** [comment]
> I did a little experimentation this morning. Update the indentation in the Q&A section to be 4 spaces instead of 6. This should fix the issue. I noticed that this markdown is stricter to the number of spaces.
> 
> Snapshot of my `make serve` after the update: Screenshot 2022-10-10 at 9 24 50 AM

@ericvn Thanks! It looks great. Just revised.

**Review by ericvn — APPROVED** [review]
Thanks. Indention looks correct now.

**Comment by ericvn** [comment]
Cherry-pick to 1.15 since it has the new markdown and needs this same indentation fix.

**Pull request merged**
