### PR TITLE
Announce Istio 1.14 end of life

### PR DESCRIPTION
**Pull request by lei-tang**
Please provide a description for what this PR is for.
Announce Istio 1.14 end of life. A do-not-merge label is added to merge the PR on Dec. 27, 2022.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by ericvn — APPROVED** [review]

**Comment by zirain** [comment]
@lei-tang `DNM` can be removed now?

**Comment by ericvn** [comment]
> @lei-tang `DNM` can be removed now?

No. As noted in the first post: `. A do-not-merge label is added to merge the PR on Dec. 27, 2022.` On Dec. 27 the label is removed to merge this at that time.

**Comment by zirain** [comment]
> > @lei-tang `DNM` can be removed now?
> 
> No. As noted in the first post: `A do-not-merge label is added to merge the PR on Dec. 27, 2022.` On Dec. 27 the label is removed to merge this at that time.

sorry, I miss that.

**Pull request merged**
