### PR TITLE
use different pod for querying kube system pods

### PR DESCRIPTION
**Pull request by shamsher31**
To fix https://github.com/istio/istio.io/issues/8815

```
[istio-1.9.0-beta.0]$ export KUBE_POD=$(kubectl -n kube-system get pod -l component=kube-scheduler -o jsonpath='{.items[0].metadata.name}')
```

This produces proper warning message.
```
[istio-1.9.0-beta.0]$ ./bin/istioctl x describe pod -n kube-system $KUBE_PODPod: kube-scheduler-istio-testing-control-plane
   Pod does not expose ports
WARNING: kube-scheduler-istio-testing-control-plane is not part of mesh; no Istio sidecar
Warning: No Kubernetes Services select pod kube-scheduler-istio-testing-control-plane (see https://istio.io/docs/setup/kubernetes/additional-setup/requirements/ )
--------------------
2021-01-21T11:20:10.553176Z     error   klog    an error occurred forwarding 35325 -> 15000: error forwarding port 15000 to pod 0e137325f7a7c4da385948a70ae7cca525678ff15d32f16b2a0b6ba510f81ef8, uid : failed to execute portforward in network namespace "host": failed to dial 15000: dial tcp4 127.0.0.1:15000: connect: connection refused
Error: failed to execute command on sidecar: failure running port forward process: Get "http://localhost:35325/config_dump": EOF
```

### CODE REVIEW

**Comment by ericvn** [comment]
One issue I see is that IKS does not have the `kube-scheduler` pod.

**Comment by ericvn** [comment]
Working with @shamsher31, it looks like minikube, Docker for Mac, kind, and IKS all have `kubectl get pod -n kube-system -l k8s-app=kube-dns` returning 1 or more pods.

**Comment by ericvn** [comment]
I did verify the current kube-dns label commands in this PR work on IKS.

**Comment by shamsher31** [comment]
@ericvn I think the `istioctl describe` uses the first pod to query if there are multiple pods available with the same label so it's good to use the `k8s-app=kube-dns` label.

I tried on `kind` and it works fine too.

**Comment by ericvn** [comment]
The `.items[0]` should just be grabbing the first pod in the list and assigning to POD_NAME.

**Review by ericvn — APPROVED** [review]

**Pull request merged**
