### PR TITLE
Update the number of CRDs to expect during installation

### PR DESCRIPTION
**Pull request by philrud**
With the upgrade of cert-manager to v0.6.2 two new CRDs are being
introduced. The total number of CRDs should now be `58`. Updating
the CRDs installation section of the documentation accordingly.

### CODE REVIEW

**Comment by ericvn** [comment]
@philrud I've noted the same changes. Are you planning to fix the noted conflict?

**Comment by philrud** [comment]
@ericvn yes, looking

**Comment by philrud** [comment]
@ericvn rebased, could you help reviewing/merging please? thanks!

**Comment by ozevren** [comment]
/lgtm

however, it looks like your PR has an unrelated problem. You may need to sync and rebase.

**Comment by philrud** [comment]
Thanks, @ozevren . Rebased again, the CircleCI test is green now. 
@fleeto @rcaballeromx could you approve, please? Thanks.

**Comment by philrud** [comment]
cc @sdake @frankbu @gyliu513 @rootsongjc, could anyone approve please?
thanks in advance folks!

**Comment by sdake** [comment]
> cc @sdake @frankbu @gyliu513 @rootsongjc, could anyone approve please?
> thanks in advance folks!

if you use /assign sdake - I will see the approval request in my dashboards, otherwise there may be lag.

cheers
-steve

**Pull request merged**
