### PR TITLE
update markdownlint headers to match doc

### PR DESCRIPTION
**Pull request by rashmi43**
## Description

Fixes: https://github.com/istio/istio.io/issues/15148

## Reviewers

- [ ] Ambient
- [X ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

### CODE REVIEW

**Comment by craigbox** [comment]
@rashmi43 Thanks for this, but the issue in question was asking to change the engine we use, not the configuration for the current one.

The change youve proposed would  actually break every doc in istio.io, as they would all expect to start with a single `#` heading, where they currently start with a `##` heading.

**Comment by rashmi43** [comment]
thanks for your comments, how can I go about engine change?

**Comment by craigbox** [comment]
You would need to learn how the current script/build tools use the Ruby version of markdownlint, update them to package and use the Node.JS version, and then update the configuration to match our existing rules. 

You may also need to do a mass update of the docs to fix any behaviour we can't configure around.

If you are interested in doing this, then consider dropping by #docs on the Istio slack.

**Comment by rashmi43** [comment]
> You would need to learn how the current script/build tools use the Ruby version of markdownlint, update them to package and use the Node.JS version, and then update the configuration to match our existing rules.
> 
> You may also need to do a mass update of the docs to fix any behaviour we can't configure around.
> 
> If you are interested in doing this, then consider dropping by #docs on the Istio slack.

sure I will take this up

**Pull request closed without merging**
