### PR TITLE
Add Wehkamp as an Istio user

### PR DESCRIPTION
**Pull request by johnkeates**
This adds Wehkamp as a company that uses Istio.

### CODE REVIEW

**Comment by kfaseela** [comment]
Thanks for the PR @johnkeates ! :) it would be great if you could just sign the EasyCLA, so that the verification passes! and we can get this merged :)

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by johnkeates** [comment]
Hi @kfaseela, I'm currently trying to get the legal department to learn about what a CLA is, and why it would be wise to have a company-wide signing process instead of me just doing it myself (which I will end up doing if it takes too long for them to get back to me :) )

**Comment by ericvn** [comment]
I'm not sure when we will actually have the Easy-CLA the required test and the cla/google removed, but hopefully soon. Just not wanting you to chase the cla/google when it will go away at seem point.

**Comment by craigbox** [comment]
I don't know if we can kick an issue into using the new CNCF CLA instead of the Google one, so the best thing to do might be to close and re-submit this PR.  Sorry for all the hoops we're making you jump through, @johnkeates !

**Comment by johnkeates** [comment]
I'm pretty stoked to see Istio graduate so I don't mind the hoops (or changing hoops for that matter). I think I got the whole CLA thing explained and covered, so at least that knowledge has a chance to stick at the corp level which is important to me just as much.

I'll actually go and see if I can get the old (or current) one signed and if we have a global CNCF one as well I'll do that at the same time.

**Comment by craigbox** [comment]
If I try and click "Details" on the EasyCLA check, it just asks me to sign. I'm covered, else I wouldn't have been able to contribute to Istio the last few months. But it doesn't show me if John is.

**Comment by ericvn** [comment]
> [CLA Not Signed](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/34682364/82706976/13074/#/?version=2)
> 
> * ✅ login: craigbox / name: Craig Box  ([65c73d1](https://github.com/istio/istio.io/commit/65c73d12995669cd6a5508b795bbc5598145403c))
> * [❌](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/34682364/82706976/13074/#/?version=2) - login: @johnkeates / name: John Keates . The commit ([aeee4ec](https://github.com/istio/istio.io/commit/aeee4ec2e938a5253430297bf0c6e9b35d94a53a), [bbab773](https://github.com/istio/istio.io/commit/bbab773d47f68a810e8ef50847f5f05c65737b44)) is not authorized under a signed CLA. [Please click here to be authorized](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/34682364/82706976/13074/#/?version=2). For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

Shows Craig with a green check, and John with a red x.

**Review by craigbox — COMMENTED** [review]
John, we'd love to merge this, but we still need you to look at the CLA please!

**Comment by johnkeates** [comment]
There's some progress! I sent the signing notification to the CTO this afternoon, so this should finally be completed ⏳

**Comment by johnkeates** [comment]
Does EasyCLA call back to the GitHub status API as soon as the signing is complete?

**Comment by kfaseela** [comment]
Usually it does retrigger the easycla check, once you open the link and sign the cla

**Comment by craigbox** [comment]
So I guess that means he didn't sign, but I can't see that.
I have opened a ticket with the LF about how opaque this is, and how `/easycla` isn't doing anything.

**Review by ericvn — APPROVED** [review]

**Comment by johnkeates** [comment]
Just to test a thing, I'll try to see if the easyCLA dashboard actually shows anything when I try that command. I did see a bunch of identical messages the LF dashboard but I have no idea if that means it's actually getting triggered.

**Comment by johnkeates** [comment]
Same message in the timeline for EasyCLA, doing it manually again does trigger the Approval Request mail but doesn't show up as an ack or approval item. Maybe this is because I'm also the CLA manager. 

Sorry for the noise, I'll go search for an EasyCLA specific channel to talk to someone who manages it :)

**Comment by craigbox** [comment]
I have a support ticket open with the LF about this; I'll ping it.

**Pull request merged**
