### PR TITLE
Install istio-cni into kube-system to use system-node-critical priorityClass

### PR DESCRIPTION
**Pull request by rlenglet**
Fixes https://github.com/istio/istio/issues/14977
Fixes https://github.com/istio/cni/pull/126
Related to https://github.com/kubernetes/kubernetes/pull/65593

### CODE REVIEW

**Comment by rlenglet** [comment]
This will need to be backported to `release-1.2`.

**Comment by linsun** [comment]
@rlenglet why we need this change? is it because a newer version of k8s?  I'm sure we tested the instruction in 1.1.

**Comment by frankbu** [comment]
If this change is required in the current 1.2 docs, you should send the PR to the `release-1.2` branch, instead of master. The commit will be cherry-picked to master later, hopefully by a bot.

**Comment by rlenglet** [comment]
> If this change is required in the current 1.2 docs, you should send the PR to the release-1.2 branch, instead of master. The commit will be cherry-picked to master later, hopefully by a bot.

Right. I'll change the target branch to `release-1.2`. Thanks!

> why we need this change? is it because a newer version of k8s? I'm sure we tested the instruction in 1.1.

Adding the `priorityClass` is a change I made late in 1.2, after I tested the 1.2 instructions. I missed the bug because our e2e tests do install `istio-cni` into `kube-system` (cf. https://github.com/istio/cni/blob/df641f973b6c7f0c69912e6bf25fc969b12d400a/.circleci/run_e2e.sh#L27).

Since this is the only tested namespace, and the only working configuration, this should be reflected in the doc.

**Comment by linsun** [comment]
@rlenglet thanks for the explanation.  Do you foresee any issue with this when upgrading from 1.1 while using CNI and switched from istio-system ns to kube-system ns?  I think users could end up running CNI in both nses.

**Comment by sdake** [comment]
@frankbu I thought the workflow was merge to master first, then cherrypick?

cheers
-steve

**Comment by frankbu** [comment]
@sdake, it turns out that the merge-to-release-branch bot that @geeknoid added wasn't working reliably (sometimes picking up extra commits), so he had to disable it. So for now we are back to the old process of just sending PRs that belong in 1.2 to the release-1.2 branch and then in a few weeks from now we will do a bulk cherry-pick. Martin is also going to experiment with changing the merge bot to work the other way, i.e., send PRs to release branch with a `merge-to-master` label to do the automatic cherry-pick back to master.

**Pull request merged**
