### PR TITLE
Add BlaBlaCar company logo

### PR DESCRIPTION
**Pull request by etifontaine**
Add BlaBlaCar, we have been using Istio in production for more than 2 years.
It has help us to easily migrate from on-prem to the Cloud, and support more than 90 millions users worldwide.

We have made contributions to Istio and we would like to be part of this list.

https://github.com/blablacar

Thank you :) 

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by craigbox — APPROVED** [review]

**Comment by ericvn** [comment]
Note that the test will continue to fail. I will have a PR shortly which should fix the failure, and allow the test to pass.

**Pull request merged**
