### PR TITLE
Release 1.20 performance result 

### PR DESCRIPTION
**Pull request by Shuayb1**
## Reviewers

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [x] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

### CODE REVIEW

**Comment by ericvn** [comment]
I suspect this PR may have been created inadvertently, as there already is a PR against the master branch. One that work is complete, we should be able to automatically cherry-pick that to the 1.20 release.

**Comment by ericvn** [comment]
Would you add this commit to the other PR, https://github.com/istio/istio.io/pull/14228?  We can work on getting that one merged.

**Comment by ericvn** [comment]
> Would you add this last commit, the captions, to the other PR, #14228? We can work on getting that one merged.

You would want to do this in your master branch, not the release-1.20 branch associated with this PR.

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Review by ericvn — CHANGES_REQUESTED** [review]
Request since this PR shouldn't merge here.

**Comment by ericvn** [comment]
Cherry-pick: https://github.com/istio/istio.io/pull/14265

**Pull request closed without merging**
