### PR TITLE
reference docs to app-identity-access-adapter

### PR DESCRIPTION
**Pull request by huangjoyce3**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by geeknoid** [comment]
@huangjoyce3 Thanks, this looks good. Please sign the CLA and we're good to go.

**Comment by icemann92** [comment]
@googlebot I signed it!

**Comment by icemann92** [comment]
@geeknoid I have signed the CLA (we have a corporate CLA) but I still complains `CLAs are signed, but unable to verify author consent`. Any idea what might be happening? Or anybody I can reach out to?

I do have my email set on the commit and that is the one linked to my CLA.

**Comment by geeknoid** [comment]
I picked this change up as part of https://github.com/istio/istio.io/pull/4771, so closing.

Thank for the adapter & docs!

**Pull request closed without merging**
