### PR TITLE
zh:update-/docs/releases/security-vulnerabilities/index.md

### PR DESCRIPTION
**Pull request by yanrongshi**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by Xunzhuo — APPROVED** [review]

**Comment by Xunzhuo** [comment]
@yanrongshi CLA failed, make sure the email you commit is the CLA signed one

**Comment by yanrongshi** [comment]
> @yanrongshiCLA 失败，请确保您提交的电子邮件是 CLA 签名的

I have try to fix this issues,Hover it haven't any change,what should id in the next?

**Comment by kebe7jun** [comment]
image

You you an invalid email `<yanrong.shi>`, you should remove that commit.

**Comment by yanrongshi** [comment]
> image
> 
> You you an invalid email `<yanrong.shi>`, you should remove that commit.

thanks boss

**Pull request closed without merging**
