### PR TITLE
Update Twitter card preview & OG metadata

### PR DESCRIPTION
**Pull request by craigbox**
First draft of fixing #14711:

* change social image from SVG to PNG, because while Facebook supports SVG, not all OpenGraph consumers do (notably Twitter)
* add image directly with Twitter metadata.

If this looks good, I'll add support for custom images in a follow up PR.

### CODE REVIEW

**Comment by craigbox** [comment]
#14715 to fix the lint issue (the PNG has to exist first, else the tests fail; I can't add it in the same PR.)

**Comment by craigbox** [comment]
Screenshot 2024-03-11 at 3 28 41 PM

**Review by kfaseela — APPROVED** [review]

**Pull request merged**
