### PR TITLE
[zh] Localize two svg in /traffic-management/tls-configuration/

### PR DESCRIPTION
**Pull request by windsonsea**
Localize two images into Chinese.

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

### CODE REVIEW

**Review by my-git9 — APPROVED** [review]

**Review by wilsonwu — APPROVED** [review]
LGTM, thanks!

**Comment by windsonsea** [comment]
Weird. It's always failed if only images are included in this PR. When I modified some text in the markdown file that references to the both images, the CI passed.

**Pull request merged**
