### PR TITLE
Fix typo. (#9862)

### PR DESCRIPTION
**Pull request by NatasG**
[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by kebe7jun — APPROVED** [review]

**Comment by ericvn** [comment]
Noted the test failure, and looks to be correctable. See: https://github.com/istio/istio.io/pull/9865

**Pull request merged**
