### PR TITLE
[docs] modify the indentation in the configuration command so that th…

### PR DESCRIPTION
**Pull request by XinruiChentw**
…e configuration can take effect

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [X] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by windsonsea** [comment]
/ok-to-test

Please sign the CLA before review process.

**Comment by ericvn** [comment]
Also not the making this change only in the 1.18 branch will make it available on istio.io for a month or so and then it will be reverted. The change needs to be cherry-picked to master.

**Review by kfaseela — APPROVED** [review]
Please sign the CLA, so that the PR can be merged

**Review by my-git9 — APPROVED** [review]

**Review by windsonsea — COMMENTED** [review]
This PR is open for a while after comments and has been fixed in #13947, so it will be closed.

**Pull request closed without merging**
