### PR TITLE
Add img redirects

### PR DESCRIPTION
**Pull request by ericvn**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by ericvn** [comment]
As a test using the netlify generated site, I tried going to https://deploy-preview-7541--istio.netlify.app/img/logo.png and was redirected.

**Comment by ericvn** [comment]
@davidhauck I'm not sure. https://istio.io/favicons is called out in feed.xml and index.yaml.

**Comment by ericvn** [comment]
@davidhauck I think we can do the others as we research them. We do know that the Grafana dashboard uses https://istio/io/img/logo.png and this does appear to fix that.

**Comment by brian-avery** [comment]
Fixes #24618

**Comment by ldemailly** [comment]
https://istio.io/img/istio-logo.svg is 404'ing atm

**Comment by ldemailly** [comment]
> https://istio.io/img/istio-logo.svg is 404'ing atm

 refixed on master in #8209 and follow up for color issue with grafana on https://github.com/istio/istio/issues/27553

**Pull request merged**
