### PR TITLE
zh-translation:/docs/setup/additional-setup/cni/index.md

### PR DESCRIPTION
**Pull request by helight**
translate /docs/setup/additional-setup/cni/index.md to zh

### CODE REVIEW

**Comment by helight** [comment]
> /ok-to-test



> @helight: The following test **failed**, say `/retest` to rerun them all:
> 
> Test name	Commit	Details	Rerun command
> lint_istio.io	[d8bc7ee](https://github.com/istio/istio.io/commit/d8bc7eec8f6257e0696d245786b8c8711f84049f)	[link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio.io/6039/lint_istio.io/3049)	`/test lint_istio.io`
@SataQiu  this error i fixed in other pr, the err is in other file.

- ./public/zh/docs/ops/configuration/traffic-management/locality-load-balancing/index.html
  *  External link https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#failure-domain-beta-kubernetes-io-region failed: https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/ exists, but the hash 'failure-domain-beta-kubernetes-io-region' does not
- ./public/zh/docs/setup/additional-setup/cni/index.html
  *  linking to internal hash #gke-setup that does not exist (line 65535)
     <a href="#gke-setup">GKE 设置</a>
htmlproofer 3.12.0 | Error:  HTML-Proofer found 2 failures!
LINTING FAILED
Makefile.core.mk:27: recipe for target 'lint' failed
make: *** [lint] Error 1

**Comment by helight** [comment]
@SataQiu please help to review this pr. thanks for your time.

**Comment by rootsongjc** [comment]
@helight  Please refer to the issue on istio-official-doc-translation issue when submit PR  next time.

**Comment by helight** [comment]
> @helight Please refer to the issue on istio-official-doc-translation issue when submit PR next time.

ok, got that.

**Pull request merged**
