### PR TITLE
Fix the number of CRD's installed

### PR DESCRIPTION
**Pull request by jwendell**

### CODE REVIEW

**Comment by frankbu** [comment]
Have the CRDs already been removed in the current release, or does this doc change need to wait until 1.1.4 is out?

**Comment by jwendell** [comment]
@frankbu this is for 1.1.3

**Comment by sdake** [comment]
Here are the results I see in the release from 1.1.3:

```
Stevens-MacBook-Pro:files sdake$ grep CustomResource crd-10* crd-11* | wc -l
      53
Stevens-MacBook-Pro:files sdake$ ls
crd-10.yaml		crd-11.yaml		crd-certmanager-10.yaml	crd-certmanager-11.yaml
Stevens-MacBook-Pro:files sdake$ grep CustomResource crd-certmanager-1* | wc -l
       5
Stevens-MacBook-Pro:files sdake$ pwd
/Users/sdake/Downloads/istio-1.1.3/install/kubernetes/helm/istio-init/files```

**Comment by frankbu** [comment]
hmm. @sdake, are you sure you installed 1.1.3 on a clean cluster, that didn't have old CRDs still hanging around?

**Comment by frankbu** [comment]
Oh wait, you are just looking at the yamls in the distribution. So that seems to imply that all 53/58 CRDs are still being used in 1.1.3. @jwendell ???

**Comment by jwendell** [comment]
@sdake is right. This PR should go against master. Since the number is likely to change, I'll close this PR for now.

**Comment by sdake** [comment]
@frankbu this was from the distributed tarball.  I just fetched and rebased my trees.

Master has 24 CRDs.  release-1.1 has 59ish.

The CRD count is a master specific change.

**Pull request closed without merging**
