### PR TITLE
Add 1.9 eol final announcement

### PR DESCRIPTION
**Pull request by shamsher31**
Support for Istio 1.9 ends on August 24th, 2021
https://istio.io/latest/news/support/announcing-1.9-eol/

### CODE REVIEW

**Comment by ericvn** [comment]
I think it's hard to announce EOL for 8/18 when we've already announced that we will have a security fix next week. I would think we would extend the EOL until after that security patch is released.

You will also want to update the Supported Releases page.

**Comment by shamsher31** [comment]
> I think it's hard to announce EOL for 8/18 when we've already announced that we will have a security fix next week

Thanks for the update. I will work with @jacob-delgado  on this.

**Comment by jacob-delgado** [comment]
> > I think it's hard to announce EOL for 8/18 when we've already announced that we will have a security fix next week
> 
> 
> 
> Thanks for the update. I will work with @jacob-delgado  on this.

We should update the first announcement to say the 24th as well as this one.

**Comment by shamsher31** [comment]
> We should update the first announcement to say the 24th as well as this one.

Date updated.

**Review by Xunzhuo — COMMENTED** [review]
/lgtm

**Review by craigbox — APPROVED** [review]

**Comment by craigbox** [comment]
approved, i'll leave it to you to remove DNM and coordinate with the other PRs.

**Pull request merged**
