### PR TITLE
Fix bash command error

### PR DESCRIPTION
**Pull request by FangtingYan**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by kebe7jun — APPROVED** [review]
Thanks！

**Review by kfaseela — COMMENTED** [review]
LGTM

**Review by kfaseela — APPROVED** [review]

**Comment by ericvn** [comment]
It's -B4 on istio.io (English), so cherrypicking to 1.15

**Pull request merged**
