### PR TITLE
Advance master to 1.12

### PR DESCRIPTION
**Pull request by ericvn**
- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by ericvn** [comment]
Looks like I need to tweak the istioctl page.

**Comment by ericvn** [comment]
Was missing the IMAGE_VERSION update in the script to update the Makefile as well as updating to use the latest istio from master/main.

Also manually picked up some go.mod changes that were merged into the istio.io/istio go.mod.

**Review by davidhauck — APPROVED** [review]

**Comment by ericvn** [comment]
https://github.com/istio/istio.io/issues/10179 created for disabling the examples/virtual-machines test.

**Review by frankbu — APPROVED** [review]

**Pull request merged**
