### PR TITLE
Prevent translated content from referencing English content.

### PR DESCRIPTION
**Pull request by geeknoid**
- In order to allow each language's content to evolve independently,
introduce a new linter rule to prevent translated content from having
references to English content.

- Fix many such references in the existing translated content.

### CODE REVIEW

**Comment by geeknoid** [comment]
@rootsongjc We discussed challenges English doc writers have to deal with at this week's TOC meeting around broken links in translation. It became clear that we need to keep the individual languages isolated from one another to avoid problems. This PR puts in a linter rule to prevent cross-linking, and fixes a bunch of links that were pointing from the Chinese content to the English content.

Unfortunately, this leads to a number of broken links in the Chinese content. That is, the links used to point to content/en/XXX, but there is no matching content/zh/XXX and so the link checker fails.

Could you please take over this PR and fix the missing links? I think it's mostly about:

- Copying a file from the english content into the Chinese content, to be translated later.

- Adding {#XXX} annotations to headers such that links with fragment references (foo/bar#XXX) work.

As this PR touches a lot of files, it'd be best to push it in ASAP to avoid constant merge conflicts.

Thanks.

**Comment by rootsongjc** [comment]
@geeknoid We have noticed this problem when submitting Chinese documents, and we have ensured that all checks are passed without the problem of broken links.

**Comment by geeknoid** [comment]
@rootsongjc The issue is that Chinese content currently links to English content. As English content evolves, English authors end up having to modify the Chinese content in order for the cross-links to not be broken. This means that English changes are blocked on Chinese contributors.

What this PR tries to do is to separate the two worlds completely. Chinese content only references Chinese content, and English content only references English content. The two can thus evolve independently without interfering with one another.

**Comment by rootsongjc** [comment]
@istio/wg-docs-maintainers-chinese anyone who can deal with this issue?

**Comment by tanjunchen** [comment]
@rootsongjc we can deal with this pr first. Tell the translator, pay attention to the translation rules.
@geeknoid  deal with conflicts.
Next,we will open an issue to deal with this problems. Thanks

**Comment by tanjunchen** [comment]
@geeknoid: PR needs rebase.

**Comment by geeknoid** [comment]
@tanjunchen I've updated the PR to adapt to latest changes.

To avoid this getting so out of date again, can you copy this PR and address the linter issues so that it can be merged?

Thanks.

**Comment by tanjunchen** [comment]
@geeknoid sure. I will fix the same question after  your pr is merged

**Pull request closed without merging**
