### PR TITLE
step 10 is duplicated with step 4

### PR DESCRIPTION
**Pull request by SerenaFeng**
In the document, the operation of step 4 is the same with step 10:

```
4. Install the root certificate at /var/run/secrets/istio:

$ sudo mkdir -p /var/run/secrets/istio
$ sudo cp "${HOME}"/root-cert.pem /var/run/secrets/istio/root-cert.pem

10. Install the root certificate in the directory /var/run/secrets/istio

$ sudo cp "${HOME}"/root-cert.pem /var/run/secrets/istio/root-cert.pem
```

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by ericvn — APPROVED** [review]
LGTM

@SerenaFeng You will need to satisfy the CLA bot before this can merge.

**Comment by SerenaFeng** [comment]
> LGTM
> 
> @SerenaFeng You will need to satisfy the CLA bot before this can merge.

Hi ericvn,

I have signed the CLA, it still shows error, how to trigger the CLA recheck??

**Comment by ericvn** [comment]
@SerenaFeng From the CLA bot text above: In order to pass this check, please resolve this problem and then comment `@googlebot I fixed it.`. If the bot doesn't comment, it means it doesn't think anything has changed.

**Comment by ericvn** [comment]
Interesting that it found the text anywhere in the text, and reran the check and it's fixed.

**Pull request merged**
