### PR TITLE
[zh] Change a term about namespace

### PR DESCRIPTION
**Pull request by zhiyingfang2022**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

 Hello, I carefully read your document, found that namespace more translation is namespace, taking into account the principle of document consistency, so unified change to namespace.

### CODE REVIEW

**Comment by windsonsea** [comment]
Hi @zhiyingfang2022 , you need to sign the CLA before the review process.

**Review by windsonsea — COMMENTED** [review]
`package-lock.json` shall not be included in this PR.

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Review by windsonsea — APPROVED** [review]
lgtm for this consistency catch. Namespace is localized to `命名空间` currently.

**Pull request merged**
