### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by ASaiun**
changed the command when user install istio with the helm v3 (without Tiller)

### CODE REVIEW

**Comment by ostromart** [comment]
All our testing so far has been with helm v2, we haven't tested at all with v3. First, we would need to change our tests to use v3. 
For the time being we should make it clear that the docs are for v2 and migrate to v3 once tests are running with that.

**Comment by ericvn** [comment]
I haven't tried this, but if the change above works with both Helm v3 and Helm v2 what's the problem with making the update? We want to force not working with Helm 3 even though we have a warning? Note that we already have a warning for an intermediate PR. @howardjohn had a change requested so for sure need his feedback.

**Comment by howardjohn** [comment]
@ericvn I am not sure this actually makes helm 3 work. There is no testing. Helm 3 is intentionally NOT backwards compatible, so pretending it is doesn't seem like a good idea

**Comment by frankbu** [comment]
Closing because these nstructions have been removed.

**Pull request closed without merging**
