### PR TITLE
Updating InfraCloud in Pro_Services Providers (under Ecosystem)

### PR DESCRIPTION
**Pull request by chetanpdeshmukh**
Please provide a description for what this PR is for.

Updating details of InfraCloud Technologies (https://istio.io/latest/about/ecosystem/ pro services section)

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by chetanpdeshmukh** [comment]
@kfaseela Thanks for approving and merging the PR. However, I am still seeing the old content (highlighted in RED) but, I can see the new content in the [Deploy preview link of this PR](https://deploy-preview-12327--preliminary-istio.netlify.app/latest/about/ecosystem).


image

**Comment by kfaseela** [comment]
@chetanpdeshmukh : You need to look at https://preliminary.istio.io/latest/about/ecosystem as your PR is only merged to master. istio.io points to the latest stable revision. If needed, we can cherry-pick the PR to the stable version.

**Comment by chetanpdeshmukh** [comment]
> @chetanpdeshmukh : You need to look at https://preliminary.istio.io/latest/about/ecosystem as your PR is only merged to master. istio.io points to the latest stable revision. If needed, we can cherry-pick the PR to the stable version.

Ahh, thanks @kfaseela for the update. that helps :)

**Comment by chetanpdeshmukh** [comment]
@kfaseela Seems like the cherrypick didn't trigger. Mind checking, please?

**Comment by kfaseela** [comment]
Thanks @ericvn

**Comment by ericvn** [comment]
release-1.17 doesn't exist yet, so that makes sense.

**Comment by chetanpdeshmukh** [comment]
thank you @kfaseela and @ericvn :)

**Pull request merged**
