### PR TITLE
optimize html style

### PR DESCRIPTION
**Pull request by xichengliudui**
Please provide a description for what this PR is for.
`#` belongs to markdown syntax, markdown syntax does not take effect in HTML

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [x] Docs
image

### CODE REVIEW

**Review by ericvn — CHANGES_REQUESTED** [review]
Note that these files are created by running the commands. If you look at the header, you will see a message to not update theses files directly.  I'm not sure if this change should be in the scripts that post process the file or within the command output itself.

**Comment by xichengliudui** [comment]
> Note that these files are created by running the commands. If you look at the header, you will see a message to not update theses files directly. I'm not sure if this change should be in the scripts that post process the file or within the command output itself.
> 
> See https://github.com/istio/istio.io/blob/master/scripts/grab_reference_docs.sh#L150-L160



> Note that these files are created by running the commands. If you look at the header, you will see a message to not update theses files directly. I'm not sure if this change should be in the scripts that post process the file or within the command output itself.
> 
> See https://github.com/istio/istio.io/blob/master/scripts/grab_reference_docs.sh#L150-L160

The correct fix would be to convert '####' to `<h4></h4>` label

https://github.com/istio/pkg/blob/9f66753e4ffc7894b0cc1f432e6977de085a246f/collateral/control.go#L432-L527
we may need to update this func, `#### Linux` and `#### macOS` is matched as text
```go
	if cmd.Long != "" {
		g.emitText(cmd.Long)
	} else if cmd.Short != "" {
		g.emitText(cmd.Short)
	}
```

**Comment by xichengliudui** [comment]
I currently do not know how to match, do you have any clue?

**Comment by ericvn** [comment]
> I currently do not know how to match, do you have any clue?

I'm not sure if the ### Linux is part of the string, or is it added as part of the EscapeSting(). Maybe there is some snippet oc code to simply replace `####` in the emitText message.

**Comment by craigbox** [comment]
Any update, @xichengliudui?

**Pull request closed without merging**
