### PR TITLE
add ygrene to list of companies using Istio in Action

### PR DESCRIPTION
**Pull request by zparnold**
This adds Ygrene Energy Fund to the list of companies present and also removes the CSS animation that makes logos spin. The first one I'd like to have for sure, the animation I can remove, but I feel that it detracts from the companies when the `:hover` state is fired in the DOM

### CODE REVIEW

**Comment by zparnold** [comment]
I signed it!

**Comment by geeknoid** [comment]
I've received a lot of comments about folks loving the whimsy of the fidget-spinner animations we use there, so I'd like to keep that as-is. Would you just add the company logo without the animation change please?

**Comment by zparnold** [comment]
Yep! @geeknoid will do. Thanks 😄

**Comment by zparnold** [comment]
@geeknoid Just pushed

**Pull request merged**
