### PR TITLE
move dualstack to alpha

### PR DESCRIPTION
**Pull request by kfaseela**
Based on https://github.com/istio/enhancements/pull/185

### CODE REVIEW

**Comment by kfaseela** [comment]
cc @whitneygriffith @howardjohn

**Comment by dhawton** [comment]
Needs to be updated here, too: https://istio.io/latest/docs/releases/feature-stages/#core

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/releases/feature-stages/#core is automated from enhancements repo I think

**Comment by dhawton** [comment]
> https://istio.io/latest/docs/releases/feature-stages/#core is automated from enhancements repo I think

Well, not automated.. it's part of `make update_ref_docs`

**Comment by dhawton** [comment]
> https://istio.io/latest/docs/releases/feature-stages/#core is automated from enhancements repo I think

You're right.. or can be updated with `make update_ref_docs`.

**Review by dhawton — APPROVED** [review]

**Pull request merged**
