### PR TITLE
[Release-1.5] Fix the guide of "Verifying connectivity to Istio Pilot"

### PR DESCRIPTION
**Pull request by lei-tang**
Please provide a description for what this PR is for: https://github.com/istio/istio.io/issues/6676

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by frankbu** [comment]
A related issues is whether Pilot is still supposed to be used in docs.
#6711 is removing Pilot from the architecture doc, and replacing it with istiod, but it seems that Pilot isn't exactly gone. Should Pilot still be in the architecture doc?
@howardjohn WDYT?

**Comment by howardjohn** [comment]
there should probably be no references to Pilot. We can still have this doc just renamed to "Verifying connectivity to Istiod"

**Comment by lei-tang** [comment]
@frankbu I have changed Pilot to Istiod. Please take another look.

**Comment by ericvn** [comment]
Pilot still show up on a lot of the rest of the page. Not sure if we can just write another issue to fix it and let this go in (and have a half Pilot/Istiod page) or if the whole page needs to be done.

**Comment by lei-tang** [comment]
@ericvn I have pushed a commit to rename Pilot to Istiod.

**Comment by ericvn** [comment]
LGTM. Thanks for the updates. Will let @frankbu approve or ask for more changes.

**Pull request merged**
