### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by zackzhangkai**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by zackzhangkai** [comment]
I'm a member of istio , in the fact. My github name is already in the community doc. https://github.com/istio/community/blob/master/org/members.yaml#L72
But why does nobody invite me to the istio org?

**Review by craigbox — APPROVED** [review]

**Comment by craigbox** [comment]
> I'm a member of istio , in the fact. My github name is already in the community doc. https://github.com/istio/community/blob/master/org/members.yaml#L72
> But why does nobody invite me to the istio org?

I think you might have to be in [developers.yaml](https://github.com/istio/community/blob/master/org/developers.yaml) instead?

I think we are looking to merge these two soon. I'll follow up.

**Pull request merged**
