### PR TITLE
zh:sync /reference/config/security/normalization/

### PR DESCRIPTION
**Pull request by windsonsea**
Added zh text to:

```
content/zh/docs/reference/config/security/normalization/index.md
```

- [x] Docs

### CODE REVIEW

**Review by zirain — CHANGES_REQUESTED** [review]
reference docs are auto-generated from istio/api repo, I'd think we should translate them.

**Comment by zirain** [comment]
@ericvn IIRC, there's a PR related this?

**Comment by windsonsea** [comment]
> reference docs are auto-generated from istio/api repo, I'd think we should translate them.

Yes, all .html zh-files are generated but .md files are localized in this folder.

image

**Comment by zirain** [comment]
open an new ticket to track that.

**Comment by windsonsea** [comment]
This can be closed since we need not to maintain the reference docs that are generated automatically.

**Pull request closed without merging**
