### PR TITLE
zh-translation:content/en/docs/setup/install/operator/index.md

### LINKED ISSUE #8594: zh：translate Istio Operator Install
The process of installing a new version of isito was painful，due to Chinese documents are out of date。
So I plan to translate the installation document. This is the first piece。

/language zh
/assign

### PR DESCRIPTION
**Pull request by zhiguo-lu**
[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

The process of installing a new version of isito was painful，due to Chinese documents are out of date。
So I plan to translate the installation document. This is the first piece。

close #8594

### CODE REVIEW

**Comment by zhiguo-lu** [comment]
@googlebot I signed it!

**Review by rootsongjc — APPROVED** [review]
/LGTM

**Pull request merged**
