### PR TITLE
Update dates of egress blog posts

### PR DESCRIPTION
**Pull request by vadimeisenbergibm**

### CODE REVIEW

**Comment by geeknoid** [comment]
Don't forget to merge this to master.

**Comment by vadimeisenbergibm** [comment]
@geeknoid So what is the procedure now - should I submit my PRs to master from now on? And the PRs that I submit to release-1.1 I must submit also to master, right?

**Comment by geeknoid** [comment]
Correct. New work should happen in master. There is no automatic merging between master and release-1.1.

**Comment by vadimeisenbergibm** [comment]
@geeknoid I see, I will submit new PRs into master and will merge my PRs from release-1.1 into master.

**Pull request merged**
