### PR TITLE
zh: docs/setup/kubernetes/upgrade/notice/index.md

### PR DESCRIPTION
**Pull request by dreadbird**
Update some translations

### CODE REVIEW

**Comment by rootsongjc** [comment]
CI error messages:
```bash
>> 357 files are free from spelling errors
    content_zh/docs/setup/kubernetes/upgrade/notice/index.md
       25 | teway` 的情况下为 `istio-system`）。在VirtualService中引用网关资源时，请使用命名空间/名称格式，而不是使用 `n 

>> 1 spelling error found in 366 files
To learn how to address spelling errors, please see https://github.com/istio/istio.io#linting
Running ["OpenGraphCheck", "ImageCheck", "HtmlCheck", "ScriptCheck", "LinkCheck"] on ["./public"] on *.html... 
```

**Comment by dreadbird** [comment]
@rootsongjc 修复了编译错误

**Pull request merged**
