### PR TITLE
Include prometheus-operator resource example for aggregationRules

### PR DESCRIPTION
**Pull request by dntosas**
Prometheus Best Practises Doc: Include prometheus-operator resource example for aggregationRules

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by ericvn — COMMENTED** [review]
Does it make more sense to make this into two tabs?

**Comment by dntosas** [comment]
> Does it make more sense to make this into two tabs?

Nice idea @ericvn ^^ I will push changes accordingly

**Comment by ericvn** [comment]
https://meet.google.com/svg-fhth-roi

**Comment by dntosas** [comment]
@ericvn made these ones a tab ^^ let me know if you think we should change something on wording or tab titles

**Review by ericvn — APPROVED** [review]

**Pull request merged**
