### PR TITLE
update makefile versions to match docker/build-tools/Dockerfile

### PR DESCRIPTION
**Pull request by AndreaM12345**
fixes https://github.com/istio/istio.io/issues/11971

Please provide a description for what this PR is for.
in the tools repo the versions used referenced by the istio.io repo Makefile do match.  Making changes to sync the versions 

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [x] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by AndreaM12345** [comment]
with the changes get 
```
5:27:29 PM: Build command from Netlify app                                
5:27:29 PM: ────────────────────────────────────────────────────────────────
5:27:29 PM: ​
5:27:29 PM: $ make netlify
5:27:29 PM: Wrote to /opt/build/repo/package.json:
5:27:29 PM: {
5:27:29 PM:   name: repo,
5:27:29 PM:   version: 1.0.0,
5:27:29 PM:   description: | Site | Status |------|------- | istio.io | [![Netlify Status](https://api.netlify.com/api/v1/badges/c98435af-5464-4ac3-93c2-9c98faeec9b6/deploy-status)](https://app.netlify.com/sites/istio/deploys) | preliminary.istio.io | [![Netlify Status](https://api.netlify.com/api/v1/badges/a1cfd435-23d5-4a43-ac6d-8ec9230d9eb3/deploy-status)](https://app.netlify.com/sites/preliminary-istio/deploys) | archive.istio.io | [![Netlify Status](https://api.netlify.com/api/v1/badges/f8c3eecb-3c5c-48d9-b952-54c7ed0ece8f/deploy-status)](https://app.netlify.com/sites/archive-istio/deploys),
5:27:29 PM:   main: index.js,
5:27:29 PM:   directories: {
5:27:29 PM:     test: tests
5:27:29 PM:   },
5:27:29 PM:   scripts: {
5:27:29 PM:     test: echo \Error: no test specified\ && exit 1
5:27:29 PM:   },
5:27:29 PM:   keywords: [],
5:27:29 PM:   author: ,
5:27:29 PM:   license: ISC
5:27:29 PM: }
5:27:30 PM: npm WARN config production Use `--omit=dev` instead.
5:27:36 PM: added 62 packages, removed 140 packages, and changed 254 packages in 6s
5:27:36 PM: 19 packages are looking for funding
5:27:36 PM:   run `npm fund` for details
5:27:36 PM: npm WARN config production Use `--omit=dev` instead.
5:27:37 PM: up to date, audited 1 package in 1s
5:27:37 PM: found 0 vulnerabilities
5:27:39 PM: npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
5:27:39 PM: npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
5:27:39 PM: added 35 packages, and audited 36 packages in 1s
5:27:39 PM: found 0 vulnerabilities
5:27:42 PM: Start building sites …
5:27:42 PM: hugo v0.115.2-8966424e0e521fb1627216a84efd2c5d5917cb0d+extended linux/amd64 BuildDate=2023-07-08T17:06:56Z VendorInfo=gohugoio
5:27:54 PM:                    | EN  | PT-BR | ZH
5:27:54 PM: -------------------+-----+-------+------
5:27:54 PM:   Pages            | 950 |     4 | 885
5:27:54 PM:   Paginator pages  |   0 |     0 |   0
5:27:54 PM:   Non-page files   | 526 |     0 | 484
5:27:54 PM:   Static files     | 232 |   232 | 232
5:27:54 PM:   Processed images |   0 |     0 |   0
5:27:54 PM:   Aliases          |   1 |     0 |   0
5:27:54 PM:   Sitemaps         |   2 |     1 |   1
5:27:54 PM:   Cleaned          |   0 |     0 |   0
5:27:54 PM: Total in 11604 ms
5:28:00 PM: ​
5:28:00 PM: (build.command completed in 30.6s)
5:28:00 PM: ​
5:28:15 PM: (Netlify Build completed in 46s)
5:28:16 PM: Section completed: building
5:28:34 PM: Finished processing build request in 1m46.903s
```

**Comment by AndreaM12345** [comment]
since https://github.com/istio/tools/blob/master/docker/build-tools/Dockerfile#L337 has the @babel/polyfill@7.12.1 unclear what we want to do... should we update the tools repo too?

from the readme on corejs 
It seems that we would want to do something like...

netlify_install:
	@npm init -y
	@npm install --production --global \
	    sass@v1.52.1 \
	    typescript@v4.7.2 \
	    svgstore-cli@v1.3.2 \
		@babel/core@v7.18.2 \
		@babel/cli@v7.17.10 \
		@babel/preset-env@v7.18.2
	@npm install --production --save-dev \
		babel-preset-minify@v0.5.2
	@npm install --save \
		core-js@3.31.1

However I'm unable to find where is the import of babel/polyfill to replace

**Comment by ericvn** [comment]
I am certainly in favor of getting rid of the two messages:
```
5:27:39 PM: npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
5:27:39 PM: npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
```
so I think the changes you made are appropriate. I did try and look around the deploy-preview and so far haven't found any issues.

**Comment by ericvn** [comment]
And I would say after a change is merged here, we should update istio/tools to match.

**Comment by ericvn** [comment]
I wonder if you change the `-production` on the npm install to `--omit=dev`, will remove some messages as well.

**Comment by ericvn** [comment]
Per @AndreaM12345 the other messages did not appear with the latest change.

**Review by ericvn — APPROVED** [review]
LGTM. Thanks

**Pull request merged**
