### PR TITLE
[zh] sync /news/releases/1.15.x/announcing-1.15/upgrade-notes/index.md

### PR DESCRIPTION
**Pull request by Songjoy**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Review by windsonsea — APPROVED** [review]
/lgtm after minor changes

**Comment by windsonsea** [comment]
@zirain  need your help to solve the lint issue, thanks.

**Pull request merged**
