### PR TITLE
Update HUGO_VERSION to 0.127.0

### PR DESCRIPTION
**Pull request by ydFu**
## Description

chore: update HUGO_VERSION to 0.127.0

## Reviewers

[gohugoio/hugo: v0.127.0](https://github.com/gohugoio/hugo/releases/tag/v0.127.0)

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [x] Developer Infrastructure
- [ ] Localization/Translation

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
lgtm

**Comment by ydFu** [comment]
@ericvn take a look when you have time, thanks.

**Comment by ydFu** [comment]
@craigbox Please help review

**Review by craigbox — COMMENTED** [review]
Thanks.  Please note though, we don't need a PR for every new Hugo version.

**Review by craigbox — APPROVED** [review]

**Pull request merged**
