### PR TITLE
remove blackfriday

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/istio/istio.io/issues/11070 and https://github.com/istio/istio.io/issues/10341

### CODE REVIEW

**Comment by ericvn** [comment]
I did take a quick look at https://deploy-preview-11161--preliminary-istio.netlify.app/ and didn't see anything obviously wrong. I did try links, buttons, and some other items. Will let others check, and if noting noted, we can merge and hopefully get more eyes during the testing week.

**Comment by ericvn** [comment]
This does not fix #11070 as there are several remaining. From there lint_istio details:
```
Start building sites … 
hugo v0.95.0-9F2E76AF linux/amd64 BuildDate=2022-03-16T14:20:19Z VendorInfo=gohugoio
WARN 2022/04/10 17:19:42 .Path when the page is backed by a file is deprecated and will be removed in a future release. We plan to use Path for a canonical source path and you probably want to check the source is a file. To get the current behaviour, you can use a construct similar to the one below:

  {{ $path := "" }}
  {{ with .File }}
	{{ $path = .Path }}
  {{ else }}
	{{ $path = .Path }}
  {{ end }}


Re-run Hugo with the flag --panicOnWarning to get a better error message.
```

**Review by ericvn — APPROVED** [review]
No other comments. Let's merge this and see if there is any negative feedback during the upcoming testing.

**Comment by craigbox** [comment]
Sorry, I was late to this.  I'd be pleasantly surprised if there's no obvious changes; I've seen all sorts of things changing between these engines before. We should definitely make sure it's on the agenda for testing!

(I did a quick look for screenshot comparison tools but haven't installed anything yet.)

**Pull request merged**
