### PR TITLE
Update ambient getting started for ingress gw not installed by default

### PR DESCRIPTION
**Pull request by frankbu**
Please provide a description for what this PR is for.

This PR is needed before merging https://github.com/istio/istio/pull/44187

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by linsun — COMMENTED** [review]
LGTM

@danehans do you want to review also?

**Comment by ericvn** [comment]
Reviewed the page and things look good. One thing that I noticed that was outside the scope of this PR was a comment that ambient mode should work on all of the supported platforms, which I think is not true at the moment. Being that we are in a WIP section, this might not be a big issue. Not sure if the README is up to date either on platforms.

**Comment by frankbu** [comment]
This PR is needed so that we can merge https://github.com/istio/istio/pull/44187, which will break the test otherwise.

It temporarily disables part of the test, which will be re-enabled, along with other small improvements in a followup PR, after https://github.com/istio/istio/pull/44187 is pulled in for the doc testing.

**Comment by ericvn** [comment]
Classic:
```
received:
"Error: missing Kubernetes Gateway CRDs need to be installed before applying a waypoint"
expected:
"waypoint default/bookinfo-productpage applied"
```
Gateway:
```
VERIFY FAILED snip_verify_traffic_sleep_to_ingress (timeout after 120s):
received:
"command terminated with exit code 6"
expected:
"<title>Simple Bookstore App</title>"
```

**Pull request merged**
