### PR TITLE
update callout shortcode

### PR DESCRIPTION
**Pull request by Arhell**
update issue https://github.com/istio/istio.io/issues/9703

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by Arhell** [comment]
https://deploy-preview-10326--preliminary-istio.netlify.app/latest/docs/releases/contribute/shortcodes/

**Comment by Arhell** [comment]
cc @craigbox

**Comment by craigbox** [comment]
Some other examples to look at:

https://deploy-preview-10326--preliminary-istio.netlify.app/latest/blog/2018/delayering-istio/ (uses quote in blog post)
https://deploy-preview-10326--preliminary-istio.netlify.app/latest/about/case-studies (case studies still render OK)
https://deploy-preview-10326--preliminary-istio.netlify.app/latest/docs/ops/configuration/traffic-management/network-topologies/#configuring-x-forwarded-client-cert-headers (docs)

LGTM, except I'm wondering why the italic is a heavier weight than the others?

image

If that's not very very easy to fix, lets just merge it as-is.

**Comment by Arhell** [comment]
> Some other examples to look at:
> 
> https://deploy-preview-10326--preliminary-istio.netlify.app/latest/blog/2018/delayering-istio/ (uses quote in blog post)
> https://deploy-preview-10326--preliminary-istio.netlify.app/latest/about/case-studies (case studies still render OK)
> https://deploy-preview-10326--preliminary-istio.netlify.app/latest/docs/ops/configuration/traffic-management/network-topologies/#configuring-x-forwarded-client-cert-headers (docs)
> 
> LGTM, except I'm wondering why the italic is a heavier weight than the others?
> 
> image
> 
> If that's not very very easy to fix, lets just merge it as-is.

Google fonts need a little tweak

**Review by craigbox — APPROVED** [review]

**Pull request merged**
