### PR TITLE
[zh] Resync page external-controlplane

### PR DESCRIPTION
**Pull request by Zhuzhenghao**
Resync page external-controlplane.

- [ ] Configuration Infrastructure
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by windsonsea — COMMENTED** [review]
To avoid [MD029 errors](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/12648/lint_istio.io/1625365382724325376) for an ordered list, the pattern below is recommended:
```
1. List one
1. List two
1. List three
1. List four
```

**Comment by Zhuzhenghao** [comment]
> To avoid [MD029 errors](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/12648/lint_istio.io/1625365382724325376) for an ordered list, the pattern below is recommended:
> 
> ```
> 1. List one
> 1. List two
> 1. List three
> 1. List four
> ```

Is there a command which I can run locally to check my commit to make linter happy?

**Comment by windsonsea** [comment]
Hi @zirain , is there any instruction to run lint-check locally? I found a script `scripts/lint_site.sh` and run it locally, nothing output.

image

**Comment by Zhuzhenghao** [comment]
> Hi @zirain , is there any instruction to run lint-check locally? I found a script `scripts/lint_site.sh` and run it locally, nothing output.
> 
> image

Maybe `./script/build_site.sh` ?

**Review by windsonsea — APPROVED** [review]

**Pull request merged**
