### PR TITLE
fix weak algorithm

### LINKED ISSUE #9980: NGINX start failed because using weak algorithm
https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/
```
2021/06/24 06:50:31 [emerg] 1#1: SSL_CTX_use_certificate("/etc/nginx-server-certs/tls.crt") failed (SSL: error:140AB18E:SSL routines:SSL_CTX_use_certificate:ca md too weak)
nginx: [emerg] SSL_CTX_use_certificate("/etc/nginx-server-certs/tls.crt") failed (SSL: error:140AB18E:SSL routines:SSL_CTX_use_certificate:ca md too weak)
```

### PR DESCRIPTION
**Pull request by liuxu623**
fix #9980 

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by ericvn** [comment]
We typically only change the English version of the file and let the translation teams do the other languages. Otherwise, there is additional time needed for approvals from both sets of maintainers.

**Comment by ericvn** [comment]
The `gencheck failure` means that a `make gen` will need to be run and the additional files changes added to this PR.

**Comment by liuxu623** [comment]
> We typically only change the English version of the file and let the translation teams do the other languages. Otherwise, there is additional time needed for approvals from both sets of maintainers.

ok，I will change Chinese version in next PR.

**Review by kebe7jun — APPROVED** [review]

**Review by craigbox — APPROVED** [review]

**Pull request merged**
