### PR TITLE
Update master after 1.10 release

### PR DESCRIPTION
**Pull request by ericvn**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by davidhauck — APPROVED** [review]

**Comment by ericvn** [comment]
Need to update the istio test reference as well since the istioctl analyzer test uses the version output from istioctl, which when using the 1.10 test ref will return 1.10, and it's now expecting 1.11.

**Comment by ericvn** [comment]
Curious what other test issues there will be. I do expect some additional istioctl analyzer output may need to be updated in the docs as well.

**Comment by ericvn** [comment]
https://github.com/istio/istio/issues/32926 opened for a set of failing tests.

**Pull request merged**
