### PR TITLE
prepare for v1.19 as istio source is already branched

### PR DESCRIPTION
**Pull request by ericvn**
Please provide a description for what this PR is for.

Prepare for 1.19

### CODE REVIEW

**Comment by ericvn** [comment]
Also I note some spelling corrections were reverted. Let me check on the PR's that might have been in master, but not the new release-1.19 branch and get them cherry-picked.

**Comment by ericvn** [comment]
https://github.com/istio/istio/pull/46325 is the cherry-pick to update the spelling in the commands.

**Review by frankbu — APPROVED** [review]

**Comment by ericvn** [comment]
/test doc.test.profile-none

Yhis test is sometimes flaky. Else look at it on Monday.

**Pull request merged**
