### PR TITLE
fix gateways (misspelled  gateays) typo

### PR DESCRIPTION
**Pull request by boredabdel**
[ ] Configuration Infrastructure
[x ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by boredabdel** [comment]
@googlebot I fixed it

**Comment by frankbu** [comment]
This is generated documentation.
https://github.com/istio/istio.io/blob/b8aef72a509b654d331a0ffa701b48ee241ede15/content/en/docs/reference/config/networking/envoy-filter/index.html#L2

Please change the original source in istio/api
https://github.com/istio/api/blob/8bca8f68738867777a8b41948a430e56b073af8f/networking/v1alpha3/envoy_filter.proto#L64

**Comment by boredabdel** [comment]
Ah sure, thanks i opened a PR against the api code https://github.com/istio/api/pull/1496

**Comment by exqlnet** [comment]
Typo is still in [envoy-filter](https://istio.io/latest/docs/reference/config/networking/envoy-filter/)

**Pull request closed without merging**
