### PR TITLE
add test for the dry-run task

### PR DESCRIPTION
**Pull request by yangminzhu**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [x] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by yangminzhu** [comment]
@istio/wg-docs-maintainers-english @istio/wg-docs-maintainers-infra @istio/wg-test-and-release-maintainers could someone take a look? thanks.

**Review by frankbu — APPROVED** [review]

**Comment by yangminzhu** [comment]
@istio/wg-test-and-release-maintainers PTAL, thanks.

**Review by Xunzhuo — APPROVED** [review]

**Pull request merged**
