### PR TITLE
Delete completely outdated articles published in 2018(contain multi-langs version) 

### PR DESCRIPTION
**Pull request by chaseSpace**
## Description

Same as #14762, which has closed. this PR submits with a new branch instead of `master`(I have multi PRs). 

**Outdated content**

Link: https://istio.io/latest/blog/2018/egress-monitoring-access-control/
Link-zh: https://istio.io/latest/zh/blog/2018/egress-monitoring-access-control/

Most of APIs the article mentioned are no longer exist. NotExistAPIs: **logentry/stdio/rule/listchecker/listentry**.

This article mentioned using these APIs to implement access control for egress traffic, but since these APIs no longer exist and I have not found any other documents or examples related to egress traffic access control, I believe that the current isio no longer supports the function of egress traffic access control. Perhaps alternative methods can be used to implement it, but I have not found any.

So I think this article should be deleted to avoid misleading people(and time-wasting and not-good experience).

## Reviewers

- [ ] Ambient
- [√] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [√] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

### CODE REVIEW

**Comment by frankbu** [comment]
Blog posts are supposed to exist for ever. There are lots of posts that are totally outdated and won't work with current releases. They already have a warning at the top: `This blog post was written assuming Istio 1.1, so some of this content may now be outdated.` That said, maybe for docs that are completely outdated we need a more forceful warning at the top? I think this is a question for the steering committee.

cc @istio/steering-committee

**Comment by zirain** [comment]
> Blog posts are supposed to exist for ever. There are lots of posts that are totally outdated and won't work with current releases. They already have a warning at the top: `This blog post was written assuming Istio 1.1, so some of this content may now be outdated.` That said, maybe for docs that are completely outdated we need a more forceful warning at the top? I think this is a question for the steering committee.
> 
> cc @istio/steering-committee

Add tips for blogs older than one year?

**Comment by hzxuzhonghu** [comment]
Agree with @frankbu Blogs should be there forever. Each blog may suite for different releases, it is not like API documents

**Comment by chaseSpace** [comment]
> > Blog posts are supposed to exist for ever. There are lots of posts that are totally outdated and won't work with current releases. They already have a warning at the top: `This blog post was written assuming Istio 1.1, so some of this content may now be outdated.` That said, maybe for docs that are completely outdated we need a more forceful warning at the top? I think this is a question for the steering committee.
> > cc @istio/steering-committee
> 
> Add tips for blogs older than one year?

If we are plan to keep it, in order to provide a good experience, the tips should be more special, for example:

"This blog post was written assuming Istio 1.1, and some of this article content is completely outdated. The APIs below mentioned, such as **logentry/stdio/rule/listchecker/listentry**, have been removed from istio. If you want to know access control of HTTP traffic, see also [Authorization](https://istio.io/latest/docs/tasks/security/authorization/)."

So that users can clearly and quickly decide to continue reading or not.

**Comment by zirain** [comment]
> > > Blog posts are supposed to exist for ever. There are lots of posts that are totally outdated and won't work with current releases. They already have a warning at the top: `This blog post was written assuming Istio 1.1, so some of this content may now be outdated.` That said, maybe for docs that are completely outdated we need a more forceful warning at the top? I think this is a question for the steering committee.
> > > cc @istio/steering-committee
> > 
> > 
> > Add tips for blogs older than one year?
> 
> If we are plan to keep it, in order to provide a good experience, the tip should be more special, for example:
> 
> "This blog post was written assuming Istio 1.1, and some of this article content is completely outdated. The APIs below mentioned, such as **logentry/stdio/rule/listchecker/listentry**, have been removed from istio. If you want to know access control of HTTP traffic, see also [Authorization](https://istio.io/latest/docs/tasks/security/authorization/)."
> 
> > This is just an example, it may not be a perfect enough.
> 
> With this tip, users can clearly and quickly decide to continue reading or not.

You can't do this one by one, and whenever reading an article/blog/video from a long time ago, you should be aware that it may be out of date.

**Comment by chaseSpace** [comment]
> You can't do this one by one, and whenever reading an article/blog/video from a long time ago, you should be aware that it > > >may be out of date.

Yes, that's right. But what I want to say is that it does as a doc of LATEST, should bring something latest(or available this version at least). There should avoid to bring some another type of **barriers** for users. When a project iterates frequently, some things should be discarded or archive, in my opinion.

**Pull request closed without merging**
