### PR TITLE
zh: filename error

### PR DESCRIPTION
**Pull request by chenvista**
new_telemetry.yaml ->new_metrics.yaml

### CODE REVIEW

**Comment by fleeto** [comment]
`[trans-bot:N/A]`

Thank you @chenvista, the [related task issue](https://github.com/servicemesher/istio-official-translation/issues/834) had been assigned to others. will not be reported to the task issues

**Comment by SataQiu** [comment]
Thanks @chenvista 
You need to sign cla first.  Please visit https://cla.developers.google.com/ to sign.

/lgtm

**Comment by SataQiu** [comment]
@chenvista 这个 PR 需要解决冲突，需要重新提交下！而且您需要签署 CLA 协议，才能完成代码合并。^_^

**Comment by geeknoid** [comment]
@istio/wg-docs-maintainers-chinese Do we need/want this PR? If not, let's close it please.

**Comment by rootsongjc** [comment]
@geeknoid I think we can close it now.

**Pull request closed without merging**
