### PR TITLE
[zh] sync wildcard-egress-hosts

### PR DESCRIPTION
**Pull request by my-git9**
## Reviewers

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

### CODE REVIEW

**Review by windsonsea — COMMENTED** [review]
Seems the SVG can be localized too. Would like to handle this?

**Comment by my-git9** [comment]
> Seems the SVG can be localized too. Would like to handle this?

The text content here seems unreadable to humans and I don't know what to do with it. Can you give me some advice?

image

**Comment by windsonsea** [comment]
ok, all right. We can have a try to use an editor (such as inkscape) later.

**Review by windsonsea — APPROVED** [review]
Thanks.

**Pull request merged**
