### PR TITLE
Fix broken circuit-breaking test

### PR DESCRIPTION
**Pull request by frankbu**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by ldemailly** [comment]
apologies looks like -quiet doesn't apply at the stage the dynamic config is checked, let me fix that bug but in the meantime maybe use `2> /dev/null` instead?

**Comment by ldemailly** [comment]
fix incoming in https://github.com/fortio/fortio/pull/386/files

**Comment by ldemailly** [comment]
I fixed the fortio image (`fortio/fortio:latest_release` is now 1.6.6) so let's use

`-- /usr/local/bin/fortio curl -quiet URL`

**Comment by frankbu** [comment]
Force merging because lint failure is an unrelated problem.

**Pull request merged**
