### PR TITLE
Fix privileged flag.

### PR DESCRIPTION
**Pull request by lordofthejars**

### CODE REVIEW

**Comment by lordofthejars** [comment]
@googlebot I signed it!

**Comment by ericvn** [comment]
Would you also update this same txt in `istio.io/content/en/faq/security/verify-mtls-encryption.md`?

**Comment by ericvn** [comment]
Looks like this is already going in. I'll update both files in _master_

**Comment by ericvn** [comment]
I created #6997 for master with both changes, else if you make the additional change here and I see Frank now has a cherry pick back to master we can close what I just did.

**Comment by frankbu** [comment]
Fixed in #6997

**Pull request closed without merging**
