### PR TITLE
Update open usage blog post to draw distinctions in the use of "we"

### PR DESCRIPTION
**Pull request by ssuchter**
In an Istio Steering Committee discussion, we decided to update this blog post to make it more clear which uses of "we" referred to Google, and which referred to the Istio Steering Committee. This is accomplished by only using the word "we" to refer to the Istio Steering Committee, and using "Google" when that is the relevant intent.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by ssuchter** [comment]
@linsun @craigbox PTAL.

**Comment by craigbox** [comment]
LGTM.

Lin, I trust there's no concern about the "we" in the last and third-to-last paragraphs of the blog? It might pay to say "the steering committee" instead of the first we, to set the context.

**Comment by ssuchter** [comment]
Yes, I saw the "we" in the last couple paragraphs, but those seemed to be things that the Steering Committee would reasonably say. @linsun, if you feel differently, I can change them too.

**Comment by linsun** [comment]
@ssuchter thanks for the update!  Changes Looks good overall.  I think it could be more accurate to just say Google in the last few "we" in the last paragraph given IBM's blog - https://developer.ibm.com/blogs/istio-google-open-usage-commons/

**Comment by ssuchter** [comment]
Ok, fixed. PTAL. The only remaining use of "We" is in "we were proud to appoint Neeraj..." - I thought that should stay as "we", because it definitely wasn't Google who did that.

**Comment by linsun** [comment]
BTW should be Podder -> Poddar

cc @nrjpoddar

**Comment by nrjpoddar** [comment]
> BTW should be Podder -> Poddar
> 
> cc @nrjpoddar

Even I missed it..

**Comment by frankbu** [comment]
@ssuchter Please fix the lint errror so this can merge.

**Comment by ericvn** [comment]
@sshucker The lint error is actually that the incorrect spelling `Podder` is in the .spelling file. Will need the update there as well.

**Comment by ssuchter** [comment]
And ironically, I'm @ssuchter, not @sshucker. Thanks for the pointer, @ericvn.

**Pull request merged**
