### PR TITLE
Change "-ppassword" > "-password"

### PR DESCRIPTION
**Pull request by bobbypower-asm**
It seems like this is a trivial typo, as I'm not seeing other uses of "-ppassword"

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by ericvn** [comment]
Looking at https://dev.mysql.com/doc/refman/8.0/en/mysql-command-options.html it seems there should be a double hash on the options (password matches) and we should maybe expand out the -e to --execute?

@istio/wg-environments-maintainers owns this page. I'll let them determine what this should be.

**Review by bobbypower-asm — COMMENTED** [review]
Additional improvements

**Comment by ericvn** [comment]
You need to run `make gen` to create a new snippet file with the markdown file changes.

**Comment by dhawton** [comment]
`-ppassword` isn't necessarily a typo. With mysql, when you combine `-p` and additional text, it is read as the password from the commandline. In this case, `-ppassword` means "password" is being passed in as the password instead of a password prompt being generated.

**Comment by bobbypower-asm** [comment]
Good to know - thank you for that info!

**Comment by ericvn** [comment]
> `-ppassword` isn't necessarily a typo. With mysql, when you combine `-p` and additional text, it is read as the password from the commandline. In this case, `-ppassword` means "password" is being passed in as the password instead of a password prompt being generated. `-ppassword` is the same as `--password=password` https://dev.mysql.com/doc/refman/8.0/en/mysql-command-options.html#option_mysql_password

Thanks @dhawton. So the text is correct. It is just using the short `-` options and `-p{password}`.

**Pull request closed without merging**
