### PR TITLE
doc:remove the * character in istio operator install doc

### PR DESCRIPTION
**Pull request by tanjunchen**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

image

### CODE REVIEW

**Comment by craigbox** [comment]
The * is there to indicate that the Istio operator is experimental.  It's working as intended.  What caused you to want to change this?

(You're also submitting this PR to the archive for 1.12; what we would do if we agreed we needed to make a change was commit the change and regenerate the archive HTML.)

**Comment by tanjunchen** [comment]
> The * is there to indicate that the Istio operator is experimental. It's working as intended. What caused you to want to change this?
> 
> (You're also submitting this PR to the archive for 1.12; what we would do if we agreed we needed to make a change was commit the change and regenerate the archive HTML.)

ok. I get it. Because I feel that it looks a bit ugly. If it is an experimental feature, I suggest putting it at the front of this article and giving it a hint.

**Review by ericvn — CHANGES_REQUESTED** [review]
As noted, this is as designed. See https://github.com/istio/istio.io/issues/9766.

**Comment by tanjunchen** [comment]
> As noted, this is as designed. See #9766.

get it.thanks.
/close

**Pull request closed without merging**
