### PR TITLE
Fix logo hover state rotation

### LINKED ISSUE #2780: Logo hover state is not centered
Chrome - Version 69.0.3497.100 (Official Build) (64-bit)
https://istio.io/

When you hover over the logo it rotates. But the animation is not centered properly

istio-logo_hover

# expected behaviour

The logo should rotate without the circular moving its position

### PR DESCRIPTION
**Pull request by crunchie84**
The logo rotates upon hover but it was not centred correctly. This change fixes it for Chrome Version 69.0.3497.100 (Official Build)

Fixes #2780

### CODE REVIEW

**Comment by crunchie84** [comment]
> Thanks for your pull request. It looks like this may be your first contribution to a Google open source project (if not, look below for help). Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:+1: I signed it!

**Comment by geeknoid** [comment]
For this change to take effect, you need to run a "make build" step and check in the results. This will generate the actual .css file that the site uses.

One day we'll use Hugo pipes to eliminate the need to check in the .css files and just have them generated on the fly, but we're waiting for Netlify to fix things on their end to allow this.

Thanks.

**Comment by crunchie84** [comment]
- [x] The circle is now also circulair (the edges were cut off)
- [x] The animation now is rotating correctly centered
- [x] I have invoked `make build` and pushed the resulting css files

[https://memegenerator.net/img/images/13315021/fresh-shave-guy.jpg](theworldmakessenseagain
)

Tested in 
- Chrome Version 69.0.3497.100 (Official Build)
064f37b
- Safari Version 12.0 (13606.2.11)
- at 100% font size and 200% font size for the `min-width` css selector to also be verified

**Comment by geeknoid** [comment]
Thanks for the fix.

**Pull request merged**
