### PR TITLE
Update istio reference to a recent release-1.15 commit

### PR DESCRIPTION
**Pull request by ericvn**
Please provide a description for what this PR is for.

Pull in latest istio release-15 branch commit. The automated job over the weekend contained a regression. This contains a fix for that regression.

### CODE REVIEW

**Comment by ericvn** [comment]
First test: @39e40ed4ea41280e77f9aa524750dc5675695323

**Comment by ericvn** [comment]
First commit passes tests.  Moving to commit: 4173db962e6e4b7fe94a3dc03d57310dd0c746f7

**Comment by ericvn** [comment]
Verified the current failures are caused by https://github.com/istio/istio/pull/40402

**Comment by ericvn** [comment]
Close for now since verified test failure PR.

**Comment by ericvn** [comment]
Reopen to test commit.

**Comment by ericvn** [comment]
Needed to wait for the images to be built.

**Comment by ericvn** [comment]
Looks like that commit failed to build everything in post submit. Trying a new commit.

**Review by frankbu — APPROVED** [review]

**Pull request merged**
