### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by lijiansgit**
fix option 2 import error

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [x] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA
https://github.com/istio/istio.io/pull/10541/checks?check_run_id=4323018243

**Comment by Kmoneal** [comment]
@lijiansgit just checking in since CLA still needs your attention.

**Comment by lijiansgit** [comment]
> @lijiansgit just checking in since CLA still needs your attention.

Alreadly sign CLA , Have any other questions ?

**Review by Xunzhuo — APPROVED** [review]

**Pull request merged**
