### PR TITLE
zh-translation: docs/reference/config/networking/destination-rule/ind…

### PR DESCRIPTION
**Pull request by my-git9**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by zirain** [comment]
reference pages ares auto-generated by bots.
@ericvn do we update the infra?

**Comment by ericvn** [comment]
@zirain I had looked into the possibility of updating the translated reference docs to match the English versions in a prior PR, but did not get feedback if we should make it happen and I closed it. For reference, it was https://github.com/istio/istio.io/pull/10719.

@craigbox Thoughts on re-doing my earlier PR to update the `zh` version of the reference files as part of our normal automated reference doc updates?

**Comment by craigbox** [comment]
not enough context to have an opinion sorry.

**Comment by kebe7jun** [comment]
> @zirain I had looked into the possibility of updating the translated reference docs to match the English versions in a prior PR, but did not get feedback if we should make it happen and I closed it. For reference, it was #10719 and that referred to #10717.
> 
> @craigbox Thoughts on re-doing my earlier PR to update the `zh` version of the reference files as part of our normal automated reference doc updates?

I think it is necessary to update the reference of `zh` automatically, this part of the content is not quite suitable for manual translation into Chinese, it may be more obscure and difficult to understand, build at this stage, if the update can be automatic, keep the accuracy of the content I think more good.

**Comment by ericvn** [comment]
Talking with @craigbox I think it makes sense to update the translated docs at the same time as the English docs. I'll create a PR for that soon.

**Comment by ericvn** [comment]
https://github.com/istio/istio.io/pull/11252 was created to update the `zh` side of the reference docs at the same time as the `en` directory. The daily automated job would now update both.

**Pull request closed without merging**
