### PR TITLE
[zh] Sync istio#14200 into Chinese

### PR DESCRIPTION
**Pull request by carolsi**
## Reviewers

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

### CODE REVIEW

**Comment by zirain** [comment]
pleae sign CLA

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by carolsi** [comment]
@zirain finished

**Review by windsonsea — APPROVED** [review]
lgtm, thanks.

**Pull request merged**
