### PR TITLE
Add /zh in /zh

### PR DESCRIPTION
**Pull request by tanjunchen**
ref:https://github.com/istio/istio.io/pull/5751

In order to allow each language's content to evolve independently,
introduce a new linter rule to prevent translated content from having
references to English content.

Fix many such references in the existing translated content.

### CODE REVIEW

**Comment by tanjunchen** [comment]
@geeknoid @rootsongjc  Do we need to do something else?

**Comment by geeknoid** [comment]
Hi, Thanks for all the work. There are still a bunch of linter warnings however, they seem focused on the aliases. You can't have an aliases: directive in the Chinese content that is trying to create an alias for the English content. You can either add /zh in front of all the aliases.

**Comment by tanjunchen** [comment]
@googlebot I consent

**Comment by geeknoid** [comment]
@googlebot I consent

**Comment by tanjunchen** [comment]
@geeknoid  Hello,There is some spelling errors. The CI looks like unhappy.I don't know why the robot failed. Is it because of spelling mistakes?

**Comment by geeknoid** [comment]
You're getting very close to having this working.

The remaining problem are due to the # sequences which include words not in the English dictionary. For example, "dns", "istio", "tls", "kubernetes". In the dictionary, these are spelled DNS, Istio, TLS, and Kubernetes. So switch all those to use the right capitalization, and everything should pass.

**Comment by malphi** [comment]
@googlebot I consent

**Comment by tanjunchen** [comment]
@geeknoid  Done. The CI seems OK.    can you help me @wuti1609  @Lovnx  ?Thanks!

**Comment by geeknoid** [comment]
@lovnx and @wuti1609, please leave a comment on this PR that says "@googlebot I consent". This will make the CLA bot happy and then this PR can merge.

Thank you.

**Comment by geeknoid** [comment]
@frankbu @rcaballeromx @duderino @howardjohn 

After this PR merges, the Chinese and English content will be completely independent from one another, and we'll have linter rules in place to prevent links between the two. I think this'll help velocity overall.

**Comment by Lovnx** [comment]
@googlebot I consent

**Comment by tanjunchen** [comment]
@geeknoid  once  @wuti1609  comment,i will fix conficts

**Comment by wuti1609** [comment]
@googlebot I consent

**Pull request merged**
