### PR TITLE
zh_translation: fix error ca-cert.pem

### PR DESCRIPTION
**Pull request by andrewshaoyu**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by andrewshaoyu** [comment]
Anything wrong?

**Comment by andrewshaoyu** [comment]
@googlebot I signed it!

**Comment by andrewshaoyu** [comment]
then?

**Review by rootsongjc — APPROVED** [review]
/LGTM

**Pull request merged**
