### PR TITLE
Add updated profile to the list of istioctl profile list

### PR DESCRIPTION
**Pull request by shamsher31**
This is with respect to #6713 . The same list should be reflected in all docs.

### CODE REVIEW

**Comment by frankbu** [comment]
This fixed in #6547

**Comment by shamsher31** [comment]
@frankbu This is for `zh` and `pt-br` docs. I can see the docs for `en` is already updated.  But #6547 does not consist updates for `zh` and `pt-br`.

**Comment by frankbu** [comment]
@shamsher31, sorry, I didn't notice that. I think it might be better, anyway, to let the individual translation teams update their versions after the en version is final. The en version may still not be in its final state.

**Comment by shamsher31** [comment]
Sounds good. Thanks @frankbu

**Pull request closed without merging**
