### PR TITLE
fix slider items on mobile

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/istio/istio.io/issues/15334

### CODE REVIEW

**Comment by craigbox** [comment]
That's awesome, Ihor.  I really appreciate that you help out with things like this!
The spacing between the items is probably a little wide when. you're at the smallest setting

Screenshot 2024-06-26 at 9 40 42 PM

anything we can do about that?

**Review by Arhell — COMMENTED** [review]
I'll see what can be done.

**Comment by Arhell** [comment]
@craigbox enlarged the image, should be better

**Comment by craigbox** [comment]
I can still break this with certain sized but merging in the name of iterative improvement

/cherry-pick release-1.22

**Review by craigbox — APPROVED** [review]

**Pull request merged**
