### PR TITLE
update d2iq company logo

### PR DESCRIPTION
**Pull request by Arhell**
before
Screenshot_1

after
Screenshot_1

### CODE REVIEW

**Comment by ericvn** [comment]
I'm not sure if we have a great algorithm for figuring out how much to tweak these images. I think this makes it a little small.

**Comment by Arhell** [comment]
> I'm not sure if we have a great algorithm for figuring out how much to tweak these images. I think this makes it a little small.

did a little less

**Comment by Arhell** [comment]
https://deploy-preview-13746--preliminary-istio.netlify.app/latest/about/ecosystem

**Review by kfaseela — APPROVED** [review]

**Pull request merged**
