### PR TITLE
Remove the destination rule in peer authn doc.

### PR DESCRIPTION
**Pull request by incfly**
https://github.com/istio/istio/issues/32788 doc part change.

### CODE REVIEW

**Comment by incfly** [comment]
Verified that the expected behavior: no long need the destination rule for the workload level peer authn. (We didable httpbin.bar port 80). With new Istiod image, this continues to be 200 for a side car injected client. Without it, it'll be 503.

**Review by yangminzhu — APPROVED** [review]

**Review by craigbox — APPROVED** [review]

**Comment by ericvn** [comment]
@incfly, note that the tests are still failing. You can run them locally to help debug as well.

**Comment by incfly** [comment]
it seems like the doc test is still using 1.11 release candidate. [1] I will have to wait for the 1.11 release to come out before submit this PR. (which makes sense since the feature improvement does not get into 1.11, only available in 1.12).

However, I find it very hard to run doc test scripts locally.

- `test.sh` itself does not have `source helpers.sh` to include those libraries. 
- the test have to run from a istio download folder to have `sample/xxx` in the current folder.
- it has to be bash due to some usage of `shopt` bash built-ins.

In the end I still even didn't not manage to run this locally other than bothering CI. Did I miss anything?  @ericvn 

/cc @justinpettit 

https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio.io/10117/doc.test.profile_default_istio.io/1420087996295680000/artifacts/tests-setup-profile-default-1cf/_suite_context/istio-deployment-609241564/iop.yaml

**Comment by ericvn** [comment]
@incfly The tests will continue to use the 1.11 istio builds until we branch istio.io (happens when we GA 1.11.0). At this point the master/main branch is still for 1.11. 

For running tests, see `https://github.com/istio/istio.io/tree/master/tests`. On my Mac, I spin up a kind cluster, and run something like: `TEST_ENV=kind ADDITIONAL_CONTAINER_OPTIONS="--network host" make doc.test.profile_none TEST=ops/diagnostic-tools/istioctl-analyze/test.sh`. Be careful of HUB/TAG.

**Comment by incfly** [comment]
Good to know that thanks!

**Comment by ericvn** [comment]
The master branch should be used by tests once https://github.com/istio/istio.io/pull/10176 is merged.

**Comment by incfly** [comment]
/retest

Weird the CI does not trigger the things.

**Comment by incfly** [comment]
/retest

failing test is not related to security task.

**Pull request merged**
