### PR TITLE
Allow proposing an image in your blog

### PR DESCRIPTION
**Pull request by craigbox**
If you define

```social_image: /blog/2024/blog-post/image.png```

in your front matter, and include that image, it should end up as the social preview.

### CODE REVIEW

**Comment by craigbox** [comment]
Closes #14711.

**Comment by craigbox** [comment]
remove test data in `content/en/blog/2024/kubecon-eu/index.md` before merging

**Comment by craigbox** [comment]
To do:

- [ ] View source on https://deploy-preview-14720--preliminary-istio.netlify.app/latest/blog/2024/kubecon-eu/ and confirm og:image etc are now FQDNs
- [ ] Put that URL into a tweet and see what happens
- [ ] When it's good, remove the blog post change from the PR

**Comment by kfaseela** [comment]
> To do:
> 
> - [ ] View source on https://deploy-preview-14720--preliminary-istio.netlify.app/latest/blog/2024/kubecon-eu/ and confirm og:image etc are now FQDNs
> - [ ] Put that URL into a tweet and see what happens
> - [ ] When it's good, remove the blog post change from the PR

The netlify preview does not seem to be proper as of now? Not ready for review?

**Comment by craigbox** [comment]
Nio, I did not get the magic incantation for Netlify correct.  The `<og>` tags have to be fully qualified and that means I need to feed the deploy URL for each preview into Netlify.  Trying another fix now.

**Comment by craigbox** [comment]
ok _finally_

https://www.opengraph.xyz/url/https%3A%2F%2Fdeploy-preview-14720--preliminary-istio.netlify.app%2Fv1.21%2Fblog%2F2024%2Fkubecon-eu%2F looks good.

Twitter I think has cached a bad result so I'm unable to preview it there.

**Comment by craigbox** [comment]
This will now _possibly_ work when deployed on istio.io, but will require #14725 to work well.

**Review by kfaseela — APPROVED** [review]

**Comment by kfaseela** [comment]
/ cherrypick release-1.20

**Pull request merged**
