### PR TITLE
Polidea update - tables, header fixes

### PR DESCRIPTION
**Pull request by Jakub-Sadowski**
Fix tables overflow and header shadow box starting earlier

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by ericvn** [comment]
Buttons like on the News page continue to have problems. They seem to toggle on OK (go from white to highlighted), but don't toggle off visually (they say highlighted). The items in the list to seem to update correctly. Example Click `Release` button and it highlights and you see only release items. Click `Support` and it highlights and adds the items to the list. Click the `Support` button again, the items are removed but the button stays highlighted.

Pages like `About-Service Mesh` have garbage characters on them, like:
```
Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia 
```

Not sure when those pages are planning to get updates for logos, etc.

**Comment by ericvn** [comment]
Also the Get Involved report a bug section has nothing about creating issues in GitHub, and reporting Security Vulnerabilities in StackOverflow is NOT the correct way to do it. Obviously, this seems to be a copy of sections, but they need to be correct if they go live. @brian-avery for the note on Security Vulnerability reporting.

**Comment by craigbox** [comment]
> Also the Get Involved report a bug section has nothing about creating issues in GitHub, and reporting Security Vulnerabilities in StackOverflow is NOT the correct way to do it. Obviously, this seems to be a copy of sections, but they need to be correct if they go live. @brian-avery for the note on Security Vulnerability reporting.

Copy for this page has been updated [here](https://deploy-preview-9322--istio-polidea.netlify.app/latest/get-involved/) but hasn't been merged yet.

**Comment by brian-avery** [comment]
I feel like Bugs & Security needs to be separate and highlighted better, but I'll leave that up to the editors for now. My first thought reading through it is I should go to the report a bug for security issues..

**Comment by brian-avery** [comment]
image

That blue being the same color as the background makes it somewhat hard to read when they overlap

**Comment by brian-avery** [comment]
image
Are bugs, security reports, and discuss not contributions?

**Comment by brian-avery** [comment]
Blog and news both have a ton of white space while other pages have far less. Is this intentional?
image

**Review by davidhauck — APPROVED** [review]
lgtm

**Pull request merged**
