### PR TITLE
Escape pipe symbol if it appears in the configuration options

### PR DESCRIPTION
**Pull request by johnma14**
Fix for invalid values in Installation Options table (#3618)

### CODE REVIEW

**Comment by rvennam** [comment]
In the future, it might be worth looking into moving everything after the # into the description field

```
| `global.tracer.lightstep.secure` | `true` | example: true\|false |
```

**Comment by frankbu** [comment]
Not to mention `true|false` isn't really an example. Just `false` would make more sense.

**Comment by johnma14** [comment]
@rvennam there is already an issue open to do this: https://github.com/istio/istio.io/issues/2566. And I really need to push that PR out this week itself.

**Comment by johnma14** [comment]
@frankbu I agree. Do you think it makes more sense to make the change in the value.yaml under istio/kubernetes/helm directory?

**Comment by frankbu** [comment]
Yes, it should be changed back in the source. Now that you mention it, your `\|` fix will get wiped out next time the doc is regenerated anyway.

**Comment by johnma14** [comment]
@frankbu I actually made the change in the script (tablegen.py) to escape the pipe symbol if it appears in the value of a configuration option.  It is the updated script that generated that output you see in index.md. That way, in case this happens in other yaml files, this fix should help them as well.

**Pull request merged**
