### PR TITLE
Re-enable telemetry-api test

### PR DESCRIPTION
**Pull request by ericvn**
Please provide a description for what this PR is for.

Fixes https://github.com/istio/istio.io/issues/13315

### CODE REVIEW

**Comment by ericvn** [comment]
Runs locally, just not in the pipeline. Will investigate this some more.

**Comment by ericvn** [comment]
See https://github.com/istio/istio.io/pull/13442 for the same issue now appearing in the 1.18 stream...

**Comment by ericvn** [comment]
The failure seems to be that we either run the commands too soon (before the stats are removed) and every follow on run will find the stats (they just don't go away). Injecting a delay does not seem to be the correct answer. It seems we would want to run once, if not found, restart the pods again , and then try again.

**Comment by ericvn** [comment]
/restest

flaky tests. Passed in earlier runs.

**Comment by ericvn** [comment]
/test doc.test.profile-none

flaky tests. Passed in earlier runs

**Review by nmittler — APPROVED** [review]

**Comment by ericvn** [comment]
/test doc.test.profile-none

flaky test. Passed in earlier runs

**Pull request merged**
