### PR TITLE
Retire helm documentation as we use a protobuf

### PR DESCRIPTION
**Pull request by sdake**
The new rendered source of truth is:
https://preliminary.istio.io/docs/reference/config/istio.operator.v1alpha1/

This is rendered from the API repo protobuf which (may) need description fields
set. That protobuf is here:

https://github.com/istio/api/blob/master/operator/v1alpha1/operator.proto

### CODE REVIEW

**Comment by ericvn** [comment]
Just a pointer as the lint links need fixing since I'm not sure if these are in the contribution guidelines yet:
```
From the doc WG notes: Propose process for fixing broken links to documents that we remove:
If the broken link is from a release announcement (e.g. announcing-1.3.8), change the link to point to the same document in the corresponding archive release (e.g., prepend https://archive.istio.io/1.3 to the link).
Else if there is a replacement doc (containing an alias for it), change the link to reference the new doc.
Else change the link to point the same doc in the latest archive release where it still exists (e.g., https://archive.istio.io/1.4).
``

**Comment by sdake** [comment]
https://github.com/istio/istio.io/issues/7067

**Comment by sdake** [comment]
Superceeded by https://github.com/istio/istio.io/pull/7106

**Pull request closed without merging**
