### PR TITLE
[zh] sync /install/helm/index.md

### PR DESCRIPTION
**Pull request by windsonsea**
Sync with en.
```
content/zh/docs/setup/install/helm/index.md
```

- [x] Docs

### CODE REVIEW

**Review by zirain — APPROVED** [review]

**Comment by zirain** [comment]
v1.16 will release soon, skip cherry-pick

**Comment by windsonsea** [comment]
oh, is anything wrong? I don't understand the log.

**Comment by zirain** [comment]
https://github.com/istio/istio.io/issues/12229

**Pull request merged**
