### PR TITLE
manual cherrypick of 5025 to release-1.3 branch

### PR DESCRIPTION
**Pull request by vadimeisenbergibm**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by geeknoid** [comment]
A bunch of links need to be fixed to accomodate the differences between 1.3 and master

**Comment by geeknoid** [comment]
@vadimeisenbergibm Do we want this PR?

**Comment by vadimeisenbergibm** [comment]
@geeknoid yes, let me fix this PR.

**Pull request merged**
