### PR TITLE
Add updated meshex instructions to 1.0 branch

### PR DESCRIPTION
**Pull request by LisaFC**

### CODE REVIEW

**Comment by LisaFC** [comment]
This is cherry-picked from #3057

**Comment by geeknoid** [comment]
1.1 is right around the corner. Do we still need this PR?

**Comment by LisaFC** [comment]
Yeah, possibly, though it does mean existing users will have to wait for 1.1 (or go to preliminary) for working meshex instructions. (also is mesh expansion going to change at all in 1.1?)

**Pull request closed without merging**
