### PR TITLE
update istio.io@customers doc

### PR DESCRIPTION
**Pull request by jackge007**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by shamsher31** [comment]
Thanks @jackge007 . can you please provide company name in PR and if possible reference to how they are using Istio.

**Comment by frankbu** [comment]
> Thanks @jackge007 . can you please provide company name in PR and if possible reference to how they are using Istio.

You also need to add the new entry in: https://github.com/istio/istio.io/blob/master/content/en/about/community/customers/index.md, and please [sign the CLA](https://github.com/istio/istio.io/pull/7436#issuecomment-636585128).

**Comment by frankbu** [comment]
Closing this for lack of activity.

@jackge007 Please feel free to reopen if you can address the review comments, above.

**Pull request closed without merging**
