### PR TITLE
[docs] Update ecosystem page with Layer5

### PR DESCRIPTION
**Pull request by theBeginner86**
This PR updates the ecosystem page with [Layer5](https://layer5.io) company.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by ericvn** [comment]
Just noting that Meshery is already under integrations.

**Comment by theBeginner86** [comment]
> Just noting that Meshery is already under integrations.

@ericvn 

But I was looking forward to adding **Layer5** as a company(/provider) that builds platforms for managing service meshes like Istio. 
I think my PR description looked misleading 😅

**Comment by craigbox** [comment]
I don't think of Layer5 as a "provider" of Istio, being a company that you can pay to get Istio installed or managed by. It feels like you could list Meshery as an integration (which it is) and you could possibly list Layer5 as a provider of professional services?

If this isn't a correct representation please update the bug with more details.

**Comment by leecalcote** [comment]
Thanks for this, @theBeginner86. @craigbox, good point of clarification. Layer5 offers a managed Istio service: Meshery Cloud ([login])(https://meshery.layer5.io). In this context, Meshery acts as an Istio distribution with Layer5 operating the management plane as a service. 

I hope this helps. 👍

**Comment by craigbox** [comment]
I'm going to update the link to https://layer5.io/service-mesh-management/meshery to make that obvious (note the other links are not to google.com but to the Anthos Service Mesh page, for example) and will merge. Thanks!

**Review by craigbox — APPROVED** [review]
/cherry-pick release-1.14

**Comment by leecalcote** [comment]
🎈 Thank you, @craigbox 👍

**Pull request merged**
