### PR TITLE
[zh] Sync 1.6 upgrade note into Chinese

### PR DESCRIPTION
**Pull request by wilsonwu**
Sync 1.6 upgrade note into Chinese:
```
content\zh\news\releases\1.6.x\announcing-1.6\upgrade-notes\index.md
```

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by kebe7jun** [comment]
Maintenance for version 1.6 has already ended, and we will no longer translate content.

**Comment by wilsonwu** [comment]
OK, thanks, just want to make the Chinese version site as completed as the English version.

**Comment by wilsonwu** [comment]
Should this need to be merged? Other two 1.6 release notes already been merged. @windsonsea @kebe7jun

**Comment by kebe7jun** [comment]
I think EOL contents should not get merged.

**Comment by wilsonwu** [comment]
No problem, I close this PR.

**Pull request closed without merging**
