### PR TITLE
Add documentation in Ukrainian

### PR DESCRIPTION
**Pull request by Andygol**
## Description

I am pleased to present the translation of Istio's documentation into Ukrainian 🇺🇦. I hope this contribution will be reviewed and incorporated into the documentation.

The translation contains all the documentation except for the [Reference/Configuration](https://istio.io/latest/docs/reference/config/) and [Reference/Commands](https://istio.io/latest/docs/reference/commands/) sections, which I hope will be added later.

image |  image
-- | --
image |  image

Everything looks good except for one drawback. I couldn't get the desired result locally with the FAQ page in Ukrainian, while the English and Chinese versions work as expected. I have an issue (locally), when I click on a question, no action is taken, the answer section is not displayed.

If I missed something, please correct me and let me know what it was. 🙏 

## Reviewers

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [x] Localization/Translation

### CODE REVIEW

**Comment by dhawton** [comment]
Not sure how I feel about this, tbh. Keeping the translations up to date is a constant and continual effort, as can be seen by the multiple per day PRs to handle translations to Chinese by multiple people. Do we have enough of a contributor base fluent in Ukrainian to not only handle the translations, but also to review/approve? Has this been discussed in the workgroup meetings and/or TOC/SC?

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by craigbox** [comment]
Hi @Andygol,

This clearly represents a _lot_ of work and is a very large contribution. **Thank you!**

As @dhawton has said, we are not qualified to review it.  My only experience here is with our Chinese documentation, which has many contributors. How would you recommend we (a) review the first drop (b) ensure it is kept up to date without it being a burden on you personally (c) manage divergence from the English docs?

For example, I see https://kubernetes.io/uk/docs/home/ has a tag

> Information in this document may be out of date
> his document has an older update date than the original, so the information it contains may be out of date. If you're able to read English, see the English version for the most up-to-date information

That seems like something we could add with minimal effort, though it has downsides in that any update to the translated content will remove the warning, even if not all the changes are ported across. ([Kubernetes PR](https://github.com/kubernetes/website/pull/41768))

**Comment by Andygol** [comment]
Hello @craigbox !

Thank you for your kind words about my translation efforts into Ukrainian. However, I see that the project is not ready to accept new languages due to the lack of a clear strategy in this direction. 

At the current pace of the project's development, keeping the documentation up-to-date is a difficult but important task. However, keeping the translations of the documentation up-to-date imposes an additional burden. 

а) The Ukrainian translation is currently up-to-date at the time of the creation of the PR and you can accept it as is. b) I am ready to join the Istio project and spend some of my free time keeping the Ukrainian documentation up to date. Obtaining a membership in the Istio organization with the respective powers for this will streamline the process. c) The approach that was borrowed from the Kubernetes documentation project requires a lot of manual work to find differences between versions, rather than the translation itself. This is not conducive to the creation and dissemination of documentation in other languages. The introduction of Translation Documentation Systems to keep translations up to date, such as CrowdIn, can change the situation for the better.

**Comment by craigbox** [comment]
I'm pretty happy with A and B, and if you're willing to help us with something with regard to C, I think we are good to go. I will put this on the agenda for the next working group meeting to confirm.

Can you suggest how we might do a spot check on your work?  A few pages I translated with Google Translate seemed OK, but it would be good to have a human help out here

**Comment by Andygol** [comment]
👋 Hi there.

Are there any follow-ups regarding accepting Ukrainian translation of the documentation?

**Comment by craigbox** [comment]
We still need to arrange some way to review this, and then we can progress.

**Comment by smarunich** [comment]
I can help to review if needed. cc @ZackButcher

**Comment by kfaseela** [comment]
> I can help to review if needed. cc @ZackButcher 

@craigbox what do you think? If we have atleast one round of review, we can get this in?

**Comment by kfaseela** [comment]
+1 for merging

**Review by craigbox — APPROVED** [review]
Thanks to you both - let's go live!

**Comment by Andygol** [comment]
Thanks to all who made this possible 👏

**Comment by craigbox** [comment]
Be aware there will be some changes - at least one on the front page - that we'll want to be updated quickly when 1.24 lands in a day or two.

**Pull request merged**
