### PR TITLE
EOL announcement for release-1.17

### PR DESCRIPTION
**Pull request by johnma14**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by ericvn — APPROVED** [review]
But needs the EasyCLA to be verified.

**Review by kfaseela — APPROVED** [review]

**Review by ericvn — APPROVED** [review]

**Pull request merged**
