### PR TITLE
Update index.md  : Changed an oversight in localizing a Chinese word

### PR DESCRIPTION
**Pull request by msfmydream**
Changed an oversight in localizing a Chinese word

## Description

Changed an oversight in localizing a Chinese word

## Reviewers

- [ ] Ambient
- [X ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [x] Localization/Translation

[](https://istio.io/latest/docs/ops/integrations/prometheus/#installation)

### CODE REVIEW

**Comment by wilsonwu** [comment]
Welcome to contribute to Istio.

/ok-to-test

**Comment by wilsonwu** [comment]
@msfmydream I think we have a better way is submit the fix to master branch and cheery pick to release-1.22, do you think so?

**Comment by msfmydream** [comment]
@wilsonwu   I understand. thank you for your suggestion. should I need to create another new PR ？

**Review by windsonsea — APPROVED** [review]
Let's kick this in. This is to fix a phrase typo from `默` to `默认`.

**Pull request merged**
