### PR TITLE
Fix typo.

### PR DESCRIPTION
**Pull request by NatasG**
[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by kebe7jun — APPROVED** [review]

**Comment by NatasG** [comment]
@kebe7jun  why does this job fail? 
```
tests/tests.mk:29: recipe for target 'doc.test.profile_default' failed
```

**Comment by kebe7jun** [comment]
> @kebe7jun why does this job fail?
> 
> ```
> tests/tests.mk:29: recipe for target 'doc.test.profile_default' failed
> ```

Doesn't matter, just retest it.

**Pull request merged**
