### PR TITLE
add empty and preview profile to the table

### PR DESCRIPTION
**Pull request by shamsher31**
Before:

before

After:

after

### CODE REVIEW

**Comment by ericvn** [comment]
Not sure if you want to pick up some additional changes in this PR, but I have https://github.com/istio/istio.io/issues/8396 open to add some words about the vendor profiles.

**Comment by shamsher31** [comment]
Yes, I will add that to the same PR.

**Comment by ericvn** [comment]
I guess adding to this PR and cherry-picking wouldn't work. I'll approve this one, let it flow to 1.7, and we can pick up the vendor in a new one.

**Review by ericvn — APPROVED** [review]

**Pull request merged**
