### PR TITLE
Show exact 1.15 EOL date

### PR DESCRIPTION
**Pull request by howardjohn**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by ericvn — APPROVED** [review]

**Comment by howardjohn** [comment]
master is already good

**Comment by ericvn** [comment]
I guess we could have cherry-picked the other way but likely that had more changes than we needed.

**Comment by howardjohn** [comment]
Yep

**Pull request merged**
