### PR TITLE
Fixed CRD count and added note regarding cert-manager

### LINKED ISSUE #3687: incorrect # CRDs since 1.1.0-RC5
Since 1.1.0-RC5 there are (again :-) 56 CRDs (instead of 58) to check during helm install:
 
https://github.com/istio/istio.io/blame/master/content/docs/setup/kubernetes/install/helm/index.md#L123-L128
https://github.com/istio/istio.io/blame/master/content/docs/setup/kubernetes/install/helm/index.md#L242-L247

### PR DESCRIPTION
**Pull request by brian-avery**
The CRD count was previously set at 58, but the actual CRDs produced are 53. 

Fixes #3687

### CODE REVIEW

**Comment by geeknoid** [comment]
Please rebase and repush. That should take care of the CI failure.

Thanks.

**Comment by brian-avery** [comment]
Thanks @geeknoid. Rebase done and make lint rerun.

**Comment by geeknoid** [comment]
Fixes #3687

**Pull request merged**
