### PR TITLE
 zh-translation:content/zh/docs/tasks/security/authentication/authn-policy/index.md

### PR DESCRIPTION
**Pull request by mrshengzyzy**
[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by craigbox — APPROVED** [review]
EN edits LGTM

**Review by rootsongjc — APPROVED** [review]
/LGTM

**Comment by ericvn** [comment]
Test failure was in `tasks/security/authorization/authz-custom/test.sh`
```
VERIFY FAILED snip_enable_with_external_authorization_5 (timeout after 300s):
received:
"2021/04/01 02:38:28 Starting gRPC server at [::]:9000
2021/04/01 02:38:28 Starting HTTP server at [::]:8000
2021/04/01 02:38:30 [gRPCv3][denied]: httpbin.foo:8000/headers, attributes: source:{address:{socket_address:{address:"10.244.0.38"  port_value:47952}}  principal:"spiffe://cluster.local/ns/foo/sa/sleep"}  destination:{address:{socket_address:{address:"10.244.0.37"  port_value:80}}  principal:"spiffe://cluster.local/ns/foo/sa/httpbin"}  request:{time:{seconds:1617244710  nanos:868381000}  http:{id:"8004237145582290549"  method:"GET"  headers:{key:":authority"  value:"httpbin.foo:8000"}  headers:{key:":method"  value:"GET"}  headers:{key:":path"  value:"/headers"}  headers:{key:":scheme"  value:"http"}  headers:{key:"accept"  value:"*/*"}  headers:{key:"user-agent"  value:"curl/7.76.0-DEV"}  headers:{key:"x-b3-sampled"  value:"0"}  headers:{key:"x-b3-spanid"  value:"051431da4b57e1ab"}  headers:{key:"x-b3-traceid"  value:"2bb2824973fee535051431da4b57e1ab"}  headers:{key:"x-envoy-attempt-count"  value:"1"}  headers:{key:"x-ext-authz"  value:"deny"}  headers:{key:"x-forwarded-client-cert"  value:"By=spiffe://cluster.local/ns/foo/sa/httpbin;Hash=2740f027a97a7790b83f325895d69741dfc6466de1569bdba60f0664104ee6cf;Subject=\"\";URI=spiffe://cluster.local/ns/foo/sa/sleep"}  headers:{key:"x-forwarded-proto"  value:"http"}  headers:{key:"x-request-id"  value:"92328e56-7514-4f53-ad1e-c85654a44c23"}  path:"/headers"  host:"httpbin.foo:8000"  scheme:"http"  protocol:"HTTP/1.1"}}  metadata_context:{}"
expected:
"
+ [gRPCv3][allowed]
+ [gRPCv3][denied]
"
```

**Comment by ericvn** [comment]
Last set had the `/examples/virtual-machines/test.sh ` as well as the `tasks/security/authorization/authz-custom/test.sh` failure.

**Pull request merged**
