### PR TITLE
Update to istio 1.19.0-rc.0 + samples fix

### PR DESCRIPTION
**Pull request by ericvn**
Please provide a description for what this PR is for.

Pull in the latest 1.19 istio commit for tests.
The latest release-1.19 references a gateway-api rc (+ commits) version. Update the code to parse that and apply as appropriate.

### CODE REVIEW

**Comment by ericvn** [comment]
TRest fail when using the 0.8.0 rc1 and rc2 versions in the tests. Trying again with 0.7.1.

**Comment by ericvn** [comment]
Now waiting on https://github.com/istio/istio/pull/46707

**Comment by ericvn** [comment]
Also removed the expectation for `wasm` in the envoy test as it was removed.

**Review by hanxiaop — APPROVED** [review]

**Review by dhawton — APPROVED** [review]
LGTM

**Review by frankbu — APPROVED** [review]

**Comment by ericvn** [comment]
/test doc.test.profile-none

Flakes over the last few runs include:
- setup/additinal-setup/getting-started/test.sh
- ops/configuration/traffic-management/network-topologies/gtwapi/sh
- task/traffic-management/ingress/gtwapi.sh
but none of these fail every time.

**Pull request merged**
