### PR TITLE
fix security example policy

### PR DESCRIPTION
**Pull request by yangminzhu**
Fix https://github.com/istio/istio/issues/31777.

Also added a basic tests to verify the policy pass validation, we may add more tests later.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by ericvn — APPROVED** [review]

**Comment by ericvn** [comment]
I looks like the new `tasks/security/authorization/authz-custom/test.sh ` is having issues with not getting an allowed message in the logs:
```
VERIFY FAILED snip_enable_with_external_authorization_5 (timeout after 300s):
received:
"2021/04/01 16:01:24 Starting gRPC server at [::]:9000
2021/04/01 16:01:24 Starting HTTP server at [::]:8000
2021/04/01 16:01:29 [gRPCv3][denied]: httpbin.foo:8000/headers, attributes: source:{address:{socket_address:{address:"10.244.0.38"  port_value:45166}}  principal:"spiffe://cluster.local/ns/foo/sa/sleep"}  destination:{address:{socket_address:{address:"10.244.0.37"  port_value:80}}  principal:"spiffe://cluster.local/ns/foo/sa/httpbin"}  request:{time:{seconds:1617292889  nanos:533964000}  http:{id:"9216958666343270219"  method:"GET"  headers:{key:":authority"  value:"httpbin.foo:8000"}  headers:{key:":method"  value:"GET"}  headers:{key:":path"  value:"/headers"}  headers:{key:":scheme"  value:"http"}  headers:{key:"accept"  value:"*/*"}  headers:{key:"user-agent"  value:"curl/7.76.0-DEV"}  headers:{key:"x-b3-sampled"  value:"0"}  headers:{key:"x-b3-spanid"  value:"2374c0369d1ce528"}  headers:{key:"x-b3-traceid"  value:"ff943a67fcda45902374c0369d1ce528"}  headers:{key:"x-envoy-attempt-count"  value:"1"}  headers:{key:"x-ext-authz"  value:"deny"}  headers:{key:"x-forwarded-client-cert"  value:"By=spiffe://cluster.local/ns/foo/sa/httpbin;Hash=82868b5fe05d6243ab32ac0907f0a1ca139ae180233e8fe20d3abcf246cea026;Subject=\"\";URI=spiffe://cluster.local/ns/foo/sa/sleep"}  headers:{key:"x-forwarded-proto"  value:"http"}  headers:{key:"x-request-id"  value:"43560653-bea1-4588-baef-89bd54cb711c"}  path:"/headers"  host:"httpbin.foo:8000"  scheme:"http"  protocol:"HTTP/1.1"}}  metadata_context:{}"
expected:
"
+ [gRPCv3][allowed]
+ [gRPCv3][denied]
"
```

**Comment by ericvn** [comment]
@yangminzhu Is there an issue with issue where the `[gRPCv3][allowed]` is not being found in the logs. I've looked back through the last 6 failures, and all of them are missing the message in their logs. Is there something timing related issue where logging isn't being done of the `allowed`?

**Comment by yangminzhu** [comment]
> @yangminzhu Is there an issue with issue where the `[gRPCv3][allowed]` is not being found in the logs. I've looked back through the last 6 failures, and all of them are missing the message in their logs. Is there something timing related issue where logging isn't being done of the `allowed`?

There might be a timing issue here, I'm currently debugging it

**Pull request merged**
