### PR TITLE
update intel company logo

### PR DESCRIPTION
**Pull request by Arhell**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

made the logo a little smaller

### CODE REVIEW

**Comment by ericvn** [comment]
Is there some formula/process being used to figure out this resizing? I'm more concerned that someone would comeback and say why is our logo now seem smaller than others. Granted, a more square logo will be scaled down less than one that is wider in our square boxes. As noted in another issue, there are some formulas that try to take in account the height and with of pictures and scaling in square boxes to prevent some of this larger logo appearance. We don't seem to be able to apply the formulas ourselves in the code, but if we had a formula that said we would scale down the logo by `x` based on it's height/width ratio, then we have something to say that we are consistently doing this and not potentially favoring some logos.

**Comment by Arhell** [comment]
> Is there some formula/process being used to figure out this resizing? I'm more concerned that someone would comeback and say why is our logo now seem smaller than others. Granted, a more square logo will be scaled down less than one that is wider in our square boxes. As noted in another issue, there are some formulas that try to take in account the height and with of pictures and scaling in square boxes to prevent some of this larger logo appearance. We don't seem to be able to apply the formulas ourselves in the code, but if we had a formula that said we would scale down the logo by `x` based on it's height/width ratio, then we have something to say that we are consistently doing this and not potentially favoring some logos.

Doing it because of this https://github.com/istio/istio.io/issues/13574

I want to do everything a little at a time in about 1 size, but the big ones definitely need to be reduced

**Comment by ericvn** [comment]
Comment added in the issue to an article which talks about a fixed ratio. I'm not sure if that is easily applied to these images during manual resizing or not.

**Comment by Arhell** [comment]
you can do everything through css but the pictures (content) should be suitable, but unfortunately not in this case.

**Review by ericvn — APPROVED** [review]

**Pull request merged**
