### PR TITLE
[release-1.17] Update the istio test reference to the 1.17.6 candidate

### PR DESCRIPTION
**Pull request by ericvn**
Please provide a description for what this PR is for.

Update the istio test reference to the 1.17.6 candidate

Also update the test script so one can run them locally on an arm machine.

### CODE REVIEW

**Comment by ericvn** [comment]
Failure in `tasks/traffic-management/egress/egress-kubernetes-services/test.sh`. Running again, but I don't recall flakes in this test.

**Comment by ericvn** [comment]
/test doc.test.profile-demo

So test passed the second run. Try a third time..

**Comment by ericvn** [comment]
Third time also passed.

**Comment by ericvn** [comment]
4th time the egress test passed so 3 out of 4 times.

**Review by johnma14 — COMMENTED** [review]
LGTM. Thanks @ericvn

**Review by johnma14 — APPROVED** [review]

**Review by kfaseela — APPROVED** [review]

**Comment by ericvn** [comment]
1.17.6 release is imminent so remove the DNM and let this merge.

**Pull request merged**
