### PR TITLE
zh-translation: about/contribute/diagrams/index.md

### PR DESCRIPTION
**Pull request by elkan1788**
Upgrade the Chinese translation in path: about/contribute/diagrams/index.md

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by elkan1788** [comment]
@googlebot I signed it!

**Comment by elkan1788** [comment]
@googlebot I fixed it.

**Comment by elkan1788** [comment]
@googlebot I signed it!

**Comment by kebe7jun** [comment]
你这个，翻译的应该是 https://istio.io/latest/about/contribute/formatting/
但是你的 title 又对不上。
仔细检查下吧。

**Pull request closed without merging**
