### PR TITLE
Remove IST0117 message for 1.20

### PR DESCRIPTION
**Pull request by hanxiaop**
Please provide a description for what this PR is for.

Should be merged in 1.20 like https://github.com/istio/istio.io/pull/13717.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by wilsonwu** [comment]
No problem for the Chinese version syncing if the English update is correct.

**Review by ericvn — DISMISSED** [review]
Currently the master branch for istio.io is for the 1.19 release (until we branch it on release day. Hold this PR until then.

**Review by ericvn — APPROVED** [review]
Although I think this change is already merged.

**Comment by hanxiaop** [comment]
> Although I think this change is already merged.

Thanks, I think the `data/analysis.yaml` should already be updated, but the messages need to be deleted manually.

**Pull request merged**
