### PR TITLE
[zh]update content/zh/docs/tasks/traffic-management/ingress/ingress-control/index.md

### PR DESCRIPTION
**Pull request by yanrongshi**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by zirain — CHANGES_REQUESTED** [review]
wait https://github.com/istio/istio.io/pull/11969/files

**Comment by zirain** [comment]
https://github.com/istio/istio.io/pull/11969 is merged, please check the doc again.

**Review by rootsongjc — APPROVED** [review]
/LGTM

**Comment by windsonsea** [comment]
Due to already included in #12154 and no response for a long time, this PR will be closed.

**Pull request closed without merging**
