### PR TITLE
add some vocabularies in .spelling file

### PR DESCRIPTION
**Pull request by yuxiaobo96**
Signed-off-by: yuxiaobo <yuxiaobogo@163.com>

ref: https://github.com/servicemesher/istio-official-translation/issues/1445

### CODE REVIEW

**Comment by yuxiaobo96** [comment]
@rootsongjc 
Please help me to test.

**Comment by rootsongjc** [comment]
@yuxiaobo96 I have no access to merge this PR. You need ask @geeknoid

**Comment by yuxiaobo96** [comment]
Ok, I know.

**Comment by yuxiaobo96** [comment]
@geeknoid 
To solve the title anchor point problem, we need to add some words to the .spelling file.
Please help me check. 
THX.

**Comment by geeknoid** [comment]
Hi,

We don't want to add these words to the dictionary because it will lead people to misspell the words in normal text (using kubernetes instead of Kubernetes is generally incorrect for example).  So I'm going to close this.

Thanks.

**Pull request closed without merging**
