### PR TITLE
Attempt to build on netlify with 0.95.0 hugo

### PR DESCRIPTION
**Pull request by jacob-delgado**
Attempt to upgrade hugo on netlify

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by jacob-delgado** [comment]
See https://github.com/istio/istio.io/issues/11070

**Comment by ericvn** [comment]
@davidhauck Not sure how to best verify that the updated Hugo, etc don't have an adverse effect. Is it a wait and see if anyone finds something wrong with preliminary.istio.io? How about logs from the build? Can we compare to what we see in our current pipeline? Similar to https://github.com/istio/istio.io/issues/11070?

**Comment by craigbox** [comment]
When we change the markdown renderer, we should diff the `public` directory before and after.  I'm not sure there's a useful equivalent for here?  Download a few pages before/after?

**Comment by jacob-delgado** [comment]
The pages now have better human readable html in the newer Hugo versions. I'm not sure a diff would show anything.

**Comment by davidhauck** [comment]
I'm not sure there's a great way to check what the differences are with the newer hugo version. Probably just wait and see if anyone finds anything wrong with preliminary.istio.io. 

I do remember trying to update hugo in the past and had some problems. Maybe the newest hugo versions don't have those problems any more. Either way, we should look around in the preview site to make sure everything is still working

**Review by ericvn — APPROVED** [review]
I'm fine adding this for now. We'll want to fix some of the other items, change from blackfriday, etc. but can do in another PR. We can revert this if we find issues with preliminary.istio.io.

**Pull request merged**
