### PR TITLE
prepare for v1.23

### PR DESCRIPTION
**Pull request by dhawton**
## Description

Prepare for 1.23 release

## Reviewers

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

### CODE REVIEW

**Review by thedebugger — APPROVED** [review]

**Comment by dhawton** [comment]
/test doc.test.profile-ambient

extend wasm flake

**Comment by craigbox** [comment]
/retest

Failing tests:

* [default](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio.io/15443/doc.test.profile-default_istio.io/1814072962765033472/artifacts/tests-setup-profile-default-c1e/TestDocs/tasks/traffic-management/circuit-breaking/test.sh/test.sh/_test_context/test.sh_output.txt)

  * `Error: unknown flag: --for` - possibly related to the `istioctl x wait` command changing in 1.23?
  * the output has extra semi-colons in it.  investigating if this is a change in Envoy output or if for some reason the hostname has a semicolon suffixed.

* none:
 * [config-resource-ready](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio.io/15443/doc.test.profile-none_istio.io/1814073085142241280/artifacts/tests-setup-profile-none-eff9ba/TestDocs/ops/configuration/mesh/config-resource-ready/test.sh/test.sh/_test_context/test.sh_output.txt)
  * [dns-proxy](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio.io/15443/doc.test.profile-none_istio.io/1814073085142241280/artifacts/tests-setup-profile-none-eff9ba/TestDocs/ops/configuration/traffic-management/dns-proxy/test.sh/test.sh/_test_context/test.sh_output.txt)
  * [canary upgrade](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio.io/15443/doc.test.profile-none_istio.io/1814073085142241280/artifacts/tests-setup-profile-none-eff9ba/TestDocs/setup/upgrade/canary/canary_upgrade_test.sh/canary_upgrade_test.sh/_test_context/canary_upgrade_test.sh_output.txt)

**Review by zirain — APPROVED** [review]

**Comment by dhawton** [comment]
dns-proxy page failure is in the section about Auto Allocation.. which received a few changes in 1.23. I don't believe this is related to dual stack, as the SE above the auto allocation does pass the test.

**Comment by craigbox** [comment]
/retest

Latest links:

* [DNS proxy](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio.io/15443/doc.test.profile-none_istio.io/1815488167738871808/artifacts/tests-setup-profile-none-4cd669/TestDocs/ops/configuration/traffic-management/dns-proxy/test.sh/test.sh/_test_context/test.sh_output.txt)
* [authz-tcp](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio.io/15443/doc.test.profile-default_istio.io/1815500825582112768/artifacts/tests-setup-profile-default-0d4/TestDocs/tasks/security/authorization/authz-tcp/test.sh/test.sh/_test_context/test.sh_output.txt) - flake?
* [circuit breaking](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio.io/15443/doc.test.profile-default_istio.io/1815500825582112768/artifacts/tests-setup-profile-default-0d4/TestDocs/tasks/traffic-management/circuit-breaking/test.sh/test.sh/_test_context/test.sh_output.txt) -  the page/snips were updated, this test output doesn't reflect that.

**Comment by dhawton** [comment]
/test doc.test.profile-ambient

Flake

**Comment by craigbox** [comment]
/test doc.test.profile-none

[Might be a flake](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio.io/15443/doc.test.profile-none_istio.io/1815536138970992640/artifacts/tests-setup-profile-none-e9b365/TestDocs/ops/configuration/traffic-management/dns-proxy/test.sh/test.sh/_test_context/test.sh_output.txt) even though it's also in the DNS Proxy page. It looks like it just didn't get programmed in time.

**Comment by dhawton** [comment]
> /test doc.test.profile-none
> 
> [Might be a flake](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio.io/15443/doc.test.profile-none_istio.io/1815536138970992640/artifacts/tests-setup-profile-none-e9b365/TestDocs/ops/configuration/traffic-management/dns-proxy/test.sh/test.sh/_test_context/test.sh_output.txt) even though it's also in the DNS Proxy page. It looks like it just didn't get programmed in time.

No.. it's another change in istioctl. I have disabled that validation for now.. I'll take a look at both first thing in the AM, but as long as we fix before 1.23.0 it should be ok to disable for now.

**Comment by craigbox** [comment]
> No.. it's another change in istioctl.

Cool.  (I tried testing with 1.23.0-alpha.0 which still had the same output.)

**Pull request merged**
