### PR TITLE
Update "Visualizing Your Mesh" istio.io page with Kiali v1.34

### PR DESCRIPTION
**Pull request by jshaughn**
https://github.com/kiali/kiali/issues/3888

The "Visualizing Your Mesh" [page](https://istio.io/latest/docs/tasks/observability/kiali/) Is out of date for more recent versions of the Kiali addon.  This PR updates text and screenshots to be more in line with the Kiali version for v1.9 and v1.10 of Istio.

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

cc @esnible

### CODE REVIEW

**Comment by jshaughn** [comment]
@googlebot I signed it!

**Comment by craigbox** [comment]
LGTM, /cc @esnible

**Review by esnible — APPROVED** [review]
Looks good to me.  This will conflict with the automation I am working on in https://github.com/istio/istio.io/pull/9570 but I don't mind!  I will continue working on the automation once this merges.

**Comment by jshaughn** [comment]
Thanks, @esnible , sorry for any conflict pain, I was unaware of the automation effort.  Steps have not really changed, just updated for currency.  I'll merge (or someone else can) as soon as the merge button activates :)

**Review by ericvn — APPROVED** [review]

**Pull request merged**
