### PR TITLE
multicluster doc: Use label to filter Service for helloworld

### LINKED ISSUE #8272: Issue with docs/setup/install/multicluster/index.md
https://preliminary.istio.io/latest/docs/setup/install/multicluster/#deploy-the-helloworld-service

image

The section `Deploy the HelloWorld Service` is meant to deploy just the `Service` , but the given command deploys the Service, v1 Deployment and v2 Deployment.

cc: @linsun

### PR DESCRIPTION
**Pull request by rvennam**
Use label for helloworld Service to only apply the Service and not the v1 and v2 Deployments 

Fixes #8272

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by frankbu** [comment]
This change depends on a newer istio/istio build for the test framework. Will `/retest` after next update of test build, which should fix the broken MC tests in this PR.

**Comment by shamsher31** [comment]
> This PR's tests may be failing because of this issue too: [istio/istio#27838](https://github.com/istio/istio/issues/27838)

@frankbu Hope will be fixed by https://github.com/istio/release-builder/pull/433

**Comment by frankbu** [comment]
It seems that the reason we hadn't noticed that both version deployments were (without this PR) being deployed to both clusters is because the tests are missing the `get pods` verification described in the doc. The [verify_load_balancing function in common.sh](https://github.com/istio/istio.io/blob/88628a1a405731d4990b7ddfc0f050cb958595ce/content/en/docs/setup/install/multicluster/common.sh#L67) should be changed to the following:
```
# verify_load_balancing verifies that traffic is load balanced properly
# between CLUSTER1 and CLUSTER2.
function verify_load_balancing()
{
  # Deploy HelloWorld and Sleep.
  snip_deploy_the_helloworld_service_1
  snip_deploy_the_helloworld_service_2
  snip_deploy_the_helloworld_service_3

  snip_deploy_helloworld_v1_1
  (KUBECONFIG="${KUBECONFIG_CLUSTER1}"; _wait_for_deployment sample helloworld-v1)
  _verify_like snip_deploy_helloworld_v1_2 "$snip_deploy_helloworld_v1_2_out"  

  snip_deploy_helloworld_v2_1
  (KUBECONFIG="${KUBECONFIG_CLUSTER2}"; _wait_for_deployment sample helloworld-v2)
  _verify_like snip_deploy_helloworld_v2_2 "$snip_deploy_helloworld_v2_2_out"  

  snip_deploy_sleep_1
  (KUBECONFIG="${KUBECONFIG_CLUSTER1}"; _wait_for_deployment sample sleep)
  _verify_like snip_deploy_sleep_2 "$snip_deploy_sleep_2_out"  
  (KUBECONFIG="${KUBECONFIG_CLUSTER2}"; _wait_for_deployment sample sleep)
  _verify_like snip_deploy_sleep_3 "$snip_deploy_sleep_3_out"
  
  local EXPECTED_RESPONSE_FROM_CLUSTER1="Hello version: v1, instance:"
  local EXPECTED_RESPONSE_FROM_CLUSTER2="Hello version: v2, instance:"

  # Verify we hit both clusters from CLUSTER1
  _verify_contains snip_verifying_crosscluster_traffic_1 "$EXPECTED_RESPONSE_FROM_CLUSTER1"
  _verify_contains snip_verifying_crosscluster_traffic_1 "$EXPECTED_RESPONSE_FROM_CLUSTER2"

  # Verify we hit both clusters from CLUSTER2
  _verify_contains snip_verifying_crosscluster_traffic_3 "$EXPECTED_RESPONSE_FROM_CLUSTER1"
  _verify_contains snip_verifying_crosscluster_traffic_3 "$EXPECTED_RESPONSE_FROM_CLUSTER2"
}
```
This should cause the tests to fail without this PR, but should pass with it unless there's a bug in the runtime.

**Comment by nmittler** [comment]
@rvennam I'm taking care of this in https://github.com/istio/istio.io/pull/8309, which has additional fixes ... you can go ahead and close this out.

**Comment by rvennam** [comment]
Sounds good

**Pull request closed without merging**
