### PR TITLE
Ambient beta get started guide patch

### PR DESCRIPTION
**Pull request by nauticalmike**
## Description

Adjusting removing the inpod from doc per @bleggett 's suggestion https://github.com/istio/istio.io/pull/14788#discussion_r1543751871

## Reviewers

- [x] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

### CODE REVIEW

**Review by bleggett — APPROVED** [review]
TY! Wording SGTM, rest LGTM outside of @ericvn's comments

**Comment by nauticalmike** [comment]
thanks @bleggett, @ericvn will do shortly

**Comment by nauticalmike** [comment]
@ericvn I'm hitting the RBAC denied issue [here](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio.io/14805/doc.test.profile-none_istio.io/1773795553054822400/artifacts/tests-setup-profile-none-4be872/TestDocs/ops/ambient/getting-started/gtwapi_test.sh/gtwapi_test.sh/_test_context/gtwapi_test.sh_output.txt):
```
VERIFY FAILED snip_layer_7_authorization_policy_4 (timeout after 120s):
received:
"<!doctype html>
<html lang=en>
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>"
expected:
"RBAC: access denied"
```

What should I do here?

**Comment by ericvn** [comment]
> @ericvn I'm hitting an issue [here](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio.io/14805/doc.test.profile-none_istio.io/1773795553054822400/artifacts/tests-setup-profile-none-4be872/TestDocs/ops/ambient/getting-started/gtwapi_test.sh/gtwapi_test.sh/_test_context/gtwapi_test.sh_output.txt):
> 
> ```
> VERIFY FAILED snip_layer_7_authorization_policy_4 (timeout after 120s):
> received:
> "<!doctype html>
> <html lang=en>
> <title>405 Method Not Allowed</title>
> <h1>Method Not Allowed</h1>
> <p>The method is not allowed for the requested URL.</p>"
> expected:
> "RBAC: access denied"
> ```
> 
> What should I do here? What I mean is on this step we are supposed to get an `RBAC: access denied` but the verify received something else. This test was working fine before and the previous run just timed out after 1h.

Correct. This is the problem that moving up istio references causes breaking the tests. I'm not sure what the resolution should be, but see the discussion in Slack mentioned above with @ilrudie

**Comment by bleggett** [comment]
Since this is mostly a wording fix and doctests seem to need a rework in the wake of the waypoint attach changes, suggest we leave the tests disabled here, and raise an issue to fix+enable the doctests.

**Comment by ericvn** [comment]
> Since this is mostly a wording fix and doctests seem to need a rework in the wake of the waypoint attach changes, suggest we leave the tests disabled here, and raise an issue to fix+enable the doctests.

The tests are disabled and there already is a release blocker issue to enable and fix them: https://github.com/istio/istio/issues/50145.

What you need to do in this PR would be to not rename the disabled test back so that we are trying to run it, and likely only include any index.md changes you desire. Note that the doc will need to be reworked and test rewritten in the next few weeks as I believe 1.22 is planned for release in a month or so.

**Comment by craigbox** [comment]
@nauticalmike please rebase and we can get the wording changes in separately from the test changes!

**Comment by craigbox** [comment]
I think the change we made to getting started in #15168 includes all of this so I'll close it with thanks!

**Pull request closed without merging**
