### PR TITLE
add nearpod logo

### PR DESCRIPTION
**Pull request by Fmowers**
Add Nearpod logo to website

[x ] Docs

### CODE REVIEW

**Comment by frankbu** [comment]
@Fmowers Please sign the CLA so we can merge your PR.
https://github.com/istio/istio.io/pull/8028#issuecomment-680909318

**Comment by Fmowers** [comment]
@frankbu Do we really have to sign this to get my company's logo on to the website. Legal department read it and doesn't like the idea of signing it when we are not technically contributing anything other than our company's logo in the community section of the website.

**Comment by frankbu** [comment]
> Do we really have to sign this to get my company's logo on to the website.

@Fmowers I believe this has to do with confirming that we have permission to display your logo on the Istio site.
cc @istio/steering-committee 
https://github.com/istio/istio.io/pull/8028#issuecomment-683991820

**Comment by frankbu** [comment]
Closing because PR can't be merged without CLA.

@Fmowers feel free to reopen if you decide to sign the CLA.

**Pull request closed without merging**
