### PR TITLE
Accessibility update aria links

### PR DESCRIPTION
**Pull request by Arhell**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

resolve https://github.com/istio/istio.io/issues/10924

### CODE REVIEW

**Comment by Arhell** [comment]
cc @raigbox
no errors after checking

**Comment by Arhell** [comment]
cc @craigbox
no errors after checking

**Comment by craigbox** [comment]
LGTM, but I'm not familiar with the tabindex settings.  Can you please give me a sentence explaining the change?

**Comment by Arhell** [comment]
> LGTM, but I'm not familiar with the tabindex settings. Can you please give me a sentence explaining the change?

just clarified, left it, it does not affect the check

**Comment by Arhell** [comment]
here is what is written in Accessibility Insights for Web

> An ARIA role attribute can be added to an element to instruct assistive technologies to treat the element as something other than its native HTML element type. For example, an <li> element with role="option" is to be treated as a selectable option in a listbox control, not as a static list item.
> 
> Some ARIA "child" roles identify managed controls that are always part of a larger composite control, identified by a "parent" role. For example, role="option" identifies a child control that is managed by a parent control identified by role="listbox". People who use assistive technologies might find it difficult or impossible to use a child control if its managing control lacks the required parent role.

for our page I think this attribute is redundant

**Review by craigbox — APPROVED** [review]

**Pull request merged**
