### PR TITLE
The vendor directory should be in .gitignore

### PR DESCRIPTION
**Pull request by litong01**
Signed-off-by: Tong Li <litong01@us.ibm.com>

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [x] Developer Infrastructure

### CODE REVIEW

**Comment by ericvn** [comment]
We use modules and don't use the vendor directory so it shouldn't need to be in the .gitignore. Why add it for no reason. Can you give me an example of what would create the vendor directory in istio.io?

**Comment by litong01** [comment]
> We use modules and don't use the vendor directory so it shouldn't need to be in the .gitignore. Why add it for no reason. Can you give me an example of what would create the vendor directory in istio.io?

@ericvn there is this go.mod file, when import to VS code, it will be treated as go project to find dependencies, after running `go mod vendor` which produces vendor directory, then VS code will be happy. Without the vendor directory, VS code keeps searching, which makes vs code sluggish. I think adding this will help in that regard. and it wont hurt anything but help a lot in terms of IDE and git operations.

**Comment by ericvn** [comment]
@litong01 I hadn't heard of vscode having that issue before and hadn't seen it myself.

I suspect you really want this to be `/vendor/` so you are only ignoring the vendor directory in the root folder?

**Comment by litong01** [comment]
> @litong01 I hadn't heard of vscode having that issue before and hadn't seen it myself.
> 
> I suspect you really want this to be `/vendor/` so you are only ignoring the vendor directory in the root directory of the repo?

That is right. that should be same thing as vendor like how istio is doing. if it also refers the subdirectory, it should have been vendor/**/*

**Comment by ericvn** [comment]
The way it is now, it will ignore any file or directory called vendor anywhere in the source tree.
ex:
```
a/vendor
a/vendor/
vendor
vendor/
```

I'm not saying istio/istio is correct.

**Comment by ericvn** [comment]
Based on earlier discussion, can we close this one now?

**Comment by litong01** [comment]
do not need it after discussion.

**Pull request closed without merging**
