### PR TITLE
Remove "Helm with Tiller" install path docs

### PR DESCRIPTION
**Pull request by jpapejr**
Removes the Helm with Tiller install path since we've already removed the related upgrade path. Updates still have a reference to istioldie 1.4 if someone still needs to see it.

### CODE REVIEW

**Comment by frankbu** [comment]
@jpapejr since the auto cherry-pick had a merge conflict, you'll need to manually send a PR to the release-1.5 branch.

**Comment by jpapejr** [comment]
@frankbu https://github.com/istio/istio.io/pull/6869

**Pull request merged**
