### PR TITLE
update authorization

### PR DESCRIPTION
**Pull request by linsun**
done in istio proxy now since istio 1.1 which is why mixer policy check is disabled by default: https://github.com/istio/istio/issues/11736

### CODE REVIEW

**Comment by frankbu** [comment]
Not sure we need to update anything in this doc since it is in the process of being replaced by a totally new security concepts rewrite.

cc: @rcaballeromx

**Comment by linsun** [comment]
cc @johnma14

**Comment by linsun** [comment]
@frankbu I created a 1.4 PR - https://github.com/istio/istio.io/pull/6148.  I'm good to have this corrected in 1.5 doc in the future.

**Comment by frankbu** [comment]
Fixed in #6148

**Pull request closed without merging**
