### PR TITLE
Fix docs on customTags

### PR DESCRIPTION
**Pull request by taer**
it has a typo and that was the one example I used to copy/pasta

Just fixes the docs on custom-tags.

### CODE REVIEW

**Comment by kfaseela** [comment]
cc @zirain

**Review by dhawton — CHANGES_REQUESTED** [review]
This should be made against master branch. We can cherry-pick to release-1.22 after.

**Comment by taer** [comment]
> This should be made against master branch. We can cherry-pick to release-1.22 after.

OMG.  No idea how I did that. Will fixing soon

**Comment by taer** [comment]
@dhawton There are a few more instances of custom_tags in the docs. mostly in the meshConfig/defaultConfig.

Think those might be deprecated? They are note referenced here: https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#Tracing

that tracing section reached via: https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig

**Review by zirain — APPROVED** [review]
LGTM, can you make CI happy.

you may need to run `make gen` locally.

**Comment by taer** [comment]
> LGTM, can you make CI happy.
> 
> you may need to run `make gen` locally.

done

**Review by dhawton — APPROVED** [review]

**Pull request merged**
