### PR TITLE
Move back doc links to v1beta1 since we are still supporting 1.15

### PR DESCRIPTION
**Pull request by ericvn**
See https://github.com/istio/istio/pull/26285

### CODE REVIEW

**Comment by frankbu** [comment]
The platform setup page says that Istio 1.7 supports Kubernetes releases: 1.16, 1.17, 1.18, buy not 1.15. Is that wrong?

**Comment by ericvn** [comment]
@howardjohn I'm not sure if the 1.15 is a full support statement or more of a we won't break people who use 1.15. I suspect it's the former, but haven't seen an official statement (after the doc we had approved where 1.15 wasn't supported).

**Comment by howardjohn** [comment]
I think we will unofficially support 1.15 *maybe*. We might not even. the webhook stuff is only semi-related, we had to revert because of upgrade issues

**Pull request merged**
