### PR TITLE
Move from trustworthy-jwt yaml to default-yaml

### PR DESCRIPTION
**Pull request by ericvn**
Please provide a description for what this PR is for.

There is a desire to remove the trustworthy.jwt from istio/istio, changing to default. Make the updates here as well.

### CODE REVIEW

**Review by jacob-delgado — APPROVED** [review]

**Comment by ericvn** [comment]
Tried a small commit and that seems to have fixed it. I see @howardjohn shows a command that might run it again to try next time as well.

**Review by kfaseela — APPROVED** [review]

**Comment by kfaseela** [comment]
i think some of our wiki pages are using the deleted trustworthy-jwt yaml in examples... on how to setup test env locally.. (not sure)..

**Comment by ericvn** [comment]
> i think some of our wiki pages are using the deleted trustworthy-jwt yaml in examples... on how to setup test env locally.. (not sure)..

I did a search and only came up with the test README.

**Comment by kfaseela** [comment]
> > i think some of our wiki pages are using the deleted trustworthy-jwt yaml in examples... on how to setup test env locally.. (not sure)..
> 
> I did a search and only came up with the test README.

I meant the wiki pages. eg: https://github.com/istio/istio/wiki/Istio-Test-Framework

**Pull request merged**
