### PR TITLE
[kiali] issue 19232 talk about changing configmap

### PR DESCRIPTION
**Pull request by jmazzitelli**
fixes https://github.com/istio/istio/issues/19232

### CODE REVIEW

**Comment by ericvn** [comment]
Did you mean to put these into 1.4 without putting them in _master_? Normally, things are put into _master_ and cherrypicked back. Else this might need to be cherrypicked to master from 1.4?

**Comment by jmazzitelli** [comment]
> Did you mean to put these into 1.4 without putting them in _master_? Normally, things are put into _master_ and cherrypicked back. Else this might need to be cherrypicked to master from 1.4?

The reason is because we hope in the next release users shouldn't even know about/care/edit the configmap - that's for the kiali operator (and only the kiali operator) to modify.

So while this is valid for 1.4, it hopefully should not be valid instructions going forward and thus not in master.

Hopefully, these PRs can get combined/merged once the installer/operator repos get combined into the "monorepo":

https://github.com/istio/installer/pull/556
https://github.com/istio/operator/pull/622

That will introduce the kiali operator and the instructions in this PR will no longer be valid.

**Comment by adammil2000** [comment]
@jmazzitelli  We should continue to hold the approval of this PR until these other two are completed, correct?

https://github.com/istio/installer/pull/556
https://github.com/istio/operator/pull/622

Thanks!

**Comment by jmazzitelli** [comment]
@adammil2000 actually, this PR should be merged... this PR is going in the istio 1.4 documentation - and these doc changes are relevant for that istio version.

We do not want these doc changes in master because the hope is the kiali operator will make it into Istio 1.5's istioctl (that's what the changes in those two PRs will attempt to do) and thus makes the docs in this PR obsolete.

**Pull request merged**
