### PR TITLE
zh-translation: content/zh/docs/reference/glossary/service-producer.md

### PR DESCRIPTION
**Pull request by depfish**
ref: https://github.com/servicemesher/istio-official-translation/issues/1377

### CODE REVIEW

**Comment by tanjunchen** [comment]
Sign CLA

**Comment by depfish** [comment]
> 
> 
> Sign CLA

Signed already :)

**Comment by tanjunchen** [comment]
@depfish 
Once you've signed (or fixed any issues), please reply here with ```@googlebot I signed it!``` and we'll verify it.

**Comment by tanjunchen** [comment]
@rootsongjc  review content and approve if CI passes

**Pull request merged**
