### PR TITLE
Use zipkin collector address instead of jaeger to avoid confusion.

### PR DESCRIPTION
**Pull request by bianpengyuan**
There is no need to mention port number. Operator should know which port they should be using for zipkin and jaeger trace report. It has caused some confusions: https://github.com/istio/istio.io/issues/9668 and https://github.com/istio/istio/issues/32026#issuecomment-831561949

### CODE REVIEW

**Comment by douglas-reid** [comment]
I'm not sure we want this PR. We are serving the zipkin API, which on most deployments of both services (and in our sample deployments) is on port `9411`. If traffic to port `9411` is not working, then there must be a separate issue (or a backwards incompatibility that was introduced).

**Comment by bianpengyuan** [comment]
> I'm not sure we want this PR. We are serving the zipkin API, which on most deployments of both services (and in our sample deployments) is on port `9411`. If traffic to port `9411` is not working, then there must be a separate issue (or a backwards incompatibility that was introduced).

Jaeger collector service does not use port 9411, which makes the doc confusing. I can remove the jaeger one only, if we want to keep zipkin 9411 documented.

**Comment by douglas-reid** [comment]
> > I'm not sure we want this PR. We are serving the zipkin API, which on most deployments of both services (and in our sample deployments) is on port `9411`. If traffic to port `9411` is not working, then there must be a separate issue (or a backwards incompatibility that was introduced).
> 
> Jaeger collector service does not use port 9411, which makes the doc confusing. I can remove the jaeger one only, if we want to keep zipkin 9411 documented.

It should. The all-in-one should be enabling the optional Zipkin port. That's been our jaeger integration story from 0.1. Did we remove it?

**Comment by douglas-reid** [comment]
> > > I'm not sure we want this PR. We are serving the zipkin API, which on most deployments of both services (and in our sample deployments) is on port `9411`. If traffic to port `9411` is not working, then there must be a separate issue (or a backwards incompatibility that was introduced).
> > 
> > 
> > Jaeger collector service does not use port 9411, which makes the doc confusing. I can remove the jaeger one only, if we want to keep zipkin 9411 documented.
> 
> It should. The all-in-one should be enabling the optional Zipkin port. That's been our jaeger integration story from 0.1. Did we remove it?

Maybe we should update with a warning about enabling the optional port, per our sample config: https://github.com/istio/istio/blob/master/samples/addons/jaeger.yaml#L33-L34 ?

**Comment by bianpengyuan** [comment]
I think the problem is 9411 is not exposed at jaeger-collector service: https://github.com/istio/istio.io/issues/9668#issuecomment-831579695

**Comment by ericvn** [comment]
Any updates on this PR?

**Comment by ericvn** [comment]
Waiting on approval from @douglas-reid

**Pull request closed without merging**
