### PR TITLE
Add 1.10 pre-EOL announcement

### PR DESCRIPTION
**Pull request by Monkeyanator**
EOL warning for 1.10

### CODE REVIEW

**Comment by ericvn** [comment]
While I believe that the n+2 + 6 weeks is correct for the 1.10 release, it was mentioned to present to the TOC about carrying this forward for future releases. Since we mention a formula here and there was a discussion of a blog for support going forward, I think we can wait until the TOC meeting on Nov 29 before merging this. That date still leaves a 30 day notice for EOL notice.

**Comment by Monkeyanator** [comment]
> While I believe that the n+2 + 6 weeks is correct for the 1.10 release, it was mentioned to present to the TOC about carrying this forward for future releases. Since we mention a formula here and there was a discussion of a blog for support going forward, I think we can wait until the TOC meeting on Nov 29 before merging this. That date still leaves a 30 day notice for EOL notice.

Sounds good.

**Comment by Monkeyanator** [comment]
From 11/29 TOC we will be carrying the policy forward.

**Review by frankbu — APPROVED** [review]
The publish date is a little old here, but I better late than never :)

**Pull request merged**
