### PR TITLE
zh: update the anchor-point for the clean-up of authz-deny and custom

### PR DESCRIPTION
**Pull request by saltbo**
Please provide a description for what this PR is for.
fix the anchor-point for the clean-up of authz-deny and custom

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by windsonsea** [comment]
As the first contribution, this is a good catch, thanks.

/lgtm

**Review by rootsongjc — APPROVED** [review]
/LGTM

**Pull request merged**
