### PR TITLE
translate getting-started page to brazilian portuguese pt-br

### PR DESCRIPTION
**Pull request by JohnWillker**
Reading [this](https://github.com/istio/istio.io/issues/6344) issue I started translating some pages and the first one that makes sense to me is this.

### CODE REVIEW

**Comment by JohnWillker** [comment]
> @googlebot I signed it!

@googlebot I signed it!

**Comment by JohnWillker** [comment]
@gbaufake look this

**Comment by gbaufake** [comment]
I'm going to review it.

**Comment by gbaufake** [comment]
ok-to-test

**Comment by JohnWillker** [comment]
> ok-to-test

@gbaufake 
I think you meant: `/ok-to-test`

**Comment by JohnWillker** [comment]
I believe that the tests failed because of this [problem](https://github.com/istio/istio.io/issues/6857).

**Comment by gbaufake** [comment]
@brian-avery Can you give me any insight here? it doesn't need to be related to Portuguese content :)

**Comment by brian-avery** [comment]
Test looks like it's failing from: https://github.com/istio/istio.io/pull/7043

**Pull request merged**
