### PR TITLE
docs: add opencensusagent docs

### PR DESCRIPTION
**Pull request by brianwolfe**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Still WIP. Trying to get the time to finish this up, but pushing it so I can start to execute tests.

Fixes https://github.com/istio/istio.io/issues/8166

### CODE REVIEW

**Comment by craigbox** [comment]
Any update on this PR, Brian?

**Comment by brianwolfe** [comment]
@craigbox Thanks for the ping. I haven’t had time for a few weeks. I can try to make some progress this weekend.

**Comment by PatrikSteuer** [comment]
This content is really helpful, thanks a lot!

**Comment by tillig** [comment]
It would be awesome to see this get merged. I spent a lot of time digging around in forums and chats to find that I was missing the `global.proxy.tracer` setting. This doc would have saved me a ton of time.

**Comment by verysonglaa** [comment]
Hi all, I am in the process of creating a new updated PR based on this code. It should be ready in a few days.

**Review by craigbox — COMMENTED** [review]
I'm going to close this, given we merged #11239.

**Pull request closed without merging**
