### PR TITLE
[release-1.18] manual cherry pick of release notes 1.16.6, 1.17.4, 1.18.1

### PR DESCRIPTION
**Pull request by dhawton**
Please provide a description for what this PR is for.

Manual cherry pick of #13563 -- release notes

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by johnma14 — COMMENTED** [review]
LGTM

**Review by ericvn — APPROVED** [review]

**Comment by ericvn** [comment]
Test failure looks similar to one I saw in the main branch. Checking.

**Comment by ericvn** [comment]
Merging https://github.com/istio/istio.io/pull/13559 which should fix the test. If we are ready to publish we can force merge this if needed.

**Pull request merged**
