### PR TITLE
[release-1.21] Update test reference and reference docs for 1.21.1

### PR DESCRIPTION
**Pull request by ericvn**
## Description

Run istio.io tests with new istio commit. Also update the reference docs.

### CODE REVIEW

**Comment by ericvn** [comment]
/test doc.test.profile-demo

rate-limit flake

**Comment by ericvn** [comment]
rate-limit failed again:
```
VERIFY FAILED snip_verify_global_rate_limit_2 (timeout after 120s):
received:
"429
429
200"
expected:
"200
200
429
```

**Comment by ericvn** [comment]
/test doc.test.profile-demo

try once more

**Review by frankbu — APPROVED** [review]

**Pull request merged**
