### PR TITLE
docs: add casdoor into example OpenID providers

### PR DESCRIPTION
**Pull request by ComradeProgrammer**
docs: add casdoor into example OpenID providers

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [X ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by craigbox** [comment]
Please also consider adding information to the integrations page at https://istio.io/latest/about/ecosystem/ !

**Comment by ComradeProgrammer** [comment]
> Please also consider adding information to the integrations page at https://istio.io/latest/about/ecosystem/ !
> 
> (You'll have to add `Casdoor` to `/.spelling` to fix the lint error)

I see, `Casdoor` has been added into `/.spelling`

**Review by craigbox — APPROVED** [review]
/cherrypick master

**Pull request merged**
