### PR TITLE
Fixed Hugo's warning regarding index file

### PR DESCRIPTION
**Pull request by arijitvt**
## Description

Fixing the Hugo's warning during `make serve`, reported in the issue #14154 .

## Reviewers

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

### CODE REVIEW

**Comment by windsonsea** [comment]
Hi @arijitvt, lint-check is easy to fail when only a filename is changed. How about to change something in the file like:

```
---
title: Ambient Mesh 使用指南
description: 如何使用 Ambient Mesh。
weight: 2
owner: istio/wg-networking-maintainers
test: n/a
---
-
- 本页正在建设中。
```

**Comment by arijitvt** [comment]
Thanks for that. Will make the change. I think the actual issue is some bug in the hugo but thanks for the lead. I will make the change to make the ci happy.

**Review by windsonsea — APPROVED** [review]
lgtm

**Pull request merged**
