### PR TITLE
Add GetYourGuide logo to Istio in Action page

### PR DESCRIPTION
**Pull request by fabiolanfranchi**
We are using Istio in production since beginning of this year.
Highlights for us are the expressiveness of VirtualServices and the concept of Ingress Gateways.

### CODE REVIEW

**Comment by sdake** [comment]
@fabiolanfranchi I've taken a look at your whois information, SSL certificate, business registration, etc.  All looks good.

Thanks for being willing to be highlighted as an Istio customer!

Would you mind rebasing this PR on the release-1.1 branch?  Your changes will land in master in about 20-30 days, but go live on the site as soon as this PR merges.

Cheers
-steve

**Comment by sdake** [comment]
Current version LGTM

**Comment by fabiolanfranchi** [comment]
Closing this in favor of https://github.com/istio/istio.io/pull/3892

**Pull request closed without merging**
