### PR TITLE
[zh] Sync #15024 move non-usage stuff out of ztunnel usage guide into Chinese

### PR DESCRIPTION
**Pull request by wilsonwu**
## Description

Sync #15024 move non-usage stuff out of ztunnel usage guide into Chinese

## Reviewers

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [x] Localization/Translation

### CODE REVIEW

**Comment by craigbox** [comment]
Be aware these pages are all changing very rapidly at the moment; I would hate for you to be translating content we're just going to remove in a week's time...

**Comment by wilsonwu** [comment]
> Be aware these pages are all changing very rapidly at the moment; I would hate for you to be translating content we're just going to remove in a week's time...

So currently the structure is stable or not? Because it is a very hard work if I sync changes after all English update finish, it is easy by sync changes PR by PR, and I suggest that English maintainer need to think twice before changing the content structure.

**Comment by wilsonwu** [comment]
After check, set to draft and waiting for the English doc structure stable.

**Comment by wilsonwu** [comment]
Close this PR by doc structure with big changes, let's sync later after all get stable.

**Pull request closed without merging**
