### PR TITLE
[zh] Sync the page weight of releases/contribute/github

### PR DESCRIPTION
**Pull request by Xieql**
Please provide a description for what this PR is for.

Sync the page weight of releases/contribute/github to https://github.com/istio/istio.io/blob/5705e8d69ab4532fa253d370fa6ac48bdb2ffb4b/content/en/docs/releases/contribute/github/index.md?plain=1#L4

To improve clarity and consistency, it would be beneficial to move the content of this section to the first item, similar to the structure of the English version.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by windsonsea** [comment]
Hi @Xieql , you need to sign [cla](https://github.com/istio/istio.io/pull/13051/checks?check_run_id=12745251211) before reviewing.

**Comment by Xieql** [comment]
> Hi @Xieql , you need to sign [cla](https://github.com/istio/istio.io/pull/13051/checks?check_run_id=12745251211) before reviewing.

ok, it's done

**Comment by windsonsea** [comment]
Hi @Xieql , would you like to check more content out of sync and not very correct on this page:

image

**Comment by Xieql** [comment]
> Hi @Xieql , would you like to check more content out of sync and not very correct on this page:
> 
> image

ok， I will check this page in full

**Review by windsonsea — APPROVED** [review]
Thanks.

**Pull request merged**
