### PR TITLE
Update Galley feature stages.

### PR DESCRIPTION
**Pull request by ozevren**

### CODE REVIEW

**Comment by ozevren** [comment]
What am I doing wrong here?

**Comment by duderino** [comment]
@ozevren I think some external envoy URLs changed.  All of my doc PRs from today are failing with the same error

**Comment by ozevren** [comment]
@geeknoid any insights? How can I help to resolve this?

**Comment by rcaballeromx** [comment]
@ozevren Please rebase the PR for the issues to pass. We have merged fixes for the links.

**Comment by ozevren** [comment]
done.

**Pull request merged**
