### PR TITLE
Update monitor port translation

### PR DESCRIPTION
**Pull request by ericvn**
Documentation updates in translated files that coincide with istio/istio#11421 which changed the default monitoring port from 9093 to 15014.

The English files are updated in PR https://github.com/istio/istio.io/pull/3183

WIP until that PR is merged.

### CODE REVIEW

**Comment by rootsongjc** [comment]
@ericvn I see this PR is still `work-in-progress`, once https://github.com/istio/istio.io/pull/3183 PR merged, this one will be merged too.

**Comment by ericvn** [comment]
Per comments in #3183 I added a commit to remove the changes in content_zh/docs/reference as done in that PR.

**Comment by ericvn** [comment]
Removed the [WIP] since the underlying [istio/istio#11421](https://github.com/istio/istio/pull/11421) was merged.

**Pull request merged**
