### PR TITLE
[release-1.20] Add ambient helm installation guide (#13871)

### PR DESCRIPTION
**Pull request by hanxiaop**
## Description

Resolve https://github.com/istio/istio.io/issues/14329

## Reviewers

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

### CODE REVIEW

**Comment by hanxiaop** [comment]
> /test doc.test.profile-none

I think there's another PR needs to be cherry-picked, which fixed the helm script.

**Comment by hanxiaop** [comment]
Blocked by https://github.com/istio/istio.io/pull/14331.

**Review by kfaseela — APPROVED** [review]

**Pull request merged**
