### PR TITLE
zh: docs/tasks/traffic-management/ingress/ingress-sidecar-tls-termination

### PR DESCRIPTION
**Pull request by rootsongjc**
- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by windsonsea — COMMENTED** [review]
Overall LGTM. Some tips:
- 您
- Ingress Gateway 和 Sidecar 不译时保持一致，首字母大写
- 一些 namespace 的名称保持不译

**Comment by windsonsea** [comment]
还漏了几个没改 😄

**Comment by rootsongjc** [comment]
> 还漏了几个没改 😄

已完成

**Review by windsonsea — APPROVED** [review]

**Review by kfaseela — APPROVED** [review]

**Review by Xunzhuo — APPROVED** [review]

**Comment by kfaseela** [comment]
This test seems to be failing too often now! Need to fix

**Pull request merged**
