### PR TITLE
Extend doc test timeout from 60 minutes to 75 minutes.

### PR DESCRIPTION
**Pull request by ericvn**
Please provide a description for what this PR is for.

Just a PR to see if extending the timeout may help with some of the profile_default test failures. Looking at the logs, it seems that the tests are hanging so this isn't necessarily a good thing as we'll just end up waiting longer for it to fail. That's why this is a DNM.

### CODE REVIEW

**Comment by ericvn** [comment]
/test doc.test.profile_default

try again

**Comment by frankbu** [comment]
As I mentioned in the issue comment, I once tried bumping the timeout to 2 hours and it still failed, so it seems like somehow it gets into a deadlock state?

**Comment by ericvn** [comment]
Agree Frank. In this case I think the networking fails to install correctly and the traffic just doesn't flow.

**Pull request closed without merging**
