### PR TITLE
adds tetrate istio fundamentals course to training page

### PR DESCRIPTION
**Pull request by eitansuez**
## Description

Adds Tetrate Istio Fundamentals course to training page.

## Reviewers

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

### CODE REVIEW

**Review by kfaseela — APPROVED** [review]

**Comment by eitansuez** [comment]
Thank you for merging @kfaseela .  Would it be possible to also cherry-pick into the current 1.22 release?  Thanks in advance.

**Pull request merged**
