### PR TITLE
zh:remove outdated files in docs/concepts

### PR DESCRIPTION
**Pull request by jzhupup**
Removed one outdated zh files to sync with the en version:
```
content/zh/docs/concepts/what-is-istio/index.md
```

- [ ] Configuration Infrastructure
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by windsonsea** [comment]
The en version has redirected this page to: https://istio.io/latest/about/service-mesh/

In my opinion, we can sync and remove this page too since we also have the same `about` page now: https://istio.io/latest/zh/about/service-mesh/

**Review by ericvn — APPROVED** [review]
Agree this page can be removed as it has been replaced. As this PR doesn't have translation to review, I will approve.

**Pull request merged**
