### PR TITLE
(#6837) remove istio.io test for enabling/disabling policy enforcement

### LINKED ISSUE #6837: Remove policies istio.io test as it is deprecated
In Istio 1.6, https://preliminary.istio.io/docs/tasks/policy-enforcement/enabling-policy/ is marked as deprecated as Mixer is gone. So we should remove corresponding test in **tests/policies** .

### PR DESCRIPTION
**Pull request by su225**
Fixes #6837

### CODE REVIEW

**Comment by frankbu** [comment]
@su225 please resolve the conflict with main_test.go

**Comment by su225** [comment]
@frankbu - Done. Rebased, resolved conflicts and pushed changes.

**Pull request merged**
