### PR TITLE
Fix gtw wait in util functions

### PR DESCRIPTION
**Pull request by frankbu**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by ericvn** [comment]
I did try this change locally against the latest istio commit and it still fails. That said, I believe this change is need to go along with the PR from last week with the status updates.

**Review by ericvn — APPROVED** [review]

**Comment by danehans** [comment]
@ericvn @frankbu the issue appears to be related to Gateway status checking ([xref](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio.io/12940/doc.test.profile_none_istio.io/1639810553960468480/artifacts/tests-setup-profile-none-f6de60/TestDocs/ops/ambient/getting-started/test.sh/test.sh/_test_context/test.sh_debug.txt)). I'm testing a fix locally and will push a PR shortly.

**Comment by ericvn** [comment]
I was testing ` ... make doc.test.profile_demo TEST=examples/bookinfo/gtwapi_test.sh`

**Comment by danehans** [comment]
@ericvn I have tests passing locally for that PR (https://github.com/istio/istio.io/pull/12932) when I pass in `ISTIO_SHA=3d9647d33f84`. I will break out the changes from that PR that are needed to get CI fixed due to Gateway status changes.

**Pull request merged**
