### PR TITLE
Small improvements to egress gateway doc

### PR DESCRIPTION
**Pull request by frankbu**
## Description

Depends on https://github.com/istio/istio/pull/48865. Doc test will fail until latest istio build pull for doc testing.

## Reviewers

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

### CODE REVIEW

**Review by dhawton — APPROVED** [review]
contents lgtm, and looks like the dependency PR merged

**Comment by frankbu** [comment]
> contents lgtm, and looks like the dependency PR merged

Yep, just need a `/retest` on Monday, after the weekend doc-testing istio update merges. Thanks.

**Comment by dhawton** [comment]
Looks like the test is still failing.. from artifacts:

```
VERIFY FAILED snip_egress_gateway_for_https_traffic_8 (timeout after 120s):
received:
"2024-01-25T02:14:05.175158Z	info	cache	Root cert has changed, start rotating root cert
2024-01-25T02:14:05.175176Z	info	ads	XDS: Incremental Pushing ConnectedEndpoints:2 Version:
2024-01-25T02:14:05.175225Z	info	cache	returned workload trust anchor from cache	ttl=23h59m59.824776881s
2024-01-25T02:14:05.175281Z	info	cache	returned workload trust anchor from cache	ttl=23h59m59.824719781s
2024-01-25T02:14:05.175652Z	info	ads	SDS: PUSH request for node:cnn-egress-gateway-istio-574dd66f7f-psqjx.default resources:1 size:1.1kB resource:ROOTCA
2024-01-25T02:14:05.175653Z	info	cache	returned workload certificate from cache	ttl=23h59m59.824368761s
2024-01-25T02:14:05.175703Z	info	cache	returned workload trust anchor from cache	ttl=23h59m59.824297521s
2024-01-25T02:14:05.175942Z	info	ads	SDS: PUSH request for node:cnn-egress-gateway-istio-574dd66f7f-psqjx.default resources:1 size:4.0kB resource:default
2024-01-25T02:14:06.787610Z	info	Readiness succeeded in 1.758788704s
2024-01-25T02:14:06.787978Z	info	Envoy proxy is ready"
expected:
"outbound|443||edition.cnn.com"
```

**Pull request merged**
