### PR TITLE
fix typo in the pilot-agent page

### PR DESCRIPTION
**Pull request by JinVei**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by kfaseela — APPROVED** [review]
/ok-to-test

**Comment by ericvn** [comment]
Note that this change will be reverted in a day since the change is made upstream and copied here. You likely need to make the change in the command text.

**Comment by ericvn** [comment]
The change should be made here: [                "The minimum duration for which agent waits before it checks for active connections and terminates proxy"+
                        "when number of active connections become zero").Get()](https://github.com/istio/istio/blob/master/pilot/cmd/pilot-agent/options/options.go#L153-L154)

**Comment by kfaseela** [comment]
Thanks @ericvn for pointing this out. @JinVei could you please push the right PR in istio repo?

**Comment by JinVei** [comment]
> The change should be made here: [ "The minimum duration for which agent waits before it checks for active connections and terminates proxy"+ "when number of active connections become zero").Get()](https://github.com/istio/istio/blob/master/pilot/cmd/pilot-agent/options/options.go#L153-L154)
> 
> Line 153 needs a space between proxy and double-quote.

Thx, I will push a PR to this repo later.

**Pull request merged**
