### PR TITLE
zh: Update Chinese contents

### PR DESCRIPTION
**Pull request by rootsongjc**
Update <tip>, <idea> and <warning> tags in Chinese contents https://github.com/istio/istio.io/issues/3228
@geeknoid Some files have problems, can you figure out why the lint failed in those files?

### CODE REVIEW

**Comment by geeknoid** [comment]
The lint errors in the faq section are due to use of `>` in some of the individual faq pages. For example, content_zh/help/faq/mixer/writing-custom-adapters.md has that in it.

Note that at this point, you can't turn on the lint rule fully since there are still a few legitimate uses of blockquotes in the English content which I need to find a way to hide from the lint check. I'm probably just going to introduce {{< quote >}} as an annotation for this purpose.

**Comment by geeknoid** [comment]
I added support for {{< quote >}} and fixed the few remaining English warnings for the new lint rule. If you sync, you should be able to fix all the Chinese warnings and enable the lint rule for everyone.

**Comment by rootsongjc** [comment]
@geeknoid #3228 fixed

**Comment by rootsongjc** [comment]
@geeknoid Could you merge this PR?

**Comment by rootsongjc** [comment]
@geeknoid Rebased, it's ok to merge.

**Pull request merged**
