### PR TITLE
Fixed a grammatical error in a sentence.

### PR DESCRIPTION
**Pull request by dharmkumar1**
Fixed a grammatical error in a sentence.

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by frankbu** [comment]
@dharmkumar1 You need to sign the CLA before we can merge your fix. Thanks.
https://github.com/istio/istio.io/pull/7980#issuecomment-676559707

**Comment by dharmkumar1** [comment]
@googlebot I signed it!

**Comment by dharmkumar1** [comment]
> @dharmkumar1 You need to sign the CLA before we can merge your fix. Thanks.
> [#7980 (comment)](https://github.com/istio/istio.io/pull/7980#issuecomment-676559707)

Hi Frankbu,

I have signed the CLA.

Br,
Dharam

**Comment by frankbu** [comment]
Good catch (/cherrypick) @ericvn

**Pull request merged**
