### PR TITLE
Added one FAQ - describes that ztunnel is not a SPOF.

### LINKED ISSUE #15246: Add ambient mode section to FAQ
start with "Is ztunnel a SPOF?" - content from https://blog.howardjohn.info/posts/ambient-spof/

### PR DESCRIPTION
**Pull request by ayushrakesh**
## Description

Clears misconception that ztunnel is not a Single Point of Failure.

#Resolves #15246 
 
## Reviewers

- [ ] Ambient
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

### CODE REVIEW

**Comment by ayushrakesh** [comment]
@kfaseela @craigbox Please review it.

**Comment by kfaseela** [comment]
Please fix the lint failure.

**Comment by kfaseela** [comment]
@ayushrakesh you have to fix the lint failure in your document. The error can be seen at https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/15305/lint_istio.io/1803333939767545856 , closing the PR and raising a new one will not fix the error

**Comment by ayushrakesh** [comment]
@kfaseela Yes , I am fixing it.

**Comment by kfaseela** [comment]
you need not close the PR, you can raise a new revision of the PR after fixing

**Comment by ayushrakesh** [comment]
@kfaseela I have raised a new PR.

**Comment by kfaseela** [comment]
> @kfaseela I have raised a new PR.

what is the need for raising new PR everytime? why can't you revise existing PR?

**Pull request closed without merging**
