### PR TITLE
zh-translation:content/zh/faq/general/what-deployment-environment.md

### PR DESCRIPTION
**Pull request by romainshen**
ref: https://github.com/servicemesher/istio-official-translation/issues/1405

### CODE REVIEW

**Comment by romainshen** [comment]
@googlebot I signed it!

**Comment by tanjunchen** [comment]
image

Fix Line 6 According to en/ original file format

**Comment by tanjunchen** [comment]
content/zh/boilerplates/trace-generation.md  这个文件已经被翻译 建议删除

**Comment by tanjunchen** [comment]
@romainshen 另一个目前没有被翻译 可以保留

**Comment by tanjunchen** [comment]
@romainshen  We will close the pr in two days later. Thanks your jobs!

**Comment by tanjunchen** [comment]
@romainshen   Thanks your jobs!  The file have been translated , so close this pr.
@rootsongjc

**Pull request closed without merging**
