### PR TITLE
Fixing typo in fortio command

### PR DESCRIPTION
**Pull request by rewanth1997**
**Description**
Fixing a typo error in fortio command in circuit breaking

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by frankbu** [comment]
@rewanth1997 Please sign the CLA, so we can merge your fix. Thanks.
https://github.com/istio/istio.io/pull/7463#issuecomment-638428784

**Comment by rewanth1997** [comment]
@googlebot I signed it!

**Comment by rewanth1997** [comment]
@frankbu CLA signing done :)

**Pull request merged**
