### PR TITLE
zh-translation:  docs/reference/glossary/service.md

### PR DESCRIPTION
**Pull request by orangegzx**
[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Review by kebe7jun — APPROVED** [review]
LGTM

**Review by ericvn — APPROVED** [review]

**Comment by kebe7jun** [comment]
@orangegzx 解决一下冲突呢。

**Comment by orangegzx** [comment]
resolved

**Pull request merged**
