### PR TITLE
Parse comments for configuration options

### PR DESCRIPTION
**Pull request by johnma14**
Read comments from the parsed values.yaml and store them in the description field.

Fixes Bug: #2566

### CODE REVIEW

**Comment by geeknoid** [comment]
There's one CI failure. It's about spaces in code blocks:

https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md038---spaces-inside-code-span-elements

**Comment by geeknoid** [comment]
Deploy preview for *preliminary-istio* processing.

Building with commit 6c1f13bf77435507aefe82c6cba5ffc2db58adfc

https://app.netlify.com/sites/preliminary-istio/deploys/5c8c193d0b49340008cfc463

**Comment by johnma14** [comment]
@geeknoid thank you for sharing the link to the preview site. I made some changes to remove the <br/> tag and remove the code block tag if the description field is empty. Thanks.

**Pull request merged**
