### PR TITLE
Add max-height and transition to resize header

### PR DESCRIPTION
**Pull request by rytswd**
Please provide a description for what this PR is for.

Related to #9569

This is a bit hacky as the existing scroll spy was only meant to update single element. With this update, the header size gets updated along with some other elements, and that makes the SCSS really scattered...

I just wanted to propose how this change improves the UX significantly with small CSS changes in a few places. A proper fix may need a bit of restructuring in SCSS.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by howardjohn** [comment]
Looks great! one small issue onthe main page only, when you scroll to top it flashes the fullsize white header for a split second before becoming blue: https://deploy-preview-9659--preliminary-istio.netlify.app/latest/

**Comment by rytswd** [comment]
Ah thanks for the catch, it looks like there is some other transition setup overriding my update, taking a look at that

**Comment by rytswd** [comment]
OK so I think I got the main page transition fixed, and the Try Istio button a bit smaller when scrolled. If I had more time I'd look more into making Istio logo several pixels lower, and fix up the Try Istio button animation (it looks like the text jumps around a bit) - but I give up on getting dot perfect... At least this looks better than before IMO 😅

**Comment by craigbox** [comment]
Lovely - we'll turn this over to our dev team to fix up!

**Comment by wbartosz** [comment]
I don't think changing the max-height of the buttons (Try Istio) is a good idea. They are concise throughout the app and then squash on the scroll. We could make the header a bit shorter but don't you think it is too tiny now?

**Comment by wbartosz** [comment]
I don't think changing the max-height of the buttons (Try Istio) is a good idea. They are concise throughout the app and then that single CTA one in the header squeezes on scroll.

We could make the header a bit shorter but don't you think it is too tiny now?

**Comment by rytswd** [comment]
@wbartosz Thanks for checking, some points are being discussed in the referenced issue (https://github.com/istio/istio.io/issues/9569), but let me answer all of them.

> I don't think changing the max-height of the buttons (Try Istio) is a good idea.

I originally kept the size of the button, but it was rather large and stood out a bit too much. I personally don't see why "Try Istio" button needs to stand out for every single page you go into, so having it smaller was one approach.

> We could make the header a bit shorter but don't you think it is too tiny now?

As I referenced in the related issue, I find the current size just about right - there are some other sites I use for reference:

- https://helm.sh/docs/ - a bit taller header, but the background texture helps make it feel the space is not wasted. Also, I find Helm is not as complicated and feature rich as Istio, so this rather larger header is OK, but with Istio with so much words throughout the site, I'd want less space wasted by the header
- https://vector.dev/ - very slim header, just enough for folks who come to check out the documentation
- https://argo-cd.readthedocs.io/en/latest/ - about the same height, slightly shorter
- https://fluxcd.io/docs/ - slightly taller
- https://tekton.dev/docs/ - slightly taller, about the same size with Flux CD
- https://grafana.com/docs/grafana/latest/dashboards/ - about the same size when scrolled down to the main content

I think this is about the right size, could be made slightly taller or shorter, but never as big as what we have in the preliminary doc right now. It is about making header easily accessible, but do not disturb users when they are scrolling down and going through the content.

> There's also a scrollbar within the header in mobile view once you start scrolling.

Ah I didn't notice this one, we can put overflow control for that.

**Comment by craigbox** [comment]
@wbartosz has implemented much of the new design.  I asked him to take a go at this based on your work - he has submitted #9687 - [PTAL at the render](https://deploy-preview-9687--preliminary-istio.netlify.app/latest/docs/).

It's taller than yours, but smaller than most others, which gives the "Try Istio" button room to breathe and lets it still be a viable tap target on mobile.  I think it's a good compromise and it's getting good play in #docs on Slack too.

Let me know your thoughts?

**Comment by rytswd** [comment]
Thanks @craigbox , the new PR looks perfectly reasonable, and much better in terms of code / style management. I'm closing this PR in favour of #9687.

**Pull request closed without merging**
