### PR TITLE
add proxy repo to scrap docs from

### PR DESCRIPTION
**Pull request by richardwxn**
related: https://github.com/istio/proxy/pull/2803

/cc @mandarjog @kyessenov @jasonwzm

### CODE REVIEW

**Comment by ericvn** [comment]
If you run this command, does it pull in more docs? I would assume so. Would you add them here.

**Comment by richardwxn** [comment]
@ericvn Yep I just added those docs, however shouldn't those be added by automator job?

**Comment by ericvn** [comment]
@richardwxn They will get picked up, but would never merge until the lint errors are fixed.

**Pull request merged**
