### PR TITLE
Update istio.io test reference to 1.17.0-beta.2

### PR DESCRIPTION
**Pull request by ericvn**
Please provide a description for what this PR is for.

New beta build

### CODE REVIEW

**Comment by ericvn** [comment]
Request routing has failed twice.

**Comment by ericvn** [comment]
Seems after 3 failures that the tasks/traffic-management/request-routing/gtwapi_test.sh/gtwapi_test.sh  test does have an issue. Needs some more investigation.

**Review by frankbu — APPROVED** [review]

**Pull request merged**
