### PR TITLE
zh:sync docs/setup/platform-setup/alicloud/index.md

### PR DESCRIPTION
**Pull request by windsonsea**
Fix links and resync the text between `{{< tip >}}` and `{{< /tip >}}`.

Preview: https://deploy-preview-11482--preliminary-istio.netlify.app/latest/zh/docs/setup/platform-setup/alicloud

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by craigbox** [comment]
PR needs a rebase: removes some recent additions.

**Comment by windsonsea** [comment]
> PR needs a rebase: removes some recent additions.

The preview looks good now :)

https://deploy-preview-11482--preliminary-istio.netlify.app/latest/zh/docs/setup/platform-setup/alicloud

**Review by kebe7jun — APPROVED** [review]

**Pull request merged**
