### PR TITLE
Fix docs for installation: Istio Operator is not suggested for a production environment

### PR DESCRIPTION
**Pull request by johnzheng1975**
…ction environment

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [x] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

Fix issue: https://github.com/istio/istio.io/issues/10961

### CODE REVIEW

**Comment by johnzheng1975** [comment]
ok-to-test

**Comment by johnzheng1975** [comment]
@Monkeyanator @howardjohn , please help to review, thanks

**Comment by zirain** [comment]
@johnzheng1975 can you sync to zh doc?

**Comment by johnzheng1975** [comment]
> @johnzheng1975 can you sync to zh doc?

Sure, I will do this if this is approved

**Review by howardjohn — APPROVED** [review]

**Comment by johnzheng1975** [comment]
Fixed #10963 for zn docs, about IstioOperator is not suggested on production environment

**Review by kebe7jun — APPROVED** [review]

**Review by craigbox — APPROVED** [review]

**Comment by johnzheng1975** [comment]
Seems the fail is not related with my changes.  The error is about "tasks/traffic-management/egress"
```
        --- PASS: TestDocs/tasks/traffic-management/egress/egress-kubernetes-services/test.sh/after_snapshot (2.41s)
    --- FAIL: TestDocs/tasks/traffic-management/egress/http-proxy/test.sh (182.86s)
        --- PASS: TestDocs/tasks/traffic-management/egress/http-proxy/test.sh/before_snapshot (2.41s)
        --- FAIL: TestDocs/tasks/traffic-management/egress/http-proxy/test.sh/test.sh (134.48s)
        --- PASS: TestDocs/tasks/traffic-management/egress/http-proxy/test.sh/cleanup.sh (42.88s)
```

**Comment by johnzheng1975** [comment]
Any suggestions to pass the testing? Thanks :-)

**Pull request merged**
