### PR TITLE
Test Solo out-of-tree inpod CNI against istio.io tests

### PR DESCRIPTION
**Pull request by ericvn**
## Description

Test Solo out-of-tree inpod CNI against istio.io tests.

Pulling that commit from the maser branch since it's merged there.

### CODE REVIEW

**Comment by linsun** [comment]
Nice!  subscribe cc @bleggett

**Comment by ericvn** [comment]
Failed because the release-post-submit failed for the referenced commit. Trying to rerun that now.

**Comment by ericvn** [comment]
PR was merged in the release-1.21 branch so this weekend's update should pick it up as well.

**Comment by ericvn** [comment]
Closing as https://github.com/istio/istio.io/pull/14555 should have the same new code.

**Pull request closed without merging**
