### PR TITLE
Update kind image to 1.20.5

### LINKED ISSUE #9388: docs test: update to Kubernetes 1.20
Currently we are using k8s 1.18. We should probably be testing on the latest version, like we do in istio/istio

### PR DESCRIPTION
**Pull request by ericvn**
Fixes #9388 

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by ericvn** [comment]
Need to investigate:
```
VERIFY FAILED snip_set_up_the_remote_cluster_5 (timeout after 120s):
received:
"NAME                                   DATA   AGE
istio                                  2      2m1s
istio-ca-root-cert                     1      2m5s
istio-leader                           0      2m5s
istio-namespace-controller-election    0      2m5s
istio-sidecar-injector                 2      2m1s
istio-validation-controller-election   0      2m5s
kube-root-ca.crt                       1      2m8s"
expected:
"NAME                                   DATA   AGE
istio                                  2      2m1s
istio-ca-root-cert                     1      2m9s
istio-leader                           0      2m9s
istio-namespace-controller-election    0      2m11s
istio-sidecar-injector                 2      2m1s
istio-validation-controller-election   0      2m6s"
```

**Comment by ericvn** [comment]
Not sure if this is related to the 1.20.2 or not. It would be flaky as the prior run got past this.
```
+ echo 'Could not setup KinD environment. Something wrong with KinD setup. Exporting logs.'
Could not setup KinD environment. Something wrong with KinD setup. Exporting logs.
```

**Review by frankbu — APPROVED** [review]

**Pull request merged**
