### PR TITLE
docs: fix 404 link in content/zh/get-involved/_index.md

### PR DESCRIPTION
**Pull request by foolwc**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by Xunzhuo** [comment]
cc @rootsongjc , do we need to update ServiceMesher to Cloud Native Community in China?

**Review by Xunzhuo — COMMENTED** [review]
cc @rootsongjc

**Comment by rootsongjc** [comment]
> cc @rootsongjc, do we need to update ServiceMesher to Cloud Native Community in China?

Yes, I think so. Please go ahead to update that link and text.

**Review by Xunzhuo — APPROVED** [review]

**Review by rootsongjc — APPROVED** [review]
/lgtm

**Pull request merged**
