### PR TITLE
Wrong defaults for Destination Rule

### LINKED ISSUE #13491: Wrong defaults for Destination Rule
I'm convinced that described [here](https://istio.io/latest/docs/reference/config/networking/destination-rule/#ConnectionPoolSettings-HTTPSettings) defaults for ConnectionPoolSettings.HTTPSettings are wrong. 
I've done some testing, and based on the values in the envoy stats, the limits for **http1MaxPendingRequests** and **http2MaxRequests** don't apply unless explicitly set.
As far as I can see they were removed in this pr: https://github.com/istio/istio/pull/17346

### PR DESCRIPTION
**Pull request by FVarya**
Resolve #13491 

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by windsonsea** [comment]
/ok-to-test

Hi @FVarya,  you need to sign the cla before reviewing process.

**Review by ericvn — CHANGES_REQUESTED** [review]
Note the top of the file:
```
WARNING: THIS IS AN AUTO-GENERATED FILE, DO NOT EDIT. PLEASE MODIFY THE ORIGINAL SOURCE IN THE 'https://github.com/istio/api' REPO
source_repo: https://github.com/istio/api
```
As noted the change needs to be made in a file in the istio/api repo and will then move here as part of the reference docs update job.

**Comment by FVarya** [comment]
@ericvn 
Thanks, completely overlooked
Should I open a new issue there? Or can I create a new pr there linked to the issue here?

**Comment by ericvn** [comment]
You can make the changes there and refer back to the issue here.

**Pull request closed without merging**
