### PR TITLE
Remove docs on removed PILOT_ENABLE_CONFIG_DISTRIBUTION_TRACKING feature

### PR DESCRIPTION
**Pull request by howardjohn**

### CODE REVIEW

**Comment by dhawton** [comment]
Note: This is already in #15443

**Comment by craigbox** [comment]
I only pulled out the link to the page that I removed - there is more in this PR that we need to keep.

**Comment by dhawton** [comment]
> I only pulled out the link to the page that I removed - there is more in this PR that we need to keep.

I updated the rest of the markdown.. the other bits got removed with the make update_ref_docs.

**Comment by craigbox** [comment]
Can we close this then @dhawton?

**Pull request closed without merging**
