### PR TITLE
shouldn't this be istioctl, not kubectl ?

### PR DESCRIPTION
**Pull request by gbucknel**
This looked like a typo to me ? Not 100% sure though .

### CODE REVIEW

**Comment by rokrokss** [comment]
It's kubectl.
`istioctl manifest generate ~` generates manifest.yaml from the overlay values(like vaules.yaml in helm) that can be applied by kubectl.
`istioctl manifest apply ~` applies with the overlay values, skipping above step.

**Comment by ericvn** [comment]
Agree it's `kubectl`. `istio manifest apply` is basically `istioctl manifest generate ~ | kubectl apply -f -`, the inverse of the longer line to delete the configuration.

**Comment by frankbu** [comment]
Closing because it's correct as is. The yaml file for the `-f` option in `istioctl manifest apply` would be an `IstioOperator` configuration, but in this case it contains a generated kubernetes configuration, therefore the required command is `kubectl apply -f`.

**Comment by gbucknel** [comment]
Cool - thanks, sorry for the hassle. I tried the kubectl command and it didn't work, so assumed it was wrong.

**Pull request closed without merging**
