### PR TITLE
zh: /docs/setup/kubernetes/additional-setup/config-profiles/index.md

### PR DESCRIPTION
**Pull request by fleeto**

### CODE REVIEW

**Comment by fleeto** [comment]
Hi @geeknoid , I don't know how to fix it. any suggestion?
~~~
- ./public/zh/docs/setup/kubernetes/additional-setup/config-profiles/index.html
  *  External link https://github.com/istio/istio.io/edit/release-1.1/content_zh/docs/setup/kubernetes/additional-setup/config-profiles/index.md failed: 404 No error
h
~~~

**Comment by geeknoid** [comment]
Oh, it's a chicken-and-egg problem.

Go in scripts/lint_site.sh, in the htmlproofer line towards the bottom, and where it says  .../github.com/istio/istio.io/edit/master, remove the "master" part and that'll fix it.

**Comment by fleeto** [comment]
@geeknoid It works, now I think its needs your approval.

**Pull request merged**
