### PR TITLE
zh: sync /about/feature-stages/

### PR DESCRIPTION
**Pull request by fleeto**

### CODE REVIEW

**Comment by fleeto** [comment]
/assign @geeknoid 
Hi  @geeknoid , What's wrong with CircleCI ?

**Comment by geeknoid** [comment]
Uh ho. 

Could you change the version field in .circleci/config.yml from 2.1 back to 2.0. That'll probably fix it.

**Comment by fleeto** [comment]
@geeknoid  thx, it works.

I'd modified `content/docs/setup/kubernetes/platform-setup/aws/index.md`, it needs your approval.

**Comment by fleeto** [comment]
Problems of `.circleci/config.yml` and `platform-setup/aws/index.md`  are blocking all CI process?

**Pull request merged**
