### PR TITLE
Create 404.html

### PR DESCRIPTION
**Pull request by adityakumar48**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by frankbu** [comment]
@adityakumar48 Can you explain why this is needed? Where would it be used?

**Comment by adityakumar48** [comment]
> @adityakumar48 Can you explain why this is needed? Where would it be used?

Dear Sir, because If any one mistake to go your wrong site  to  go and show to error 404 this page is not found then they to know its wrong then they are write our correct address

**Comment by frankbu** [comment]
@adityakumar48 But isn't this already handled? For example, if I access a missing page in my browser: https://preliminary.istio.io/latest/docs/setup/getting-startd/, it displays a nice html page with message `We're sorry, the page you requested cannot be found`

**Comment by adityakumar48** [comment]
> @adityakumar48 But isn't this already handled? For example, if I access a missing page in my browser: https://preliminary.istio.io/latest/docs/setup/getting-startd/, it displays a nice html page with message `We're sorry, the page you requested cannot be found`

Ok Sir

**Comment by ericvn** [comment]
Marking as spam from Hacktoberfest and closing.

**Pull request closed without merging**
