### PR TITLE
Bump master to next version

### PR DESCRIPTION
**Pull request by howardjohn**
Move https://github.com/istio/istio.io/pull/15555 to my fork

### CODE REVIEW

**Comment by craigbox** [comment]
needs update to https://istio.io/latest/blog/2019/introducing-istio-operator/ (if not more things that refer to the install doc for the operator)

It might be best to leave those files in and we can address them in a follow up PR?

**Comment by craigbox** [comment]
sigh, I was only being silly.

/retest
for realsies.

**Comment by craigbox** [comment]
[default](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/15595/doc.test.profile-default_istio.io/1826903235646984192): gateway API failure due to [this](https://istio.io/latest/news/releases/1.21.x/announcing-1.21/upgrade-notes/#gateway-name-label-modified)

**Comment by kfaseela** [comment]
is this already sorted out? Or any help needed?

**Comment by howardjohn** [comment]
There was some discussion on #docs. its not sorted out

**Comment by craigbox** [comment]
I've [identified the things](https://github.com/istio/istio.io/pull/15595#issuecomment-2306830897) that I think are causing the flakes, and would love to have someone take a look at trying to fix them.

Some that are in separate issues already:

* https://github.com/istio/istio.io/issues/15505
* https://github.com/istio/istio.io/issues/15603
* https://github.com/istio/istio/issues/36905

**Comment by kfaseela** [comment]
@nshankar13 : any idea about the multi-cluster failures?

**Comment by kfaseela** [comment]
@howardjohn @craigbox I was finally able to run this test locally, and want to ask you if you can review the below Pr and get it merged, so that we can rerun the multicluster test.. There are certain tests that have got mixed, and some steps which are supposed to be run only in non gateway api cases seem to be running in gateway api test as well. So may be we can fix that first and then would like to rerun this.

https://github.com/istio/istio.io/pull/15662

**Comment by craigbox** [comment]
Done

**Comment by kfaseela** [comment]
while the gwapi test passed this time, the webhook deletion failure is still there. let me debug that now

**Comment by craigbox** [comment]
> while the gwapi test passed this time, the webhook deletion failure is still there. let me debug that now

That's a "known issue" in istioctl. We can work around it in the tests at least

**Comment by kfaseela** [comment]
> > while the gwapi test passed this time, the webhook deletion failure is still there. let me debug that now
> 
> That's a "known issue" in istioctl. We can work around it in the tests at least

Do we have an issue raised for that already? is this applicable only on master? Coz the test passes on older versions

**Comment by craigbox** [comment]
istio/istio#36905

**Comment by kfaseela** [comment]
> [istio/istio#36905](https://github.com/istio/istio/issues/36905)

That is a very old issue, and if you see, this test passed on my gwapi PR without any issues. Doesn't that mean the cleanup problem is happening only on master?

**Comment by kfaseela** [comment]
cc @zirain , any pointers on the distributed tracing failure? https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/15595/doc.test.profile-none_istio.io/1832017004517658624

**Comment by craigbox** [comment]
Pass, I never saw any suggestion it was fixed: changed and the behaviour is
consistent. Didn't do any more research sorry.

**Comment by kfaseela** [comment]
> Pass, I never saw any suggestion it was fixed: changed and the behaviour is consistent. Didn't do any more research sorry.

The only webhook that if failed to cleanup is 

      "mutatingWebhookConfigurations": [
        "istio-revision-tag-default"
      ],

and this seems to be not deleted on the remote cluster, where the command used to delete is

`$ istioctl manifest generate -f remote-config-cluster.yaml --set values.defaultRevision=default | kubectl delete --context="${CTX_REMOTE_CLUSTER}" -f -`

**Comment by kfaseela** [comment]
Currently there is a failure at the helm install step. not sure why the test is doing istioctl for ingress and helm for egress. While both should work, let us first see if istioctl works.

```
helm install --set global.tag=1.24-alpha.89d73dc1f639d1625135923c381e4ec222247059 istio-egressgateway manifests/charts/gateway -n external-istiod --kube-context=kind-doc-cluster3 --set service.type=ClusterIP
kubectl get pod -l app=istio-egressgateway -n external-istiod --context=kind-doc-cluster3 -o 'jsonpath={.items[*].status.phase}'
```

**Comment by mikemorris** [comment]
It looks like the telemetry test is just timing out, haven't looked closer into exactly where/why that's stalling...
```
panic: test timed out after 1h0m0s
	running tests:
		TestDocs (1h0m0s)
		TestDocs/tasks/observability/distributed-tracing/skywalking/test.sh (32m27s)
		TestDocs/tasks/observability/distributed-tracing/skywalking/test.sh/test.sh (32m27s) 
```

**Comment by dhawton** [comment]
> It looks like the telemetry test is just timing out, haven't looked closer into exactly where/why that's stalling...
> 
> ```
> panic: test timed out after 1h0m0s
> 	running tests:
> 		TestDocs (1h0m0s)
> 		TestDocs/tasks/observability/distributed-tracing/skywalking/test.sh (32m27s)
> 		TestDocs/tasks/observability/distributed-tracing/skywalking/test.sh/test.sh (32m27s) 
> ```
> 
> Maybe #15515 broke something where it's waiting for an older version of a resource that will never be created now, or did that not get backported to release/1.23 but should have been?

That is in the master branch already.

**Comment by kfaseela** [comment]
Able to reproduce the external controlplane issue locally, looks like there is some issue on 1.24 with external namespace usage for installation of istio components. Will debug further and post updates

**Comment by kfaseela** [comment]
> Able to reproduce the external controlplane issue locally, looks like there is some issue on 1.24 with external namespace usage for installation of istio components. Will debug further and post updates

https://github.com/istio/istio/pull/53073 hopefully should fix the external controlplane problem

**Comment by kfaseela** [comment]
The external control plane test is fixed, now what is left is the cleanup.. Pushed a fix for it, let us see how it goes

**Comment by dhawton** [comment]
/test doc.test.profile-default

This looks like a flake?

**Comment by kfaseela** [comment]
I am not able to debug further on the skywalking test failure, if there are no other pointers, may be we can disable the test so that atleast this PR can move forward. The failing test can be debugged in a fresh new PR?

**Comment by dhawton** [comment]
> I am not able to debug further on the skywalking test failure, if there are no other pointers, may be we can disable the test so that atleast this PR can move forward. The failing test can be debugged in a fresh new PR?

I'm ok with that. I haven't had much luck and lack cycles for it.

**Comment by kfaseela** [comment]
I have raised an issue for skywalking test failure, and disabled the test on this PR, as this is blocking many things now! https://github.com/istio/istio.io/issues/15680

**Review by zirain — APPROVED** [review]

**Comment by kfaseela** [comment]
The new failure is on spire integration test.

```

Error: generate config: helm render: render chart: template: base/templates/services.yaml:1:14: executing "base/templates/services.yaml" at <.Values.global.remotePilotAddress>: nil pointer evaluating interface {}.remotePilotAddress
```

**Comment by kfaseela** [comment]
Have fixed the multiple controlplane and spire failures, hopefully this passes all tests atleast this time :(

**Review by kfaseela — APPROVED** [review]

**Pull request merged**
