### PR TITLE
zh-translation: initialize the translation content

### PR DESCRIPTION
**Pull request by rootsongjc**
- Restart the Chinese translation process, refer to https://github.com/istio/istio.io/issues/5250 @geeknoid 
- Translation progress is tracked on https://github.com/servicemesher/istio-official-translation

### CODE REVIEW

**Comment by rootsongjc** [comment]
Build failed with these errors: 

- ./public/zh/blog/2018/delayering-istio/index.html
  *  External link https://www.oreilly.com/ideas/the-unwelcome-guest-why-vms-arent-the-solution-for-next-gen-applications failed: 404 No error
- ./public/zh/news/2019/announcing-1.3.1/index.html
  *  External link https://istio.io/zh/docs failed: 404 No error

Because of https://istio.io/zh is disabled.

**Comment by geeknoid** [comment]
You also need to reenable linting of the Chinese content. That's done in scripts/lint_site.sh. Right now, it is calling check_content on content/en, you need to readd a call to check content/zh too.

**Comment by rootsongjc** [comment]
@geeknoid I have re-enabled it but only check the English words now because I have replaced `content/zh` with English docs.

**Comment by rootsongjc** [comment]
As https://istio.io/zh is not available now, all the docs with `{{< relnote >}}` shortcode will fail when linting. because of `layouts/shortcodes/relnote.html` L144 is hard coded with `istio.io`. @geeknoid

**Comment by rootsongjc** [comment]
Linting failed.

- ./public/zh/news/2019/announcing-1.4/index.html
  *  External link https://istio.io/zh/docs failed: 404 No error
htmlproofer 3.12.0 | Error:  HTML-Proofer found 1 failure!
LINTING FAILED
Makefile.core.mk:27: recipe for target 'lint' failed
make: *** [lint] Error 1

**Pull request merged**
