### PR TITLE
Add ratelimit  redis service/deployment

### PR DESCRIPTION
**Pull request by johnzheng1975**
ratelimit service/deployment and redis service/deployment is necessary for this example.
However, this is not provided.
I tried and test pass, for new changes.

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by ericvn** [comment]
@istio/wg-policies-and-telemetry-maintainers Please take a look.

**Comment by ericvn** [comment]
@johnzheng1975 In most instances, one would create the PR against the `master/main` branch and we would cherry-pick the change to the `release-1.9` branch. Maybe you used the edit option from the `istio.io` website.

There are a number of lint issues that do need to be fixed that can be found by clicking on the `Details` link on the failing lint test. You may want to retarget the change to the main branch when making these changes.

**Review by bianpengyuan — COMMENTED** [review]
I think it makes sense to *not* include the whole rate limit service in the doc here, as it implies that the rate limit service is maintained by Istio community which is actually not.

As an alternative, I would suggest
1) put this under https://github.com/istio/istio/tree/master/samples, point rate limit integration test to the sample file instead of [this test data file](https://github.com/istio/istio/blob/master/tests/integration/telemetry/policy/testdata/ratelimitservice.yaml).
2) In the doc here, we mention it clearly that you need to deploy a rate limit service for global rate limit, and you can use the demo rate limit service yaml at istio sample folder as a reference.

**Comment by johnzheng1975** [comment]
> @johnzheng1975 In most instances, one would create the PR against the `master/main` branch and we would cherry-pick the change to the `release-1.9` branch. Maybe you used the edit option from the `istio.io` website.
JohnZheng1975:  Thanks for reminder.  Next time I will create PR against the `master/main` branch.

> There are a number of lint issues that do need to be fixed that can be found by clicking on the `Details` link on the failing lint test. You may want to retarget the change to the main branch when making these changes.
JohnZheng1975:  I viewed the `Details`, seems the failing lint is not related with my changes. Just wondering this is a defect of checking system?

**Comment by johnzheng1975** [comment]
@bianpengyuan, per your suggestion, I already created a PR https://github.com/istio/istio/pull/31333
Put ratelimit deploy/service in samples.
Please help to review. Thanks.

**Comment by ericvn** [comment]
You can look at the `Details` of the failing lint job, and look at the Raw build.log txt to identify what is failing. In this case:
```
>> 642 files are free from spelling errors
./en/docs/tasks/policy-enforcement/rate-limit/index.md:64: MD009 Trailing spaces
./en/docs/tasks/policy-enforcement/rate-limit/index.md:66: MD009 Trailing spaces
./en/docs/tasks/policy-enforcement/rate-limit/index.md:66: MD010 Hard tabs
./en/docs/tasks/policy-enforcement/rate-limit/index.md:63: MD031 Fenced code blocks should be surrounded by blank lines
./en/docs/tasks/policy-enforcement/rate-limit/index.md:67: MD031 Fenced code blocks should be surrounded by blank lines
```

**Comment by johnzheng1975** [comment]
Close this.
Try another PR on master, only apply rate-limit-service.yaml from samples, when you try rate-limit task

**Pull request closed without merging**
