### PR TITLE
Remove option 2 no auth profile anymore.

### PR DESCRIPTION
**Pull request by incfly**

### CODE REVIEW

**Comment by incfly** [comment]
@istio/wg-environments-maintainers fyi. this is a leftover from the clean up of the old installation.

**Comment by incfly** [comment]
aha, i didn't realize i'm editing chinese version, which is not my intention... will update to refer to the english version.

**Comment by rootsongjc** [comment]
@incfly Can you update this PR?

**Comment by tanjunchen** [comment]
please fix conclicts.Thanks

**Comment by tanjunchen** [comment]
@rootsongjc  这个英文原文与中文都变了  目录都变了 所以应当关闭它

**Pull request closed without merging**
