### PR TITLE
fix istio install command.

### PR DESCRIPTION
**Pull request by woyaodeyangguang**
Please provide a description for what this PR is for.
The istio install command in the doc is error. Then fix it.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by zirain — APPROVED** [review]

**Comment by zirain** [comment]
/ok-to-test

need run `make gen` locally

BTW, can you fix the zh-cn doc

**Comment by kfaseela** [comment]
ideally you should raise the PR on master first, and then we cherry-pick to required branches.

**Review by ericvn — APPROVED** [review]

**Comment by ericvn** [comment]
@woyaodeyangguang You need to run `make gen` or at least `make scripts` to generate new scripts which will contain this change and merge that change here as well.

**Comment by hzxuzhonghu** [comment]
+1 Should on master first and then backport

**Comment by zirain** [comment]
this's fixed by https://github.com/istio/istio.io/pull/12651 in master branch
after v1.17 released, closed this.

**Pull request closed without merging**
