### PR TITLE
[release-1.20] Update to use 1.20.2 for testing

### PR DESCRIPTION
**Pull request by ericvn**
Update to use 1.20.2 for testing

### CODE REVIEW

**Comment by ericvn** [comment]
Looks like the same test, tasks/security/authorization/authz-ingress/test.sh, failed both times. Investigating more.

**Comment by ericvn** [comment]
Test has:
```
172.18.0.1
authorizationpolicy.security.istio.io/ingress-policy configured
Error: timeout expired before resource security.istio.io/v1beta1/AuthorizationPolicy/istio-system/ingress-policy became effective on all sidecars
Failed distribution of authorizationpolicy ingress-policy in namespace istio-system
NAME                                                    CLUSTER        CDS        LDS        EDS        RDS          ECDS         ISTIOD                      VERSION
httpbin-86869bccff-kwgtn.foo                            Kubernetes     SYNCED     SYNCED     SYNCED     SYNCED       NOT SENT     istiod-59bc44df9d-zmcf6     1.20-alpha.5f5d657c72d30a97cae97938de3a6831583e9f15
istio-eastwestgateway-7dd5466467-nr2ds.istio-system     Kubernetes     SYNCED     SYNCED     SYNCED     NOT SENT     NOT SENT     istiod-59bc44df9d-zmcf6     1.20-alpha.5f5d657c72d30a97cae97938de3a6831583e9f15
istio-egressgateway-56f7684d68-ssr9x.istio-system       Kubernetes     SYNCED     SYNCED     SYNCED     NOT SENT     NOT SENT     istiod-59bc44df9d-zmcf6     1.20-alpha.5f5d657c72d30a97cae97938de3a6831583e9f15
istio-ingressgateway-54df49f4cf-psn2v.istio-system      Kubernetes     SYNCED     SYNCED     SYNCED     SYNCED       NOT SENT     istiod-59bc44df9d-zmcf6     1.20-alpha.5f5d657c72d30a97cae97938de3a6831583e9f15
TEST: wait for failed, but continuing.
Duration: 10 seconds
```
which wasn't seen in a prior passing run.

**Comment by ericvn** [comment]
Must be flakey since it passed after several tries. Noting that the test runs fine locally on master, and using the 1.20.1 and 1.20.2 commits (not I only ran a few times on each).

**Comment by hanxiaop** [comment]
@kfaseela Do you know if this PR and https://github.com/istio/istio.io/pull/14424 can be merged or should we wait for @ericvn? Otherwise https://github.com/istio/istio.io/pull/14456 won't pass due to the version issue.

**Comment by kfaseela** [comment]
There is a dnm on the other PR

**Comment by hanxiaop** [comment]
> There is a dnm on the other PR

It seems like everything is good to go, but it may be better to wait for @ericvn to ensure there are no more commits.

**Review by kfaseela — APPROVED** [review]

**Pull request merged**
