### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by BigPapaChas**
Please provide a description for what this PR is for.

Fix typo in Istio Gateway documentation.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [ X ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by ericvn — APPROVED** [review]

**Comment by frankbu** [comment]
This is generated doc, it needs to be fixed in the istio/api repo, not here.

**Comment by BigPapaChas** [comment]
Thanks!

**Comment by ericvn** [comment]
Good catch @frankbu

**Comment by ericvn** [comment]
Note that it will need to be updated in the istio/api main branch, the release-1.15 brach (updates preliminaryistio.io) and the 1.14 branch (updates istio.io) [at the present time]. In a few weeks, istio.io will move to the 1.15 branch, while preliminaryistio will move back to the main branch.

**Pull request merged**
