### PR TITLE
Blog custom gateway

### PR DESCRIPTION
**Pull request by jsenon**
I propose to add a new blog entry for "How to create you own custom gateway?"
Replace old PR as mention by @geeknoid

### CODE REVIEW

**Comment by geeknoid** [comment]
@jsenon Julien, can you follow up on Frank and Vadim's comments from the other PR?

@frankbu Why don't you feel this is appropriate as a task?

**Comment by frankbu** [comment]
@geeknoid, there are too many things that we are demonstrating in the category of ingress/egress, so we decided to just stick to a couple of basic tasks and put the rest of the things in the edge traffic examples folder: https://preliminary.istio.io/docs/examples/advanced-gateways/

**Comment by jsenon** [comment]
@geeknoid I've taken into account Frank and Vadim comment except Helm remark because I think the most important part of this blog entry is to explain how, all components are linked together by an example, and not with an automated installation

**Comment by geeknoid** [comment]
So Frank:

If not a task, do you think this doc should be a blog post or be moved to docs/examples/advanced-gateway?

And Julien thinks he's addressed your and Vadim's feedback from #2803. So what's missing?

**Comment by frankbu** [comment]
I think it can be moved to a blog as is. Example would be fine with me too, but I think the instructions need a little more detail to be consistent with our other examples. Our examples spell out everything you need to do to run it. This one is missing steps or at least notes. A couple of examples are: In step 9, what VirtualService? To run the curl command in step 10 you need to have DNS set up.

@vadimeisenbergibm WDYT?

**Comment by frankbu** [comment]
My vote is for blog entry, which is what Julien initially proposed.

**Comment by vadimeisenbergibm** [comment]
I am OK with blog entry.

**Pull request closed without merging**
