### PR TITLE
fix weak algorithm

### LINKED ISSUE #10544: CA signature digest algorithm too weak
https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/
```bash
curl -HHost:httpbin.example.com --resolve "httpbin.example.com:443:172.18.0.6" --cacert example.com.crt "https://httpbin.example.com"
curl: (60) SSL certificate problem: CA signature digest algorithm too weak
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

### PR DESCRIPTION
**Pull request by liuxu623**
Please provide a description for what this PR is for.

Fix #10544 

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [x] Docs

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Review by lei-tang — APPROVED** [review]
Thanks for the fix! 
Nit: can you add a comment on the default digest algorithm used by openssl?

**Review by howardjohn — CHANGES_REQUESTED** [review]
Do we really need to make it more complex? This is clearly just an example of a minimal portable command to generate a cert. No one should be using this in production - it even has `example.com` in the command.

IMO a demo command should set the minimal flags possible. As is, a user will now need to try to grok why 'sha256' is used. Is it because the author likes it? Because its recommended? Because its required? It adds a lot of cognitive overload.

**Comment by liuxu623** [comment]
> Do we really need to make it more complex? This is clearly just an example of a minimal portable command to generate a cert. No one should be using this in production - it even has `example.com` in the command.
> 
> IMO a demo command should set the minimal flags possible. As is, a user will now need to try to grok why 'sha256' is used. Is it because the author likes it? Because its recommended? Because its required? It adds a lot of cognitive overload.

I try to fix #10544, and I figured it out. Because I use macOS's openssl generate certificate, and use Ubuntu's curl test.
```
macOS openssl version
LibreSSL 2.8.3
```
```
Ubuntu openssl version
OpenSSL 1.1.1f  31 Mar 2020
```
The macOS's openssl default digest algorithm is sha1, and if I use Ubuntu's openssl  generate certificate digest algorithm is sha256.

**Review by howardjohn — APPROVED** [review]
lgtm, didn't realize the curl issue.

Have to love osx...

**Comment by liuxu623** [comment]
> Thanks for the fix! Nit: can you add a comment on the default digest algorithm used by openssl?

```
macOS openssl version
LibreSSL 2.8.3
```
```
Ubuntu openssl version
OpenSSL 1.1.1f  31 Mar 2020
```
The macOS's openssl default digest algorithm is sha1, and Ubuntu's openssl is sha256.

**Review by craigbox — APPROVED** [review]
/cherrypick release-1.12

**Pull request merged**
