### PR TITLE
zh: update index.md of rabc-groups for content_zh OF release-1.2

### PR DESCRIPTION
**Pull request by yuxintong-github**
add the second content_zh part of "Configure JSON Web Token (JWT) authentication with mutual TLS".

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by yuxintong-github** [comment]
> I signed it!

I signed it!

**Comment by yuxintong-github** [comment]
the CI fail seems has nothing connect about my PR, should i concern about the CI failed?
@SataQiu

**Comment by SataQiu** [comment]
Please run the following command to trigger the CI test again:
```sh
$  git commit --allow-empty -m "relint"
$ git push
```

**Comment by SataQiu** [comment]
第二次提交你更换了 github 账号，CLA 通不过，需要使用 @yuxintong-github 账号
```sh
$ git rebase  HEAD~1
$ git commit --allow-empty -m "relint"
$ git push -f
```

**Comment by yuxintong-github** [comment]
sorry, mistake using company github

**Comment by yuxintong-github** [comment]
still failed on CI. what else can i do? 😂

**Comment by SataQiu** [comment]
你需要 rebase ，将第二次提交消除

**Pull request closed without merging**
