### PR TITLE
Nit: modify the path of `pilot-k8s.yaml`

### PR DESCRIPTION
**Pull request by LittleWat**
`pilot-k8s.yaml` is currently located at https://github.com/istio/istio/blob/master/operator/samples/pilot-k8s.yaml

so let me update the doc.

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by ericvn — CHANGES_REQUESTED** [review]
This is where I see it in the current rc0 build:
```
 ~/work/go/src/istio.io/istio-1.17.0-rc.0  find . -name pilot-k8s.yaml                                                                            
./samples/operator/pilot-k8s.yaml
```

**Comment by ericvn** [comment]
It may make sense to add a note that if you are running against a source branch as opposed to using an install, to use a different path.

**Comment by LittleWat** [comment]
Oh, thank you for your quick reply!

Ah, sorry, I thought the directory structure of `releases`  is the same as that of GitHub 🤦‍♂️ but this was wrong.

> It may make sense to add a note that if you are running against a source branch as opposed to using an install, to use a different path.

Yes, it may make sense, but  I have to add the note to every docs, and this seems to be not so important so let me close this PR. 🙇

**Pull request closed without merging**
