### PR TITLE
zh: sync /docs/setup/kubernetes/additional-setup/config-profiles/index.md

### PR DESCRIPTION
**Pull request by haiker2011**

### CODE REVIEW

**Comment by fleeto** [comment]
`[trans-bot:pushed]`

Thank you @haiker2011, the [related task issue](https://github.com/servicemesher/istio-official-translation/issues/941) had been updated.

**Comment by haiker2011** [comment]
@fleeto 已经修复

**Comment by haiker2011** [comment]
@fleeto 最近怎么经常提PR出现 ci/circleci 无法通过的问题，应该是一些链接打开超时，我修改的文件也不牵涉到那个文件，提交更新之前构建还是成功的。

**Comment by haiker2011** [comment]
open new PR

**Pull request closed without merging**
