### PR TITLE
we are using the incorrect namespace and incorrect service name

### PR DESCRIPTION
**Pull request by luis-giraldo**
According to the docs provided in https://istio.io/latest/docs/examples/bookinfo/ , the ingress-gateway is created under the istio-ingress namespace, not under the istio-system namespace

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by zirain** [comment]
you need run `make gen` to update test script

**Comment by frankbu** [comment]
> According to the docs provided in https://istio.io/latest/docs/examples/bookinfo/ , the ingress-gateway is created under the istio-ingress namespace, not under the istio-system namespace

@luis-giraldo Where in this doc does it say to create the ingress-gateway in the istio-ingress namespace? As far as I know, all of the startup and example docs use the Istio `demo` or `default` profile to install Istio, which, by default, will install the ingress gatewaway in the istio-system namespace. Installing gateways separately in a different (e.g. istio-ingress) namespace is a recommended production pattern, but not what is done by default.

**Comment by luis-giraldo** [comment]
make gen

**Comment by kfaseela** [comment]
> make gen

@luis-giraldo : you will have to run `make gen` locally in your istio.io repo, and amend this commit with the generated files

**Comment by luis-giraldo** [comment]
@frankbu this is what happens when you install via helm

**Comment by ericvn** [comment]
Ref: https://github.com/istio/istio/issues/39049

**Comment by frankbu** [comment]
> @frankbu this is what happens when you install via helm

@luis-giraldo It's unfortunate that helm and istioctl install things differently. We can't change the instructions to the helm way, it needs to accommodate both. The doc test won't pass with your change, since the doc framework does not use helm to install.

Here's a PR that updates the doc to handle ingress gateway locations more generally: #12308

**Comment by ericvn** [comment]
I believe https://github.com/istio/istio.io/pull/12315 better solve this issue. Feel free to reopen if something else is needed.

**Comment by luis-giraldo** [comment]
Yup, thanks!

**Pull request closed without merging**
