### PR TITLE
fix typo: thethe -> the

### PR DESCRIPTION
**Pull request by xichengliudui**
fix typo: thethe -> the

### CODE REVIEW

**Comment by geeknoid** [comment]
Deploy preview for *preliminary-istio* failed.

Built with commit f7b222afd24421ee0bdfb59be3b8c9a86bbe67bf

https://app.netlify.com/sites/preliminary-istio/deploys/5bf671cc05c417658a0662a7

**Comment by xichengliudui** [comment]
5:07:48 PM: ERROR 2018/11/22 09:07:48 error processing shortcode "shortcodes/image.html" for page "docs/examples/advanced-gateways/wildcard-https-egress-gateway/index.md": template: shortcodes/image.html:56:17: executing "shortcodes/image.html" at <readFile (printf "co...>: error calling readFile: stat /opt/build/repo/content_zh/content/docs/examples/advanced-gateways/wildcard-https-egress-gateway/EgressGatewayWithSNIProxy.svg: no such file or directory

This is clearly not my problem！

**Comment by geeknoid** [comment]
This is a generated file. To fix this problem, please find the corresponding file in the istio/api repo and fix it there.

Thanks.

**Pull request closed without merging**
