### PR TITLE
zh: 英文官方文档同步

### PR DESCRIPTION
**Pull request by linwenjun**
安装istio之后，相关的CRD是23(28)个，而不是53(58)个

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by rootsongjc** [comment]
@linwenjun Please sign the CLA first.

**Comment by SataQiu** [comment]
还有个类似的 PR : #4660

**Comment by linwenjun** [comment]
I signed it!

**Comment by geeknoid** [comment]
The release-1.2 branch has been archived.

**Pull request closed without merging**
