### PR TITLE
[release-1.9] Manual cherry-pick of 10352 - Move to 1.9.8

### PR DESCRIPTION
**Pull request by ericvn**
Please provide a description for what this PR is for.

Fixes: https://github.com/istio/istio.io/issues/10355

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by rvennam — APPROVED** [review]

**Review by brian-avery — APPROVED** [review]

**Comment by ericvn** [comment]
Remove 1.9.8 update. Suspicion that some update in between 1.9.4 and 1.9.8 invalidates some of the doc tests.

**Pull request merged**
