### PR TITLE
zh-translation: about/security-vulnerabilities/index.md

### PR DESCRIPTION
**Pull request by Ruil1n**
zh-translation: about/security-vulnerabilities/index.md

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by Ruil1n** [comment]
@googlebot I signed it!

**Review by kebe7jun — APPROVED** [review]

**Review by rootsongjc — APPROVED** [review]
/LGTM

**Pull request merged**
