### PR TITLE
zh-translation: /docs/tasks/security/plugin-ca-cert/index.md

### PR DESCRIPTION
**Pull request by gaohuag**
ref: https://github.com/servicemesher/istio-official-translation/issues/1388

### CODE REVIEW

**Comment by rootsongjc** [comment]
@gaohuag Please sign the CLA first.

**Comment by gaohuag** [comment]
/lint_istio.io

**Comment by gaohuag** [comment]
@googlebot I signed it!

**Comment by gaohuag** [comment]
@googlebot I fixed it.

**Comment by gaohuag** [comment]
@googlebot I fixed it.

**Comment by gaohuag** [comment]
@googlebot I signed it!

**Comment by gaohuag** [comment]
@googlebot I fixed it.

**Comment by gaohuag** [comment]
@googlebot I fixed it.

**Comment by gaohuag** [comment]
@googlebot I fixed it.

**Comment by gaohuag** [comment]
@googlebot I fixed it.

**Pull request closed without merging**
