### PR TITLE
Early draft for VM updates

### PR DESCRIPTION
**Pull request by costinm**
Would appreciate if someone can take over the change and translate it to english...

### CODE REVIEW

**Comment by irisdingbj** [comment]
@costinm  Thanks for this! since the gateway part not work in 1.5 (https://github.com/istio/istio/pull/21803). Sould we remove content/en/docs/examples/virtual-machines/multi-network/index.md totally? We can add this back in 1.5.1 with updated instruction.

**Comment by irisdingbj** [comment]
> Would appreciate if someone can take over the change and translate it to english...

I can continue work on this

**Comment by irisdingbj** [comment]
@costinm 
   This option will expose Istio control plane on the default cluster gateway, as a public address. 
This is not the case since we have not made https://github.com/istio/istio/pull/21803 part of 1.5.

**Comment by irisdingbj** [comment]
@costinm I am using https://github.com/istio/istio.io/pull/6743 to update the docs

**Comment by duderino** [comment]
@costinm this was taken over by @irisdingbj ... please make sure your content ended up getting merged appropriately

**Pull request closed without merging**
