### PR TITLE
Sync the Istio new design about struct to Chinese version

### PR DESCRIPTION
**Pull request by elkan1788**
Sync the Istio new design about struct to Chinese version.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by elkan1788** [comment]
@ericvn  Could you help review those changes and approve it? Thanks.

**Comment by craigbox** [comment]
Can you please look at the changes coming in #9575 and adjust your PR to match - we will want to merge that one first.

**Comment by elkan1788** [comment]
> Can you please look at the changes coming in #9575 and adjust your PR to match - we will want to merge that one first.

Yeah, I see. But that couldn't understand why it reference the i18n files to maintain the blog's(news's) title and description. I think use page parameters can be most agility.

**Comment by craigbox** [comment]
#9575 has been revised per your suggestion.  Thanks!

>

**Comment by elkan1788** [comment]
> #9575 has been revised per your suggestion. Thanks!

@craigbox Thanks all. Wait for your PR merge in and will rebase it.

**Review by craigbox — APPROVED** [review]

**Comment by craigbox** [comment]
Please rebase and merge at will - Polidea will fix conflicts afterwards.

**Review by kebe7jun — APPROVED** [review]

**Review by ericvn — APPROVED** [review]

**Pull request merged**
