### PR TITLE
update Solo.io and Gloo Edge logos

### PR DESCRIPTION
**Pull request by peterj**
Updating Solo.io logo and Gloo Edge logo. 

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by ericvn** [comment]
@linsun Are these now correct?

**Review by rvennam — APPROVED** [review]

**Comment by rvennam** [comment]
@ericvn yup!

**Pull request merged**
