### PR TITLE
[zh] sync update deployment/requirements document to latest

### PR DESCRIPTION
**Pull request by shuaijinchao**
Please provide a description for what this PR is for.
update deployment/requirements/index.md chinese document to latest.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by shuaijinchao** [comment]
hello @kebe7jun, I want to ask I have signed google/cla why CLA in CI still fails, what do I need to do?

**Comment by kebe7jun** [comment]
Reply `@googlebot I signed it!` may be ok if you signed.

**Comment by shuaijinchao** [comment]
@googlebot I signed it!

**Comment by kebe7jun** [comment]
https://github.com/istio/istio.io/pull/10932/checks?check_run_id=5230688796
> The following contributors were found for this pull request:
> ❌ https://github.com/istio/istio.io/commit/8205e59a42408d96d4d6fc07864c36a72f426ef0 Author: @shuaijinchao <shu******hao​@apache.org>, <shu******hao​@gmail.com>
> (Only the first commit for a unique contributor is listed.)

**Comment by kebe7jun** [comment]
you shuld sign CLA with all your emails in this commit.

**Comment by shuaijinchao** [comment]
> you shuld sign CLA with all your emails in this commit.

thx~, signed

**Review by kebe7jun — APPROVED** [review]

**Comment by kebe7jun** [comment]
@shuaijinchao Thanks!

**Pull request merged**
