### PR TITLE
update netlify hugo

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/istio/istio.io/issues/11190

### CODE REVIEW

**Comment by craigbox** [comment]
Anything in particular this version fixes or that we should watch out for in testing?
Or is this just for being up to date?

**Comment by Arhell** [comment]
Yes, just up to date.

**Comment by craigbox** [comment]
Looking at https://github.com/gohugoio/hugo/releases, there's been a bunch of 0.97 point releases in the last few days.  I think it might be best to leave this sit for a week or so and see if they find any other major bugs.  Would that be OK, @Arhell ?

**Comment by Arhell** [comment]
> Looking at https://github.com/gohugoio/hugo/releases, there's been a bunch of 0.97 point releases in the last few days. I think it might be best to leave this sit for a week or so and see if they find any other major bugs. Would that be OK, @Arhell ?

There were already bugs in 0.97.2. There were problems with the build.
I checked, everything works + I did not find any bugs for our site.

**Review by craigbox — APPROVED** [review]
ok, we can always upgrade/downgrade I guess.

**Comment by ericvn** [comment]
Not sure why these tests are failing. I'll try and look later today.

**Pull request merged**
