### PR TITLE
fix table width error

### PR DESCRIPTION
**Pull request by Arhell**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

resove https://github.com/istio/istio.io/issues/11516

### CODE REVIEW

**Comment by craigbox** [comment]
✅ https://deploy-preview-11522--preliminary-istio.netlify.app/latest/docs/releases/feature-stages/#feature-phase-definitions 
❌ https://deploy-preview-11522--preliminary-istio.netlify.app/latest/docs/reference/commands/pilot-agent/#envvars

**Comment by Arhell** [comment]
@craigbox can make minimum width for pc?

**Comment by craigbox** [comment]
I've had a quick play around with various options for `table-layout: fixed` and `word-break: break-word`, none of them seem to fix this. 

We could change Hugo to add [<wbr>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr) tags to code blocks where underscores are?  Thoughts, @ericvn ?

**Comment by Arhell** [comment]
> I've had a quick play around with various options for `table-layout: fixed` and `word-break: break-word`, none of them seem to fix this.
> 
> We could change Hugo to add tags to code blocks where underscores are? Thoughts, @ericvn ?

the problem is that there are just long words, not just blocks of code

**Comment by craigbox** [comment]
we could make you scroll inside the table?

It looks like the layout engine seems to prefer using the first row as a guideline on how wide the columns should be, which doesn't make any sense.

I don't think we want to make users hint at which columns should be what width when they create tables either.

**Comment by Arhell** [comment]
here is an example with scrolling
Screenshot_1
the same but without scrolling but there is a strip that scroll can be
Screenshot_2

**Comment by Arhell** [comment]
@craigbox
Please take a look, it's not bad.
But some tables are not full width, I think this is not critical

**Comment by craigbox** [comment]
Hey Ihor, I wasn't sure quite what to do with this one (I've had it open for a long time!)
I am not sure it was better to merge or not, but happy to take your feedback if you have any more.

**Comment by Arhell** [comment]
> Hey Ihor, I wasn't sure quite what to do with this one (I've had it open for a long time!) I am not sure it was better to merge or not, but happy to take your feedback if you have any more.

Hello, so-so solution, when I made edits so that the content would not get out, I wrote like there might be small problems because there is no way to take into account everything. But in any case, what is done is better than it was when the content climbed off the screen

Unfortunately there is no perfect solution it all depends on the content

**Pull request closed without merging**
