### PR TITLE
adding layer5 adapter to the repos

### PR DESCRIPTION
**Pull request by girishranganathan**
This PR adds Layer5 adapter to the list of adapters.

The areas that this PR affects.

[ ] Configuration Infrastructure
[ X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by geeknoid** [comment]
Note that the adapter docs won't show up on the site until someone runs "make update_ref_docs"

**Comment by girishranganathan** [comment]
@geeknoid, can you please tell me if I should run `make update_ref_docs` in my fork? or should that be done in this repo?

**Comment by girishranganathan** [comment]
Thx folks, I ran the above command and have created a new PR to tie off the last piece: https://github.com/istio/istio.io/pull/6389

**Pull request merged**
