### PR TITLE
Delete mixer filter stats as they no longer exist

### PR DESCRIPTION
**Pull request by nrjpoddar**

### CODE REVIEW

**Comment by nrjpoddar** [comment]
@douglas-reid @mandarjog I'm assuming this is ok?

**Comment by douglas-reid** [comment]
They might exist if you re-enable v1, but I don't think it matter much.  However, have the defaults enforced in `istio/istio` changed?

**Comment by nrjpoddar** [comment]
@douglas-reid I followed default install instructions and didn’t see these stats. I think we should document the new default behavior.

**Comment by nrjpoddar** [comment]
Can we get this merged?

**Comment by douglas-reid** [comment]
My only concern is that the default collection keys have not actually changed. I'm fine with hiding them in the docs, but I don't think the actual enforced behavior will match.

**Comment by douglas-reid** [comment]
To clarify: I'm not suggesting you'll see stats for these values, but that the stats inclusion list will still include them.

**Comment by nrjpoddar** [comment]
Agree with that, I now understand what you mean. As a user if the stats don’t show up it felt odd to me as I don’t understand the underlying nuances of collection keys & inclusion list.

Your call, I’m fine either way.

**Comment by douglas-reid** [comment]
Let's merge it so that we don't forget later. I don't think any use harm will come from this removal.

**Pull request merged**
