### PR TITLE
fix overlapping table

### PR DESCRIPTION
**Pull request by Arhell**
fix issue https://github.com/istio/istio.io/issues/9858

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by shamsher31 — COMMENTED** [review]
Looks good. But need to test if it affects any other part of the website.
https://deploy-preview-10238--preliminary-istio.netlify.app/latest/docs/reference/config/istio.operator.v1alpha1/#KubernetesResourcesSpec

**Comment by ericvn** [comment]
https://deploy-preview-10238--preliminary-istio.netlify.app/latest/docs/reference/config/istio.mesh.v1alpha1/ still has an overlap.

**Comment by rvennam** [comment]
@Arhell Can you show us an example of where words are not always transferred correctly after your PR? GlobalMeshOptions and IstioOperator referece pages seem OK with your PR.

**Comment by Arhell** [comment]
> @Arhell Can you show us an example of where words are not always transferred correctly after your PR? GlobalMeshOptions and IstioOperator referece pages seem OK with your PR.

https://deploy-preview-10238--preliminary-istio.netlify.app/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider-EnvoyExternalAuthorizationGrpcProvider

**Comment by craigbox** [comment]
If the problem is only that some words are broken (which are too long for
the line anyway), I think that's a win.  I'm not sure there's a fix we
could apply to break words with no obvious break - it would have to include
hyphenation, which would introduce technical incorrectness?

>

**Comment by Arhell** [comment]
> If the problem is only that some words are broken (which are too long for the line anyway), I think that's a win. I'm not sure there's a fix we could apply to break words with no obvious break - it would have to include hyphenation, which would introduce technical incorrectness?
> […](#)

Technically, unlikely, I isolated the styles to the maximum so that it would not affect other content (word wrap). Just readability can be a little difficult

**Comment by rvennam** [comment]
Agree that the new change is better than before. I say we merge this and then look into making those subtitiles smaller - h3 instead of h2 to give it more room

**Review by rvennam — APPROVED** [review]

**Comment by Arhell** [comment]
cc @craigbox

**Review by craigbox — APPROVED** [review]

**Pull request merged**
