### PR TITLE
update istio-ingress installation name in helm install instructions

### LINKED ISSUE #13497: default helm installation steps doesn't work for k8s ingress
https://istio.io/latest/docs/setup/install/helm/#installation-steps

```text
8. (Optional) Install an ingress gateway:

$ kubectl create namespace istio-ingress
$ helm install istio-ingress istio/gateway -n istio-ingress --wait
```

Following the above official steps to install istio doesn't work for k8s ingress, as the default values of `ingressService` and `ingressSelector` is `istio-ingressgateway` and `ingressgateway` respectly in [MeshConfig](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig).

We should at least change the example release name from `istio-ingress` to `istio-ingressgateway`, as did by [artifacthub example](https://artifacthub.io/packages/helm/istio-official/gateway/1.18.0#installing-the-chart) and [gateway setup example](https://istio.io/latest/docs/setup/additional-setup/gateway/#deploying-a-gateway), so the default helm installation steps works out of the box for k8s ingress.

A lot of people have stumbled upon this issue:

https://github.com/istio/istio/issues/36444#issuecomment-993105159
https://github.com/istio/istio/issues/37329
https://github.com/istio/istio/issues/44402

### PR DESCRIPTION
**Pull request by dhawton**
Please provide a description for what this PR is for.

Mesh Config has a default of looking for `istio-ingressgateway`, which is the name elsewhere and by other methods for installation. This PR changes the installation instructions to match the name used elsewhere. For example: https://istio.io/latest/docs/setup/additional-setup/gateway/#deploying-a-gateway, https://istio.io/latest/docs/setup/install/istioctl/#check-whats-installed.

Fixes #13497 

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Review by windsonsea — APPROVED** [review]
lgtm for the zh part if the en change is correct.

**Comment by zirain** [comment]
FYI: https://github.com/istio/istio.io/pull/11762#pullrequestreview-1087913597

**Comment by dhawton** [comment]
> FYI: [#11762 (review)](https://github.com/istio/istio.io/pull/11762#pullrequestreview-1087913597)

His comment is directed at the namespace rather than installation name. The installation name is consistent in this doc vs another doc with helm installation (ie, https://istio.io/latest/docs/setup/additional-setup/gateway/#deploying-a-gateway).

**Comment by zirain** [comment]
@howardjohn ptal

**Review by howardjohn — CHANGES_REQUESTED** [review]
This was intentional. Using the same names across samples, IMO, is actively harmful. users should understand what fields link things up and set them to match when appropriate.

We should not rely on a demo world where we _happened_ to name everything the same. It ends with users thinking `istio: ingressgateway` is some magic value, when really its a simple label selector. I have seen this countless times. I have never seen the same with Kubernetes Service -- but probably we would, if their docs always used `hello: world` in _every_ sample and treated it as a bug if it wasn't that.

**Comment by dhawton** [comment]
> This was intentional. Using the same names across samples, IMO, is actively harmful. users should understand what fields link things up and set them to match when appropriate.
> 
> We should not rely on a demo world where we _happened_ to name everything the same. It ends with users thinking `istio: ingressgateway` is some magic value, when really its a simple label selector. I have seen this countless times. I have never seen the same with Kubernetes Service -- but probably we would, if their docs always used `hello: world` in _every_ sample and treated it as a bug if it wasn't that.

However the current documentation varies from the default value we specify in the meshConfig for ingressService, which is `istio-ingressgateway` (https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig). This makes it feel like a bug since a user could follow the documentation as-is, and not have a working Ingress controller without additional steps that are not documented in this page. For a new person coming in to the project, installation steps are a great way to get started and not always best practice. As far as the linked comment by @zirain, I agree, the changing of namespaces is a good move and we document that in the Deploying Gateway docs.

I guess an alternative could be to update the documentation to clarify that the name in this step differs from meshConfig's default value and additional steps are required. I'm trying to approach this as someone who knows Kubernetes and Helm, but doesn't know Istio. I would follow the guide to get a learning environment setup and play in, and nothing seems to indicate that this wouldn't work "out of the box" until they go to test the environment and see the ingress not working.

**Pull request closed without merging**
