### PR TITLE
add istio.io/operator as vanity URL

### PR DESCRIPTION
**Pull request by waynz0r**
Add istio.io/operator to golang vanity redirects

[x] Configuration Infrastructure

### CODE REVIEW

**Comment by waynz0r** [comment]
@googlebot I signed it!

**Comment by geeknoid** [comment]
May I ask what this is needed for? Where do we need istio.io/operator?

**Comment by waynz0r** [comment]
@geeknoid, I would like to use a pkg from istio.io/operator/pkg in another project.

**Comment by waynz0r** [comment]
thanks @geeknoid!

**Pull request merged**
