### PR TITLE
Remove global.externalIstiod from remote examples

### PR DESCRIPTION
**Pull request by luksa**
## Description

The need to use this value was removed in https://github.com/istio/istio/pull/53542.

## Reviewers

- [ ] Ambient
- [ ] Docs
- [x] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

### CODE REVIEW

**Comment by luksa** [comment]
Ah, the tests didn't run against the latest Istio version, hence the failure. Is there automation that updates the Istio version in this repo or do I need to update it myself?

**Comment by dhawton** [comment]
> Ah, the tests didn't run against the latest Istio version, hence the failure. Is there automation that updates the Istio version in this repo or do I need to update it myself?

There is some automation, runs daily at 2am UTC.

**Review by bleggett — APPROVED** [review]
TY!

**Comment by dhawton** [comment]
Looks like there were changes in istio/istio that broke doc tests again... I don't have cycles at the moment to look in to it, but if another docs maintainer cannot I'll try when I can.

**Comment by bleggett** [comment]
> Looks like there were changes in istio/istio that broke doc tests again... I don't have cycles at the moment to look in to it, but if another docs maintainer cannot I'll try when I can.

I suspect https://github.com/istio/istio/pull/53542 probably broke an assumption in the doc tests in this repo.

That assumption is probably _bad_, and the docs tests should be updated/fixed.

**Comment by bleggett** [comment]
It looks like the injected sidecars in the doctests are failing to come up because the webhook name is wrong (somehow, despite https://github.com/istio/istio/pull/53542, something is expecting a Service named `istiod-remote` and it's getting `istiod`, or vice-versa), so injection is failing.

**Comment by luksa** [comment]
@bleggett you sure this is running against the Istio version that includes the changes in [istio/istio#5](https://github.com/istio/istio/pull/53542)? According to the logs, the test ran against `ISTIO_VERSION=1.24-alpha.1c546ae8a14a9a64f171c7fe228925ebaf3a3348`, which is a week old commit, whereas my changes went in yesterday.

**Comment by bleggett** [comment]
> @bleggett you sure this is running against the Istio version that includes the changes in [istio/istio#5](https://github.com/istio/istio/pull/53542)? According to the logs, the test ran against `ISTIO_VERSION=1.24-alpha.1c546ae8a14a9a64f171c7fe228925ebaf3a3348`, which is a week old commit, whereas my changes went in yesterday.

Oh yep, that would be why.

Feel free to manually update the ref in this PR, with `go get`: https://github.com/istio/istio.io/blob/master/README.md#updating-the-test-reference-for-a-given-release-stream

**Review by sridhargaddam — APPROVED** [review]

**Comment by dhawton** [comment]
> > @bleggett you sure this is running against the Istio version that includes the changes in [istio/istio#5](https://github.com/istio/istio/pull/53542)? According to the logs, the test ran against `ISTIO_VERSION=1.24-alpha.1c546ae8a14a9a64f171c7fe228925ebaf3a3348`, which is a week old commit, whereas my changes went in yesterday.
> 
> Oh yep, that would be why.
> 
> Feel free to manually update the ref in this PR, with `go get`: https://github.com/istio/istio.io/blob/master/README.md#updating-the-test-reference-for-a-given-release-stream

That should only happen in the automated PRs.. do not do it in regular docs PRs.. especially if there is something that could be broken.

**Review by dhawton — APPROVED** [review]

**Comment by bleggett** [comment]
> That should only happen in the automated PRs.. do not do it in regular docs PRs.. especially if there is something that could be broken.

(for my own understanding) - what is the extra risk here? The automator opens a PR that must pass the same CI gates as any other PR, so whether the ref is bumped in a person PR versus an automator PR shouldn't change stability much - the same CI has to pass either way.

**Pull request merged**
