### PR TITLE
zh: Fix the numbers of CRDs to right to follow the latest release version

### PR DESCRIPTION
**Pull request by Aisuko**
Signed-off-by: Aisuko <urakiny@gmail.com>

Please provide a description for what this PR is for.
* fixes: #4823 

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by frankbu** [comment]
I added the cherrypick/master label, but now I wonder if it even belongs in the release-1.2 branch at all. If the change is only required in the 1.3 release, the PR should only be sent to the master branch.

**Comment by Aisuko** [comment]
Thanks for your reply,  this PR only for `release-1.2` branch.   The master branch will make a check today.

**Comment by Aisuko** [comment]
Hello, sir @frankbu, I believe the master branch doesn't have this issue, please see link below https://github.com/istio/istio.io/blob/master/content/zh/boilerplates/verify-crds.md.

**Comment by Aisuko** [comment]
cc @geeknoid Hello, sir, How can I pass the `istio.io-lint` autotest?

**Comment by geeknoid** [comment]
release-1.2 is now archived.

**Pull request closed without merging**
