### PR TITLE
fix translation errors

### PR DESCRIPTION
**Pull request by wulianglongrd**
fix translation errors

Please provide a description for what this PR is for.
fix translation errors

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by kfaseela** [comment]
Ideally, you should raise the PR on master first, and once merged, cherry-pick to 1.16

**Comment by wulianglongrd** [comment]
> Ideally, you should raise the PR on master first, and once merged, cherry-pick to 1.16

thanks and the new PR #12408

**Pull request closed without merging**
