### PR TITLE
Replace deprecated api versions

### PR DESCRIPTION
**Pull request by pipo02mix**
Update API version for Ingress, Deployments, Daemonsets and Pod Security Policies

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by pipo02mix** [comment]
Follow-up of https://github.com/istio/istio/pull/24772

**Comment by shamsher31** [comment]
Not sure if it is a good idea to update archived docs as it will be built and deployed separately from main docs.

**Comment by pipo02mix** [comment]
yes it makes sense I will only change `en` folder then

**Comment by frankbu** [comment]
@pipo02mix I'm not sure what the goal is here, but most of these docs are old archived versions, they're not supposed to ever change. Also, even in the latest release docs, blogs are supposed to be read only. If you want to update the version, it should only be in `.md` files under `content/en/docs`, and maybe FAQ, but that's it.

**Comment by frankbu** [comment]
Closing this PR, because it has triggered unnecessary reviewers. Please open a new PR with only the en .md file changes.

**Comment by pipo02mix** [comment]
ok sorry for the inconveniences. I will do only with the md

**Pull request closed without merging**
