### PR TITLE
Fix doc test

### PR DESCRIPTION
**Pull request by hanxiaop**
Please provide a description for what this PR is for.

/cc @ericvn The message was removed in https://github.com/istio/istio/pull/45885

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by kfaseela** [comment]
will you be adding docs for the new error message that has been added?

**Review by kfaseela — APPROVED** [review]

**Comment by hanxiaop** [comment]
> will you be adding docs for the new error message that has been added?

I think @nicole-lihui is working on this in https://github.com/istio/istio.io/pull/13800

**Comment by ericvn** [comment]
Thanks for removing the message. Not sure how that relates to the PR title at the moment.

**Comment by ericvn** [comment]
You also need to remove the \zh\ version of the file.

**Pull request merged**
