### PR TITLE
zh-translation: /docs/ops/configuration/telemetry/in-proxy-service-telemetry/index.md

### PR DESCRIPTION
**Pull request by ilylia**
ref: https://github.com/servicemesher/istio-official-translation/issues/1659

### CODE REVIEW

**Comment by yuxiaobo96** [comment]
@rootsongjc

**Comment by rootsongjc** [comment]
@yuxiaobo96 Can I merge this PR now?

**Comment by yuxiaobo96** [comment]
@rootsongjc 
可以的，检查过了

**Pull request merged**
