### PR TITLE
[release-1.7] Update 1.6 docs: new ref docs, install changes

### PR DESCRIPTION
**Pull request by ericvn**
This is a test of pulling release-1.6 release branch updates into the docs. These updates should show up on the 1.6 doc pages.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by ericvn** [comment]
Some notes on the process:

Running the `make command` I ended up with
```
...
 *** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
...
```
which was the same problem we had when running this during the release branching. The changes we put into the _master_ branch to add the git config file into the container must not have been copied to the _release_1.7_ branch.

In this case, it's the few git commands that fail, and they can be done manually afterwards (git add, git commit, git push).

Note: even if we had the change from _master_, that still failed with a user problem.

**Comment by ericvn** [comment]
Weird the netlify test is now showing failed. I was using earlier to see that the actual 1.6 pages (had to change link to point to netlify url with v1.6). Maybe my playing out there caused th other jobs to fail and then netlify?

**Comment by ericvn** [comment]
Showing that things did work, one can go to `https://deploy-preview-8154--istio.netlify.app/v1.6/docs/reference/commands/istioctl/#envvars` and see that ENVOY_READINESS_CHECK_TIMEOUT was added after ENABLE_CA_SERVER which is the second change in archive/v1.6/docs/reference/commands/istioctl/index.html.

**Comment by ericvn** [comment]
Ran again today to add the 1.6.10 reference doc update changes, and also left the changes in the `zh` branch. Looks like the Netlify tests ran successfully. Not sure if there was a timeout increase due to some failed merges in another 1.7 PR over the weekend.

So for now, DNM until 1.6.10 is released.

**Comment by ericvn** [comment]
Verified that https://deploy-preview-8154--istio-staging.netlify.app/v1.6/docs/reference/commands/istioctl/#istioctl-manifest-migrate had the new text from the latest commit.

**Comment by ericvn** [comment]
1.6.10 is released, so this PR can be merged.

**Review by frankbu — APPROVED** [review]

**Pull request merged**
