### PR TITLE
starting fixup for ambient getting-stated tests

### PR DESCRIPTION
**Pull request by ilrudie**
## Description

Enable and fix ambient mode getting started tests

fixes #14941 

## Reviewers

- [X] Ambient
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Localization/Translation

### CODE REVIEW

**Comment by ericvn** [comment]
Note you also need to rename the disabled gtw-test.sh file.

**Comment by ilrudie** [comment]
I was thinking it might be easier to work through the failures one at a time but maybe that's not the case and I should dive in on the other tests too

**Comment by ericvn** [comment]
> I was thinking it might be easier to work through the failures one at a time but maybe that's not the case and I should dive in on the other tests too

Either way works. If the failure in the second test is caused by missing cleanup in the first test, it may make sense to wait. Otherwise, if you are actually using the PR's testing to test changes instead of locally, I find it easier to debug both and change both with each commit, since it'll run both tests each time.

**Comment by dhawton** [comment]
just popping DNM so it doesn't accidentally get merged while you're working on the tests

**Comment by ilrudie** [comment]
@dhawton and @ericvn, I will remove the istio api bits shortly but I think this is looking much better now. LMK if it looks like I still have something broken which just isn't failing

**Comment by dhawton** [comment]
> @dhawton and @ericvn, I will remove the istio api bits shortly but I think this is looking much better now. LMK if it looks like I still have something broken which just isn't failing

Looks LGTM. Nothing stands out.

**Review by ericvn — APPROVED** [review]
LGTM. Feel free to remove the DNM whenever you are done.

**Pull request merged**
