### PR TITLE
fix id of rust ztunnel

### PR DESCRIPTION
**Pull request by zhengbingxian**
Please provide a description for what this PR is for.

Fix id of rust ztunnel.    Now it works not as expect.      [Here is the link](https://istio.io/latest/zh/blog/2023/rust-based-ztunnel/#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E9%87%8D%E7%94%A8-envoywhy-not-reuse-envoy)

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Ambient
- [X] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by windsonsea** [comment]
The fix is correct. Not sure whether these archived docs can be modified or not?

**Comment by zhengbingxian** [comment]
@windsonsea    I use `make serve`  to test  it locally and it works well.   
what's the next ? Or is there anything left should I to do?

**Comment by windsonsea** [comment]
cc @zirain to confirm the changes for archived docs

**Comment by zirain** [comment]
please do not update archieve content

**Comment by zirain** [comment]
blog is not versioned, you should correct the markdown on master, then cherrypick to `release-1.18`(which is the current release branch).

**Review by zirain — CHANGES_REQUESTED** [review]
https://github.com/istio/istio.io/pull/13505#issuecomment-1621339811

**Comment by windsonsea** [comment]
Seems this can be closed.

**Pull request closed without merging**
