### PR TITLE
fix circuit breaker task

### PR DESCRIPTION
**Pull request by masquee**
use `consecutive5xxErrors` instead of `consecutiveErrors `

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by craigbox** [comment]
/assign @istio/wg-networking-maintainers 

Can you confirm if this field has changed?  The docs at https://istio.io/latest/docs/reference/config/networking/destination-rule/ don't mention `consecutiveErrors` but the examples on the page do.

**Comment by craigbox** [comment]
there's a warning saying "outlier detection consecutive errors is deprecated, use consecutiveGatewayErrors or consecutive5xxErrors instead"

Looks like we should update our reference docs too

**Comment by ericvn** [comment]
Reference docs were updated in master with https://github.com/istio/api/pull/1885.  Not sure if that whole PR should be cherrypicked to 1.9 or not?

**Review by howardjohn — APPROVED** [review]

**Comment by ericvn** [comment]
@masquee You need to run a `make gen` which will create an updated snips.sh which you will need to add to this PR.

**Comment by masquee** [comment]
> @masquee You need to run a `make gen` which will create an updated snips.sh which you will need to add to this PR.

done.

**Review by ericvn — APPROVED** [review]

**Pull request merged**
