### PR TITLE
Blog typo

### PR DESCRIPTION
**Pull request by shpwrck**
Mata -> Meta

Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

### CODE REVIEW

**Comment by craigbox** [comment]
Thanks for catching this!  Can you please sign the CLA so we can take the commit?

**Comment by ericvn** [comment]
Hi @shpwrck. Are you planning to satisfy the CLA requirements? If not, I can create a similar PR to get the change updated.

**Comment by shpwrck** [comment]
I don't know what's wrong with the CLA. I've filled it out before.
image

**Comment by ericvn** [comment]
@shpwrck OK. I re-ran the CLA test yet again, and this time it passed. Not sure what was going on in the background.  Thanks again for the PR.

**Review by ericvn — APPROVED** [review]

**Pull request merged**
