### PR TITLE
[zh] Localize the install doc arch image into Chinese

### PR DESCRIPTION
**Pull request by wilsonwu**
## Description

Localize the install doc arch image into Chinese

## Reviewers

@windsonsea 

- [ ] Ambient
- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [x] Localization/Translation

### CODE REVIEW

**Review by windsonsea — COMMENTED** [review]
这 2 个蓝色的词要翻吗：
- Config/Endpoints
- Endpoints

**Comment by wilsonwu** [comment]
> 这 2 个蓝色的词要翻吗：
> 
> * Config/Endpoints
> * Endpoints

感觉可以翻译，之前有点纠结，那我翻译掉吧。

**Review by windsonsea — APPROVED** [review]
The [preview](https://deploy-preview-14131--preliminary-istio.netlify.app/latest/zh/docs/setup/install/multicluster/primary-remote/) looks good.

**Pull request merged**
