### PR TITLE
Add Liulishuo to customers

### PR DESCRIPTION
**Pull request by XSAM**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

### CODE REVIEW

**Comment by ericvn** [comment]
@craigbox Is there some permission required to add a new customer?

**Comment by craigbox** [comment]
if there is, I grant it herewith

**Review by ericvn — APPROVED** [review]

**Comment by ericvn** [comment]
@XSAM As you included the updates to the Chinese files, we also need the translation team approval for this. I'm not sure how long that will take. Normally, we would just merge updates to the English files in a PR and let the translation team move them to the Chinese branch later. @frankbu might want to merge without waiting on approval from translation team.

**Pull request merged**
