### PR TITLE
Correct log statement

### PR DESCRIPTION
**Pull request by olibye**

### CODE REVIEW

**Comment by olibye** [comment]
I signed it!

**Comment by frankbu** [comment]
@olibye PRs to the master branch are preliminary doc changes for Istio 1.2. If you'd like this fix to appear on the istio.io site now, you need to send the PR to the `release-1.1` branch.

**Comment by olibye** [comment]
Understood, i've created #4006 
Will #4006 get merged back into master at some point?

**Comment by frankbu** [comment]
For a few more weeks, all PRs to `release-1.1` will get merged to master for you. Eventually, once we are well into the release 1.2 cycle, changes that are needed in both 1.2 and 1.1 will need to sent to both branches.

**Pull request closed without merging**
