### PR TITLE
update version 1.0.7 for downloading and release notes.

### PR DESCRIPTION
**Pull request by yangminzhu**
This is for branch `release-1.0`

### CODE REVIEW

**Comment by yangminzhu** [comment]
@geeknoid the test failed with error ```/bin/sh: scripts/gen_site.sh: not found Exited with code 127``` which seems unrelated to this PR, do you know what caused it?

**Comment by geeknoid** [comment]
The release 1.0 branch has been archived at this point and is only available from archive.istio.io. We shouldn't be updating any content in that branch.

**Comment by yangminzhu** [comment]
@geeknoid If some followed the download page in https://archive.istio.io/v1.0/docs/setup/kubernetes/download-release/, they will  get the latest version `1.1.2`, not the `1.0.7`. I thought the 1.0 site should always provide information about 1.0 version for user still using it. That's why we publish the fix for 1.0.7, right?

**Comment by geeknoid** [comment]
Yes, in general we want the releases to be self consistent even over time. The 1.0 doc set had a couple issues in that regard, including the specific link you mention. When 1.1 is archived in a few months, it won't have this problem.

**Comment by geeknoid** [comment]
I'm not sure why CI is failing like that. That's awfully strange. But we shouldn't be modifying the archived site anyway, so let's just close this PR.

**Pull request closed without merging**
