### PR TITLE
Replace installPackagePath with install_package_path

### PR DESCRIPTION
**Pull request by hb-chen**
https://github.com/istio/istio/issues/22368

### CODE REVIEW

**Comment by ostromart** [comment]
Hi @hb-chen this doesn't seem right but I want to understand why you believe it fixes the problem. Maybe you can include part of your console output to show that this works?

**Comment by hb-chen** [comment]
> Hi @hb-chen this doesn't seem right but I want to understand why you believe it fixes the problem. Maybe you can include part of your console output to show that this works?

1. istioctl version
```
istioctl version --remote=false
1.5.0
```

2. default generate
```
istioctl manifest generate > gen-1.yaml
```
3. modify prometheus templates clusterrole.yaml, remove `verbs: ["get"]`
```diff
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: prometheus-{{ .Release.Namespace }}
    labels:
      app: prometheus
      release: {{ .Release.Name }}
  rules:
  - apiGroups: [""]
    resources:
    - nodes
    - services
    - endpoints
    - pods
    - nodes/proxy
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
    - configmaps
    verbs: ["get"]
  - nonResourceURLs: ["/metrics"]
-    verbs: ["get"]
```

4. use `--set installPackagePath=`
```
istioctl manifest generate \           
--set installPackagePath=$PWD/install/kubernetes/operator/charts > gen-2.yaml
```

5. use `--set install_package_path=` , get an error `no such file or directory`
```
istioctl manifest generate \           
--set install_package_path=$PWD/install/kubernetes/operator/charts > gen-3.yaml
Error: open {$PWD}/install/kubernetes/operator/charts/profiles/default.yaml: no such file or directory
```

6. use `--set install_package_path=` and `--set profile` , it's ok.
```
istioctl manifest generate \           
--set install_package_path=$PWD/install/kubernetes/operator/charts \
--set profile=$PWD/install/kubernetes/operator/profiles/default.yaml > gen-3.yaml
```
7. now we get 3 generated yaml file, show diff.
```
diff -s gen-1.yaml gen-2.yaml
Files gen-1.yaml and gen-2.yaml are identical

diff -s gen-1.yaml gen-3.yaml
33d32
<   verbs: ["get"]
```

**Comment by frankbu** [comment]
Closing, fixed in https://github.com/istio/istio.io/pull/6953

**Comment by hb-chen** [comment]
https://github.com/istio/istio.io/pull/6953 `installPackagePath`  isn't work, should be `install_package_path`.
And  the`zh` doc also need to update.

**Comment by ostromart** [comment]
It should be installPackagePath - please try it again with 1.5 latest.

**Comment by frankbu** [comment]
@hb-chen, zh doc should be fixed in separate translation PRs, after the en version is merged. The usual process:
1. fix/change en version of docs.
2. translation team updates zh docs when they become out of sync with en.

**Comment by hb-chen** [comment]
> It should be installPackagePath - please try it again with 1.5 latest.

I test with `1.5.0` on `osx`.
[istio-1.5.0-osx.tar.gz](https://github.com/istio/istio/releases/download/1.5.0/istio-1.5.0-osx.tar.gz)

`install_package_path` ok, `installPackagePath` isn't work.

**Comment by hb-chen** [comment]
I checkout `1.5.0`
Test with this func
```
func TestGenManifests(t *testing.T) {
	l := NewLogger(true, os.Stdout, os.Stderr)
	ysf, err := yamlFromSetFlags([]string{"installPackagePath=/istio-1.5.0/install/kubernetes/operator/charts", "profile=/istio-1.5.0/install/kubernetes/operator/profiles/default.yaml"}, true, l)
	if err != nil {
		t.Error(err)
	} else {
		t.Log(ysf)
	}

	_, spec, err := GenManifests([]string{}, ysf, true, nil, l)
	if err != nil {
		t.Error(err)
	} else {
		t.Logf("installPackagePath: %v",spec.InstallPackagePath)
	}

	ysf, err = yamlFromSetFlags([]string{"install_package_path=/istio-1.5.0/install/kubernetes/operator/charts", "profile=/istio-1.5.0/install/kubernetes/operator/profiles/default.yaml"}, true, l)
	if err != nil {
		t.Error(err)
	} else {
		t.Log(ysf)
	}

	_, spec, err = GenManifests([]string{}, ysf, false, nil, l)
	if err != nil {
		t.Error(err)
	} else {
		t.Logf("install_package_path: %v",spec.InstallPackagePath)
	}
}
```
Run result:
```
--- PASS: TestGenManifests (0.82s)
    manifest-common_test.go:14: spec:
          installPackagePath: /istio-1.5.0/install/kubernetes/operator/charts
          profile: /istio-1.5.0/install/kubernetes/operator/profiles/default.yaml
        
    manifest-common_test.go:21: installPackagePath: 
    manifest-common_test.go:28: spec:
          install_package_path: /istio-1.5.0/install/kubernetes/operator/charts
          profile: /istio-1.5.0/install/kubernetes/operator/profiles/default.yaml
        
    manifest-common_test.go:35: install_package_path: /istio-1.5.0/install/kubernetes/operator/charts
PASS
```

The `installPackagePath` is empty.

**Comment by hb-chen** [comment]
`release-1.5` latest is ok.

**Pull request closed without merging**
