### PR TITLE
zh-translation:content/zh/docs/tasks/traffic-management/egress/http-proxy/index.md

### PR DESCRIPTION
**Pull request by yuer1727**
ref:https://github.com/servicemesher/istio-official-translation/issues/1327

### CODE REVIEW

**Comment by yuer1727** [comment]
@geeknoid  Hello ,  my issue has a cla problem which is confused me.  But my other two issues were cla successful without problems.  Could you ignore this issue's cla and make it passed?

**Comment by JuwanXu** [comment]
你的cla检查没有通过可能是因为你的提交记录中有一个名为`jiaming.rjm`的账号提交记录导致的，我遇到过类似情况

**Comment by yuer1727** [comment]
> 你的cla检查没有通过可能是因为你的提交记录中有一个名为`jiaming.rjm`的账号提交记录导致的，我遇到过类似情况

got . 我试试。

**Pull request closed without merging**
