### PR TITLE
fix wide tables under the table of contents

### PR DESCRIPTION
**Pull request by Arhell**
Please provide a description for what this PR is for.

And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

resolve https://github.com/istio/istio.io/issues/11055

### CODE REVIEW

**Comment by Arhell** [comment]
page https://deploy-preview-11065--preliminary-istio.netlify.app/latest/docs/tasks/observability/logs/otel-provider/#default-access-log-format

**Review by zirain — APPROVED** [review]
LGTM
the `word-break` is the root cause.

**Comment by zirain** [comment]
BTW, https://deploy-preview-11065--preliminary-istio.netlify.app/latest/docs/tasks/observability/logs/access-log/ is also fixed.

**Review by craigbox — APPROVED** [review]

**Pull request merged**
