### PR TITLE
[release-1.22.1 branch] Wasm Configuration for Ambient Mode - Updates 

### PR DESCRIPTION
**Pull request by adilmp1**
Manual cherry pick of : https://github.com/istio/istio.io/pull/15136

Fixes https://github.com/istio/istio.io/issues/15166

### CODE REVIEW

**Comment by kfaseela** [comment]
This need to be merged only for 1.22.1

**Comment by kfaseela** [comment]
That is correct @ericvn

**Comment by craigbox** [comment]
/retest

(This is holding up my cherrypicking of all the related docs, so either this goes in first, or I'll take it in another cherrypick I'm doing.)

**Comment by craigbox** [comment]
Closes #15166

**Comment by craigbox** [comment]
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio.io/15172/doc.test.profile-none_istio.io_release-1.22/1805913855021289472/artifacts/tests-setup-profile-none-72ecf3/TestDocs/ambient/usage/extend-waypoint-wasm/test.sh/test.sh/_test_context/test.sh_output.txt

Should this work now? @kfaseela

**Comment by kfaseela** [comment]
If the test is running against 1.22.1 this should pass now.

**Comment by kfaseela** [comment]
@zirain @dhawton is it possible to confirm if the below PR made it to 1.22.1? Then only the current PR will pass the docs test. https://github.com/istio/istio/pull/51063

**Comment by dhawton** [comment]
It is in 1.22.1... https://github.com/istio/istio/commits/release-1.22.1-patch/ lists the commit

**Comment by dhawton** [comment]
It doesn't seem like we have bumped what version we are installing in docs. https://github.com/istio/istio.io/blob/release-1.22/go.mod#L16 I can do this in the morning

**Comment by craigbox** [comment]
Thanks @dhawton. Can we add this step to what the RMs do when they cut a new point release?

**Comment by kfaseela** [comment]
we need to retest after https://github.com/istio/istio.io/pull/15354

**Review by kfaseela — APPROVED** [review]

**Pull request merged**
