### PR TITLE
Wildcard configuration for arbitrary domains with non root user

### PR DESCRIPTION
**Pull request by wangmeng**
This PR is to track the change for issue: https://github.com/istio/istio.io/issues/9348

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

It contains the necessary change to run the solution with non root user. 

**The change includes:**
- The created egress gateway (istio-proxy container) will use port 8443 to handle the request for 443 request from sidecar, so egress gateway can run as non-root user. 
- The sni-proxy in the same  egressgateway pod will change to listen on port 18443 instead, since 8443 is used by istio-proxy in the same pod. 
- sni-proxy nginx pid file setup with custom path that do not require root access. 
- The port section in egressgateway-with-sni-proxy.yaml is optional, since it is actually the current default behavior for gateway. Still leave it here to demonstrate this Wildcard configuration solution actually could be used not only for the 443 port, but can be customized to support any port with tls protocol. 
```
              ports:
              - port: 443
                targetPort: 8443
                name: https
```

I made the change for files:
`content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md`
`content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/test.sh`

For file: `content/en/docs/tasks/traffic-management/egress/wildcard-egress-hosts/snips.sh`
As it mentioned as below, I assume it would be automatically updated. 
```
THIS IS AN AUTO-GENERATED FILE, DO NOT EDIT. PLEASE MODIFY THE ORIGINAL MARKDOWN FILE:
#          docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md
```

Thanks.

### CODE REVIEW

**Comment by craigbox** [comment]
/ok-to-test

>

**Comment by ericvn** [comment]
@wangmeng You need to run `make gen` to update the other files.

**Comment by ericvn** [comment]
@istio/wg-networking-maintainers Looking for approval. Thanks.

**Comment by wangmeng** [comment]
Thanks for looking into the PR. 

After using `make gen`, as suggested by @ericvn, to regenerate the `snips.sh` for wildcard-egress-hosts, the wildcard related test can pass. 

The only failure case now is the timeout setting doesn't work as expected for egress-control, which is not related to this PR's change. And tracking via: https://github.com/istio/istio.io/pull/9325

**Review by howardjohn — APPROVED** [review]
This is reasonable to me, thanks

**Review by ericvn — APPROVED** [review]

**Pull request merged**
